#!/bin/bash
# -------------------------------------------
# debug.sh
#
# a Node.js app for running the PDG test suite
#
# Written by Ed Zavada, 2012
# Copyright (c) 2012, Dream Rock Studios, LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the
# following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
# NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
# USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# -------------------------------------------

export NODE_DEBUG=""
unset NODE_DEBUG

# load pdgrc
_SD=`pwd`;while [ "`pwd`" != '/' ];do { if [ -e ".pdgrc" ];then { source .pdgrc;break; } fi;cd ..; } done;cd $_SD

# start an echo server
node tools/echo_tcp.js > /dev/null &

cd test

# check for specific test file or .js file
if [ -z "$1" ]; then
    echo "Usage: test/debug [spec | {file}.js]"
    echo "  Runs a give app or test suite under both C++ and JavaScript debuggers"
    echo " - spec is the name of a file in test/spec, without path or .spec.js extension"
    echo " - {file}.js is a path to a javascript file, including .js extension"
    echo "   eg: test/debug test/js/main.js   -- runs the gui test app in the debugger"
    kill %1
    exit 1
else
    if [[ $1 == *".js" ]]; then
        JS_MAIN="$1"
        if [[ $JS_MAIN != "/"* ]]; then
            JS_MAIN="$PDG_ROOT/$1"
        fi
        TARGET_SPEC="";
    else
        JS_MAIN="$PDG_ROOT/test/client_test.js"
        TARGET_SPEC="$1"
    fi
fi 
# start the debugger
node-inspector &

open http://127.0.0.1:8080/debug?port=5858

# run the tests, some of which use the echo server
lldb pdg -- --debug-brk $JS_MAIN $TARGET_SPEC
EXIT_CODE=$?

# kill the echo server and node-inspector
kill %1
kill %2

exit $EXIT_CODE
