#!/bin/bash
# -------------------------------------------
# run.sh
#
# a Node.js app for running the PDG test suite
#
# Written by Ed Zavada, 2012
# Copyright (c) 2012, Dream Rock Studios, LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the
# following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
# NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
# USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# -------------------------------------------

export NODE_DEBUG=
unset NODE_DEBUG

# load pdgrc
_SD=`pwd`;while [ "`pwd`" != '/' ];do { if [ -e ".pdgrc" ];then { source .pdgrc;break; } fi;cd ..; } done;cd $_SD

# start an echo server
node tools/echo_tcp.js > /dev/null &

cd test

if [ "$1" = "--debug" ]; then

	# check if we passed a specific test file
	if [ -z "$2" ]; then
		TARGET=spec
	else
		TARGET=$2
	fi 
	# start the debugger
	node-inspector &

	# run the tests, some of which use the echo server
	node --debug-brk $PDG_ROOT/node_modules/jasmine-node/lib/jasmine-node/cli.js --verbose --forceexit $TARGET
	EXIT_CODE=$?

	# kill the echo server and node-inspector
	kill %1
	kill %2
else

	# check if we passed a specific test file
	if [ -z "$1" ]; then
		TARGET=spec
	else
		TARGET=$1
	fi

	# run the tests, some of which use the echo server
	jasmine-node --verbose --forceexit $TARGET
	EXIT_CODE=$?

	# kill the echo server
	kill %1
fi

exit $EXIT_CODE
