#!/bin/bash
# -------------------------------------------
# node.sh
#
# Invokes a Node.js app for running the PDG test suite
#
# Written by Ed Zavada, 2012
# Copyright (c) 2012, Dream Rock Studios, LLC
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the
# following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
# NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
# USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# -------------------------------------------

export NODE_DEBUG=
unset NODE_DEBUG

# load pdgrc
_SD=`pwd`;while [ "`pwd`" != '/' ];do { if [ -e ".pdgrc" ];then { source .pdgrc;break; } fi;cd ..; } done;cd $_SD
if [ -z "$PDG_ROOT" ]; then
    PDG_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
    export PDG_ROOT
fi
source "$PDG_ROOT/test/lib/test_env.sh"
pdg_test_prepare_env "node"

NODE_BIN="$PDG_ROOT/tools/node"
if [ ! -x "$NODE_BIN" ]; then
    NODE_BIN="$(command -v node)"
fi

if [ -z "$NODE_BIN" ]; then
    echo "Error: could not find a Node.js executable."
    exit 1
fi

# ensure we're in the PDG_ROOT directory
if [ -n "$PDG_ROOT" ]; then
    cd "$PDG_ROOT"
elif [ -f "tools/echo_tcp.js" ]; then
    # we're already in the right place
    :
else
    # try to find the PDG_ROOT by looking for tools/echo_tcp.js
    _SD=`pwd`
    while [ "`pwd`" != '/' ]; do
        if [ -f "tools/echo_tcp.js" ]; then
            break
        fi
        cd ..
    done
    if [ ! -f "tools/echo_tcp.js" ]; then
        echo "Error: Could not find tools/echo_tcp.js. Please run from PDG_ROOT directory or set PDG_ROOT environment variable."
        exit 1
    fi
    cd "$_SD"
fi

# start an echo server
"$NODE_BIN" "$PDG_ROOT/tools/echo_tcp.js" > /dev/null &

PDG_DEBUG="$PDG_DEBUG" NODE_DEBUG="$NODE_DEBUG" "$NODE_BIN" "$PDG_ROOT/test/node_test.js" "$@"
EXIT_CODE=$?

# kill the echo server
kill %1

exit $EXIT_CODE
