Pixel Dust Game Engine: Port Class Reference
Port Class Reference
Graphics
#include <port.h>
Public Member Functions
Rect getDrawingArea ()
Rect getClipRect ()
void setClipRect (const Rect &rect)
void fillRect (const Rect &r, Color rgba=PDG_BLACK_COLOR)
you can also pass in a RotatedRect instead of a Quad, since the conversion is automatic
void fillRect (const RotatedRect &rr, Color rgba=PDG_BLACK_COLOR)
void fillRect (const Quad &quad, Color rgba=PDG_BLACK_COLOR)
void frameRect (const Rect &r, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void frameRect (const RotatedRect &rr, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void frameRect (const Quad &quad, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void drawLine (const Point &from, const Point &to, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void drawSpline (const Spline &spline, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f, int numSegments=50)
void fillPolygon (const Polygon &poly, Color rgba=PDG_BLACK_COLOR)
void framePolygon (const Polygon &poly, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void frameOval (const Point &centerPt, float xRadius, float yRadius, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void fillOval (const Point &centerPt, float xRadius, float yRadius, Color rgba=PDG_BLACK_COLOR)
void frameCircle (const Point &centerPt, float radius, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void fillCircle (const Point &centerPt, float radius, Color rgba=PDG_BLACK_COLOR)
void frameRoundRect (const Rect &rect, float radius, Color rgba=PDG_BLACK_COLOR, float thickness=1.0f)
void fillRoundRect (const Rect &rect, float radius, Color rgba=PDG_BLACK_COLOR)
void fillRectWithGradient (const Rect &r, Color startColor, Color endColor)
you can also pass in a Rect or a RotatedRect instead of a Quad, since the conversion is automatic
void fillRectWithGradient (const RotatedRect &rr, Color startColor, Color endColor)
void fillRectWithGradient (const Quad &quad, Color startColor, Color endColor)
void drawImage (Image *img, const Point &loc)
draws image at given location
void drawImage (Image *img, const Rect &r)
draws image into a given rectangle, scaling as needed
void drawImage (Image *img, const Rect &r, FitType fitType, bool clipOverflow=false)
draws image into a given rectangle, scaling as specified to fit, with optional clipping
void drawImage (Image *img, const RotatedRect &rr)
draws image at given location, scaling if necessary to fit
void drawImage (Image *img, const Quad &quad)
draws image into a given quad-polygon, mapping each of the corners to the corresponding points
void drawImage (ImageStrip *img, int frame, const Point &loc)
draws single frame of multiframe image at given location
void drawImage (ImageStrip *img, int frame, const Rect &r)
draws single frame of multiframe image into a given rectangle, scaling as needed
void drawImage (ImageStrip *img, int frame, const Rect &r, FitType fitType, bool clipOverflow=false)
draws single frame of multiframe image into a given rectangle, scaling as specified to fit, with optional clipping
void drawImage (ImageStrip *img, int frame, const RotatedRect &rr)
draws single frame of multiframe image at given location, scaling if necessary to fit
void drawImage (ImageStrip *img, int frame, const Quad &quad)
draws single frame of multiframe image into a given quad-polygon, mapping each of the corners to the corresponding points
void drawTexture (Image *img, const Rect &r)
draws image as texture filling given area, replicating as needed to fill entire area
void drawTexture (ImageStrip *img, int frame, const Rect &r)
draws single frame of multiframe image as texture filling given area, replicating as needed to fill entire area
void drawTexturedSphere (Image *img, const Point &loc, float radius, float rotation=0.0f, const Offset &polarOffsetRadians=Offset(0, 0), const Offset &lightOffsetRadians=Offset(0, 0))
draws image as texture wrapped around a sphere
void drawTexturedSphere (ImageStrip *img, int frame, const Point &loc, float radius, float rotation=0.0f, const Offset &polarOffsetRadians=Offset(0, 0), const Offset &lightOffsetRadians=Offset(0, 0))
draws single frame of multiframe image as texture wrapped around a sphere
void drawText (const char *text, const Point &loc, int size, uint32 style=textStyle_Plain, Color rgba=PDG_BLACK_COLOR)
void drawText (const char *text, const Rect &r, int size, uint32 style=textStyle_Plain, Color rgba=PDG_BLACK_COLOR)
void drawText (const char *text, const RotatedRect &rr, int size, uint32 style=textStyle_Plain, Color rgba=PDG_BLACK_COLOR)
void drawText (const char *text, const Quad &quad, int size, uint32 style=textStyle_Plain, Color rgba=PDG_BLACK_COLOR)
int getTextWidth (const char *text, int size, uint32 style=textStyle_Plain, int len=-1)
Font * getCurrentFont (uint32 style=textStyle_Plain)
void setFont (Font *font=0)
void setFontForStyle (Font *font, uint32 style)
void setFontScalingFactor (float scaleBy)
int startTrackingMouse (const Rect &rect, void *userData=0)
void stopTrackingMouse (int trackingRef)
void setCursor (Image *cursorImage, const Point &hotSpot)
Image * getCursor ()
void resetCursor ()
Detailed Description
Graphics A collection of static enumerations that are used when drawing
Port An area in which drawing is done, a viewport. This could be a full screen drawing context or a window.
Member Function Documentation
drawImage() [1/10]
void drawImage (Image * img, const Point & loc)
draws image at given location
Referenced by drawImage(), drawImage(), drawImage(), and drawImage().
drawImage() [2/10]
void drawImage (Image * img, const Quad & quad)
draws image into a given quad-polygon, mapping each of the corners to the corresponding points
drawImage() [3/10]
void drawImage (Image * img, const Rect & r) inline
draws image into a given rectangle, scaling as needed
References drawImage().
drawImage() [4/10]
void drawImage (Image * img, const Rect & r, FitType fitType, bool clipOverflow = false)
draws image into a given rectangle, scaling as specified to fit, with optional clipping
drawImage() [5/10]
void drawImage (Image * img, const RotatedRect & rr) inline
draws image at given location, scaling if necessary to fit
References drawImage().
drawImage() [6/10]
void drawImage (ImageStrip * img, int frame, const Point & loc)
draws single frame of multiframe image at given location
drawImage() [7/10]
void drawImage (ImageStrip * img, int frame, const Quad & quad)
draws single frame of multiframe image into a given quad-polygon, mapping each of the corners to the corresponding points
drawImage() [8/10]
void drawImage (ImageStrip * img, int frame, const Rect & r) inline
draws single frame of multiframe image into a given rectangle, scaling as needed
References drawImage().
drawImage() [9/10]
void drawImage (ImageStrip * img, int frame, const Rect & r, FitType fitType, bool clipOverflow = false)
draws single frame of multiframe image into a given rectangle, scaling as specified to fit, with optional clipping
drawImage() [10/10]
void drawImage (ImageStrip * img, int frame, const RotatedRect & rr) inline
draws single frame of multiframe image at given location, scaling if necessary to fit
References drawImage().
drawLine()
void drawLine (const Point & from, const Point & to, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f)
drawSpline()
void drawSpline (const Spline & spline, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f, int numSegments = 50)
drawText() [1/4]
void drawText (const char * text, const Point & loc, int size, uint32 style = textStyle_Plain, Color rgba = PDG_BLACK_COLOR)
References pdg::textStyle_Plain.
Referenced by drawText(), and drawText().
drawText() [2/4]
void drawText (const char * text, const Quad & quad, int size, uint32 style = textStyle_Plain, Color rgba = PDG_BLACK_COLOR)
References pdg::textStyle_Plain.
drawText() [3/4]
void drawText (const char * text, const Rect & r, int size, uint32 style = textStyle_Plain, Color rgba = PDG_BLACK_COLOR) inline
References drawText().
drawText() [4/4]
void drawText (const char * text, const RotatedRect & rr, int size, uint32 style = textStyle_Plain, Color rgba = PDG_BLACK_COLOR) inline
References drawText().
drawTexture() [1/2]
void drawTexture (Image * img, const Rect & r)
draws image as texture filling given area, replicating as needed to fill entire area
drawTexture() [2/2]
void drawTexture (ImageStrip * img, int frame, const Rect & r)
draws single frame of multiframe image as texture filling given area, replicating as needed to fill entire area
drawTexturedSphere() [1/2]
void drawTexturedSphere (Image * img, const Point & loc, float radius, float rotation = 0.0f, const Offset & polarOffsetRadians = Offset(0, 0), const Offset & lightOffsetRadians = Offset(0, 0))
draws image as texture wrapped around a sphere
drawTexturedSphere() [2/2]
void drawTexturedSphere (ImageStrip * img, int frame, const Point & loc, float radius, float rotation = 0.0f, const Offset & polarOffsetRadians = Offset(0, 0), const Offset & lightOffsetRadians = Offset(0, 0))
draws single frame of multiframe image as texture wrapped around a sphere
fillCircle()
void fillCircle (const Point & centerPt, float radius, Color rgba = PDG_BLACK_COLOR)
fillOval()
void fillOval (const Point & centerPt, float xRadius, float yRadius, Color rgba = PDG_BLACK_COLOR)
fillPolygon()
void fillPolygon (const Polygon & poly, Color rgba = PDG_BLACK_COLOR)
fillRect() [1/3]
void fillRect (const Quad & quad, Color rgba = PDG_BLACK_COLOR)
fillRect() [2/3]
void fillRect (const Rect & r, Color rgba = PDG_BLACK_COLOR) inline
you can also pass in a RotatedRect instead of a Quad, since the conversion is automatic
References fillRect().
Referenced by fillRect(), and fillRect().
fillRect() [3/3]
void fillRect (const RotatedRect & rr, Color rgba = PDG_BLACK_COLOR) inline
References fillRect().
fillRectWithGradient() [1/3]
void fillRectWithGradient (const Quad & quad, Color startColor, Color endColor)
fillRectWithGradient() [2/3]
void fillRectWithGradient (const Rect & r, Color startColor, Color endColor) inline
you can also pass in a Rect or a RotatedRect instead of a Quad, since the conversion is automatic
References fillRectWithGradient().
Referenced by fillRectWithGradient(), and fillRectWithGradient().
fillRectWithGradient() [3/3]
void fillRectWithGradient (const RotatedRect & rr, Color startColor, Color endColor) inline
References fillRectWithGradient().
fillRoundRect()
void fillRoundRect (const Rect & rect, float radius, Color rgba = PDG_BLACK_COLOR)
frameCircle()
void frameCircle (const Point & centerPt, float radius, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f)
frameOval()
void frameOval (const Point & centerPt, float xRadius, float yRadius, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f)
framePolygon()
void framePolygon (const Polygon & poly, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f)
frameRect() [1/3]
void frameRect (const Quad & quad, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f)
frameRect() [2/3]
void frameRect (const Rect & r, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f) inline
References frameRect().
Referenced by frameRect(), and frameRect().
frameRect() [3/3]
void frameRect (const RotatedRect & rr, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f) inline
References frameRect().
frameRoundRect()
void frameRoundRect (const Rect & rect, float radius, Color rgba = PDG_BLACK_COLOR, float thickness = 1.0f)
getClipRect()
Rect getClipRect ()
getCurrentFont()
Font * getCurrentFont (uint32 style = textStyle_Plain)
References pdg::textStyle_Plain.
getCursor()
Image * getCursor ()
getDrawingArea()
Rect getDrawingArea ()
getTextWidth()
int getTextWidth (const char * text, int size, uint32 style = textStyle_Plain, int len = -1)
References pdg::textStyle_Plain.
resetCursor()
void resetCursor ()
setClipRect()
void setClipRect (const Rect & rect)
setCursor()
void setCursor (Image * cursorImage, const Point & hotSpot)
setFont()
void setFont (Font * font = 0)
setFontForStyle()
void setFontForStyle (Font * font, uint32 style)
setFontScalingFactor()
void setFontScalingFactor (float scaleBy)
startTrackingMouse()
int startTrackingMouse (const Rect & rect, void * userData = 0)
stopTrackingMouse()
void stopTrackingMouse (int trackingRef)