Pixel Dust Game Engine: Sprite Class Reference
Sprite Class Reference
#include <sprite.h>
Public Types
enum {
animate_StartToEnd = 0 ,
animate_EndToStart = 1 ,
animate_Unidirectional = 0 ,
animate_Bidirectional = 2 ,
animate_NoLooping = 0 ,
animate_Looping = 4 ,
start_FromFirstFrame = -1 ,
start_FromLastFrame = -2 ,
all_Frames = 0 ,
action_CollideSprite = 0 ,
action_CollideWall = 1 ,
action_Offscreen = 2 ,
action_Onscreen = 3 ,
action_ExitLayer = 4 ,
action_AnimationLoop = 8 ,
action_AnimationEnd = 9 ,
action_FadeComplete = 10 ,
action_FadeInComplete = 11 ,
action_FadeOutComplete = 12 ,
action_JointBreak = 13 ,
action_SpriterTrigger = 14 ,
action_AnimationBlendComplete = 15 ,
touch_MouseEnter = 20 ,
touch_MouseLeave = 21 ,
touch_MouseDown = 22 ,
touch_MouseUp = 23 ,
touch_MouseClick = 24 ,
collide_None = 0 ,
collide_Point = 1 ,
collide_BoundingBox = 2 ,
collide_CollisionRadius = 3 ,
collide_AlphaChannel = 4 ,
collide_SpriterCollisionBox = 5 ,
collide_Last = collide_SpriterCollisionBox
}
Public Member Functions
SERIALIZABLE_TAG (CLASSTAG_SPRITE)
SERIALIZABLE_METHODS ()
RotatedRect getFrameRotatedBounds (int frameNum=-1)
Sprite & setFrame (int frame)
int getCurrentFrame ()
int getFrameCount ()
void startFrameAnimation (float fps, int startingFrame=start_FromFirstFrame, int numFrames=all_Frames, int animateFlags=animate_Looping)
void stopFrameAnimation ()
bool getWantsAnimLoopEvents ()
bool getWantsAnimEndEvents ()
Sprite & setWantsAnimLoopEvents (bool wantsThem=true)
Sprite & setWantsAnimEndEvents (bool wantsThem=true)
void addFramesImage (Image *image, int startingFrame=start_FromFirstFrame, int numFrames=all_Frames)
void setDrawHelper (ISpriteDrawHelper *helper)
void setPostDrawHelper (ISpriteDrawHelper *helper)
void changeFramesImage (Image *oldImage, Image *newImage)
void offsetFrameCenters (int offsetX, int offsetY, Image *image=0, int startingFrame=start_FromFirstFrame, int numFrames=all_Frames)
Offset getFrameCenterOffset (Image *image=0, int frameNum=0)
Sprite & setOpacity (float opacity)
float getOpacity ()
void fadeTo (float targetOpacity, ms_delta msDuration, EasingFunc easing=linearTween)
void fadeIn (ms_delta msDuration, EasingFunc easing=linearTween)
void fadeOut (ms_delta msDuration, EasingFunc easing=linearTween)
Sprite & moveBehind (Sprite *sprite)
Sprite & moveInFrontOf (Sprite *sprite)
Sprite & moveToFront ()
Sprite & moveToBack ()
int getZOrder ()
bool isBehind (Sprite *sprite)
bool getWantsCollideWallEvents ()
Sprite & setWantsCollideWallEvents (bool wantsThem=true)
Sprite & enableCollisions (int collisionType=collide_AlphaChannel)
Sprite & disableCollisions ()
int getCollisionType () const
Sprite & setCollisionRadius (float pixelRadius)
float getCollisionRadius ()
void useCollisionMask (Image *frameImage, Image *maskImage)
void setCollisionHelper (ISpriteCollideHelper *helper)
Sprite & setElasticity (float elasticity)
float getElasticity ()
bool getWantsMouseOverEvents ()
bool getWantsClickEvents ()
int getMouseDetectMode ()
bool getWantsOffscreenEvents ()
Sprite & setWantsMouseOverEvents (bool wantsThem=true)
Sprite & setWantsClickEvents (bool wantsThem=true)
Sprite & setMouseDetectMode (int collisionType=collide_BoundingBox)
Sprite & setWantsOffscreenEvents (bool wantsThem=true)
void setUserData (UserData *userData)
void freeUserData ()
SpriteLayer * getLayer ()
Public Member Functions inherited from EventEmitter
virtual void addHandler (IEventHandler *inHandler, long inType=all_events)
add a new handler for some event type, or for all events if no type specified
virtual void removeHandler (IEventHandler *inHandler, long inType=all_events)
Remove a handler for some event type, or for all events if no type specified.
virtual void clear (bool doRelease=true)
remove all handlers
virtual void blockEvent (long inEventType)
temporarily ignore all events of a particular type, just drop them on the floor
virtual void unblockEvent (long inEventType)
stop ignoring events of a particular type, no recovery of previously ignored events
EventEmitter ()
constructor for new event emitter
virtual bool postEvent (long inEventType, void *inEventData, EventEmitter *fromEmitter=0)
post an event for immediate handling locally, or relay it to the EventManger
Public Member Functions inherited from Animated
SERIALIZABLE_TAG (CLASSTAG_ANIMATED)
SERIALIZABLE_METHODS ()
Rect getBoundingBox ()
RotatedRect getRotatedBounds ()
Animated & setLocation (const Point &loc)
Point getLocation ()
Animated & moveTo (float x, float y)
Animated & moveTo (const Point &where)
Animated & move (float deltaX, float deltaY)
Animated & move (const Offset &delta)
virtual void moveTo (const Point &loc, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void moveTo (float x, float y, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void move (float deltaX, float deltaY, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void move (const Offset &delta, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
virtual Animated & setVelocity (const Vector &deltaPerSec)
virtual Vector getVelocity ()
Animated & setSpeed (float speed)
float getSpeed ()
Animated & setVelocityInRadians (float speed, float direction)
float getMovementDirectionInRadians ()
Animated & setVelocity (float deltaXPerSec, float deltaYPerSec)
Animated & stopMoving ()
virtual void accelerateTo (float speed, ms_delta msDuration, EasingFunc easing=linearTween)
void accelerate (float deltaSpeed, ms_delta msDuration, EasingFunc easing=linearTween)
Animated & setSize (float width, float height)
Animated & setWidth (float width)
float getWidth ()
Animated & setHeight (float height)
float getHeight ()
Animated & grow (float factor)
Animated & stretch (float widthFactor, float heightFactor)
Animated & startGrowing (float amountPerSecond)
Animated & stopGrowing ()
Animated & startStretching (float widthPerSecond, float heightPerSecond)
Animated & stopStretching ()
virtual void resizeTo (float width, float height, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void resize (float deltaWidth, float deltaHeight, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void grow (float factor, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void stretch (float widthFactor, float weightFactor, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
Animated & setRotation (float radiansRotation)
float getRotation ()
Animated & setCenterOffset (const Offset &offset)
Offset getCenterOffset ()
Animated & rotateTo (float radiansRotation)
Animated & rotate (float radians)
Animated & setSpin (float radiansPerSecond)
float getSpin ()
Animated & stopSpinning ()
Animated & setFlipX (bool flip)
Animated & setFlipY (bool flip)
Animated & flipX ()
Animated & flipY ()
bool isFlippedX ()
bool isFlippedY ()
virtual void rotateTo (float radiansRotation, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void rotate (float radians, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenterTo (float xOffset, float yOffset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenterTo (const Offset &offset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenter (float deltaXOffset, float deltaYOffset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenter (const Offset &offset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
Animated * wait (ms_delta msDuration)
virtual Animated & setMass (float mass)
float getMass ()
virtual Animated & setFriction (float frictionCoefficient)
Animated & setMoveFriction (float frictionCoefficient)
Animated & setSpinFriction (float frictionCoefficient)
Animated & setSizeFriction (float frictionCoefficient)
float getMoveFriction ()
float getSpinFriction ()
float getSizeFriction ()
virtual void applyForce (const Vector &force, ms_delta msDuration=duration_Instantaneous)
virtual void applyForce (float forceX, float forceY, ms_delta msDuration=duration_Instantaneous)
virtual void applyTorque (float forceSpin, ms_delta msDuration=duration_Instantaneous)
virtual void stopAllForces ()
virtual void addAnimationHelper (IAnimationHelper *helper)
virtual void removeAnimationHelper (IAnimationHelper *helper)
virtual void clearAnimationHelpers ()
Public Member Functions inherited from ISerializable
virtual uint32 getSerializedSize (ISerializer *serializer) const =0
Get number of bytes needed to hold serialized state.
virtual void serialize (ISerializer *serializer) const =0
Write self out to a serializer.
virtual void deserialize (IDeserializer *deserializer)=0
Read self from a deserializer.
virtual uint32 getMyClassTag () const =0
Get a tag value that uniquely represents this class.
ISerializable ()
virtual ~ISerializable ()
Public Member Functions inherited from RefCountedObj
virtual void addRef () const throw ()
virtual void release () const throw ()
Static Public Member Functions
static pdg::ISerializable * CreateInstance ()
Static Public Member Functions inherited from Animated
static pdg::ISerializable * CreateInstance ()
Public Attributes
long spriteId
bool wantsMouseOver
bool wantsClicks
bool wantsAnimLoop
bool wantsAnimEnd
bool wantsOffscreen
bool wantsWallCollide
UserData * userData
Friends
class SpriteLayer
class TileLayer
class SpriteManager
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
animate_StartToEnd
animate_EndToStart
animate_Unidirectional
animate_Bidirectional
animate_NoLooping
animate_Looping
start_FromFirstFrame
start_FromLastFrame
all_Frames
action_CollideSprite
action_CollideWall
action_Offscreen
action_Onscreen
action_ExitLayer
action_AnimationLoop
action_AnimationEnd
action_FadeComplete
action_FadeInComplete
action_FadeOutComplete
action_JointBreak
action_SpriterTrigger
action_AnimationBlendComplete
touch_MouseEnter
touch_MouseLeave
NOT IMPLEMENTED
touch_MouseDown
NOT IMPLEMENTED
touch_MouseUp
touch_MouseClick
collide_None
collide_Point
collide_BoundingBox
collide_CollisionRadius
collide_AlphaChannel
collide_SpriterCollisionBox
collide_Last
Member Function Documentation
addFramesImage()
void addFramesImage (Image * image, int startingFrame = start_FromFirstFrame, int numFrames = all_Frames)
References all_Frames, and start_FromFirstFrame.
changeFramesImage()
void changeFramesImage (Image * oldImage, Image * newImage)
CreateInstance()
pdg::ISerializable * CreateInstance () inline static
disableCollisions()
Sprite & disableCollisions ()
enableCollisions()
Sprite & enableCollisions (int collisionType = collide_AlphaChannel)
References collide_AlphaChannel.
fadeIn()
void fadeIn (ms_delta msDuration, EasingFunc easing = linearTween)
References pdg::linearTween().
fadeOut()
void fadeOut (ms_delta msDuration, EasingFunc easing = linearTween)
References pdg::linearTween().
fadeTo()
void fadeTo (float targetOpacity, ms_delta msDuration, EasingFunc easing = linearTween)
References pdg::linearTween().
freeUserData()
void freeUserData ()
getCollisionRadius()
float getCollisionRadius ()
getCollisionType()
int getCollisionType () const inline
getCurrentFrame()
int getCurrentFrame ()
getElasticity()
float getElasticity ()
getFrameCenterOffset()
Offset getFrameCenterOffset (Image * image = 0, int frameNum = 0)
getFrameCount()
int getFrameCount () inline
getFrameRotatedBounds()
RotatedRect getFrameRotatedBounds (int frameNum = -1)
getLayer()
SpriteLayer * getLayer () inline
References SpriteLayer.
getMouseDetectMode()
int getMouseDetectMode () inline
getOpacity()
float getOpacity ()
getWantsAnimEndEvents()
bool getWantsAnimEndEvents () inline
References wantsAnimEnd.
getWantsAnimLoopEvents()
bool getWantsAnimLoopEvents () inline
References wantsAnimLoop.
getWantsClickEvents()
bool getWantsClickEvents () inline
References wantsClicks.
getWantsCollideWallEvents()
bool getWantsCollideWallEvents () inline
References wantsWallCollide.
getWantsMouseOverEvents()
bool getWantsMouseOverEvents () inline
References wantsMouseOver.
getWantsOffscreenEvents()
bool getWantsOffscreenEvents () inline
References wantsOffscreen.
getZOrder()
int getZOrder ()
isBehind()
bool isBehind (Sprite * sprite)
moveBehind()
Sprite & moveBehind (Sprite * sprite)
Referenced by moveToBack().
moveInFrontOf()
Sprite & moveInFrontOf (Sprite * sprite)
Referenced by moveToFront().
moveToBack()
Sprite & moveToBack () inline
References moveBehind().
moveToFront()
Sprite & moveToFront () inline
References moveInFrontOf().
offsetFrameCenters()
void offsetFrameCenters (int offsetX, int offsetY, Image * image = 0, int startingFrame = start_FromFirstFrame, int numFrames = all_Frames)
References all_Frames, and start_FromFirstFrame.
SERIALIZABLE_METHODS()
SERIALIZABLE_METHODS ()
SERIALIZABLE_TAG()
SERIALIZABLE_TAG (CLASSTAG_SPRITE)
setCollisionHelper()
void setCollisionHelper (ISpriteCollideHelper * helper)
setCollisionRadius()
Sprite & setCollisionRadius (float pixelRadius)
setDrawHelper()
void setDrawHelper (ISpriteDrawHelper * helper)
setElasticity()
Sprite & setElasticity (float elasticity)
setFrame()
Sprite & setFrame (int frame)
setMouseDetectMode()
Sprite & setMouseDetectMode (int collisionType = collide_BoundingBox)
References collide_BoundingBox, and pdg::duration_Instantaneous.
setOpacity()
Sprite & setOpacity (float opacity)
setPostDrawHelper()
void setPostDrawHelper (ISpriteDrawHelper * helper)
setUserData()
void setUserData (UserData * userData)
References userData.
setWantsAnimEndEvents()
Sprite & setWantsAnimEndEvents (bool wantsThem = true) inline
References wantsAnimEnd.
setWantsAnimLoopEvents()
Sprite & setWantsAnimLoopEvents (bool wantsThem = true) inline
References wantsAnimLoop.
setWantsClickEvents()
Sprite & setWantsClickEvents (bool wantsThem = true)
setWantsCollideWallEvents()
Sprite & setWantsCollideWallEvents (bool wantsThem = true) inline
References wantsWallCollide.
setWantsMouseOverEvents()
Sprite & setWantsMouseOverEvents (bool wantsThem = true)
setWantsOffscreenEvents()
Sprite & setWantsOffscreenEvents (bool wantsThem = true) inline
References wantsOffscreen.
startFrameAnimation()
void startFrameAnimation (float fps, int startingFrame = start_FromFirstFrame, int numFrames = all_Frames, int animateFlags = animate_Looping)
References all_Frames, animate_Looping, and start_FromFirstFrame.
stopFrameAnimation()
void stopFrameAnimation ()
useCollisionMask()
void useCollisionMask (Image * frameImage, Image * maskImage)
Friends And Related Symbol Documentation
SpriteLayer
friend class SpriteLayer friend
References SpriteLayer.
Referenced by getLayer(), and SpriteLayer.
SpriteManager
friend class SpriteManager friend
References SpriteManager.
Referenced by SpriteManager.
TileLayer
friend class TileLayer friend
References TileLayer.
Referenced by TileLayer.
Member Data Documentation
spriteId
long spriteId
userData
UserData* userData
Referenced by setUserData().
wantsAnimEnd
bool wantsAnimEnd
Referenced by getWantsAnimEndEvents(), and setWantsAnimEndEvents().
wantsAnimLoop
bool wantsAnimLoop
Referenced by getWantsAnimLoopEvents(), and setWantsAnimLoopEvents().
wantsClicks
bool wantsClicks
Referenced by getWantsClickEvents().
wantsMouseOver
bool wantsMouseOver
Referenced by getWantsMouseOverEvents().
wantsOffscreen
bool wantsOffscreen
Referenced by getWantsOffscreenEvents(), and setWantsOffscreenEvents().
wantsWallCollide
bool wantsWallCollide
Referenced by getWantsCollideWallEvents(), and setWantsCollideWallEvents().