Pixel Dust Game Engine: Deserializer Class Reference
Deserializer Class Reference
Serialization
#include <deserializer.h>
Public Member Functions
virtual uint64 deserialize_8u ()
Deserialize an 8 byte (64 bit) value.
virtual uint32 deserialize_4u ()
Deserialize a 4 byte (32 bit) value.
virtual uint32 deserialize_3u ()
Deserialize a 3 byte (24 bit) value.
virtual uint16 deserialize_2u ()
Deserialize a 2 byte (16 bit) value.
virtual uint8 deserialize_1u ()
Deserialize an 1 byte (8 bit) value.
virtual bool deserialize_bool ()
Deserialize a boolean (1 bit) value.
virtual uint32 deserialize_uint ()
Deserialize an unsigned value.
virtual Color deserialize_color () MAY_THROW(out_of_data)
Deserialize a pdg::Color value.
virtual Offset deserialize_offset () MAY_THROW(out_of_data)
Deserialize a pdg::Offset value.
virtual Rect deserialize_rect () MAY_THROW(out_of_data)
Deserialize a pdg::Rect.
virtual RotatedRect deserialize_rotr () MAY_THROW(out_of_data)
Deserialize a pdg::RotatedRect.
virtual Quad deserialize_quad () MAY_THROW(out_of_data)
Deserialize a pdg::Quad.
virtual uint32 deserialize_str (char *outStr, size_t strMaxLen)
Deserialize a string value.
virtual uint32 deserialize_strGetLen ()
get length of a string value, as if it were deserialized
virtual uint32 deserialize_mem (void *outMem, uint32 memMaxLen)
Deserialize an arbitrary block of memory.
virtual uint32 deserialize_memGetLen ()
Deserialize a string value.
virtual ISerializable * deserialize_obj ()
Deserialize a serializable object.
void setDataPtr (void *ptr, uint32 ptrSize)
Deserializer ()
Deserializer (void *ptr, uint32 ptrSize)
virtual ~Deserializer ()
Public Member Functions inherited from IDeserializer
int64 deserialize_8 () MAY_THROW(out_of_data)
int32 deserialize_4 () MAY_THROW(out_of_data)
int16 deserialize_2 () MAY_THROW(out_of_data)
int8 deserialize_1 () MAY_THROW(out_of_data)
float deserialize_f () MAY_THROW(out_of_data)
Serialize a floating point value into a buffer.
double deserialize_d () MAY_THROW(out_of_data)
Serialize a double precision floating point value into a buffer.
Point deserialize_point () MAY_THROW(out_of_data)
Deserialize a pdg::Point value.
Vector deserialize_vector () MAY_THROW(out_of_data)
Deserialize a pdg::Vector value.
void deserialize_string (std::string &outStr) MAY_THROW((out_of_data
Deserialize a string value into a std::string.
template<typename T>
T * deserialize_ref () MAY_THROW((out_of_data
Deserialize a reference to a non-serializable object.
Protected Member Functions
virtual char * statusDump (int hiliteBytes=0)
virtual void * deserialize_ptr ()
Protected Member Functions inherited from IDeserializer
IDeserializer ()
Protected Attributes
uint8 * mDataPtr
uint8 * mDataEnd
uint8 * p
uint32 mDataSize
uint8 mLastBoolByte
int mBoolBitOffset
bool mUsingTags
std::vector< ISerializable * > mDeserializedInstances
Protected Attributes inherited from IDeserializer
virtual void bad_tag
virtual void sync_error
virtual void unknown_object = 0
Additional Inherited Members
Public Types inherited from IDeserializer
typedef ISerializable *(* CreateSerializableFunc) ()
Static Public Member Functions inherited from IDeserializer
template<class T>
static void registerClass ()
Register a class that is derived from Serializable.
static void registerClass (uint32 classTag, CreateSerializableFunc classNewFunc)
Register a class that is derived from ISerializable.
static void registerObject (void *obj, uint32 uniqueId)
Register object that is not serializable for use with |de|serialize_ref()
Public Attributes inherited from IDeserializer
int traceDepth
virtual uint32 bad_tag = 0
void bad_tag
virtual ISerializable bad_tag
virtual ISerializable sync_error
virtual ISerializable unknown_object = 0
T bad_tag
T sync_error
T unknown_object
Detailed Description
A class to serialize data into memory
Constructor & Destructor Documentation
Deserializer() [1/2]
Deserializer ()
References Deserializer().
Referenced by Deserializer(), Deserializer(), and ~Deserializer().
Deserializer() [2/2]
Deserializer (void * ptr, uint32 ptrSize)
References Deserializer().
~Deserializer()
virtual ~Deserializer () virtual
References Deserializer().
Member Function Documentation
deserialize_1u()
virtual uint8 deserialize_1u () virtual
Deserialize an 1 byte (8 bit) value.
internal pointer is advanced 1 btye
Returns
the deserialized 8 bit value
Implements IDeserializer.
deserialize_2u()
virtual uint16 deserialize_2u () virtual
Deserialize a 2 byte (16 bit) value.
internal pointer is advanced 2 btyes
Returns
the deserialized 16 bit value
Implements IDeserializer.
deserialize_3u()
virtual uint32 deserialize_3u () virtual
Deserialize a 3 byte (24 bit) value.
internal pointer is advanced 3 btyes
Returns
the deserialized 24 bit value
Implements IDeserializer.
deserialize_4u()
virtual uint32 deserialize_4u () virtual
Deserialize a 4 byte (32 bit) value.
internal pointer is advanced 4 btyes
Returns
the deserialized 32 bit value
Implements IDeserializer.
deserialize_8u()
virtual uint64 deserialize_8u () virtual
Deserialize an 8 byte (64 bit) value.
internal pointer is advanced 8 btyes
Returns
the deserialized 64 bit value
Implements IDeserializer.
deserialize_bool()
virtual bool deserialize_bool () virtual
Deserialize a boolean (1 bit) value.
internal pointer gets advanced by 1 or 0 bytes, depending on bytes required to store the value
Returns
the boolean that was deserialized This is optimized for series of boolean values, so that between 1 and 8 bools serialized sequentially only use a single byte
Implements IDeserializer.
deserialize_color()
virtual Color deserialize_color () virtual
Deserialize a pdg::Color value.
internal pointer is advanced by ? bytes, depending on bytes required to store value
Returns
the Color that was deserialized
Implements IDeserializer.
deserialize_mem()
virtual uint32 deserialize_mem (void * outMem, uint32 memMaxLen) virtual
Deserialize an arbitrary block of memory.
Parameters
p a reference to a buffer pointer; pointer gets advanced past mem block to start of next entity in buffer
outMem,a buffer to hold the resulting block of memory
memMaxLen,the max length of the output block, that the buffer can accomodate If the serialized string is longer than outStrMaxLen, it will be truncated and the buffer pointer p will still be advanced past the string to the start of the next entity in the buffer.
Returns
the length of the string in bytes
Reimplemented from IDeserializer.
References deserialize_mem().
Referenced by deserialize_mem().
deserialize_memGetLen()
virtual uint32 deserialize_memGetLen () virtual
Deserialize a string value.
internal pointer is NOT advanced. Use this to pre-flight allocation for blocks of memory
Returns
the length of the serialized block of memory in bytes
Reimplemented from IDeserializer.
References deserialize_memGetLen().
Referenced by deserialize_memGetLen().
deserialize_obj()
virtual ISerializable * deserialize_obj () virtual
Deserialize a serializable object.
internal pointer gets advanced past object to start of next entity in buffer
Returns
NULL, or a newly created Serializable object NULL return happens if serialized object reference was null, or if the object could not be deserialized If object could not be deserialized, either because the subclass was unknown or because the data was corrupt, the internal pointer will still be advanced past the object to the start of the next entity in the buffer.
Reimplemented from IDeserializer.
References deserialize_obj().
Referenced by deserialize_obj().
deserialize_offset()
virtual Offset deserialize_offset () virtual
Deserialize a pdg::Offset value.
internal pointer is advanced by 1 to 9 bytes, depending on bytes required to store value
Returns
the Offset that was deserialized
Implements IDeserializer.
References deserialize_offset().
Referenced by deserialize_offset().
deserialize_ptr()
virtual void * deserialize_ptr () protected virtual
Reimplemented from IDeserializer.
deserialize_quad()
virtual Quad deserialize_quad () virtual
Deserialize a pdg::Quad.
internal pointer is advanced by 1, 3 or 5 bytes, depending on bytes required to store value
Returns
the Quad that was deserialized
Implements IDeserializer.
References deserialize_quad().
Referenced by deserialize_quad().
deserialize_rect()
virtual Rect deserialize_rect () virtual
Deserialize a pdg::Rect.
internal pointer is advanced by ? bytes, depending on bytes required to store value
Returns
the Rect that was deserialized
Implements IDeserializer.
References deserialize_rect().
Referenced by deserialize_rect().
deserialize_rotr()
virtual RotatedRect deserialize_rotr () virtual
Deserialize a pdg::RotatedRect.
internal pointer is advanced by ? bytes, depending on bytes required to store value
Returns
the RotatedRect that was deserialized
Implements IDeserializer.
References deserialize_rotr().
Referenced by deserialize_rotr().
deserialize_str()
virtual uint32 deserialize_str (char * outStr, size_t strMaxLen) virtual
Deserialize a string value.
Parameters
outStr,a buffer to hold the resulting string
strMaxLen,the max length of the output string, including the NUL terminator, that the buffer can accomodate If the serialized string is longer than outStrMaxLen, it will be truncated and the internal pointer p will still be advanced past the string to the start of the next entity in the internal buffer.
Returns
the length of the string in bytes
Reimplemented from IDeserializer.
References deserialize_str().
Referenced by deserialize_str().
deserialize_strGetLen()
virtual uint32 deserialize_strGetLen () virtual
get length of a string value, as if it were deserialized
internal pointer is NOT advanced. Use this to pre-flight allocation for longer strings
Returns
the length of the serialized string in bytes
Reimplemented from IDeserializer.
References deserialize_strGetLen().
Referenced by deserialize_strGetLen().
deserialize_uint()
virtual uint32 deserialize_uint () virtual
Deserialize an unsigned value.
internal pointer is advanced by 1, 3 or 5 bytes, depending on bytes required to store value
Returns
the unsigned value that was deserialized
Implements IDeserializer.
setDataPtr()
void setDataPtr (void * ptr, uint32 ptrSize)
References setDataPtr().
Referenced by setDataPtr().
statusDump()
virtual char * statusDump (int hiliteBytes = 0) protected virtual
Implements IDeserializer.
Member Data Documentation
mBoolBitOffset
int mBoolBitOffset protected
mDataEnd
uint8* mDataEnd protected
mDataPtr
uint8* mDataPtr protected
mDataSize
uint32 mDataSize protected
mDeserializedInstances
std::vector<ISerializable*> mDeserializedInstances protected
mLastBoolByte
uint8 mLastBoolByte protected
mUsingTags
bool mUsingTags protected
p
uint8* p protected