Pixel Dust Game Engine: PDGException Class Reference
PDGException Class Reference
#include <pdgexception.h>
Public Member Functions
PDGException (const char *desc)
virtual const char * what () const throw ()
Constructor & Destructor Documentation
PDGException()
PDGException (const char * desc) inline
Referenced by bad_tag::bad_tag(), out_of_data::out_of_data(), sync_error::sync_error(), and unknown_object::unknown_object().
Member Function Documentation
what()
virtual const char * what () const throw () inline virtual