Pixel Dust Game Engine: SpriteLayer Class Reference
SpriteLayer Class Reference
#include <spritelayer.h>
Public Types
enum {
addSprites = true ,
dontAddSprites = false ,
action_ErasePort = 40 ,
action_PreDrawLayer = 41 ,
action_PostDrawLayer = 42 ,
action_DrawPortComplete = 43 ,
action_AnimationStart = 44 ,
action_PreAnimateLayer = 45 ,
action_PostAnimateLayer = 46 ,
action_AnimationComplete = 47 ,
action_ZoomComplete = 48 ,
action_FadeInComplete = 49 ,
action_FadeOutComplete = 50
}
Public Member Functions
void setSerializationFlags (uint32 flags)
Port * getSpritePort () const
virtual void setSpritePort (Port *port)
virtual void startAnimations ()
virtual void stopAnimations ()
virtual void hide ()
virtual void show ()
virtual bool isHidden ()
virtual void fadeIn (ms_delta msDuration, EasingFunc easing=linearTween)
virtual void fadeOut (ms_delta msDuration, EasingFunc easing=linearTween)
virtual void moveBehind (SpriteLayer *layer)
virtual void moveInFrontOf (SpriteLayer *layer)
void moveToFront ()
void moveToBack ()
int getZOrder ()
virtual void moveWith (SpriteLayer *layer, float moveRatio=1.0f, float zoomRatio=1.0f)
void setOrigin (const Point &origin)
Point getOrigin () const
void setAutoCenter (bool autoCenter=true)
void setFixedMoveAxis (bool fixedAxis=true)
virtual void setZoom (float zoomLevel)
float getZoom () const
virtual void zoomTo (float zoomLevel, ms_delta msDuration, EasingFunc easing=easeInOutQuad, Rect keepInRect=Rect(0, 0), const Point *centerOn=0)
void zoom (float deltaZoomLevel, ms_delta msDuration, EasingFunc easing=easeInOutQuad, Rect keepInRect=Rect(0, 0), const Point *centerOn=0)
virtual Sprite * findSprite (long id)
virtual Sprite * getNthSprite (int index)
virtual int getSpriteZOrder (Sprite *sprite)
virtual bool isSpriteBehind (Sprite *sprite, Sprite *otherSprite)
virtual bool hasSprite (Sprite *sprite)
virtual void addSprite (Sprite *newSprite)
virtual void addSpriteInFrontOf (Sprite *newSprite, Sprite *targetSprite)
virtual void removeSprite (Sprite *oldSprite)
virtual void removeAllSprites ()
virtual void enableCollisions ()
virtual void disableCollisions ()
virtual void enableCollisionsWithLayer (SpriteLayer *otherLayer)
virtual void disableCollisionsWithLayer (SpriteLayer *otherLayer)
virtual Sprite * createSprite ()
virtual Sprite * cloneSprite (const Sprite *originalSprite)
virtual Point layerToPort (const Point &p) const
virtual Offset layerToPort (const Offset &p) const
virtual Vector layerToPort (const Vector &p) const
virtual RotatedRect layerToPort (const Rect &r) const
virtual RotatedRect layerToPort (const RotatedRect &r) const
virtual Quad layerToPort (const Quad &q) const
virtual Point portToLayer (const Point &p) const
virtual Offset portToLayer (const Offset &p) const
virtual Vector portToLayer (const Vector &p) const
virtual RotatedRect portToLayer (const Rect &r) const
virtual RotatedRect portToLayer (const RotatedRect &r) const
virtual Quad portToLayer (const Quad &q) const
Public Member Functions inherited from EventEmitter
virtual void addHandler (IEventHandler *inHandler, long inType=all_events)
add a new handler for some event type, or for all events if no type specified
virtual void removeHandler (IEventHandler *inHandler, long inType=all_events)
Remove a handler for some event type, or for all events if no type specified.
virtual void clear (bool doRelease=true)
remove all handlers
virtual void blockEvent (long inEventType)
temporarily ignore all events of a particular type, just drop them on the floor
virtual void unblockEvent (long inEventType)
stop ignoring events of a particular type, no recovery of previously ignored events
EventEmitter ()
constructor for new event emitter
virtual bool postEvent (long inEventType, void *inEventData, EventEmitter *fromEmitter=0)
post an event for immediate handling locally, or relay it to the EventManger
Public Member Functions inherited from Animated
SERIALIZABLE_TAG (CLASSTAG_ANIMATED)
SERIALIZABLE_METHODS ()
Rect getBoundingBox ()
RotatedRect getRotatedBounds ()
Animated & setLocation (const Point &loc)
Point getLocation ()
Animated & moveTo (float x, float y)
Animated & moveTo (const Point &where)
Animated & move (float deltaX, float deltaY)
Animated & move (const Offset &delta)
virtual void moveTo (const Point &loc, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void moveTo (float x, float y, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void move (float deltaX, float deltaY, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void move (const Offset &delta, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
virtual Animated & setVelocity (const Vector &deltaPerSec)
virtual Vector getVelocity ()
Animated & setSpeed (float speed)
float getSpeed ()
Animated & setVelocityInRadians (float speed, float direction)
float getMovementDirectionInRadians ()
Animated & setVelocity (float deltaXPerSec, float deltaYPerSec)
Animated & stopMoving ()
virtual void accelerateTo (float speed, ms_delta msDuration, EasingFunc easing=linearTween)
void accelerate (float deltaSpeed, ms_delta msDuration, EasingFunc easing=linearTween)
Animated & setSize (float width, float height)
Animated & setWidth (float width)
float getWidth ()
Animated & setHeight (float height)
float getHeight ()
Animated & grow (float factor)
Animated & stretch (float widthFactor, float heightFactor)
Animated & startGrowing (float amountPerSecond)
Animated & stopGrowing ()
Animated & startStretching (float widthPerSecond, float heightPerSecond)
Animated & stopStretching ()
virtual void resizeTo (float width, float height, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void resize (float deltaWidth, float deltaHeight, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void grow (float factor, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void stretch (float widthFactor, float weightFactor, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
Animated & setRotation (float radiansRotation)
float getRotation ()
Animated & setCenterOffset (const Offset &offset)
Offset getCenterOffset ()
Animated & rotateTo (float radiansRotation)
Animated & rotate (float radians)
Animated & setSpin (float radiansPerSecond)
float getSpin ()
Animated & stopSpinning ()
Animated & setFlipX (bool flip)
Animated & setFlipY (bool flip)
Animated & flipX ()
Animated & flipY ()
bool isFlippedX ()
bool isFlippedY ()
virtual void rotateTo (float radiansRotation, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void rotate (float radians, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenterTo (float xOffset, float yOffset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenterTo (const Offset &offset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenter (float deltaXOffset, float deltaYOffset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenter (const Offset &offset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
Animated * wait (ms_delta msDuration)
virtual Animated & setMass (float mass)
float getMass ()
virtual Animated & setFriction (float frictionCoefficient)
Animated & setMoveFriction (float frictionCoefficient)
Animated & setSpinFriction (float frictionCoefficient)
Animated & setSizeFriction (float frictionCoefficient)
float getMoveFriction ()
float getSpinFriction ()
float getSizeFriction ()
virtual void applyForce (const Vector &force, ms_delta msDuration=duration_Instantaneous)
virtual void applyForce (float forceX, float forceY, ms_delta msDuration=duration_Instantaneous)
virtual void applyTorque (float forceSpin, ms_delta msDuration=duration_Instantaneous)
virtual void stopAllForces ()
virtual void addAnimationHelper (IAnimationHelper *helper)
virtual void removeAnimationHelper (IAnimationHelper *helper)
virtual void clearAnimationHelpers ()
Public Member Functions inherited from ISerializable
virtual uint32 getSerializedSize (ISerializer *serializer) const =0
Get number of bytes needed to hold serialized state.
virtual void serialize (ISerializer *serializer) const =0
Write self out to a serializer.
virtual void deserialize (IDeserializer *deserializer)=0
Read self from a deserializer.
virtual uint32 getMyClassTag () const =0
Get a tag value that uniquely represents this class.
ISerializable ()
virtual ~ISerializable ()
Public Member Functions inherited from RefCountedObj
virtual void addRef () const throw ()
virtual void release () const throw ()
Public Member Functions inherited from Serializable< SpriteLayer >
virtual ~Serializable ()
Static Public Member Functions
static SpriteLayer * getLayer (long id)
Static Public Member Functions inherited from Animated
static pdg::ISerializable * CreateInstance ()
Static Public Member Functions inherited from Serializable< SpriteLayer >
static ISerializable * CreateInstance ()
Public Attributes
const float noZoom
long layerId
Friends
class Sprite
class SpriteManager
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
addSprites
dontAddSprites
action_ErasePort
action_PreDrawLayer
action_PostDrawLayer
action_DrawPortComplete
action_AnimationStart
action_PreAnimateLayer
action_PostAnimateLayer
action_AnimationComplete
action_ZoomComplete
action_FadeInComplete
action_FadeOutComplete
Member Function Documentation
addSprite()
virtual void addSprite (Sprite * newSprite) virtual
References Sprite.
addSpriteInFrontOf()
virtual void addSpriteInFrontOf (Sprite * newSprite, Sprite * targetSprite) virtual
References Sprite.
cloneSprite()
virtual Sprite * cloneSprite (const Sprite * originalSprite) virtual
References Sprite.
createSprite()
virtual Sprite * createSprite () virtual
References Sprite.
disableCollisions()
virtual void disableCollisions () virtual
disableCollisionsWithLayer()
virtual void disableCollisionsWithLayer (SpriteLayer * otherLayer) virtual
enableCollisions()
virtual void enableCollisions () virtual
enableCollisionsWithLayer()
virtual void enableCollisionsWithLayer (SpriteLayer * otherLayer) virtual
fadeIn()
virtual void fadeIn (ms_delta msDuration, EasingFunc easing = linearTween) virtual
References pdg::linearTween().
fadeOut()
virtual void fadeOut (ms_delta msDuration, EasingFunc easing = linearTween) virtual
References pdg::linearTween().
findSprite()
virtual Sprite * findSprite (long id) virtual
References Sprite.
getLayer()
SpriteLayer * getLayer (long id) static
getNthSprite()
virtual Sprite * getNthSprite (int index) virtual
References Sprite.
getOrigin()
Point getOrigin () const inline
getSpritePort()
Port * getSpritePort () const inline
getSpriteZOrder()
virtual int getSpriteZOrder (Sprite * sprite) virtual
References Sprite.
getZoom()
float getZoom () const inline
getZOrder()
int getZOrder ()
hasSprite()
virtual bool hasSprite (Sprite * sprite) virtual
References Sprite.
hide()
virtual void hide () virtual
isHidden()
virtual bool isHidden () virtual
isSpriteBehind()
virtual bool isSpriteBehind (Sprite * sprite, Sprite * otherSprite) virtual
References Sprite.
layerToPort() [1/6]
virtual Offset layerToPort (const Offset & p) const virtual
layerToPort() [2/6]
virtual Point layerToPort (const Point & p) const virtual
Referenced by layerToPort().
layerToPort() [3/6]
virtual Quad layerToPort (const Quad & q) const virtual
layerToPort() [4/6]
virtual RotatedRect layerToPort (const Rect & r) const virtual
layerToPort() [5/6]
virtual RotatedRect layerToPort (const RotatedRect & r) const virtual
layerToPort() [6/6]
Vector layerToPort (const Vector & p) const inline virtual
References layerToPort().
moveBehind()
virtual void moveBehind (SpriteLayer * layer) virtual
Referenced by moveToBack().
moveInFrontOf()
virtual void moveInFrontOf (SpriteLayer * layer) virtual
Referenced by moveToFront().
moveToBack()
void moveToBack () inline
References moveBehind().
moveToFront()
void moveToFront () inline
References moveInFrontOf().
moveWith()
virtual void moveWith (SpriteLayer * layer, float moveRatio = 1.0f, float zoomRatio = 1.0f) virtual
portToLayer() [1/6]
virtual Offset portToLayer (const Offset & p) const virtual
portToLayer() [2/6]
virtual Point portToLayer (const Point & p) const virtual
Referenced by portToLayer().
portToLayer() [3/6]
virtual Quad portToLayer (const Quad & q) const virtual
portToLayer() [4/6]
virtual RotatedRect portToLayer (const Rect & r) const virtual
portToLayer() [5/6]
virtual RotatedRect portToLayer (const RotatedRect & r) const virtual
portToLayer() [6/6]
Vector portToLayer (const Vector & p) const inline virtual
References portToLayer().
removeAllSprites()
virtual void removeAllSprites () virtual
removeSprite()
virtual void removeSprite (Sprite * oldSprite) virtual
References Sprite.
setAutoCenter()
void setAutoCenter (bool autoCenter = true) inline
setFixedMoveAxis()
void setFixedMoveAxis (bool fixedAxis = true) inline
setOrigin()
void setOrigin (const Point & origin) inline
setSerializationFlags()
void setSerializationFlags (uint32 flags)
References setSerializationFlags().
Referenced by setSerializationFlags().
setSpritePort()
virtual void setSpritePort (Port * port) virtual
setZoom()
virtual void setZoom (float zoomLevel) virtual
show()
virtual void show () virtual
startAnimations()
virtual void startAnimations () virtual
stopAnimations()
virtual void stopAnimations () virtual
zoom()
void zoom (float deltaZoomLevel, ms_delta msDuration, EasingFunc easing = easeInOutQuad, Rect keepInRect = Rect(0,0), const Point * centerOn = 0) inline
References zoomTo().
zoomTo()
virtual void zoomTo (float zoomLevel, ms_delta msDuration, EasingFunc easing = easeInOutQuad, Rect keepInRect = Rect(0, 0), const Point * centerOn = 0) virtual
References pdg::easeInOutQuad().
Referenced by zoom().
Friends And Related Symbol Documentation
Sprite
friend class Sprite friend
References Sprite.
Referenced by addSprite(), addSpriteInFrontOf(), TileLayer::checkCollision(), cloneSprite(), createSprite(), findSprite(), getNthSprite(), getSpriteZOrder(), hasSprite(), isSpriteBehind(), removeSprite(), and Sprite.
SpriteManager
friend class SpriteManager friend
References SpriteManager.
Referenced by SpriteManager.
Member Data Documentation
layerId
long layerId
noZoom
const float noZoom