Pixel Dust Game Engine: Renderer Class Reference
Renderer Class Reference abstract
#include <renderer.h>
Public Member Functions
virtual ~Renderer ()=default
virtual void drawLine (const Point &from, const Point &to, const Attributes &attrs)=0
virtual void drawRect (const Rect &rect, const Attributes &attrs)=0
virtual void drawQuad (const Quad &quad, const Attributes &attrs)=0
virtual void drawPolygon (const Polygon &polygon, const Attributes &attrs)=0
virtual void drawSpline (const Spline &spline, const Attributes &attrs)=0
virtual void drawEllipse (const Point &center, float xRadius, float yRadius, const Attributes &attrs)=0
virtual void drawArc (const Point &center, float xRadius, float yRadius, float startAngle, float endAngle, const Attributes &attrs)=0
virtual void drawBezier (const Point &from, const Point &control1, const Point &control2, const Point &to, const Attributes &attrs)=0
void drawCircle (const Point &center, float radius, const Attributes &attrs)
void drawVector (const Vector &v, const Attributes &attrs)
void drawRoundedRect (const Rect &rect, float radius, const Attributes &attrs)
virtual void setClipRect (const Rect &rect)=0
virtual Rect getClipRect () const =0
virtual Rect getDrawingArea () const =0
Constructor & Destructor Documentation
~Renderer()
virtual ~Renderer () virtual default
Member Function Documentation
drawArc()
virtual void drawArc (const Point & center, float xRadius, float yRadius, float startAngle, float endAngle, const Attributes & attrs) pure virtual
drawBezier()
virtual void drawBezier (const Point & from, const Point & control1, const Point & control2, const Point & to, const Attributes & attrs) pure virtual
drawCircle()
void drawCircle (const Point & center, float radius, const Attributes & attrs) inline
References drawEllipse().
drawEllipse()
virtual void drawEllipse (const Point & center, float xRadius, float yRadius, const Attributes & attrs) pure virtual
Referenced by drawCircle().
drawLine()
virtual void drawLine (const Point & from, const Point & to, const Attributes & attrs) pure virtual
Referenced by drawVector().
drawPolygon()
virtual void drawPolygon (const Polygon & polygon, const Attributes & attrs) pure virtual
drawQuad()
virtual void drawQuad (const Quad & quad, const Attributes & attrs) pure virtual
drawRect()
virtual void drawRect (const Rect & rect, const Attributes & attrs) pure virtual
Referenced by drawRoundedRect().
drawRoundedRect()
void drawRoundedRect (const Rect & rect, float radius, const Attributes & attrs) inline
References drawRect(), and Attributes::roundedCorners().
drawSpline()
virtual void drawSpline (const Spline & spline, const Attributes & attrs) pure virtual
drawVector()
void drawVector (const Vector & v, const Attributes & attrs) inline
References drawLine().
getClipRect()
virtual Rect getClipRect () const pure virtual
getDrawingArea()
virtual Rect getDrawingArea () const pure virtual
setClipRect()
virtual void setClipRect (const Rect & rect) pure virtual