Pixel Dust Game Engine: Drawing Class Reference
Drawing Class Reference abstract
#include <drawing.h>
Public Member Functions
virtual ElementRef * addLine (const Point &from, const Point &to)=0
virtual ElementRef * addSpline (const Spline &spline)=0
virtual ElementRef * addRect (const Rect &rect)=0
virtual ElementRef * addRotatedRect (const RotatedRect &rect)=0
virtual ElementRef * addQuad (const Quad &quad)=0
virtual ElementRef * addPolygon (const Polygon &polygon)=0
virtual ElementRef * addCircle (const Point &center, float radius)=0
virtual ElementRef * addOval (const Point &center, float xRadius, float yRadius)=0
virtual ElementRef * addImage (const Rect &rect, const Image &image)=0
virtual ElementRef * addImageStrip (const Rect &rect, const ImageStrip &imageStrip)=0
virtual ElementRef * addDrawing (const Rect &rect, const Drawing &drawing)=0
virtual size_t getElementCount () const =0
virtual ElementRef * getElement (size_t index) const =0
virtual ElementRef * getElementHitBy (const Point &point) const =0
virtual Rect getBounds () const =0
virtual Point centerPoint () const =0
virtual bool empty () const =0
virtual void draw (Port *port)=0
virtual void draw (Port *port, const Rect &rect)=0
virtual void draw (Port *port, const Quad &quad)=0
virtual void draw (Port *port, const RotatedRect &rr)=0
Static Public Member Functions
static Drawing * create ()
Protected Member Functions
Drawing ()
virtual ~Drawing ()
Constructor & Destructor Documentation
Drawing()
Drawing () inline protected
Referenced by addDrawing(), and create().
~Drawing()
virtual ~Drawing () inline protected virtual
Member Function Documentation
addCircle()
virtual ElementRef * addCircle (const Point & center, float radius) pure virtual
addDrawing()
virtual ElementRef * addDrawing (const Rect & rect, const Drawing & drawing) pure virtual
References Drawing().
addImage()
virtual ElementRef * addImage (const Rect & rect, const Image & image) pure virtual
addImageStrip()
virtual ElementRef * addImageStrip (const Rect & rect, const ImageStrip & imageStrip) pure virtual
addLine()
virtual ElementRef * addLine (const Point & from, const Point & to) pure virtual
addOval()
virtual ElementRef * addOval (const Point & center, float xRadius, float yRadius) pure virtual
addPolygon()
virtual ElementRef * addPolygon (const Polygon & polygon) pure virtual
addQuad()
virtual ElementRef * addQuad (const Quad & quad) pure virtual
addRect()
virtual ElementRef * addRect (const Rect & rect) pure virtual
addRotatedRect()
virtual ElementRef * addRotatedRect (const RotatedRect & rect) pure virtual
addSpline()
virtual ElementRef * addSpline (const Spline & spline) pure virtual
centerPoint()
virtual Point centerPoint () const pure virtual
create()
Drawing * create () static
References Drawing().
draw() [1/4]
virtual void draw (Port * port) pure virtual
draw() [2/4]
virtual void draw (Port * port, const Quad & quad) pure virtual
draw() [3/4]
virtual void draw (Port * port, const Rect & rect) pure virtual
draw() [4/4]
virtual void draw (Port * port, const RotatedRect & rr) pure virtual
empty()
virtual bool empty () const pure virtual
getBounds()
virtual Rect getBounds () const pure virtual
getElement()
virtual ElementRef * getElement (size_t index) const pure virtual
getElementCount()
virtual size_t getElementCount () const pure virtual
getElementHitBy()
virtual ElementRef * getElementHitBy (const Point & point) const pure virtual