Pixel Dust Game Engine: ElementRef Class Reference
ElementRef Class Reference
#include <drawing.h>
Public Member Functions
ElementRef & withLineColor (const Color &color)
ElementRef & withLineThickness (float thickness)
ElementRef & withLineOpacity (float opacity)
ElementRef & withFrameNumber (int frameNumber)
ElementRef & withFillColor (const Color &color)
ElementRef & withFillOpacity (float opacity)
ElementRef & withFillGradient (const Point &startPoint, const Color &startColor, const Point &endPoint, const Color &endColor)
ElementRef & withFillRadialGradient (const Point &centerPoint, const Color &centerColor, float radius, const Color &endColor)
ElementRef & withTransform (const Rect &rect)
ElementRef & withTransform (const Quad &quad)
ElementRef & withRotation (float radians, const Point &aroundPoint)
ElementType type () const
const std::vector< Point > & getControlPoints () const
const Point & getControlPoint (int controlPointIndex) const
void changeControlPoint (int controlPointIndex, const Point &controlPoint)
void moveForward ()
void moveBackward ()
void moveToFront ()
void moveToBack ()
void remove ()
ElementRef (Drawing *drawing, uint32_t index)
Protected Attributes
Drawing * drawing
uint32_t index
Constructor & Destructor Documentation
ElementRef()
ElementRef (Drawing * drawing, uint32_t index) inline
References drawing, and index.
Referenced by withFillColor(), withFillGradient(), withFillOpacity(), withFillRadialGradient(), withFrameNumber(), withLineColor(), withLineOpacity(), withLineThickness(), withRotation(), withTransform(), and withTransform().
Member Function Documentation
changeControlPoint()
void changeControlPoint (int controlPointIndex, const Point & controlPoint)
getControlPoint()
const Point & getControlPoint (int controlPointIndex) const
getControlPoints()
const std::vector< Point > & getControlPoints () const
moveBackward()
void moveBackward ()
moveForward()
void moveForward ()
moveToBack()
void moveToBack ()
moveToFront()
void moveToFront ()
remove()
void remove ()
type()
ElementType type () const
withFillColor()
ElementRef & withFillColor (const Color & color)
References ElementRef().
withFillGradient()
ElementRef & withFillGradient (const Point & startPoint, const Color & startColor, const Point & endPoint, const Color & endColor)
References ElementRef().
withFillOpacity()
ElementRef & withFillOpacity (float opacity)
References ElementRef().
withFillRadialGradient()
ElementRef & withFillRadialGradient (const Point & centerPoint, const Color & centerColor, float radius, const Color & endColor)
References ElementRef().
withFrameNumber()
ElementRef & withFrameNumber (int frameNumber)
References ElementRef().
withLineColor()
ElementRef & withLineColor (const Color & color)
References ElementRef().
withLineOpacity()
ElementRef & withLineOpacity (float opacity)
References ElementRef().
withLineThickness()
ElementRef & withLineThickness (float thickness)
References ElementRef().
withRotation()
ElementRef & withRotation (float radians, const Point & aroundPoint)
References ElementRef().
withTransform() [1/2]
ElementRef & withTransform (const Quad & quad)
References ElementRef().
withTransform() [2/2]
ElementRef & withTransform (const Rect & rect)
References ElementRef().
Member Data Documentation
drawing
Drawing* drawing protected
Referenced by ElementRef().
index
uint32_t index protected
Referenced by ElementRef().