Pixel Dust Game Engine: Animated Class Reference
Animated Class Reference
#include <animated.h>
Public Member Functions
SERIALIZABLE_TAG (CLASSTAG_ANIMATED)
SERIALIZABLE_METHODS ()
Rect getBoundingBox ()
RotatedRect getRotatedBounds ()
Animated & setLocation (const Point &loc)
Point getLocation ()
Animated & moveTo (float x, float y)
Animated & moveTo (const Point &where)
Animated & move (float deltaX, float deltaY)
Animated & move (const Offset &delta)
virtual void moveTo (const Point &loc, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void moveTo (float x, float y, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void move (float deltaX, float deltaY, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void move (const Offset &delta, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
virtual Animated & setVelocity (const Vector &deltaPerSec)
virtual Vector getVelocity ()
Animated & setSpeed (float speed)
float getSpeed ()
Animated & setVelocityInRadians (float speed, float direction)
float getMovementDirectionInRadians ()
Animated & setVelocity (float deltaXPerSec, float deltaYPerSec)
Animated & stopMoving ()
virtual void accelerateTo (float speed, ms_delta msDuration, EasingFunc easing=linearTween)
void accelerate (float deltaSpeed, ms_delta msDuration, EasingFunc easing=linearTween)
Animated & setSize (float width, float height)
Animated & setWidth (float width)
float getWidth ()
Animated & setHeight (float height)
float getHeight ()
Animated & grow (float factor)
Animated & stretch (float widthFactor, float heightFactor)
Animated & startGrowing (float amountPerSecond)
Animated & stopGrowing ()
Animated & startStretching (float widthPerSecond, float heightPerSecond)
Animated & stopStretching ()
virtual void resizeTo (float width, float height, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void resize (float deltaWidth, float deltaHeight, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void grow (float factor, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void stretch (float widthFactor, float weightFactor, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
Animated & setRotation (float radiansRotation)
float getRotation ()
Animated & setCenterOffset (const Offset &offset)
Offset getCenterOffset ()
Animated & rotateTo (float radiansRotation)
Animated & rotate (float radians)
Animated & setSpin (float radiansPerSecond)
float getSpin ()
Animated & stopSpinning ()
Animated & setFlipX (bool flip)
Animated & setFlipY (bool flip)
Animated & flipX ()
Animated & flipY ()
bool isFlippedX ()
bool isFlippedY ()
virtual void rotateTo (float radiansRotation, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void rotate (float radians, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenterTo (float xOffset, float yOffset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenterTo (const Offset &offset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenter (float deltaXOffset, float deltaYOffset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
void changeCenter (const Offset &offset, ms_delta msDuration, EasingFunc easing=easeInOutQuad)
Animated * wait (ms_delta msDuration)
virtual Animated & setMass (float mass)
float getMass ()
virtual Animated & setFriction (float frictionCoefficient)
Animated & setMoveFriction (float frictionCoefficient)
Animated & setSpinFriction (float frictionCoefficient)
Animated & setSizeFriction (float frictionCoefficient)
float getMoveFriction ()
float getSpinFriction ()
float getSizeFriction ()
virtual void applyForce (const Vector &force, ms_delta msDuration=duration_Instantaneous)
virtual void applyForce (float forceX, float forceY, ms_delta msDuration=duration_Instantaneous)
virtual void applyTorque (float forceSpin, ms_delta msDuration=duration_Instantaneous)
virtual void stopAllForces ()
virtual void addAnimationHelper (IAnimationHelper *helper)
virtual void removeAnimationHelper (IAnimationHelper *helper)
virtual void clearAnimationHelpers ()
Public Member Functions inherited from ISerializable
virtual uint32 getSerializedSize (ISerializer *serializer) const =0
Get number of bytes needed to hold serialized state.
virtual void serialize (ISerializer *serializer) const =0
Write self out to a serializer.
virtual void deserialize (IDeserializer *deserializer)=0
Read self from a deserializer.
virtual uint32 getMyClassTag () const =0
Get a tag value that uniquely represents this class.
ISerializable ()
virtual ~ISerializable ()
Public Member Functions inherited from RefCountedObj
virtual void addRef () const throw ()
virtual void release () const throw ()
Static Public Member Functions
static pdg::ISerializable * CreateInstance ()
Member Function Documentation
accelerate()
void accelerate (float deltaSpeed, ms_delta msDuration, EasingFunc easing = linearTween) inline
References accelerateTo(), and getSpeed().
accelerateTo()
virtual void accelerateTo (float speed, ms_delta msDuration, EasingFunc easing = linearTween) virtual
References pdg::linearTween().
Referenced by accelerate().
addAnimationHelper()
virtual void addAnimationHelper (IAnimationHelper * helper) virtual
applyForce() [1/2]
virtual void applyForce (const Vector & force, ms_delta msDuration = duration_Instantaneous) virtual
References pdg::duration_Instantaneous.
Referenced by applyForce().
applyForce() [2/2]
void applyForce (float forceX, float forceY, ms_delta msDuration = duration_Instantaneous) inline virtual
References applyForce().
applyTorque()
virtual void applyTorque (float forceSpin, ms_delta msDuration = duration_Instantaneous) virtual
References pdg::duration_Instantaneous.
changeCenter() [1/2]
void changeCenter (const Offset & offset, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References changeCenterTo().
changeCenter() [2/2]
void changeCenter (float deltaXOffset, float deltaYOffset, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References changeCenter().
Referenced by changeCenter().
changeCenterTo() [1/2]
void changeCenterTo (const Offset & offset, ms_delta msDuration, EasingFunc easing = easeInOutQuad)
References pdg::easeInOutQuad().
changeCenterTo() [2/2]
void changeCenterTo (float xOffset, float yOffset, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References changeCenterTo().
Referenced by changeCenter(), and changeCenterTo().
clearAnimationHelpers()
virtual void clearAnimationHelpers () virtual
CreateInstance()
pdg::ISerializable * CreateInstance () inline static
flipX()
Animated & flipX () inline
References setFlipX().
flipY()
Animated & flipY () inline
References setFlipY().
getBoundingBox()
Rect getBoundingBox () inline
References RotatedRectT::getBounds(), and getRotatedBounds().
getCenterOffset()
Offset getCenterOffset () inline
getHeight()
float getHeight () inline
getLocation()
Point getLocation () inline
Referenced by move().
getMass()
float getMass () inline
getMoveFriction()
float getMoveFriction () inline
getMovementDirectionInRadians()
float getMovementDirectionInRadians () inline
References getVelocity(), and VectorT::vectorAngle().
Referenced by setSpeed().
getRotatedBounds()
RotatedRect getRotatedBounds () inline
References RectT::center().
Referenced by getBoundingBox().
getRotation()
float getRotation () inline
getSizeFriction()
float getSizeFriction () inline
getSpeed()
float getSpeed () inline
References getVelocity(), and VectorT::vectorLength().
Referenced by accelerate().
getSpin()
float getSpin ()
getSpinFriction()
float getSpinFriction () inline
getVelocity()
virtual Vector getVelocity () virtual
Referenced by getMovementDirectionInRadians(), and getSpeed().
getWidth()
float getWidth () inline
grow() [1/2]
Animated & grow (float factor) inline
References stretch().
grow() [2/2]
void grow (float factor, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References stretch().
isFlippedX()
bool isFlippedX () inline
isFlippedY()
bool isFlippedY () inline
move() [1/4]
Animated & move (const Offset & delta) inline
References getLocation(), and setLocation().
move() [2/4]
void move (const Offset & delta, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References moveTo().
move() [3/4]
Animated & move (float deltaX, float deltaY) inline
References move().
Referenced by move(), and move().
move() [4/4]
void move (float deltaX, float deltaY, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References move().
moveTo() [1/4]
virtual void moveTo (const Point & loc, ms_delta msDuration, EasingFunc easing = easeInOutQuad) virtual
References pdg::easeInOutQuad().
moveTo() [2/4]
Animated & moveTo (const Point & where) inline
References setLocation().
moveTo() [3/4]
Animated & moveTo (float x, float y) inline
References moveTo().
Referenced by move(), moveTo(), and moveTo().
moveTo() [4/4]
void moveTo (float x, float y, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References moveTo().
removeAnimationHelper()
virtual void removeAnimationHelper (IAnimationHelper * helper) virtual
resize()
void resize (float deltaWidth, float deltaHeight, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References resizeTo().
resizeTo()
virtual void resizeTo (float width, float height, ms_delta msDuration, EasingFunc easing = easeInOutQuad) virtual
References pdg::easeInOutQuad().
Referenced by resize(), and stretch().
rotate() [1/2]
Animated & rotate (float radians) inline
References setRotation().
rotate() [2/2]
void rotate (float radians, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References rotateTo().
rotateTo() [1/2]
Animated & rotateTo (float radiansRotation) inline
References setRotation().
Referenced by rotate().
rotateTo() [2/2]
virtual void rotateTo (float radiansRotation, ms_delta msDuration, EasingFunc easing = easeInOutQuad) virtual
References pdg::easeInOutQuad().
SERIALIZABLE_METHODS()
SERIALIZABLE_METHODS ()
SERIALIZABLE_TAG()
SERIALIZABLE_TAG (CLASSTAG_ANIMATED)
setCenterOffset()
Animated & setCenterOffset (const Offset & offset) inline
setFlipX()
Animated & setFlipX (bool flip)
Referenced by flipX().
setFlipY()
Animated & setFlipY (bool flip)
Referenced by flipY().
setFriction()
Animated & setFriction (float frictionCoefficient) inline virtual
References setMoveFriction(), setSizeFriction(), and setSpinFriction().
setHeight()
Animated & setHeight (float height) inline
Referenced by setSize().
setLocation()
Animated & setLocation (const Point & loc) inline
Referenced by move(), and moveTo().
setMass()
Animated & setMass (float mass) inline virtual
setMoveFriction()
Animated & setMoveFriction (float frictionCoefficient) inline
Referenced by setFriction().
setRotation()
Animated & setRotation (float radiansRotation)
Referenced by rotate(), and rotateTo().
setSize()
Animated & setSize (float width, float height) inline
References setHeight(), and setWidth().
setSizeFriction()
Animated & setSizeFriction (float frictionCoefficient) inline
Referenced by setFriction().
setSpeed()
Animated & setSpeed (float speed) inline
References getMovementDirectionInRadians(), and setVelocityInRadians().
setSpin()
Animated & setSpin (float radiansPerSecond)
setSpinFriction()
Animated & setSpinFriction (float frictionCoefficient) inline
Referenced by setFriction().
setVelocity() [1/2]
virtual Animated & setVelocity (const Vector & deltaPerSec) virtual
Referenced by setVelocity(), setVelocityInRadians(), and stopMoving().
setVelocity() [2/2]
Animated & setVelocity (float deltaXPerSec, float deltaYPerSec) inline
References setVelocity().
setVelocityInRadians()
Animated & setVelocityInRadians (float speed, float direction) inline
References setVelocity().
Referenced by setSpeed().
setWidth()
Animated & setWidth (float width) inline
Referenced by setSize().
startGrowing()
Animated & startGrowing (float amountPerSecond) inline
References startStretching().
startStretching()
Animated & startStretching (float widthPerSecond, float heightPerSecond) inline
Referenced by startGrowing().
stopAllForces()
virtual void stopAllForces () virtual
stopGrowing()
Animated & stopGrowing () inline
References stopStretching().
stopMoving()
Animated & stopMoving () inline
References setVelocity().
stopSpinning()
Animated & stopSpinning () inline
stopStretching()
Animated & stopStretching () inline
Referenced by stopGrowing(), and stretch().
stretch() [1/2]
Animated & stretch (float widthFactor, float heightFactor) inline
References stopStretching(), OffsetT::x, and OffsetT::y.
Referenced by grow(), and grow().
stretch() [2/2]
void stretch (float widthFactor, float weightFactor, ms_delta msDuration, EasingFunc easing = easeInOutQuad) inline
References resizeTo().
wait()
Animated * wait (ms_delta msDuration) inline