Pixel Dust Game Engine: UserData Class Reference
UserData Class Reference
#include <userdata.h>
Public Member Functions
template<class T>
T * getData ()
void * getData ()
void release ()
Static Public Member Functions
static UserData * makeUserDataViaCopy (void *ptr, long dataSize, UserFreeFuncT freeFunc=0)
static UserData * makeUserDataWithCustomFree (void *ptr, UserFreeFuncT freeFunc)
static UserData * makeUserDataFromRefCountedObj (RefCountedObj *obj)
static UserData * makeUserDataFromPointer (void *ptr, FreeDataT freeHow=data_Free)
Protected Member Functions
UserData ()
~UserData ()
Protected Attributes
FreeDataT freeHow
UserFreeFuncT freeFunc
void * data
Constructor & Destructor Documentation
UserData()
UserData () protected
Referenced by makeUserDataFromPointer(), makeUserDataFromRefCountedObj(), makeUserDataViaCopy(), and makeUserDataWithCustomFree().
~UserData()
~UserData () protected
Member Function Documentation
getData() [1/2]
template<class T> T * getData () inline
References data.
getData() [2/2]
void * getData () inline
References data.
makeUserDataFromPointer()
UserData * makeUserDataFromPointer (void * ptr, FreeDataT freeHow = data_Free) static
References UserData(), pdg::data_Free, and freeHow.
makeUserDataFromRefCountedObj()
UserData * makeUserDataFromRefCountedObj (RefCountedObj * obj) static
References UserData().
makeUserDataViaCopy()
UserData * makeUserDataViaCopy (void * ptr, long dataSize, UserFreeFuncT freeFunc = 0) static
References UserData(), and freeFunc.
makeUserDataWithCustomFree()
UserData * makeUserDataWithCustomFree (void * ptr, UserFreeFuncT freeFunc) static
References UserData(), and freeFunc.
release()
void release () inline
Member Data Documentation
data
void* data protected
Referenced by getData().
freeFunc
UserFreeFuncT freeFunc protected
Referenced by makeUserDataViaCopy(), and makeUserDataWithCustomFree().
freeHow
FreeDataT freeHow protected
Referenced by makeUserDataFromPointer().