Pixel Dust Game Engine: RectT Class Reference
RectT Class Reference
#include <coordinates.h>
Public Member Functions
bool empty () const
return true if this rectangle is empty (no width or no height)
bool contains (const PointT< T > &p) const
return true if the point is inside this rectangle
bool contains (const RectT< T > &r) const
return true if the rectangle passed in is entirely inside this rectangle
bool overlaps (const RectT< T > &r) const
return true if this rectangle overlaps the other rectangle at all (sharing an edge is not overlapping)
PointT< T > leftTop () const
get the top left corner point of the rectangle
PointT< T > rightTop () const
get the top right corner point of the rectangle
PointT< T > leftBottom () const
get the bottom left corner point of the rectangle
PointT< T > rightBottom () const
get the bottom right corner point of the rectangle
PointT< T > centerPoint () const
get the center point of the rectangle, rounds down if fractional
T x1 () const
get the 1st x coordinate (leftmost)
T y1 () const
get the 1st y coordinate (topmost)
T x2 () const
get the 2nd x coordinate (rightmost)
T y2 () const
get the 2nd y coordinate (bottom-most)
T width () const
get the width of the rectangle
T height () const
get the height of the rectangle
RectT< T > intersection (const RectT< T > &r) const
get a new rectangle that is the overlapping area of the the rectangles
RectT< T > unionWith (const RectT< T > &r) const
get the smallest possible new rectangle that contains both rectangles
RectT< T > & moveLeft (T delta)
move the rectangle to the left by some amount
RectT< T > & moveRight (T delta)
move the rectangle to the right by some amount
RectT< T > & moveUp (T delta)
move the rectangle up by some amount
RectT< T > & moveDown (T delta)
move the rectangle down by some amount
RectT< T > & moveXTo (T x)
move the rectangle to a particular x location, leaving y unchanged
RectT< T > & moveYTo (T y)
move the rectangle to a particular y location, leaving x unchanged
RectT< T > & moveTo (T x, T y)
move the rectangle to a particular (x, y) location
RectT< T > & moveTo (PointT< T > p)
move the rectangle to a particular point
RectT< T > & center (PointT< T > p)
move the rectangle to be centered over a particular point
RectT< T > & center (RectT< T > r)
move the rectangle to be centered within/relative to another rectangle
RectT< T > & setSize (T n)
set the size (width & height) of the rectangle
RectT< T > & setWidth (T w)
set the width of the rectangle
RectT< T > & setHeight (T h)
set the height of the rectangle
RectT< T > & horzShrink (T delta)
reduce the width of the rectangle while leaving the center point unchanged
RectT< T > & vertShrink (T delta)
reduce the height of the rectangle while leaving the center point unchanged
RectT< T > & horzGrow (T delta)
increase the width of the rectangle while leaving the center point unchanged
RectT< T > & vertGrow (T delta)
increase the height of the rectangle while leaving the center point unchanged
RectT< T > & shrink (T delta)
reduce the height and width of the rectangle while leaving the center point unchanged
RectT< T > & grow (T delta)
increase the height and width of the rectangle while leaving the center point unchanged
RectT< T > & horzScale (float f)
change the x coordinates of the rectangle by a multiplier
RectT< T > & vertScale (float f)
change the y coordinates of the rectangle by a multiplier
RectT< T > & scale (float f)
change the coordinates of the rectangle by a multiplier
RectT< T > & round ()
round the coordinates to closest whole number
operator QuadT< T > ()
bool operator== (const RectT< T > &r2)
return true if this rectangle is equal to the other
bool operator!= (const RectT< T > &r2)
return true if this rectangle is not equal to the other
RectT< T > & operator= (const RectT< T > &r2)
set rectangle equal to another
RectT< T > & operator+= (const PointT< T > &p1)
offset this rectangle's location by adding x & y coordinates of the point
RectT< T > & operator-= (const PointT< T > &p1)
offset this rectangle's location by subtracting x & y coordinates of the point
RectT< T > & operator+= (const RectT< T > &r2)
add another rectangle to this one by adding coordinates
RectT< T > & operator-= (const RectT< T > &r2)
subtract another rectangle from this one by subtracting coordinates
RectT< T > operator+ (const PointT< T > &p1)
get a rectangle offset by adding the x & y coordinates of a point
RectT< T > operator- (const PointT< T > &p1)
get a rectangle offset by subtracting the x & y coordinates of a point
RectT< T > operator+ (const RectT< T > &r2)
add two rectangles together by adding coordinates
RectT< T > operator- (const RectT< T > &r2)
subtract one rectangle from another by subtracting coordinates
RectT (T wid, T hgt)
create a rectangle with origin at (0,0) and set its height and width values
RectT (T lft, T tp, T rgt, T bot)
create a rectangle with left, top, right, and bottom coordinates (x1, y1, x2, y2) specified
RectT (const PointT< T > &lftTop, const PointT< T > &rgtBot)
create a rectangle given its top left and bottom right corner points
RectT (const PointT< T > &lftTop, T wid, T hgt)
create a rectangle given its top teft corner point and a height and width
RectT ()
create an empty rectangle with origin at (0,0)
RectT (const RectT< T > &other)
copy constructor
Public Attributes
T left
leftmost coordinate of a rectangle on a grid or screen
T top
topmost coordinate of a rectangle on a grid or screen
T right
rightmost coordinate of a rectangle on a grid or screen
T bottom
bottom-most coordinate of a rectangle on a grid or screen
Detailed Description
Rectangle for 2D coordinate system. Rect is a class that provides support for dealing with rectangles in 2 dimensional space.
Constructor & Destructor Documentation
RectT() [1/6]
RectT (T wid, T hgt) inline
create a rectangle with origin at (0,0) and set its height and width values
RectT() [2/6]
RectT (T lft, T tp, T rgt, T bot) inline
create a rectangle with left, top, right, and bottom coordinates (x1, y1, x2, y2) specified
RectT() [3/6]
RectT (const PointT< T > & lftTop, const PointT< T > & rgtBot) inline
create a rectangle given its top left and bottom right corner points
RectT() [4/6]
RectT (const PointT< T > & lftTop, T wid, T hgt) inline
create a rectangle given its top teft corner point and a height and width
RectT() [5/6]
RectT () inline
create an empty rectangle with origin at (0,0)
RectT() [6/6]
RectT (const RectT< T > & other) inline
copy constructor
Member Function Documentation
center() [1/2]
RectT< T > & center (PointT< T > p) inline
move the rectangle to be centered over a particular point
Referenced by Animated::getRotatedBounds().
center() [2/2]
RectT< T > & center (RectT< T > r) inline
move the rectangle to be centered within/relative to another rectangle
centerPoint()
PointT< T > centerPoint () const inline
get the center point of the rectangle, rounds down if fractional
contains() [1/2]
bool contains (const PointT< T > & p) const inline
return true if the point is inside this rectangle
contains() [2/2]
bool contains (const RectT< T > & r) const inline
return true if the rectangle passed in is entirely inside this rectangle
Referenced by RectT< float >::contains().
empty()
bool empty () const inline
return true if this rectangle is empty (no width or no height)
Referenced by RectT< float >::overlaps().
grow()
RectT< T > & grow (T delta) inline
increase the height and width of the rectangle while leaving the center point unchanged
height()
T height () const inline
get the height of the rectangle
Referenced by RectT< float >::center(), RectT< float >::centerPoint(), RectT< float >::moveTo(), and RectT< float >::moveYTo().
horzGrow()
RectT< T > & horzGrow (T delta) inline
increase the width of the rectangle while leaving the center point unchanged
Referenced by RectT< float >::grow().
horzScale()
RectT< T > & horzScale (float f) inline
change the x coordinates of the rectangle by a multiplier
Referenced by RectT< float >::scale().
horzShrink()
RectT< T > & horzShrink (T delta) inline
reduce the width of the rectangle while leaving the center point unchanged
Referenced by RectT< float >::shrink().
intersection()
RectT< T > intersection (const RectT< T > & r) const inline
get a new rectangle that is the overlapping area of the the rectangles
Referenced by RectT< float >::overlaps().
leftBottom()
PointT< T > leftBottom () const inline
get the bottom left corner point of the rectangle
Referenced by QuadT< float >::QuadT(), RectT< float >::contains(), and RectT< float >::operator QuadT< T >().
leftTop()
PointT< T > leftTop () const inline
get the top left corner point of the rectangle
Referenced by QuadT< float >::QuadT(), RectT< float >::contains(), and RectT< float >::operator QuadT< T >().
moveDown()
RectT< T > & moveDown (T delta) inline
move the rectangle down by some amount
moveLeft()
RectT< T > & moveLeft (T delta) inline
move the rectangle to the left by some amount
moveRight()
RectT< T > & moveRight (T delta) inline
move the rectangle to the right by some amount
moveTo() [1/2]
RectT< T > & moveTo (PointT< T > p) inline
move the rectangle to a particular point
Referenced by RectT< float >::moveTo().
moveTo() [2/2]
RectT< T > & moveTo (T x, T y) inline
move the rectangle to a particular (x, y) location
Referenced by RectT< float >::center(), and RectT< float >::center().
moveUp()
RectT< T > & moveUp (T delta) inline
move the rectangle up by some amount
moveXTo()
RectT< T > & moveXTo (T x) inline
move the rectangle to a particular x location, leaving y unchanged
moveYTo()
RectT< T > & moveYTo (T y) inline
move the rectangle to a particular y location, leaving x unchanged
operator QuadT< T >()
operator QuadT< T > () inline
operator!=()
bool operator!= (const RectT< T > & r2)
return true if this rectangle is not equal to the other
operator+() [1/2]
RectT< T > operator+ (const PointT< T > & p1)
get a rectangle offset by adding the x & y coordinates of a point
operator+() [2/2]
RectT< T > operator+ (const RectT< T > & r2)
add two rectangles together by adding coordinates
operator+=() [1/2]
RectT< T > & operator+= (const PointT< T > & p1)
offset this rectangle's location by adding x & y coordinates of the point
operator+=() [2/2]
RectT< T > & operator+= (const RectT< T > & r2)
add another rectangle to this one by adding coordinates
operator-() [1/2]
RectT< T > operator- (const PointT< T > & p1)
get a rectangle offset by subtracting the x & y coordinates of a point
operator-() [2/2]
RectT< T > operator- (const RectT< T > & r2)
subtract one rectangle from another by subtracting coordinates
operator-=() [1/2]
RectT< T > & operator-= (const PointT< T > & p1)
offset this rectangle's location by subtracting x & y coordinates of the point
operator-=() [2/2]
RectT< T > & operator-= (const RectT< T > & r2)
subtract another rectangle from this one by subtracting coordinates
operator=()
RectT< T > & operator= (const RectT< T > & r2)
set rectangle equal to another
operator==()
bool operator== (const RectT< T > & r2)
return true if this rectangle is equal to the other
overlaps()
bool overlaps (const RectT< T > & r) const inline
return true if this rectangle overlaps the other rectangle at all (sharing an edge is not overlapping)
rightBottom()
PointT< T > rightBottom () const inline
get the bottom right corner point of the rectangle
Referenced by QuadT< float >::QuadT(), RectT< float >::contains(), and RectT< float >::operator QuadT< T >().
rightTop()
PointT< T > rightTop () const inline
get the top right corner point of the rectangle
Referenced by QuadT< float >::QuadT(), RectT< float >::contains(), and RectT< float >::operator QuadT< T >().
round()
RectT< T > & round () inline
round the coordinates to closest whole number
scale()
RectT< T > & scale (float f) inline
change the coordinates of the rectangle by a multiplier
setHeight()
RectT< T > & setHeight (T h) inline
set the height of the rectangle
Referenced by RectT< float >::moveTo(), RectT< float >::moveYTo(), and RectT< float >::setSize().
setSize()
RectT< T > & setSize (T n) inline
set the size (width & height) of the rectangle
setWidth()
RectT< T > & setWidth (T w) inline
set the width of the rectangle
Referenced by RectT< float >::moveTo(), RectT< float >::moveXTo(), and RectT< float >::setSize().
shrink()
RectT< T > & shrink (T delta) inline
reduce the height and width of the rectangle while leaving the center point unchanged
unionWith()
RectT< T > unionWith (const RectT< T > & r) const inline
get the smallest possible new rectangle that contains both rectangles
vertGrow()
RectT< T > & vertGrow (T delta) inline
increase the height of the rectangle while leaving the center point unchanged
Referenced by RectT< float >::grow().
vertScale()
RectT< T > & vertScale (float f) inline
change the y coordinates of the rectangle by a multiplier
Referenced by RectT< float >::scale().
vertShrink()
RectT< T > & vertShrink (T delta) inline
reduce the height of the rectangle while leaving the center point unchanged
Referenced by RectT< float >::shrink().
width()
T width () const inline
get the width of the rectangle
Referenced by RectT< float >::center(), RectT< float >::centerPoint(), RectT< float >::moveTo(), and RectT< float >::moveXTo().
x1()
T x1 () const inline
get the 1st x coordinate (leftmost)
x2()
T x2 () const inline
get the 2nd x coordinate (rightmost)
y1()
T y1 () const inline
get the 1st y coordinate (topmost)
y2()
T y2 () const inline
get the 2nd y coordinate (bottom-most)
Member Data Documentation
bottom
T bottom
bottom-most coordinate of a rectangle on a grid or screen
Referenced by RectT< float >::intersection(), and RectT< float >::unionWith().
left
T left
leftmost coordinate of a rectangle on a grid or screen
Referenced by RectT< float >::center(), RectT< float >::intersection(), and RectT< float >::unionWith().
right
T right
rightmost coordinate of a rectangle on a grid or screen
Referenced by RectT< float >::intersection(), and RectT< float >::unionWith().
top
T top
topmost coordinate of a rectangle on a grid or screen
Referenced by RectT< float >::center(), RectT< float >::intersection(), and RectT< float >::unionWith().