Pixel Dust Game Engine: Events
Events
Things used to notify your code of user input or other significant events.
Classes
struct StartupInfo
struct ShutdownInfo
struct TimerInfo
struct KeyInfo
struct ModifierKeyInfo
struct PortResizeInfo
struct PortDrawInfo
struct SoundEventInfo
struct SpriteAnimateInfo
struct SpriteLayerInfo
struct NetConnect
struct NetDisconnect
struct NetData
struct NetError
Enumerations
enum {
eventType_Startup = 1 ,
eventType_Shutdown = 2 ,
eventType_Timer = 3 ,
eventType_KeyDown = 4 ,
eventType_KeyUp = 5 ,
eventType_KeyPress = 6 ,
eventType_MouseDown = 7 ,
eventType_MouseUp = 8 ,
eventType_MouseMove = 9 ,
eventType_NetConnect = 10 ,
eventType_NetDisconnect = 11 ,
eventType_NetData = 12 ,
eventType_NetError = 13 ,
eventType_SoundEvent = 14 ,
eventType_PortResized = 15 ,
eventType_ScrollWheel = 16 ,
eventType_SpriteAnimate = 17 ,
eventType_SpriteLayer = 18 ,
eventType_SpriteTouch = 19 ,
eventType_SpriteCollide = 20 ,
eventType_SpriteBreak = 21 ,
eventType_MouseEnter = 22 ,
eventType_MouseLeave = 23 ,
eventType_PortDraw = 24 ,
eventType_SpriteTriggerEvent = 25 ,
eventType_last
}
enum {
key_Break = 1 ,
key_Home = 2 ,
key_End = 3 ,
key_Clear = 4 ,
key_Help = 5 ,
key_Pause = 6 ,
key_Mute = 7 ,
key_Backspace = 8 ,
key_Delete = 127 ,
key_Tab = 9 ,
key_PageUp = 11 ,
key_PageDown = 12 ,
key_Return = 13 ,
key_Enter = key_Return ,
key_F1 = 14 ,
key_F2 = 15 ,
key_F3 = 16 ,
key_F4 = 17 ,
key_F5 = 18 ,
key_F6 = 19 ,
key_F7 = 20 ,
key_F8 = 21 ,
key_F9 = 22 ,
key_F10 = 23 ,
key_F11 = 24 ,
key_F12 = 25 ,
key_FirstF = key_F1 ,
key_LastF = key_F12 ,
key_Insert = 26 ,
key_Escape = 27 ,
key_LeftArrow = 28 ,
key_RightArrow = 29 ,
key_UpArrow = 30 ,
key_DownArrow = 31 ,
key_FirstPrintable = 32
}
enum {
soundEvent_DonePlaying ,
soundEvent_Looping ,
soundEvent_FailedToPlay
}
Functions
struct KeyPressInfo PDG_SUBCLASS_OF (ModifierKeyInfo)
struct MouseTrackingInfo PDG_SUBCLASS_OF (MouseInfo)
Detailed Description
Things used to notify your code of user input or other significant events.
Collection of classes, types and constants used by the Event Manager
Enumeration Type Documentation
anonymous enum
anonymous enum
Keycodes these will be returned in KeyPressInfo->unicode
Enumerator
key_Break
key_Home
key_End
key_Clear
key_Help
key_Pause
key_Mute
key_Backspace
key_Delete
key_Tab
key_PageUp
key_PageDown
key_Return
key_Enter
key_F1
key_F2
key_F3
key_F4
key_F5
key_F6
key_F7
key_F8
key_F9
key_F10
key_F11
key_F12
key_FirstF
key_LastF
key_Insert
key_Escape
key_LeftArrow
key_RightArrow
key_UpArrow
key_DownArrow
key_FirstPrintable
anonymous enum
anonymous enum
Enumerator
soundEvent_DonePlaying
soundEvent_Looping
a non-looping sound finished playing
soundEvent_FailedToPlay
a looping sound finished playing and is restarting
a sound failed to play
anonymous enum
anonymous enum
EventTypes these are used by the EventManager to identify specific events
Enumerator
eventType_Startup
eventType_Shutdown
eventType_Timer
eventType_KeyDown
eventType_KeyUp
eventType_KeyPress
eventType_MouseDown
eventType_MouseUp
eventType_MouseMove
eventType_NetConnect
eventType_NetDisconnect
eventType_NetData
eventType_NetError
eventType_SoundEvent
eventType_PortResized
eventType_ScrollWheel
eventType_SpriteAnimate
eventType_SpriteLayer
eventType_SpriteTouch
eventType_SpriteCollide
eventType_SpriteBreak
eventType_MouseEnter
eventType_MouseLeave
eventType_PortDraw
eventType_SpriteTriggerEvent
eventType_last
Function Documentation
PDG_SUBCLASS_OF() [1/2]
struct ScrollWheelInfo PDG_SUBCLASS_OF (ModifierKeyInfo)
Event Data for eventType_KeyPress. This event will be received for each key press and also for repeat key events when a key is held down
Event Data for eventType_MouseDown, eventType_MouseUp, and eventType_MouseMoved. On multitouch platforms touches and gestures are represented by a series of mouse events where buttonNumber represents a unique finger by order it was placed on the touch surface
Event Data for eventType_ScrollWheel.
the unicode char code for the key, or 0 if no unicode equivalent
true if this is a repeat key event because the key is held down
location of the mouse at the time of the event
state of the left mouse button, true means pressed
state of the right mouse button, true means pressed
button number of the mouse button for mouseUp, mouseDown: 0 = left, 1 = right, 2 = middle button, etc... or for touch gestures this is the unique finger by order placed on the touch surface
mouse position where the last mouse down happened
how many milliseconds since the last mouse down event
the amount of movement horizontally, with positive movement being to the right, negative to the left
the amount of movement vertically, with positive movement being down, negative up
References PDG_SUBCLASS_OF().
Referenced by PDG_SUBCLASS_OF(), PDG_SUBCLASS_OF(), and PDG_SUBCLASS_OF().
PDG_SUBCLASS_OF() [2/2]
struct SpriteTouchInfo PDG_SUBCLASS_OF (MouseInfo)
Event Data for eventType_MouseEnter, and eventType_MouseLeave.
Event Data for eventType_SpriteTouch.
true if the mouse is entering the rectangle, false if it is leaving
the tracking reference for this tracking rectangle, pass to port->stopTrackingMouse() to stop tracking
the data associated with this tracking rectangle, passed in by app when tracking was started
the area being tracked, in port coordinates
what kind of touch occurred, one of the pdg::Sprite::touch_Xxxx enumeration values
which sprite was touched
what layer the Sprite was in when touched
References PDG_SUBCLASS_OF().