Pixel Dust Game Engine: pdg Namespace Reference
pdg Namespace Reference
Namespaces
namespace EasingFuncIds
Classes
class Animated
class Attributes
class AutoCriticalSection
class AutoMutex
class AutoMutexNoThrow
class bad_tag
struct Color
class ConfigManager
class CriticalSection
class Deserializer
class Drawing
class ElementRef
class EventEmitter
Distributes events to event handlers.
class EventManager
struct FindDataT
class Font
class GraphicsManager
class IAnimationHelper
class IDeserializer
class IEventHandler
class Image
class ImageStrip
class Internet
class ISerializable
Represents an object which can be serialized.
class ISerializer
class ISpriteCollideHelper
class ISpriteDrawHelper
struct KeyInfo
class LogManager
struct MemStats
struct ModifierKeyInfo
class Mutex
struct NetConnect
struct NetData
struct NetDisconnect
struct NetError
class NetworkManager
class OffsetT
class OS
class out_of_data
class PDGException
class PointT
class Polygon
class Port
struct PortDrawInfo
struct PortResizeInfo
class QuadT
class RectT
class RefCountedObj
class Renderer
class ResourceManager
class RotatedRectT
class Semaphore
class Serializable
class Serializer
A container for static methods that do the actual serialization.
struct ShutdownInfo
class Singleton
class Sound
struct SoundEventInfo
class SoundManager
class Spline
class Sprite
struct SpriteAnimateInfo
class SpriteLayer
struct SpriteLayerInfo
struct StartupInfo
class sync_error
class TileLayer
class timeout
class TimerException
struct TimerInfo
class TimerManager
class unknown_object
class UserData
class VectorT
Typedefs
typedef OffsetT< float > Offset
typedef PointT< float > Point
typedef VectorT< float > Vector
typedef RectT< float > Rect
typedef QuadT< float > Quad
typedef RotatedRectT< float > RotatedRect
typedef float(* EasingFunc) (ms_delta timeOffsetMs, float beginVal, float change, ms_delta durationMs)
typedef uint16 utf16char
typedef uint32 utf32char
typedef bool(* ReceiveFunc) (int status, int httpResultCode, char *dataPtr, size_t dataSize, void *context)
typedef bool(* GatekeeperFunc) (NetData *ndptr, void *gateContext)
typedef std::basic_string< utf16char > utf16string
typedef void(* UserFreeFuncT) (void *data)
Enumerations
enum {
duration_Constant = -1 ,
duration_Instantaneous = 0
}
enum {
lftTop = 0 ,
rgtTop = 1 ,
rgtBot = 2 ,
lftBot = 3
}
enum ElementType {
type_Line = 1 ,
type_Spline ,
type_Rect ,
type_RotatedRect ,
type_Quad ,
type_Polygon ,
type_Circle ,
type_Oval ,
type_Image ,
type_ImageStrip ,
type_Drawing
}
enum { all_events = 0 }
enum {
eventType_Startup = 1 ,
eventType_Shutdown = 2 ,
eventType_Timer = 3 ,
eventType_KeyDown = 4 ,
eventType_KeyUp = 5 ,
eventType_KeyPress = 6 ,
eventType_MouseDown = 7 ,
eventType_MouseUp = 8 ,
eventType_MouseMove = 9 ,
eventType_NetConnect = 10 ,
eventType_NetDisconnect = 11 ,
eventType_NetData = 12 ,
eventType_NetError = 13 ,
eventType_SoundEvent = 14 ,
eventType_PortResized = 15 ,
eventType_ScrollWheel = 16 ,
eventType_SpriteAnimate = 17 ,
eventType_SpriteLayer = 18 ,
eventType_SpriteTouch = 19 ,
eventType_SpriteCollide = 20 ,
eventType_SpriteBreak = 21 ,
eventType_MouseEnter = 22 ,
eventType_MouseLeave = 23 ,
eventType_PortDraw = 24 ,
eventType_SpriteTriggerEvent = 25 ,
eventType_last
}
enum {
key_Break = 1 ,
key_Home = 2 ,
key_End = 3 ,
key_Clear = 4 ,
key_Help = 5 ,
key_Pause = 6 ,
key_Mute = 7 ,
key_Backspace = 8 ,
key_Delete = 127 ,
key_Tab = 9 ,
key_PageUp = 11 ,
key_PageDown = 12 ,
key_Return = 13 ,
key_Enter = key_Return ,
key_F1 = 14 ,
key_F2 = 15 ,
key_F3 = 16 ,
key_F4 = 17 ,
key_F5 = 18 ,
key_F6 = 19 ,
key_F7 = 20 ,
key_F8 = 21 ,
key_F9 = 22 ,
key_F10 = 23 ,
key_F11 = 24 ,
key_F12 = 25 ,
key_FirstF = key_F1 ,
key_LastF = key_F12 ,
key_Insert = 26 ,
key_Escape = 27 ,
key_LeftArrow = 28 ,
key_RightArrow = 29 ,
key_UpArrow = 30 ,
key_DownArrow = 31 ,
key_FirstPrintable = 32
}
enum {
screenPos_Normal ,
screenPos_Rotated180 ,
screenPos_Rotated90Clockwise ,
screenPos_Rotated90CounterClockwise ,
screenPos_FaceUp ,
screenPos_FaceDown
}
enum {
soundEvent_DonePlaying ,
soundEvent_Looping ,
soundEvent_FailedToPlay
}
enum Style {
textStyle_Plain = 0 ,
textStyle_Bold = 1 ,
textStyle_Italic = 2 ,
textStyle_Underline = 4 ,
textStyle_Centered = 16 ,
textStyle_LeftJustified = 0 ,
textStyle_RightJustified = 32
}
enum {
screenNum_PrimaryScreen = -1 ,
screenNum_BestFitScreen = -2
}
enum FitType {
fit_None ,
fit_Height ,
fit_Width ,
fit_Inside ,
fit_Fill ,
fit_FillKeepProportions
}
how images should fit into rectangles
enum LineStyle {
LineStyle_Solid ,
LineStyle_Dashed ,
LineStyle_Dotted ,
LineStyle_DashDot ,
LineStyle_DashDotDot
}
enum BlendMode {
BlendMode_Normal ,
BlendMode_Additive ,
BlendMode_Multiply ,
BlendMode_Screen ,
BlendMode_Darken ,
BlendMode_Lighten
}
enum GradientType {
GradientType_None ,
GradientType_Linear ,
GradientType_Radial
}
enum {
ser_Positions = 1 << 0 ,
ser_ZOrder = 1 << 1 ,
ser_Sizes = 1 << 2 ,
ser_Animations = 1 << 3 ,
ser_Motion = 1 << 4 ,
ser_Forces = 1 << 5 ,
ser_Physics = 1 << 6 ,
ser_LayerDraw = 1 << 7 ,
ser_ImageRefs = 1 << 8 ,
ser_SCMLRefs = 1 << 9 ,
ser_HelperRefs = 1 << 10 ,
ser_ImageData = 1 << 11 ,
ser_SCMLData = 1 << 12 ,
ser_HelperObjs = 1 << 13 ,
ser_InitialData = 1 << 14 ,
ser_Micro = ser_Positions | ser_ZOrder ,
ser_Update = ser_Micro | ser_Sizes | ser_Animations | ser_Motion | ser_Forces | ser_Physics ,
ser_Full = ser_Update | ser_ImageRefs | ser_SCMLRefs | ser_HelperRefs | ser_InitialData
}
enum {
timer_OneShot = true ,
timer_Repeating = false ,
timer_Never = 0xffffffff
}
enum FreeDataT {
data_DoNothing = 0 ,
data_Free = 1 ,
data_Delete = 2 ,
data_ArrayDelete = 3 ,
data_CallUserFunc = 4 ,
obj_RefCountedRelease = 5
}
Functions
bool operator== (const Color &a, const Color &b)
check to see if two colors are the same, IGNORES ALPHA
float linearTween (ms_delta ut, float b, float c, ms_delta ud)
float easeInQuad (ms_delta ut, float b, float c, ms_delta ud)
float easeOutQuad (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutQuad (ms_delta ut, float b, float c, ms_delta ud)
float easeInCubic (ms_delta ut, float b, float c, ms_delta ud)
float easeOutCubic (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutCubic (ms_delta ut, float b, float c, ms_delta ud)
float easeInQuart (ms_delta ut, float b, float c, ms_delta ud)
float easeOutQuart (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutQuart (ms_delta ut, float b, float c, ms_delta ud)
float easeInQuint (ms_delta ut, float b, float c, ms_delta ud)
float easeOutQuint (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutQuint (ms_delta ut, float b, float c, ms_delta ud)
float easeInSine (ms_delta ut, float b, float c, ms_delta ud)
float easeOutSine (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutSine (ms_delta ut, float b, float c, ms_delta ud)
float easeInExpo (ms_delta ut, float b, float c, ms_delta ud)
float easeOutExpo (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutExpo (ms_delta ut, float b, float c, ms_delta ud)
float easeInCirc (ms_delta ut, float b, float c, ms_delta ud)
float easeOutCirc (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutCirc (ms_delta ut, float b, float c, ms_delta ud)
float easeInBounce (ms_delta ut, float b, float c, ms_delta ud)
float easeOutBounce (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutBounce (ms_delta ut, float b, float c, ms_delta ud)
float easeInBack (ms_delta ut, float b, float c, ms_delta ud)
float easeOutBack (ms_delta ut, float b, float c, ms_delta ud)
float easeInOutBack (ms_delta ut, float b, float c, ms_delta ud)
uint8 easingFuncToId (EasingFunc func)
EasingFunc easingIdToFunc (uint8 id)
const char * getEventName (long eventType)
struct KeyPressInfo PDG_SUBCLASS_OF (ModifierKeyInfo)
struct MouseTrackingInfo PDG_SUBCLASS_OF (MouseInfo)
struct SpriteCollideInfo PDG_SUBCLASS_OF (SpriteAnimateInfo)
SpriteLayer * createSpriteLayer ()
SpriteLayer * createSpriteLayer (Port *port=0)
void cleanupLayer (SpriteLayer *layer)
TileLayer * createTileLayer (Port *port)
TileLayer * createTileLayer ()
Variables
EasingFunc gEasingFunctions [NUM_EASING_FUNCTIONS]
int gNumCustomEasings
long gNextSpriteEventId
const Attributes DEFAULT_LINE_ATTRIBUTES
const Attributes DEFAULT_FILL_ATTRIBUTES
template<class T>
T * Singleton< T >::sInstance = 0
MemStats gSoundStats
Typedef Documentation
EasingFunc
typedef float(* EasingFunc) (ms_delta timeOffsetMs, float beginVal, float change, ms_delta durationMs)
GatekeeperFunc
typedef bool(* GatekeeperFunc) (NetData *ndptr, void *gateContext)
Offset
typedef OffsetT<float> Offset
Point
typedef PointT< float > Point
Quad
typedef QuadT<float> Quad
ReceiveFunc
typedef bool(* ReceiveFunc) (int status, int httpResultCode, char *dataPtr, size_t dataSize, void *context)
Rect
typedef RectT<float> Rect
RotatedRect
typedef RotatedRectT<float> RotatedRect
UserFreeFuncT
typedef void(* UserFreeFuncT) (void *data)
utf16char
typedef uint16 utf16char
utf16string
typedef std::basic_string<utf16char> utf16string
utf32char
typedef uint32 utf32char
Vector
typedef VectorT<float> Vector
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
duration_Constant
duration_Instantaneous
anonymous enum
anonymous enum
Enumerator
all_events
anonymous enum
anonymous enum
Enumerator
screenPos_Normal
screenPos_Rotated180
screenPos_Rotated90Clockwise
screenPos_Rotated90CounterClockwise
screenPos_FaceUp
screenPos_FaceDown
anonymous enum
anonymous enum
Enumerator
ser_Positions
ser_ZOrder
ser_Sizes
ser_Animations
ser_Motion
ser_Forces
ser_Physics
ser_LayerDraw
ser_ImageRefs
ser_SCMLRefs
ser_HelperRefs
ser_ImageData
ser_SCMLData
ser_HelperObjs
ser_InitialData
ser_Micro
ser_Update
ser_Full
anonymous enum
anonymous enum
Enumerator
timer_OneShot
timer_Repeating
timer_Never
anonymous enum
anonymous enum
Enumerator
screenNum_PrimaryScreen
screenNum_BestFitScreen
anonymous enum
anonymous enum
Enumerator
lftTop
rgtTop
rgtBot
lftBot
BlendMode
enum BlendMode
Enumerator
BlendMode_Normal
BlendMode_Additive
BlendMode_Multiply
BlendMode_Screen
BlendMode_Darken
BlendMode_Lighten
ElementType
enum ElementType
Enumerator
type_Line
type_Spline
type_Rect
type_RotatedRect
type_Quad
type_Polygon
type_Circle
type_Oval
type_Image
type_ImageStrip
type_Drawing
FitType
enum FitType
how images should fit into rectangles
Enumerator
fit_None
fit_Height
fit_Width
fit_Inside
fit_Fill
fit_FillKeepProportions
FreeDataT
enum FreeDataT
Enumerator
data_DoNothing
data_Free
data_Delete
data_ArrayDelete
data_CallUserFunc
obj_RefCountedRelease
GradientType
enum GradientType
Enumerator
GradientType_None
GradientType_Linear
GradientType_Radial
LineStyle
enum LineStyle
Enumerator
LineStyle_Solid
LineStyle_Dashed
LineStyle_Dotted
LineStyle_DashDot
LineStyle_DashDotDot
Function Documentation
cleanupLayer()
void cleanupLayer (SpriteLayer * layer)
createSpriteLayer() [1/2]
SpriteLayer * createSpriteLayer ()
createSpriteLayer() [2/2]
SpriteLayer * createSpriteLayer (Port * port = 0)
createTileLayer() [1/2]
TileLayer * createTileLayer ()
createTileLayer() [2/2]
TileLayer * createTileLayer (Port * port)
easeInBack()
float easeInBack (ms_delta ut, float b, float c, ms_delta ud)
easeInBounce()
float easeInBounce (ms_delta ut, float b, float c, ms_delta ud)
easeInCirc()
float easeInCirc (ms_delta ut, float b, float c, ms_delta ud)
easeInCubic()
float easeInCubic (ms_delta ut, float b, float c, ms_delta ud)
easeInExpo()
float easeInExpo (ms_delta ut, float b, float c, ms_delta ud)
easeInOutBack()
float easeInOutBack (ms_delta ut, float b, float c, ms_delta ud)
easeInOutBounce()
float easeInOutBounce (ms_delta ut, float b, float c, ms_delta ud)
easeInOutCirc()
float easeInOutCirc (ms_delta ut, float b, float c, ms_delta ud)
easeInOutCubic()
float easeInOutCubic (ms_delta ut, float b, float c, ms_delta ud)
easeInOutExpo()
float easeInOutExpo (ms_delta ut, float b, float c, ms_delta ud)
easeInOutQuad()
float easeInOutQuad (ms_delta ut, float b, float c, ms_delta ud)
Referenced by Animated::changeCenterTo(), Sound::changePitch(), Animated::moveTo(), Animated::resizeTo(), Animated::rotateTo(), and SpriteLayer::zoomTo().
easeInOutQuart()
float easeInOutQuart (ms_delta ut, float b, float c, ms_delta ud)
easeInOutQuint()
float easeInOutQuint (ms_delta ut, float b, float c, ms_delta ud)
easeInOutSine()
float easeInOutSine (ms_delta ut, float b, float c, ms_delta ud)
easeInQuad()
float easeInQuad (ms_delta ut, float b, float c, ms_delta ud)
easeInQuart()
float easeInQuart (ms_delta ut, float b, float c, ms_delta ud)
easeInQuint()
float easeInQuint (ms_delta ut, float b, float c, ms_delta ud)
easeInSine()
float easeInSine (ms_delta ut, float b, float c, ms_delta ud)
easeOutBack()
float easeOutBack (ms_delta ut, float b, float c, ms_delta ud)
easeOutBounce()
float easeOutBounce (ms_delta ut, float b, float c, ms_delta ud)
easeOutCirc()
float easeOutCirc (ms_delta ut, float b, float c, ms_delta ud)
easeOutCubic()
float easeOutCubic (ms_delta ut, float b, float c, ms_delta ud)
easeOutExpo()
float easeOutExpo (ms_delta ut, float b, float c, ms_delta ud)
easeOutQuad()
float easeOutQuad (ms_delta ut, float b, float c, ms_delta ud)
easeOutQuart()
float easeOutQuart (ms_delta ut, float b, float c, ms_delta ud)
easeOutQuint()
float easeOutQuint (ms_delta ut, float b, float c, ms_delta ud)
easeOutSine()
float easeOutSine (ms_delta ut, float b, float c, ms_delta ud)
easingFuncToId()
uint8 easingFuncToId (EasingFunc func)
easingIdToFunc()
EasingFunc easingIdToFunc (uint8 id)
getEventName()
const char * getEventName (long eventType)
linearTween()
float linearTween (ms_delta ut, float b, float c, ms_delta ud)
Referenced by Animated::accelerateTo(), Sound::changeOffsetX(), Sound::changeVolume(), Sound::fadeIn(), Sprite::fadeIn(), SpriteLayer::fadeIn(), Sound::fadeOut(), Sprite::fadeOut(), SpriteLayer::fadeOut(), and Sprite::fadeTo().
operator==()
bool operator== (const Color & a, const Color & b) inline
check to see if two colors are the same, IGNORES ALPHA
References Color::blue, Color::green, and Color::red.
Variable Documentation
DEFAULT_FILL_ATTRIBUTES
const Attributes DEFAULT_FILL_ATTRIBUTES extern
DEFAULT_LINE_ATTRIBUTES
const Attributes DEFAULT_LINE_ATTRIBUTES extern
gEasingFunctions
EasingFunc gEasingFunctions[NUM_EASING_FUNCTIONS] extern
gNextSpriteEventId
long gNextSpriteEventId extern
gNumCustomEasings
int gNumCustomEasings extern
gSoundStats
MemStats gSoundStats extern
Singleton< T >::sInstance
template<class T> T* Singleton< T >::sInstance = 0