// Supported Jasmine suites in the browser and iOS JSC harnesses.
(function(root) {
    var shared = [
    "async_runner",
    "animated",
    "animatedattributes",
    "animated_controls",
    "animated_programming",
    "animated_browser_callbacks",
    "animated_chaining",
    "part",
    "physicsbody",
    "collider",
    "particle",
    "animation_pose",
    "spriter_playback",
    "animation_event_filtering",
    "color",
    "color_bindings",
    "configmanager",
    "drawing",
    "event_filtering_comprehensive",
    "eventemitter",
    "eventmanager",
    "filemanager",
    "font",
    "graphicsmanager",
    "image",
    "imagestrip",
    "log",
    "matrix_bindings",
    "memblock",
    "mvc-app",
    "mvc_animation",
    "netclient",
    "netconnection",
    "netserver",
    "node_runtime",
    "offscreen",
    "offset",
    "offset_vector_bindings",
    "point",
    "point_bindings",
    "polygon",
    "polygon_bindings",
    "port",
    "process_lifetime",
    "quad",
    "quad_bindings",
    "rect",
    "rect_bindings",
    "resourcemanager",
    "rotatedrect",
    "serialization",
    "serialized_data",
    "serialized_objects",
    "sound",
    "soundmanager",
    "spline",
    "sprite",
    "sprite_layer_event_filtering",
    "spritelayer",
    "spriter",
    "spriter_animblend",
    "spriter_attach",
    "spriter_charmap",
    "spriter_collisions",
    "spriter_events",
    "spriter_subentity",
    "tilelayer",
    "timermanager",
    "vector"
];
    // Individual specs gate capabilities unavailable in a particular runtime.
    var catalog = {web: shared, ios: shared.slice()};
    if (typeof module !== "undefined") module.exports = catalog;
    else root.PDG_CLIENT_SPECS = catalog;
}(typeof window !== "undefined" ? window : this));
