Pixel Dust Game Engine: Vector Class Reference
Vector Class Reference
Graphics | Animation
vector (magnitude and direction) within a 2D coordinate system.
Public Member Functions
Vector ()
Vector (number x, number y)
Vector (number[] xy)
Vector (object xy)
number dotProduct (Vector vector)
get dot product for this vector with a 2nd vector
Vector normal ()
get the normal of this vector, ie: A.normal() = (-A.y, A.x)
Point projection (Point point)
do a projection of a point onto this vector
Vector unit ()
get the unit vector of this vector, ie: A.unit() = (A.x / |A|, A.y / |A|)
number vectorAngle ()
get angle (in radians) for this vector
number vectorLength ()
get length as a vector (distance from origin)
Public Member Functions inherited from Offset
Offset ()
Offset (number x, number y)
Offset (number[] xy)
Offset (object xy)
Offset add (Offset offset)
add an offset to this one
Offset assign (Offset offset)
set this offset equal to the given offset
Offset div (Offset offset)
divide this offset by the given one
Offset dividedby (Offset offset)
return new offset that is this offset divided by given offset
boolean equals (Offset offset)
return true if this point is equal to the other
Offset minus (Offset offset)
return new offset that is this offset minus given offset
Offset mul (Offset offset)
multiply this offset by the given one
boolean notEquals (Offset offset)
return true if this point is not equal to the other
Offset plus (Offset offset)
return new offset that is this offset plus given offset
Offset sub (Offset offset)
subtract an offset from this one
Offset times (Offset offset)
return new offset that is this offset multiplied by given offset
Vector vector ()
return a new vector from this offset
Public Attributes
number x
number y
Public Attributes inherited from Offset
number x
number y
Detailed Description
vector (magnitude and direction) within a 2D coordinate system.
Point provides support for dealing with vectors as x, y floating point values in 2 dimensional space. A vector is similar to an Offset but can be treated as a magnitude and direction where an Offset can't. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point(width, height);
Constructor & Destructor Documentation
Vector() [1/4]
Vector ()
Referenced by dotProduct(), normal(), and unit().
Vector() [2/4]
Vector (number x, number y)
References x, and y.
Vector() [3/4]
Vector (number[] xy)
Vector() [4/4]
Vector (object xy)
Member Function Documentation
dotProduct()
number dotProduct (Vector vector)
get dot product for this vector with a 2nd vector
References Vector(), and Offset::vector().
normal()
Vector normal ()
get the normal of this vector, ie: A.normal() = (-A.y, A.x)
References Vector().
projection()
Point projection (Point point)
do a projection of a point onto this vector
unit()
Vector unit ()
get the unit vector of this vector, ie: A.unit() = (A.x / |A|, A.y / |A|)
References Vector().
vectorAngle()
number vectorAngle ()
get angle (in radians) for this vector
vectorLength()
number vectorLength ()
get length as a vector (distance from origin)
Member Data Documentation
x
number x
Referenced by Vector().
y
number y
Referenced by Vector().
User Comments