Pixel Dust Game Engine: Quad Class Reference
Quad Class Reference
Graphics | Animation
4 point polygon in 2D system
Public Member Functions
Quad ()
Quad (Point p1, Point p2, Point p3, Point p4)
Quad (Point[] p)
Quad (Quad q)
Quad (Rect r)
Quad (RotatedRect r)
Point centerPoint ()
return the calculated centerpoint of the quad
boolean contains (Point p)
returns true if the point is contained within this quad
boolean equals (Quad q2)
return true if this quad is equal to the given one
Rect getBounds ()
return a rectangle that bounds the quad
moveDown (number delta)
move the quad down by some amount
moveLeft (number delta)
move the quad to the left by some amount
moveRight (number delta)
move the quad to the right by some amount
moveUp (number delta)
move the quad up by some amount
boolean notEquals (Quad q2)
return true if this quad is not equal to the given one
rotate (number rotationRadians, Offset centerPtOffset=Point(0, 0))
rotate(n): rotate the quad by a rotation in radians (around the calculated center point of the quad); rotate(n, [Offset] o): rotate the quad by a rotation in radians around an offset center point
Public Attributes
Point[] points
Detailed Description
4 point polygon in 2D system
Quad is a class that provides support for dealing with 4 point ploygons in 2 dimensional space The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point(width, height);
Constructor & Destructor Documentation
Quad() [1/6]
Quad ()
Referenced by Quad(), equals(), and notEquals().
Quad() [2/6]
Quad (Quad q)
References Quad().
Quad() [3/6]
Quad (Rect r)
Quad() [4/6]
Quad (RotatedRect r)
Quad() [5/6]
Quad (Point p1, Point p2, Point p3, Point p4)
Quad() [6/6]
Quad (Point[] p)
Member Function Documentation
centerPoint()
Point centerPoint ()
return the calculated centerpoint of the quad
contains()
boolean contains (Point p)
returns true if the point is contained within this quad
equals()
boolean equals (Quad q2)
return true if this quad is equal to the given one
References Quad().
getBounds()
Rect getBounds ()
return a rectangle that bounds the quad
moveDown()
moveDown (number delta)
move the quad down by some amount
moveLeft()
moveLeft (number delta)
move the quad to the left by some amount
moveRight()
moveRight (number delta)
move the quad to the right by some amount
moveUp()
moveUp (number delta)
move the quad up by some amount
notEquals()
boolean notEquals (Quad q2)
return true if this quad is not equal to the given one
References Quad().
rotate()
rotate (number rotationRadians, Offset centerPtOffset = Point(0,0))
rotate(n): rotate the quad by a rotation in radians (around the calculated center point of the quad); rotate(n, [Offset] o): rotate the quad by a rotation in radians around an offset center point
Member Data Documentation
points
Point [] points
User Comments