Pixel Dust Game Engine: Rect Class Reference
Rect Class Reference
Graphics | Animation
Rectangle for 2D coordinate system.
Public Member Functions
Rect ()
Rect (number left, number top, number right, number bottom)
Rect (number w, number h)
Rect (Point leftTop, Point rightBottom)
Rect (Point topLeft, number w, number h)
Rect add (Point p)
add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates
Rect add (Rect r2)
add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates
Rect assign (Rect r2)
set this rectangle equal to the given one
center (Point p)
center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle
center (Rect r)
center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle
Point centerPoint ()
get center point of this rectangle
boolean contains (Point p)
contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle
boolean contains (Rect r)
contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle
Rect div (Point p)
div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle
Rect div (Rect r2)
div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle
Rect dividedby (Point p)
Divide this rectangle by a point, returning a new rectangle with scaled dimensions.
Rect dividedby (Rect r2)
Divide this rectangle by another rectangle, returning a new rectangle with scaled dimensions.
boolean empty ()
return true if this rectangle is empty (no width or no height)
boolean equals (Rect r2)
return true if this rectangle is equal to the given one
grow (number delta)
increase the height and width of the rectangle while leaving the center point unchanged
number height ()
get the height of this rectangle
horzGrow (number delta)
increase the width of the rectangle while leaving the center point unchanged
horzScale (number f)
change the x coordinates of the rectangle by a multiplier
horzShrink (number delta)
reduce the width of the rectangle while leaving the center point unchanged
Rect intersection (Rect r)
get a new rectangle that is the overlapping area of the the rectangles
Point leftBottom ()
get bottom left corner point of this rectangle
Point leftTop ()
get top left corner point of this rectangle
Rect minus (Point p)
Subtract a point from this rectangle, shifting its position.
Rect minus (Rect r2)
Subtract another rectangle from this rectangle, returning the difference.
moveDown (number delta)
move the rectangle down by some amount
moveLeft (number delta)
move the rectangle to the left by some amount
moveRight (number delta)
move the rectangle to the right by some amount
moveTo (number x, number y)
moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point
moveTo (Point p)
moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point
moveUp (number delta)
move the rectangle up by some amount
moveXTo (number x)
move the rectangle to a particular x location, leaving y unchanged
moveYTo (number y)
move the rectangle to a particular y location, leaving x unchanged
Rect mul (Point p)
mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle
Rect mul (Rect r2)
mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle
boolean notEquals (Rect r2)
return true if this rectangle is not equal to the given one
boolean overlaps (Rect r)
return true if this rectangle overlaps the other rectangle at all (sharing an edge is not overlapping)
Rect plus (Point p)
Add a point to this rectangle, shifting its position.
Rect plus (Rect r2)
Add another rectangle to this rectangle, returning the combined result.
Point rightBottom ()
get bottom right corner point of this rectangle
Point rightTop ()
get top right corner point of this rectangle
round ()
round the coordinates to closest whole number
scale (number f)
change the coordinates of the rectangle by a multiplier
setHeight (number h)
Set the height of this rectangle, keeping the top edge fixed.
setSize (number n)
set the size (width & height) of the rectangle
setWidth (number w)
Set the width of this rectangle, keeping the left edge fixed.
shrink (number delta)
reduce the height and width of the rectangle while leaving the center point unchanged
Rect sub (Point p)
sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates
Rect sub (Rect r2)
sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates
Rect times (Point p)
Multiply this rectangle by a point, scaling its dimensions.
Rect times (Rect r2)
Multiply this rectangle by another rectangle, scaling its dimensions.
Quad toQuad ()
convert rectangle to a Quad
Rect unionWith (Rect r)
get the smallest possible new rectangle that contains both rectangles
vertGrow (number delta)
increase the height of the rectangle while leaving the center point unchanged
vertScale (number f)
change the y coordinates of the rectangle by a multiplier
vertShrink (number delta)
reduce the height of the rectangle while leaving the center point unchanged
number width ()
get the width of this rectangle
number x1 ()
alias for Rect.left
number x2 ()
alias for Rect.right
number y1 ()
alias for Rect.top
number y2 ()
alias for Rect.bottom
Public Attributes
number bottom
number left
number right
number top
Detailed Description
Rectangle for 2D coordinate system.
Rect is a class that provides support for dealing with rectangles in 2 dimensional space. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point(width, height);
Constructor & Destructor Documentation
Rect() [1/5]
Rect ()
Referenced by RotatedRect::RotatedRect(), add(), add(), assign(), center(), contains(), div(), div(), dividedby(), dividedby(), equals(), intersection(), minus(), minus(), mul(), mul(), notEquals(), overlaps(), plus(), plus(), sub(), sub(), times(), times(), and unionWith().
Rect() [2/5]
Rect (number w, number h)
Rect() [3/5]
Rect (Point topLeft, number w, number h)
Rect() [4/5]
Rect (Point leftTop, Point rightBottom)
References leftTop(), and rightBottom().
Rect() [5/5]
Rect (number left, number top, number right, number bottom)
References bottom, left, right, and top.
Member Function Documentation
add() [1/2]
Rect add (Point p)
add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates
References Rect().
add() [2/2]
Rect add (Rect r2)
add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates
References Rect().
assign()
Rect assign (Rect r2)
set this rectangle equal to the given one
References Rect().
center() [1/2]
center (Point p)
center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle
center() [2/2]
center (Rect r)
center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle
References Rect().
centerPoint()
Point centerPoint ()
get center point of this rectangle
contains() [1/2]
boolean contains (Point p)
contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle
contains() [2/2]
boolean contains (Rect r)
contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle
References Rect().
div() [1/2]
Rect div (Point p)
div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle
References Rect().
div() [2/2]
Rect div (Rect r2)
div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle
References Rect().
dividedby() [1/2]
Rect dividedby (Point p)
Divide this rectangle by a point, returning a new rectangle with scaled dimensions.
References Rect().
dividedby() [2/2]
Rect dividedby (Rect r2)
Divide this rectangle by another rectangle, returning a new rectangle with scaled dimensions.
References Rect().
empty()
boolean empty ()
return true if this rectangle is empty (no width or no height)
equals()
boolean equals (Rect r2)
return true if this rectangle is equal to the given one
References Rect().
grow()
grow (number delta)
increase the height and width of the rectangle while leaving the center point unchanged
height()
number height ()
get the height of this rectangle
horzGrow()
horzGrow (number delta)
increase the width of the rectangle while leaving the center point unchanged
horzScale()
horzScale (number f)
change the x coordinates of the rectangle by a multiplier
horzShrink()
horzShrink (number delta)
reduce the width of the rectangle while leaving the center point unchanged
intersection()
Rect intersection (Rect r)
get a new rectangle that is the overlapping area of the the rectangles
References Rect().
leftBottom()
Point leftBottom ()
get bottom left corner point of this rectangle
leftTop()
Point leftTop ()
get top left corner point of this rectangle
Referenced by Rect().
minus() [1/2]
Rect minus (Point p)
Subtract a point from this rectangle, shifting its position.
References Rect().
minus() [2/2]
Rect minus (Rect r2)
Subtract another rectangle from this rectangle, returning the difference.
References Rect().
moveDown()
moveDown (number delta)
move the rectangle down by some amount
moveLeft()
moveLeft (number delta)
move the rectangle to the left by some amount
moveRight()
moveRight (number delta)
move the rectangle to the right by some amount
moveTo() [1/2]
moveTo (number x, number y)
moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point
moveTo() [2/2]
moveTo (Point p)
moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point
moveUp()
moveUp (number delta)
move the rectangle up by some amount
moveXTo()
moveXTo (number x)
move the rectangle to a particular x location, leaving y unchanged
moveYTo()
moveYTo (number y)
move the rectangle to a particular y location, leaving x unchanged
mul() [1/2]
Rect mul (Point p)
mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle
References Rect().
mul() [2/2]
Rect mul (Rect r2)
mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle
References Rect().
notEquals()
boolean notEquals (Rect r2)
return true if this rectangle is not equal to the given one
References Rect().
overlaps()
boolean overlaps (Rect r)
return true if this rectangle overlaps the other rectangle at all (sharing an edge is not overlapping)
References Rect().
plus() [1/2]
Rect plus (Point p)
Add a point to this rectangle, shifting its position.
References Rect().
plus() [2/2]
Rect plus (Rect r2)
Add another rectangle to this rectangle, returning the combined result.
References Rect().
rightBottom()
Point rightBottom ()
get bottom right corner point of this rectangle
Referenced by Rect().
rightTop()
Point rightTop ()
get top right corner point of this rectangle
round()
round ()
round the coordinates to closest whole number
scale()
scale (number f)
change the coordinates of the rectangle by a multiplier
setHeight()
setHeight (number h)
Set the height of this rectangle, keeping the top edge fixed.
setSize()
setSize (number n)
set the size (width & height) of the rectangle
setWidth()
setWidth (number w)
Set the width of this rectangle, keeping the left edge fixed.
shrink()
shrink (number delta)
reduce the height and width of the rectangle while leaving the center point unchanged
sub() [1/2]
Rect sub (Point p)
sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates
References Rect().
sub() [2/2]
Rect sub (Rect r2)
sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates
References Rect().
times() [1/2]
Rect times (Point p)
Multiply this rectangle by a point, scaling its dimensions.
References Rect().
times() [2/2]
Rect times (Rect r2)
Multiply this rectangle by another rectangle, scaling its dimensions.
References Rect().
toQuad()
Quad toQuad ()
convert rectangle to a Quad
unionWith()
Rect unionWith (Rect r)
get the smallest possible new rectangle that contains both rectangles
References Rect().
vertGrow()
vertGrow (number delta)
increase the height of the rectangle while leaving the center point unchanged
vertScale()
vertScale (number f)
change the y coordinates of the rectangle by a multiplier
vertShrink()
vertShrink (number delta)
reduce the height of the rectangle while leaving the center point unchanged
width()
number width ()
get the width of this rectangle
x1()
number x1 ()
alias for Rect.left
x2()
number x2 ()
alias for Rect.right
y1()
number y1 ()
alias for Rect.top
y2()
number y2 ()
alias for Rect.bottom
Member Data Documentation
bottom
number bottom
Referenced by Rect().
left
number left
Referenced by Rect().
right
number right
Referenced by Rect().
top
number top
Referenced by Rect().
User Comments