Pixel Dust Game Engine: Attributes Class Reference
Attributes Class Reference
Container for styling and transformation attributes used in drawing operations.
Public Member Functions
ambientLight (Color color)
blendMode (int blendMode)
sets the blend mode for rendering operations
clipOverflow ()
Sets whether image overflow should be clipped when drawn.
fillColor (Color color)
sets the fill color for shapes and drawings
fillGradient (Point start, Color startColor, Point end, Color endColor)
sets a linear gradient fill from start point to end point
fillOpacity (number float opacity)
sets the opacity for fill operations (0.0 to 1.0)
fillRadialGradient (Point center, Color centerColor, number float radius, Color endColor)
Create a radial gradient fill from center point to outer radius.
fitType (int fit)
Sets how an image should be fitted into a target rectangle.
font (Font font)
Sets the font to use for drawing text.
frame (int frame)
Sets which frame of an ImageStrip to draw.
Color getAmbientLight ()
int getBlendMode ()
returns the current blend mode
boolean getClipOverflow ()
Gets whether image overflow should be clipped when drawn.
Color getFillColor ()
returns the current fill color
number float getFillOpacity ()
returns the current fill opacity
int getFitType ()
Gets how an image should be fitted into a target rectangle.
Font getFont ()
Gets the font to use for drawing text.
int getFrame ()
Gets which frame of an ImageStrip to draw.
Point getGradientEnd ()
returns the gradient end point
Color getGradientEndColor ()
returns the gradient end color
Point getGradientStart ()
returns the gradient start point
Color getGradientStartColor ()
returns the gradient start color
int getGradientType ()
returns the current gradient type
Offset getLightOffset ()
Gets the light source offset in spherical coordinates (radians) for sphere lighting.
Color getLineColor ()
returns the current line color
number float getLineOpacity ()
Get the current line opacity value.
uint getLineStyle ()
returns the current line style
number float getLineThickness ()
returns the current line thickness
Offset getPolarOffset ()
Gets the polar offset for rotating a textured sphere.
Point getRadialGradientCenter ()
returns the radial gradient center point
Color getRadialGradientCenterColor ()
returns the radial gradient center color
Color getRadialGradientEndColor ()
returns the radial gradient end color
number float getRadialGradientRadius ()
returns the radial gradient radius
number float getRoundedCornerRadius ()
returns the rounded corner radius
number float getSphereRotation ()
Gets the rotation angle in radians for a textured sphere.
Rect getSubsection ()
Gets the subsection of an image to draw.
number float getTextSize ()
Gets the text size in points for drawing text.
int getTextStyle ()
Gets text style flags (bold, italic, underline, alignment)
Image getTexture ()
Gets the texture image to use for drawing a sphere.
array number getTransform ()
returns the current transformation matrix
lightOffset (Offset offset)
Sets light source with spherical coordinates in radians.
lineColor (Color color)
sets the line color for strokes and outlines
lineOpacity (number float opacity)
sets the opacity for line strokes (0.0 to 1.0)
lineStyle (int lineStyle)
sets the style of line strokes (solid, dashed, etc.)
lineThickness (number float thickness)
sets the thickness of line strokes in pixels
polarOffset (Offset offset)
Sets the polar offset for rotating a textured sphere.
rotation (number float radians, Point center=Point(0, 0))
sets the rotation angle and center point for transformations
roundedCorners (number float radius)
sets the radius for rounded corners
scale (number float xFactor, number float yFactor=xFactor)
sets the scaling factors for x and y axes
skew (number float xSkew, number float ySkew)
sets the skew transformation for x and y axes
sphereRotation (number float rotation)
Sets the rotation angle in radians for a textured sphere.
subsection (Rect section)
Sets a subsection of an image to draw.
textSize (number float size)
Sets the text size in points for drawing text.
textStyle (int style)
Sets text style flags (bold, italic, underline, alignment)
texture (Image texture)
Sets the texture image to use for drawing a sphere.
transform (array number matrix)
sets the transformation matrix directly
translation (Offset offset)
sets the translation offset for transformations
Detailed Description
Container for styling and transformation attributes used in drawing operations.
Member Function Documentation
ambientLight()
ambientLight (Color color)
blendMode()
blendMode (int blendMode)
sets the blend mode for rendering operations
References blendMode().
Referenced by blendMode().
clipOverflow()
clipOverflow ()
Sets whether image overflow should be clipped when drawn.
fillColor()
fillColor (Color color)
sets the fill color for shapes and drawings
fillGradient()
fillGradient (Point start, Color startColor, Point end, Color endColor)
sets a linear gradient fill from start point to end point
fillOpacity()
fillOpacity (number float opacity)
sets the opacity for fill operations (0.0 to 1.0)
Set the opacity of filled areas (0.0 = transparent, 1.0 = opaque)
fillRadialGradient()
fillRadialGradient (Point center, Color centerColor, number float radius, Color endColor)
Create a radial gradient fill from center point to outer radius.
fitType()
fitType (int fit)
Sets how an image should be fitted into a target rectangle.
font()
font (Font font)
Sets the font to use for drawing text.
References font().
Referenced by font().
frame()
frame (int frame)
Sets which frame of an ImageStrip to draw.
References frame().
Referenced by frame().
getAmbientLight()
Color getAmbientLight ()
getBlendMode()
int getBlendMode ()
returns the current blend mode
getClipOverflow()
boolean getClipOverflow ()
Gets whether image overflow should be clipped when drawn.
getFillColor()
Color getFillColor ()
returns the current fill color
getFillOpacity()
number float getFillOpacity ()
returns the current fill opacity
getFitType()
int getFitType ()
Gets how an image should be fitted into a target rectangle.
getFont()
Font getFont ()
Gets the font to use for drawing text.
getFrame()
int getFrame ()
Gets which frame of an ImageStrip to draw.
getGradientEnd()
Point getGradientEnd ()
returns the gradient end point
getGradientEndColor()
Color getGradientEndColor ()
returns the gradient end color
getGradientStart()
Point getGradientStart ()
returns the gradient start point
getGradientStartColor()
Color getGradientStartColor ()
returns the gradient start color
getGradientType()
int getGradientType ()
returns the current gradient type
getLightOffset()
Offset getLightOffset ()
Gets the light source offset in spherical coordinates (radians) for sphere lighting.
getLineColor()
Color getLineColor ()
returns the current line color
getLineOpacity()
number float getLineOpacity ()
Get the current line opacity value.
getLineStyle()
uint getLineStyle ()
returns the current line style
getLineThickness()
number float getLineThickness ()
returns the current line thickness
getPolarOffset()
Offset getPolarOffset ()
Gets the polar offset for rotating a textured sphere.
getRadialGradientCenter()
Point getRadialGradientCenter ()
returns the radial gradient center point
getRadialGradientCenterColor()
Color getRadialGradientCenterColor ()
returns the radial gradient center color
getRadialGradientEndColor()
Color getRadialGradientEndColor ()
returns the radial gradient end color
getRadialGradientRadius()
number float getRadialGradientRadius ()
returns the radial gradient radius
getRoundedCornerRadius()
number float getRoundedCornerRadius ()
returns the rounded corner radius
getSphereRotation()
number float getSphereRotation ()
Gets the rotation angle in radians for a textured sphere.
getSubsection()
Rect getSubsection ()
Gets the subsection of an image to draw.
getTextSize()
number float getTextSize ()
Gets the text size in points for drawing text.
getTextStyle()
int getTextStyle ()
Gets text style flags (bold, italic, underline, alignment)
getTexture()
Image getTexture ()
Gets the texture image to use for drawing a sphere.
getTransform()
array number getTransform ()
returns the current transformation matrix
lightOffset()
lightOffset (Offset offset)
Sets light source with spherical coordinates in radians.
The lightOffset is an Offset with two values representing spherical coordinates in radians: offset.x (ρ/rho): Horizontal angle (azimuth) - rotation around the vertical axis offset.y (θ/theta): Vertical angle (elevation/polar angle) - angle from the horizontal plane
Key Points Offset(0, 0): Light directly in front at horizon level Offset(π/2, 0): Light from the right side at horizon level Offset(0, π/2): Light from directly above Offset(π, 0): Light from behind at horizon level The values are relative to the sphere's center, with the light positioned at a distance proportional to the sphere's radius.
lineColor()
lineColor (Color color)
sets the line color for strokes and outlines
lineOpacity()
lineOpacity (number float opacity)
sets the opacity for line strokes (0.0 to 1.0)
lineStyle()
lineStyle (int lineStyle)
sets the style of line strokes (solid, dashed, etc.)
References lineStyle().
Referenced by lineStyle().
lineThickness()
lineThickness (number float thickness)
sets the thickness of line strokes in pixels
polarOffset()
polarOffset (Offset offset)
Sets the polar offset for rotating a textured sphere.
rotation()
rotation (number float radians, Point center = Point(0,0))
sets the rotation angle and center point for transformations
Referenced by sphereRotation().
roundedCorners()
roundedCorners (number float radius)
sets the radius for rounded corners
scale()
scale (number float xFactor, number float yFactor = xFactor)
sets the scaling factors for x and y axes
skew()
skew (number float xSkew, number float ySkew)
sets the skew transformation for x and y axes
sphereRotation()
sphereRotation (number float rotation)
Sets the rotation angle in radians for a textured sphere.
References rotation().
subsection()
subsection (Rect section)
Sets a subsection of an image to draw.
textSize()
textSize (number float size)
Sets the text size in points for drawing text.
textStyle()
textStyle (int style)
Sets text style flags (bold, italic, underline, alignment)
texture()
texture (Image texture)
Sets the texture image to use for drawing a sphere.
References texture().
Referenced by texture().
transform()
transform (array number matrix)
sets the transformation matrix directly
translation()
translation (Offset offset)
sets the translation offset for transformations
User Comments