Pixel Dust Game Engine: Offset Class Reference
Offset Class Reference
Graphics | Animation
offset within a 2D coordinate system
Public Member Functions
Offset ()
Offset (number x, number y)
Offset (number[] xy)
Offset (object xy)
Offset add (Offset offset)
add an offset to this one
Offset assign (Offset offset)
set this offset equal to the given offset
Offset div (Offset offset)
divide this offset by the given one
Offset dividedby (Offset offset)
return new offset that is this offset divided by given offset
boolean equals (Offset offset)
return true if this point is equal to the other
Offset minus (Offset offset)
return new offset that is this offset minus given offset
Offset mul (Offset offset)
multiply this offset by the given one
boolean notEquals (Offset offset)
return true if this point is not equal to the other
Offset plus (Offset offset)
return new offset that is this offset plus given offset
Offset sub (Offset offset)
subtract an offset from this one
Offset times (Offset offset)
return new offset that is this offset multiplied by given offset
Vector vector ()
return a new vector from this offset
Public Attributes
number x
number y
Detailed Description
offset within a 2D coordinate system
Offset provides support for dealing with offsets as x, y floating point values in 2 dimensional space. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point(width, height);
Constructor & Destructor Documentation
Offset() [1/4]
Offset ()
Referenced by add(), assign(), div(), dividedby(), equals(), minus(), mul(), notEquals(), Point::offset(), plus(), sub(), and times().
Offset() [2/4]
Offset (number x, number y)
References x, and y.
Offset() [3/4]
Offset (number[] xy)
Offset() [4/4]
Offset (object xy)
Member Function Documentation
add()
Offset add (Offset offset)
add an offset to this one
References Offset().
assign()
Offset assign (Offset offset)
set this offset equal to the given offset
References Offset().
div()
Offset div (Offset offset)
divide this offset by the given one
References Offset().
dividedby()
Offset dividedby (Offset offset)
return new offset that is this offset divided by given offset
References Offset().
equals()
boolean equals (Offset offset)
return true if this point is equal to the other
References Offset().
minus()
Offset minus (Offset offset)
return new offset that is this offset minus given offset
References Offset().
mul()
Offset mul (Offset offset)
multiply this offset by the given one
References Offset().
notEquals()
boolean notEquals (Offset offset)
return true if this point is not equal to the other
References Offset().
plus()
Offset plus (Offset offset)
return new offset that is this offset plus given offset
References Offset().
sub()
Offset sub (Offset offset)
subtract an offset from this one
References Offset().
times()
Offset times (Offset offset)
return new offset that is this offset multiplied by given offset
References Offset().
vector()
Vector vector ()
return a new vector from this offset
Referenced by Vector::dotProduct().
Member Data Documentation
x
number x
Referenced by Offset().
y
number y
Referenced by Offset().
User Comments