Pixel Dust Game Engine: Polygon Class Reference
Polygon Class Reference
Geometric shape defined by a collection of points with support for transformations and boolean operations.
Public Member Functions
addPoint (Point point)
adds a point to the end of the polygon
addSpline (Spline spline)
adds a spline curve to the polygon
center (Point point)
centers the polygon at the specified point
Point centerPoint ()
returns the center point of the polygon
clearPoints ()
removes all points from the polygon
boolean contains (Point point)
returns true if the specified point is inside the enclosed area of the Polygon
boolean empty ()
returns true if the polygon has no points
boolean equals (Polygon other)
returns true if this polygon equals another polygon
Rect getBounds ()
returns the bounding rectangle of the polygon
Point getPoint (uint index)
gets the point at the specified index
uint getPointCount ()
returns the number of points in the polygon
horzScale (number factor)
scales the polygon horizontally by the specified factor
insertPoint (uint index, Point point)
inserts a point at the specified index
Polygon intersection (Polygon other)
returns the intersection of this polygon with another polygon
Polygon move (Offset offset)
moves the polygon by the specified offset vector
Polygon moveDown (number delta)
moves the polygon down by the specified amount
moveLeft (number delta)
moves the polygon left by the specified amount
Polygon moveRight (number delta)
moves the polygon right by the specified amount
moveTo (number x, number y)
moves the polygon to the specified coordinates
Polygon moveUp (number delta)
moves the polygon up by the specified amount
moveXTo (number x)
moves the polygon to the specified x coordinate
moveYTo (number y)
moves the polygon to the specified y coordinate
removePoint (uint index)
removes the point at the specified index
rotate (number radians)
rotates the polygon by the specified angle in radians
rotateAround (number radians, Point centerPoint)
rotates the polygon around the specified center point
scale (number factor)
scales the polygon by the specified factor
scaleAround (number factor, Point centerPoint)
scales the polygon around the specified center point
setPoint (uint index, Point point)
sets the point at the specified index
Polygon unionWith (Polygon other)
returns the union of this polygon with another polygon
vertScale (number factor)
scales the polygon vertically by the specified factor
Detailed Description
Geometric shape defined by a collection of points with support for transformations and boolean operations.
Member Function Documentation
addPoint()
addPoint (Point point)
adds a point to the end of the polygon
addSpline()
addSpline (Spline spline)
adds a spline curve to the polygon
center()
center (Point point)
centers the polygon at the specified point
centerPoint()
Point centerPoint ()
returns the center point of the polygon
Referenced by rotateAround(), and scaleAround().
clearPoints()
clearPoints ()
removes all points from the polygon
contains()
boolean contains (Point point)
returns true if the specified point is inside the enclosed area of the Polygon
empty()
boolean empty ()
returns true if the polygon has no points
equals()
boolean equals (Polygon other)
returns true if this polygon equals another polygon
getBounds()
Rect getBounds ()
returns the bounding rectangle of the polygon
getPoint()
Point getPoint (uint index)
gets the point at the specified index
getPointCount()
uint getPointCount ()
returns the number of points in the polygon
horzScale()
horzScale (number factor)
scales the polygon horizontally by the specified factor
insertPoint()
insertPoint (uint index, Point point)
inserts a point at the specified index
intersection()
Polygon intersection (Polygon other)
returns the intersection of this polygon with another polygon
move()
Polygon move (Offset offset)
moves the polygon by the specified offset vector
moveDown()
Polygon moveDown (number delta)
moves the polygon down by the specified amount
moveLeft()
moveLeft (number delta)
moves the polygon left by the specified amount
moveRight()
Polygon moveRight (number delta)
moves the polygon right by the specified amount
moveTo()
moveTo (number x, number y)
moves the polygon to the specified coordinates
moveUp()
Polygon moveUp (number delta)
moves the polygon up by the specified amount
moveXTo()
moveXTo (number x)
moves the polygon to the specified x coordinate
moveYTo()
moveYTo (number y)
moves the polygon to the specified y coordinate
removePoint()
removePoint (uint index)
removes the point at the specified index
rotate()
rotate (number radians)
rotates the polygon by the specified angle in radians
rotateAround()
rotateAround (number radians, Point centerPoint)
rotates the polygon around the specified center point
References centerPoint().
scale()
scale (number factor)
scales the polygon by the specified factor
scaleAround()
scaleAround (number factor, Point centerPoint)
scales the polygon around the specified center point
References centerPoint().
setPoint()
setPoint (uint index, Point point)
sets the point at the specified index
unionWith()
Polygon unionWith (Polygon other)
returns the union of this polygon with another polygon
vertScale()
vertScale (number factor)
scales the polygon vertically by the specified factor
User Comments