Pixel Dust Game Engine: Point Class Reference
Point Class Reference
Graphics | Animation
point for 2D coordinate system
Public Member Functions
Point ()
create with x = 0, y = 0
Point (number x, number y)
create and set x & y values
Point (number[] xy)
create and set x & y values
Point (object xy)
create and set x & y values
number distance (Point point)
get distance from another point
Offset offset (Point point)
get the offset of this point from another point
Public Member Functions inherited from Offset
Offset ()
Offset (number x, number y)
Offset (number[] xy)
Offset (object xy)
Offset add (Offset offset)
add an offset to this one
Offset assign (Offset offset)
set this offset equal to the given offset
Offset div (Offset offset)
divide this offset by the given one
Offset dividedby (Offset offset)
return new offset that is this offset divided by given offset
boolean equals (Offset offset)
return true if this point is equal to the other
Offset minus (Offset offset)
return new offset that is this offset minus given offset
Offset mul (Offset offset)
multiply this offset by the given one
boolean notEquals (Offset offset)
return true if this point is not equal to the other
Offset plus (Offset offset)
return new offset that is this offset plus given offset
Offset sub (Offset offset)
subtract an offset from this one
Offset times (Offset offset)
return new offset that is this offset multiplied by given offset
Vector vector ()
return a new vector from this offset
Public Attributes
number x
number y
Public Attributes inherited from Offset
number x
number y
Detailed Description
point for 2D coordinate system
Point provides support for dealing with points as x, y floating point values in 2 dimensional space. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point(width, height);
Coordinates Diagram
Constructor & Destructor Documentation
Point() [1/4]
Point ()
create with x = 0, y = 0
Referenced by distance(), and offset().
Point() [2/4]
Point (number x, number y)
create and set x & y values
Parameters
x the horizontal coordinate
y the vertical coordinate
References x, and y.
Point() [3/4]
Point (number[] xy)
create and set x & y values
Parameters
xy an array of numbers with x as element 0 and y as element 1
Point() [4/4]
Point (object xy)
create and set x & y values
Parameters
xy an object with x and y members, for example: {x: 1, y: 4}
Member Function Documentation
distance()
number distance (Point point)
get distance from another point
Parameters
point the other Point
References Point().
offset()
Offset offset (Point point)
get the offset of this point from another point
References Offset::Offset(), and Point().
Member Data Documentation
x
number x
Referenced by Point().
y
number y
Referenced by Point().
User Comments