Pixel Dust Game Engine: Managers
Managers
The main points of interface to the Pixel Dust Game Framework.
Classes
class ConfigManager
used for loading and saving application configuration info
class EventManager
Distributes events to event handlers.
class FileManager
extras beyond what Node.js FileSystem provides
class GraphicsManager
Used to create and track ports (GUI Only)
class LogManager
used for doing logging with variable debug levels
class ResourceManager
used for loading resources
class SoundManager
used for application wide sound settings and options (GUI Only)
class TimerManager
manages timers that can fire at a particular time, or repeatedly at an interval
Functions
cfg
the singleton instance of the ConfigManager
evt
the singleton instance of the EventManager
fs
the singleton instance of the FileManager
gfx
the singleton instance of the GraphicsManager
res
the singleton instance of the ResourceManager
snd
the singleton instance of the SoundManager
tm
the singleton instance of the TimerManager
Detailed Description
The main points of interface to the Pixel Dust Game Framework.
Function Documentation
cfg()
cfg related
the singleton instance of the ConfigManager
var username = pdg.cfg.getConfigString('username');
References cfg().
Referenced by cfg().
evt()
evt related
the singleton instance of the EventManager
var aIsPressed = pdg.evt.isKeyDown('a');
References evt().
Referenced by evt().
fs()
fs related
the singleton instance of the FileManager
var fileList = pdg.fs.findFiles('examples/*.scml');
References fs().
Referenced by fs().
gfx()
gfx related
the singleton instance of the GraphicsManager
var r = new Rect(1024, 768);
var port = pdg.gfx.createWindowPort(r, "PDG Test Window");
References gfx().
Referenced by gfx().
res()
res related
the singleton instance of the ResourceManager
pdg.res.openResourceFile('./data');
console.log(pdg.res.getResourcePaths());
References res().
Referenced by res().
snd()
snd related
the singleton instance of the SoundManager
pdg.snd.setVolume(0.5);
References snd().
Referenced by snd().
tm()
tm related
the singleton instance of the TimerManager
pdg.tm.pause();
References tm().
Referenced by tm().
User Comments