.TH "Animation" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animation \- Animation
.PP
 \- Things related to animation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimated\fP"
.br
.RI "something that can be automatically moved, spun or resized over time\&. "
.ti -1c
.RI "class \fBIAnimationHelper\fP"
.br
.RI "helper for add-on or complex motion during animation "
.ti -1c
.RI "class \fBOffset\fP"
.br
.RI "offset within a 2D coordinate system "
.ti -1c
.RI "class \fBPoint\fP"
.br
.RI "point for 2D coordinate system "
.ti -1c
.RI "class \fBQuad\fP"
.br
.RI "4 point polygon in 2D system "
.ti -1c
.RI "class \fBRect\fP"
.br
.RI "Rectangle for 2D coordinate system\&. "
.ti -1c
.RI "class \fBRotatedRect\fP"
.br
.RI "rectangle with rotation for 2D coordinate system\&. "
.ti -1c
.RI "class \fBSprite\fP"
.br
.RI "animated, moving image that is automatically moved, animated, and drawn "
.ti -1c
.RI "struct \fBSpriteAnimateEvent\fP"
.br
.RI "a Sprite did some animation (\fIOptional\fP) "
.ti -1c
.RI "class \fBSpriteLayer\fP"
.br
.RI "creates and tracks collections of sprites "
.ti -1c
.RI "class \fBVector\fP"
.br
.RI "vector (magnitude and direction) within a 2D coordinate system\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBaction_AnimationBlendComplete\fP = 15"
.br
.RI "eventType_SpriteAnimate action: a Spriter animation blend completed\&. "
.ti -1c
.RI "const \fBaction_AnimationComplete\fP = 47"
.br
.RI "eventType_SpriteLayer action: all animations for every \fBSpriteLayer\fP have completed "
.ti -1c
.RI "const \fBaction_AnimationEnd\fP = 9"
.br
.RI "eventType_SpriteAnimate action: a sprite animation has completed "
.ti -1c
.RI "const \fBaction_AnimationLoop\fP = 8"
.br
.RI "eventType_SpriteAnimate action: a sprite animation has completed and is looping back to the start "
.ti -1c
.RI "const \fBaction_AnimationStart\fP = 44"
.br
.RI "eventType_SpriteLayer action: starting animations for all SpriteLayers "
.ti -1c
.RI "const \fBaction_ExitLayer\fP = 4"
.br
.RI "eventType_SpriteAnimate action: a sprite has moved outside the layer boundaries\&. "
.ti -1c
.RI "const \fBaction_FadeComplete\fP = 10"
.br
.RI "eventType_SpriteAnimate action: a sprite fadeTo() has completed "
.ti -1c
.RI "const \fBaction_FadeInComplete\fP = 11"
.br
.RI "eventType_SpriteAnimate action: a sprite fade-in has completed "
.ti -1c
.RI "const \fBaction_FadeOutComplete\fP = 12"
.br
.RI "eventType_SpriteAnimate action: a sprite fade-out has completed "
.ti -1c
.RI "const \fBaction_LayerFadeInComplete\fP = 49"
.br
.RI "eventType_SpriteLayer action: the fade-in of a layer has been completed "
.ti -1c
.RI "const \fBaction_LayerFadeOutComplete\fP = 50"
.br
.RI "eventType_SpriteLayer action: the fade-out of a layer has been completed "
.ti -1c
.RI "const \fBaction_Offscreen\fP = 2"
.br
.RI "eventType_SpriteAnimate action: a sprite has gone completely offscreen (\fIGUI Only\fP) "
.ti -1c
.RI "const \fBaction_Onscreen\fP = 3"
.br
.RI "eventType_SpriteAnimate action: a sprite that was off screen has moved onscreen (\fIGUI Only\fP) "
.ti -1c
.RI "const \fBaction_PostAnimateLayer\fP = 46"
.br
.RI "eventType_SpriteLayer action: all animations for a particular \fBSpriteLayer\fP have completed "
.ti -1c
.RI "const \fBaction_PreAnimateLayer\fP = 45"
.br
.RI "eventType_SpriteLayer action: about to start animations for a particular \fBSpriteLayer\fP "
.ti -1c
.RI "const \fBaction_SpriterTrigger\fP = 14"
.br
.RI "eventType_SpriteAnimate action: a Spriter animation trigger fired "
.ti -1c
.RI "const \fBaction_ZoomComplete\fP = 48"
.br
.RI "eventType_SpriteLayer action: zooming a particular sprite layer is complete "
.in -1c
.SH "Detailed Description"
.PP 
Things related to animation\&. 


.SH "Class Documentation"
.PP 
.SH "class pdg::IAnimationHelper"
.PP 
helper for add-on or complex motion during animation 


.PP
\fBWarning\fP
.RS 4
\fBAPI Stability: 1 - Experimental\fP\&. This API was introduced recently and gotten little or no real use\&. It may change or be removed in future versions\&. It may not be completely implemented and may be missing important pieces of functionality\&. Please try it out and provide feedback\&.
.RE
.PP
Implement this interface to do extra animation stuff for a specific \fBAnimated\fP object then add by calling the object's addAnimationHelper() method\&. You can have multiple Animation Helpers attached to the same object\&. Your helper will then be called every time movement for the object is calculated\&.

.PP
To create a helper:

.PP
.PP
.nf
var myHelper = new pdg\&.IAnimationHelper(function(what, msElapsed) {
                console\&.log("in my animation helper for " + what + " after " + msElapsed + "ms" );
                return true;  // not done, keep helping
});
myAnimatedObj\&.addAnimationHelper(myHelper);
.fi
.PP

.PP
If you need something more complex, you can also use classify to create a new Javascript class that derives from \fBpdg\&.IAnimationHelper\fP, and it will call the animated() method of your class\&. For example:

.PP
.PP
.nf
classify(pdg\&.IAnimationHelper, 'MyAnimationHelperClass', function() {
                def('animate', function(what, msElapsed) {
                                console\&.log("MyAnimationHelper\&.animate(" + what + ", " + msElapsed + "ms)" );
                                return false;  // all done, delete the helper
                });
});
myAnimatedObj\&.addAnimationHelper( new MyAnimationHelperClass() );
.fi
.PP
.SS "Your Custom Function:"
As you can see from the examples above, your Animation Helper function (or animate() method) will be called with two parameters, and return a boolean: 
.PP
\fBParameters\fP
.RS 4
\fIwhat\fP the \fBAnimated\fP object that is being animated 
.br
\fImsElapsed\fP the number of milliseconds that have elapsed since the last time this object's movement was calculated 
.RE
.PP
\fBReturns\fP
.RS 4
\fBtrue\fP if the helper should continue to be called; or \fBfalse\fP if it is done and should be removed from this \fBAnimated\fP object\&. 
.RE
.PP

.SH "struct pdg::SpriteAnimateEvent"
.PP 
a Sprite did some animation (\fIOptional\fP) 

A Sprite will generate one of these events when it completes an animation including fades (opacity animations), and moving on/offscreen or outside of the layer\&.

.PP
For frame based animations -- that is, calls to \fBpdg\&.Sprite\&.startFrameAnimation()\fP -- if it reaches the last frame and is not set to loop, action will be \fBpdg\&.action_AnimationEnd\fP\&. For looping animations \fBpdg\&.action_AnimationLoop\fP will be received each time the animation completes and starts over with the first frame\&.

.PP
When a Spriter animation blend -- started by \fBpdg\&.Sprite\&.blendToAnimation()\fP -- completes, action will be \fBpdg\&.action_AnimationBlendComplete\fP

.PP
For Spriter triggers embedded in a Spriter animation, action will be \fBpdg\&.action_SpriterTrigger\fP

.PP
For fades, one of three action types are possible: \fBpdg\&.action_FadeComplete\fP for calls to \fBpdg\&.Sprite\&.fadeTo()\fP, \fBpdg\&.action_FadeInComplete\fP for calls to \fBpdg\&.Sprite\&.fadeIn()\fP, and \fBpdg\&.action_FadeOutComplete\fP for calls to \fBpdg\&.Sprite\&.fadeOut()\fP\&.

.PP
When a Sprite has setWantsOffscreenEvents(true), \fBpdg\&.action_Offscreen\fP and \fBpdg\&.action_Onscreen\fP events will be generated for that sprite whenever it enters or departs the visible area of the port the layer is being rendered into\&.

.PP
When a Sprite has setWantsCollideWallEvents(true), \fBpdg\&.action_ExitLayer\fP events will be generated for that sprite whenever it moves completely outside the boundaries of the layer\&. (It will also get a \fBSpriteCollideEvent\fP when it hits the boundary)\&. 
.PP
.nf
{
    emitter: {},       // the emitter that generated this event
    eventType: 17,     // the event type (eventType_SpriteAnimate)
    action: 0,         // what happened (action_AnimationEnd/Loop or action_Fade/In/OutComplete)
    actingSprite: {},  // the Sprite that was animating
    inLayer: {}        // the SpriteLayer that contains the Sprite
}

.fi
.PP

.PP
\fBNote\fP
.RS 4
At this time other kinds of animations such as calls to \fBpdg::Sprite\&.startAnimation()\fP do not generate any events\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBpdg\&.eventType_SpriteAnimate\fP 

.PP
\fBpdg\&.Sprite\&.startFrameAnimation()\fP 

.PP
\fBpdg\&.Sprite\&.blendToAnimation()\fP 

.PP
\fBpdg\&.Sprite\&.startAnimation()\fP 

.PP
\fBpdg\&.Sprite\&.fadeTo()\fP 

.PP
\fBpdg\&.Sprite\&.fadeIn()\fP 

.PP
\fBpdg\&.Sprite\&.fadeOut()\fP 

.PP
\fBpdg\&.Sprite\&.setWantsOffscreenEvents()\fP 

.PP
\fBpdg\&.Sprite\&.setWantsCollideWallEvents()\fP 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "const action_AnimationBlendComplete = 15"

.PP
eventType_SpriteAnimate action: a Spriter animation blend completed\&. Emitted after \fBpdg\&.Sprite\&.blendToAnimation\fP is called and the blend has completed\&.

.PP
\fBSee also\fP
.RS 4
\fBpdg\&.Sprite\&.blendToAnimation\fP 

.PP
\fBpdg\&.eventType_SpriteAnimate\fP 
.RE
.PP

.SS "const action_AnimationComplete = 47"

.PP
eventType_SpriteLayer action: all animations for every \fBSpriteLayer\fP have completed Emitted once per animation step, after all animation has completed\&.

.PP
\fBSee also\fP
.RS 4
\fBaction_AnimationComplete\fP 

.PP
\fBeventType_SpriteLayer\fP 
.RE
.PP

.SS "const action_AnimationEnd = 9"

.PP
eventType_SpriteAnimate action: a sprite animation has completed 
.PP
\fBSee also\fP
.RS 4
\fBSprite\&.setWantsAnimEndEvents()\fP 

.PP
\fBSprite\&.startFrameAnimation()\fP 

.PP
\fBaction_AnimationLoop\fP 

.PP
\fBeventType_SpriteAnimate\fP 
.RE
.PP

.SS "const action_AnimationLoop = 8"

.PP
eventType_SpriteAnimate action: a sprite animation has completed and is looping back to the start 
.PP
\fBSee also\fP
.RS 4
\fBSprite\&.setWantsAnimLoopEvents()\fP 

.PP
\fBSprite\&.startFrameAnimation()\fP 

.PP
\fBaction_AnimationEnd\fP 

.PP
\fBeventType_SpriteAnimate\fP 
.RE
.PP

.SS "const action_AnimationStart = 44"

.PP
eventType_SpriteLayer action: starting animations for all SpriteLayers Emitted once per animation step, before any animation is done\&.

.PP
\fBSee also\fP
.RS 4
\fBaction_AnimationComplete\fP 

.PP
\fBeventType_SpriteLayer\fP 
.RE
.PP

.SS "const action_ExitLayer = 4"

.PP
eventType_SpriteAnimate action: a sprite has moved outside the layer boundaries\&. These events are only generated for sprites that have setWantsCollideWallEvents(true) called for them, and that the \fBSpriteLayer\fP that holds the sprite has had its size explicitly set\&.

.PP
\fBSee also\fP
.RS 4
\fBSprite\&.setWantsCollideWallEvents()\fP 

.PP
\fBSpriteLayer\&.setSize()\fP 

.PP
\fBeventType_SpriteAnimate\fP 

.PP
\fBaction_Offscreen\fP 

.PP
\fBaction_Onscreen\fP 
.RE
.PP

.SS "const action_FadeComplete = 10"

.PP
eventType_SpriteAnimate action: a sprite fadeTo() has completed 
.PP
\fBSee also\fP
.RS 4
\fBSprite\&.fadeTo()\fP 

.PP
\fBaction_FadeInComplete\fP 

.PP
\fBaction_FadeOutComplete\fP 

.PP
\fBeventType_SpriteAnimate\fP 
.RE
.PP

.SS "const action_FadeInComplete = 11"

.PP
eventType_SpriteAnimate action: a sprite fade-in has completed 
.PP
\fBSee also\fP
.RS 4
\fBSprite\&.fadeIn()\fP 

.PP
\fBaction_FadeComplete\fP 

.PP
\fBaction_FadeOutComplete\fP 

.PP
\fBeventType_SpriteAnimate\fP 

.PP
\fBSpriteAnimateEvent\fP 
.RE
.PP

.SS "const action_FadeOutComplete = 12"

.PP
eventType_SpriteAnimate action: a sprite fade-out has completed 
.PP
\fBSee also\fP
.RS 4
\fBSprite\&.fadeOut()\fP 

.PP
\fBaction_FadeComplete\fP 

.PP
\fBaction_FadeInComplete\fP 

.PP
\fBeventType_SpriteAnimate\fP 

.PP
\fBSpriteAnimateEvent\fP 
.RE
.PP

.SS "const action_LayerFadeInComplete = 49"

.PP
eventType_SpriteLayer action: the fade-in of a layer has been completed 
.PP
\fBSee also\fP
.RS 4
\fBSpriteLayer\&.fadeIn()\fP 

.PP
\fBaction_LayerFadeOutComplete\fP 

.PP
\fBeventType_SpriteLayer\fP 
.RE
.PP

.SS "const action_LayerFadeOutComplete = 50"

.PP
eventType_SpriteLayer action: the fade-out of a layer has been completed 
.PP
\fBSee also\fP
.RS 4
\fBSpriteLayer\&.fadeOut()\fP 

.PP
\fBaction_LayerFadeInComplete\fP 

.PP
\fBeventType_SpriteLayer\fP 
.RE
.PP

.SS "const action_Offscreen = 2"

.PP
eventType_SpriteAnimate action: a sprite has gone completely offscreen (\fIGUI Only\fP) This event is only generated for sprites that have setWantsOffscreenEvents(true) called\&.

.PP
\fBSee also\fP
.RS 4
\fBSprite\&.setWantsOffscreenEvents()\fP 

.PP
\fBeventType_SpriteAnimate\fP 

.PP
\fBaction_Onscreen\fP 
.RE
.PP

.SS "const action_Onscreen = 3"

.PP
eventType_SpriteAnimate action: a sprite that was off screen has moved onscreen (\fIGUI Only\fP) These events are only generated for sprites that have setWantsOffscreenEvents(true) called for them\&.

.PP
\fBSee also\fP
.RS 4
\fBSprite\&.setWantsOffscreenEvents()\fP 

.PP
\fBeventType_SpriteAnimate\fP 

.PP
\fBaction_Offscreen\fP 
.RE
.PP

.SS "const action_PostAnimateLayer = 46"

.PP
eventType_SpriteLayer action: all animations for a particular \fBSpriteLayer\fP have completed Emitted once per layer per animation step, after all animation for the layer is complete\&.

.PP
\fBSee also\fP
.RS 4
\fBaction_AnimationComplete\fP 

.PP
\fBaction_PreAnimateLayer\fP 

.PP
\fBeventType_SpriteLayer\fP 
.RE
.PP

.SS "const action_PreAnimateLayer = 45"

.PP
eventType_SpriteLayer action: about to start animations for a particular \fBSpriteLayer\fP Emitted once per layer per animation step, before any animation for that layer is performed\&.

.PP
\fBSee also\fP
.RS 4
\fBaction_AnimationStart\fP 

.PP
\fBaction_PostAnimateLayer\fP 

.PP
\fBeventType_SpriteLayer\fP 
.RE
.PP

.SS "const action_SpriterTrigger = 14"

.PP
eventType_SpriteAnimate action: a Spriter animation trigger fired Emitted whenever a Spriter animation is playing and it encounter a trigger\&.

.PP
\fBSee also\fP
.RS 4
\fBpdg\&.Sprite\&.startAnimation()\fP 

.PP
pdg\&.eventType_SpriteAnimation 
.RE
.PP

.SS "const action_ZoomComplete = 48"

.PP
eventType_SpriteLayer action: zooming a particular sprite layer is complete 
.PP
\fBSee also\fP
.RS 4
\fBSpriteLayer\&.zoom()\fP 

.PP
\fBeventType_SpriteLayer\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
