.TH "pdg" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pdg
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnimated\fP"
.br
.RI "something that can be automatically moved, spun or resized over time\&. "
.ti -1c
.RI "class \fBAttributes\fP"
.br
.RI "Container for styling and transformation attributes used in drawing operations\&. "
.ti -1c
.RI "class \fBColor\fP"
.br
.RI "color in RGB space, with optional alpha "
.ti -1c
.RI "class \fBConfigManager\fP"
.br
.RI "used for loading and saving application configuration info "
.ti -1c
.RI "class \fBCpArbiter\fP"
.br
.RI "arbitrates collisions between sprites using Chipmunk Physics (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "class \fBCpConstraint\fP"
.br
.RI "describes how two sprites are connected to one another (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "class \fBCpSpace\fP"
.br
.RI "container for simulating objects (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "class \fBDeserializer\fP"
.br
.RI "deserialize data from a serialized data stream "
.ti -1c
.RI "class \fBDrawing\fP"
.br
.RI "Container for drawing elements (lines, shapes, images) that can be rendered to a \fBPort\fP\&. "
.ti -1c
.RI "class \fBElementRef\fP"
.br
.RI "Reference to a drawing element that allows modification of its properties and control points\&. "
.ti -1c
.RI "class \fBEventEmitter\fP"
.br
.RI "Distributes events to event handlers\&. "
.ti -1c
.RI "class \fBEventManager\fP"
.br
.RI "Distributes events to event handlers\&. "
.ti -1c
.RI "class \fBFileManager\fP"
.br
.RI "extras beyond what Node\&.js FileSystem provides "
.ti -1c
.RI "class \fBFont\fP"
.br
.RI "font for text drawing and measuring (\fIGUI Only\fP) "
.ti -1c
.RI "class \fBGraphicsManager\fP"
.br
.RI "Used to create and track ports (\fIGUI Only\fP) "
.ti -1c
.RI "class \fBIAnimationHelper\fP"
.br
.RI "helper for add-on or complex motion during animation "
.ti -1c
.RI "class \fBIEventHandler\fP"
.br
.RI "Interface for any class which handles events\&. "
.ti -1c
.RI "class \fBImage\fP"
.br
.RI "A bitmap image that can be blitted onto the screen\&. "
.ti -1c
.RI "class \fBImageStrip\fP"
.br
.RI "bitmap image containing a number of frames that can be blitted onto the screen "
.ti -1c
.RI "class \fBISerializable\fP"
.br
.RI "interface for an object which can be serialized "
.ti -1c
.RI "class \fBISpriteCollideHelper\fP"
.br
.RI "helper for deciding whether 2 sprites should collide or not "
.ti -1c
.RI "class \fBISpriteDrawHelper\fP"
.br
.RI "helper for drawing sprite overlays and add-on effects "
.ti -1c
.RI "class \fBLogManager\fP"
.br
.RI "used for doing logging with variable debug levels "
.ti -1c
.RI "class \fBMemBlock\fP"
.br
.RI "holds arbitrary blocks of memory "
.ti -1c
.RI "class \fBNetClient\fP"
.br
.RI "a network endpoint that can initiate a connection "
.ti -1c
.RI "class \fBNetConnection\fP"
.br
.RI "sends data between two network endpoints "
.ti -1c
.RI "class \fBNetServer\fP"
.br
.RI "a network endpoint that can accept incoming connections "
.ti -1c
.RI "class \fBOffset\fP"
.br
.RI "offset within a 2D coordinate system "
.ti -1c
.RI "class \fBPoint\fP"
.br
.RI "point for 2D coordinate system "
.ti -1c
.RI "class \fBPolygon\fP"
.br
.RI "Geometric shape defined by a collection of points with support for transformations and boolean operations\&. "
.ti -1c
.RI "class \fBPort\fP"
.br
.RI "area in which drawing is done, a viewport (\fIGUI Only\fP) "
.ti -1c
.RI "class \fBQuad\fP"
.br
.RI "4 point polygon in 2D system "
.ti -1c
.RI "class \fBRect\fP"
.br
.RI "Rectangle for 2D coordinate system\&. "
.ti -1c
.RI "class \fBResourceManager\fP"
.br
.RI "used for loading resources "
.ti -1c
.RI "class \fBRotatedRect\fP"
.br
.RI "rectangle with rotation for 2D coordinate system\&. "
.ti -1c
.RI "class \fBSerializer\fP"
.br
.RI "serialize data into memory "
.ti -1c
.RI "class \fBSound\fP"
.br
.RI "handles both short sounds and music (\fIGUI Only\fP) "
.ti -1c
.RI "class \fBSoundManager\fP"
.br
.RI "used for application wide sound settings and options (\fIGUI Only\fP) "
.ti -1c
.RI "class \fBSpline\fP"
.br
.RI "Curved path defined by control points, supporting multiple spline types including cubic Bezier curves\&. "
.ti -1c
.RI "class \fBSprite\fP"
.br
.RI "animated, moving image that is automatically moved, animated, and drawn "
.ti -1c
.RI "class \fBSpriteLayer\fP"
.br
.RI "creates and tracks collections of sprites "
.ti -1c
.RI "class \fBTileLayer\fP"
.br
.RI "efficiently handles large tile datasets, useful for backgrounds, terrains, etc\&.\&.\&. "
.ti -1c
.RI "class \fBTimerManager\fP"
.br
.RI "manages timers that can fire at a particular time, or repeatedly at an interval "
.ti -1c
.RI "class \fBVector\fP"
.br
.RI "vector (magnitude and direction) within a 2D coordinate system\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcaptureConsole\fP ()"
.br
.ti -1c
.RI "\fBcfg\fP"
.br
.RI "the singleton instance of the \fBConfigManager\fP "
.ti -1c
.RI "\fBcleanupLayer\fP (\fBSpriteLayer\fP layer)"
.br
.ti -1c
.RI "\fBcleanupLayer\fP"
.br
.RI "free all the memory used by a \fBpdg\&.SpriteLayer\fP or \fBpdg\&.TileLayer\fP "
.ti -1c
.RI "\fBDrawing\fP \fBcreateDrawing\fP ()"
.br
.ti -1c
.RI "\fBISerializable\fP \fBcreateSerializableObject\fP (object obj, uint classTag)"
.br
.ti -1c
.RI "\fBSpriteLayer\fP \fBcreateSpriteLayer\fP (\fBPort\fP port=null)"
.br
.RI "create a new \fBSpriteLayer\fP attached to a particular port "
.ti -1c
.RI "\fBcreateSpriteLayer\fP (\fBPort\fP port=nullptr)"
.br
.RI "create a new \fBSpriteLayer\fP attached to a particular port "
.ti -1c
.RI "\fBSpriteLayer\fP \fBcreateSpriteLayerFromSpriterFile\fP (string layerSpriterFilename, boolean addSprites=true, \fBPort\fP port=null)"
.br
.RI "create a new \fBSpriteLayer\fP from an Spriter SCML file "
.ti -1c
.RI "\fBcreateSpriteLayerFromSpriterFile\fP (string layerSpriterFilename, boolean addSprites=true, \fBPort\fP port=null)"
.br
.RI "create a new \fBSpriteLayer\fP from an Spriter SCML file "
.ti -1c
.RI "\fBTileLayer\fP \fBcreateTileLayer\fP (\fBPort\fP port=null)"
.br
.RI "create a new \fBTileLayer\fP attached to a particular port "
.ti -1c
.RI "\fBcreateTileLayer\fP (\fBPort\fP port=nullptr)"
.br
.RI "create a new \fBTileLayer\fP attached to a particular port "
.ti -1c
.RI "\fBdebug\fP (string msg)"
.br
.ti -1c
.RI "\fBerror\fP (string msg)"
.br
.ti -1c
.RI "\fBevt\fP"
.br
.RI "the singleton instance of the \fBEventManager\fP "
.ti -1c
.RI "\fBfatal\fP (string msg)"
.br
.ti -1c
.RI "\fBfs\fP"
.br
.RI "the singleton instance of the \fBFileManager\fP "
.ti -1c
.RI "\fBgetConfigManager\fP"
.br
.RI "get the singleton instance of the \fBConfigManager\fP used by the pdg framework "
.ti -1c
.RI "\fBConfigManager\fP \fBgetConfigManager\fP ()"
.br
.RI "get the singleton instance of the \fBConfigManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgetEventManager\fP"
.br
.RI "get the singleton instance of the \fBEventManager\fP used by the pdg framework "
.ti -1c
.RI "\fBEventManager\fP \fBgetEventManager\fP ()"
.br
.RI "get the singleton instance of the \fBEventManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgetFileManager\fP"
.br
.RI "get the singleton instance of the \fBFileManager\fP used by the pdg framework "
.ti -1c
.RI "\fBFileManager\fP \fBgetFileManager\fP ()"
.br
.RI "get the singleton instance of the \fBFileManager\fP used by the pdg framework "
.ti -1c
.RI "\fBGraphicsManager\fP \fBgetGraphicsManager\fP ()"
.br
.RI "get the singleton instance of the \fBGraphicsManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgetGraphicsManager\fP"
.br
.RI "get the singleton instance of the \fBGraphicsManager\fP used by the pdg framework "
.ti -1c
.RI "\fBLogManager\fP \fBgetLogManager\fP ()"
.br
.RI "get the singleton instance of the \fBLogManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgetLogManager\fP"
.br
.RI "get the singleton instance of the \fBLogManager\fP used by the pdg framework "
.ti -1c
.RI "\fBResourceManager\fP \fBgetResourceManager\fP ()"
.br
.RI "get the singleton instance of the \fBResourceManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgetResourceManager\fP"
.br
.RI "get the singleton instance of the \fBResourceManager\fP used by the pdg framework "
.ti -1c
.RI "\fBSoundManager\fP \fBgetSoundManager\fP ()"
.br
.RI "get the singleton instance of the \fBSoundManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgetSoundManager\fP"
.br
.RI "get the singleton instance of the \fBSoundManager\fP used by the pdg framework "
.ti -1c
.RI "\fBTimerManager\fP \fBgetTimerManager\fP ()"
.br
.RI "get the singleton instance of the \fBTimerManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgetTimerManager\fP"
.br
.RI "get the singleton instance of the \fBTimerManager\fP used by the pdg framework "
.ti -1c
.RI "\fBgfx\fP"
.br
.RI "the singleton instance of the \fBGraphicsManager\fP "
.ti -1c
.RI "\fBidle\fP ()"
.br
.ti -1c
.RI "\fBinfo\fP (string msg)"
.br
.ti -1c
.RI "\fBlog\fP (string msg)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBon\fP (int eventType, function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonKeyDown\fP (function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonKeyPress\fP (function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonKeyUp\fP (function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseDown\fP (function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseMove\fP (function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseUp\fP (function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonShutdown\fP (function func)"
.br
.ti -1c
.RI "\fBIEventHandler\fP \fBonTimer\fP (function func)"
.br
.ti -1c
.RI "\fBopenCommandPort\fP (int port=5757)"
.br
.ti -1c
.RI "\fBopenConsole\fP ()"
.br
.ti -1c
.RI "\fBopenDebugger\fP ()"
.br
.ti -1c
.RI "\fBquit\fP ()"
.br
.ti -1c
.RI "number \fBrand\fP ()"
.br
.ti -1c
.RI "\fBregisterEasingFunction\fP (function easingFunc)"
.br
.ti -1c
.RI "\fBregisterSerializableClass\fP"
.br
.RI "register a particular class as implementing \fBISerializable\fP interface "
.ti -1c
.RI "\fBregisterSerializableClass\fP (function klass)"
.br
.ti -1c
.RI "\fBres\fP"
.br
.RI "the singleton instance of the \fBResourceManager\fP "
.ti -1c
.RI "\fBrun\fP ()"
.br
.ti -1c
.RI "\fBsetSerializationDebugMode\fP (bool debugMode)"
.br
.ti -1c
.RI "\fBsnd\fP"
.br
.RI "the singleton instance of the \fBSoundManager\fP "
.ti -1c
.RI "\fBsrand\fP (uint seed)"
.br
.ti -1c
.RI "\fBstartRepl\fP ()"
.br
.ti -1c
.RI "\fBtm\fP"
.br
.RI "the singleton instance of the \fBTimerManager\fP "
.ti -1c
.RI "\fBtrace\fP (string msg)"
.br
.ti -1c
.RI "\fBwarn\fP (string msg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBaction_AnimationBlendComplete\fP = 15"
.br
.RI "eventType_SpriteAnimate action: a Spriter animation blend completed\&. "
.ti -1c
.RI "const \fBaction_AnimationComplete\fP = 47"
.br
.RI "eventType_SpriteLayer action: all animations for every \fBSpriteLayer\fP have completed "
.ti -1c
.RI "const \fBaction_AnimationEnd\fP = 9"
.br
.RI "eventType_SpriteAnimate action: a sprite animation has completed "
.ti -1c
.RI "const \fBaction_AnimationLoop\fP = 8"
.br
.RI "eventType_SpriteAnimate action: a sprite animation has completed and is looping back to the start "
.ti -1c
.RI "const \fBaction_AnimationStart\fP = 44"
.br
.RI "eventType_SpriteLayer action: starting animations for all SpriteLayers "
.ti -1c
.RI "const \fBaction_CollideSprite\fP = 0"
.br
.ti -1c
.RI "const \fBaction_CollideWall\fP = 1"
.br
.RI "eventType_SpriteAnimate action: a sprite has hit the edge of the sprite layer "
.ti -1c
.RI "const \fBaction_DrawPortComplete\fP = 43"
.br
.RI "eventType_SpriteLayer action: all drawing for every \fBSpriteLayer\fP has completed "
.ti -1c
.RI "const \fBaction_ErasePort\fP = 40"
.br
.RI "eventType_SpriteLayer action: about to start drawing each \fBSpriteLayer\fP "
.ti -1c
.RI "const \fBaction_ExitLayer\fP = 4"
.br
.RI "eventType_SpriteAnimate action: a sprite has moved outside the layer boundaries\&. "
.ti -1c
.RI "const \fBaction_FadeComplete\fP = 10"
.br
.RI "eventType_SpriteAnimate action: a sprite fadeTo() has completed "
.ti -1c
.RI "const \fBaction_FadeInComplete\fP = 11"
.br
.RI "eventType_SpriteAnimate action: a sprite fade-in has completed "
.ti -1c
.RI "const \fBaction_FadeOutComplete\fP = 12"
.br
.RI "eventType_SpriteAnimate action: a sprite fade-out has completed "
.ti -1c
.RI "const \fBaction_JointBreak\fP = 13"
.br
.ti -1c
.RI "const \fBaction_LayerFadeInComplete\fP = 49"
.br
.RI "eventType_SpriteLayer action: the fade-in of a layer has been completed "
.ti -1c
.RI "const \fBaction_LayerFadeOutComplete\fP = 50"
.br
.RI "eventType_SpriteLayer action: the fade-out of a layer has been completed "
.ti -1c
.RI "const \fBaction_Offscreen\fP = 2"
.br
.RI "eventType_SpriteAnimate action: a sprite has gone completely offscreen (\fIGUI Only\fP) "
.ti -1c
.RI "const \fBaction_Onscreen\fP = 3"
.br
.RI "eventType_SpriteAnimate action: a sprite that was off screen has moved onscreen (\fIGUI Only\fP) "
.ti -1c
.RI "const \fBaction_PostAnimateLayer\fP = 46"
.br
.RI "eventType_SpriteLayer action: all animations for a particular \fBSpriteLayer\fP have completed "
.ti -1c
.RI "const \fBaction_PostDrawLayer\fP = 42"
.br
.RI "eventType_SpriteLayer action: completed rendering for a particular \fBSpriteLayer\fP "
.ti -1c
.RI "const \fBaction_PreAnimateLayer\fP = 45"
.br
.RI "eventType_SpriteLayer action: about to start animations for a particular \fBSpriteLayer\fP "
.ti -1c
.RI "const \fBaction_PreDrawLayer\fP = 41"
.br
.RI "eventType_SpriteLayer action: about to render a particular \fBSpriteLayer\fP "
.ti -1c
.RI "const \fBaction_SpriterTrigger\fP = 14"
.br
.RI "eventType_SpriteAnimate action: a Spriter animation trigger fired "
.ti -1c
.RI "const \fBaction_ZoomComplete\fP = 48"
.br
.RI "eventType_SpriteLayer action: zooming a particular sprite layer is complete "
.ti -1c
.RI "const \fBall_events\fP = 0"
.br
.RI "a special catch-all for events that weren't handled by specific event handlers "
.ti -1c
.RI "const \fBall_Frames\fP = 0"
.br
.ti -1c
.RI "const \fBanimate_Bidirectional\fP = 2"
.br
.ti -1c
.RI "const \fBanimate_EndToStart\fP = 1"
.br
.ti -1c
.RI "const \fBanimate_Looping\fP = 4"
.br
.ti -1c
.RI "const \fBanimate_NoLooping\fP = 0"
.br
.ti -1c
.RI "const \fBanimate_StartToEnd\fP = 0"
.br
.ti -1c
.RI "const \fBanimate_Unidirectional\fP = 0"
.br
.ti -1c
.RI "string[] \fBargv\fP"
.br
.RI "contains the arguments passed on the command line "
.ti -1c
.RI "const \fBblendMode_Additive\fP = 1"
.br
.ti -1c
.RI "const \fBblendMode_Darken\fP = 4"
.br
.ti -1c
.RI "const \fBblendMode_Lighten\fP = 5"
.br
.ti -1c
.RI "const \fBblendMode_Multiply\fP = 2"
.br
.ti -1c
.RI "const \fBblendMode_Normal\fP = 0"
.br
.ti -1c
.RI "const \fBblendMode_Screen\fP = 3"
.br
.ti -1c
.RI "\fBConfigManager\fP \fBcfg\fP"
.br
.ti -1c
.RI "const \fBcollide_AlphaChannel\fP = 4"
.br
.ti -1c
.RI "const \fBcollide_BoundingBox\fP = 2"
.br
.ti -1c
.RI "const \fBcollide_CollisionRadius\fP = 3"
.br
.ti -1c
.RI "const \fBcollide_Last\fP = 5"
.br
.ti -1c
.RI "const \fBcollide_None\fP = 0"
.br
.ti -1c
.RI "const \fBcollide_Point\fP = 1"
.br
.ti -1c
.RI "const \fBcollide_SpriterCollisionBox\fP = 5"
.br
.ti -1c
.RI "const \fBduration_Constant\fP = \-1"
.br
.ti -1c
.RI "const \fBduration_Instantaneous\fP = 0"
.br
.ti -1c
.RI "const \fBeaseInBack\fP = 25"
.br
.ti -1c
.RI "const \fBeaseInBounce\fP = 22"
.br
.ti -1c
.RI "const \fBeaseInCirc\fP = 19"
.br
.ti -1c
.RI "const \fBeaseInCubic\fP = 4"
.br
.ti -1c
.RI "const \fBeaseInExpo\fP = 16"
.br
.ti -1c
.RI "const \fBeaseInOutBack\fP = 27"
.br
.ti -1c
.RI "const \fBeaseInOutBounce\fP = 24"
.br
.ti -1c
.RI "const \fBeaseInOutCirc\fP = 21"
.br
.ti -1c
.RI "const \fBeaseInOutCubic\fP = 6"
.br
.ti -1c
.RI "const \fBeaseInOutExpo\fP = 18"
.br
.ti -1c
.RI "const \fBeaseInOutQuad\fP = 3"
.br
.ti -1c
.RI "const \fBeaseInOutQuint\fP = 12"
.br
.ti -1c
.RI "const \fBeaseInOutSine\fP = 15"
.br
.ti -1c
.RI "const \fBeaseInQuad\fP = 1"
.br
.ti -1c
.RI "const \fBeaseInQuart\fP = 7"
.br
.ti -1c
.RI "const \fBeaseInQuint\fP = 10"
.br
.ti -1c
.RI "const \fBeaseInSine\fP = 13"
.br
.ti -1c
.RI "const \fBeaseOutBack\fP = 26"
.br
.ti -1c
.RI "const \fBeaseOutBounce\fP = 23"
.br
.ti -1c
.RI "const \fBeaseOutCirc\fP = 20"
.br
.ti -1c
.RI "const \fBeaseOutCubic\fP = 5"
.br
.ti -1c
.RI "const \fBeaseOutExpo\fP = 17"
.br
.ti -1c
.RI "const \fBeaseOutQuad\fP = 2"
.br
.ti -1c
.RI "const \fBeaseOutQuart\fP = 8"
.br
.ti -1c
.RI "const \fBeaseOutQuint\fP = 11"
.br
.ti -1c
.RI "const \fBeaseOutSine\fP = 14"
.br
.ti -1c
.RI "const \fBeventType_KeyDown\fP = 4"
.br
.RI "the user pushed down on a key "
.ti -1c
.RI "const \fBeventType_KeyPress\fP = 6"
.br
.RI "the user pressed and released a key "
.ti -1c
.RI "const \fBeventType_KeyUp\fP = 5"
.br
.RI "the user released a key "
.ti -1c
.RI "const \fBeventType_MouseDown\fP = 7"
.br
.RI "the user pressed a mouse button "
.ti -1c
.RI "const \fBeventType_MouseEnter\fP = 22"
.br
.RI "the user moved the mouse into a tracking area (\fINOT IMPLEMENTED\fP) "
.ti -1c
.RI "const \fBeventType_MouseLeave\fP = 23"
.br
.RI "the user moved the mouse out of a tracking area (\fINOT IMPLEMENTED\fP) "
.ti -1c
.RI "const \fBeventType_MouseMove\fP = 9"
.br
.RI "the user moved the mouse "
.ti -1c
.RI "const \fBeventType_MouseUp\fP = 8"
.br
.RI "the user release a mouse button "
.ti -1c
.RI "const \fBeventType_PortDraw\fP = 24"
.br
.RI "a port needs to be redrawn "
.ti -1c
.RI "const \fBeventType_PortResized\fP = 15"
.br
.RI "a port was resized "
.ti -1c
.RI "const \fBeventType_ScrollWheel\fP = 16"
.br
.RI "the user moved the scroll wheel "
.ti -1c
.RI "const \fBeventType_Shutdown\fP = 2"
.br
.RI "one time application shutdown event "
.ti -1c
.RI "const \fBeventType_SoundEvent\fP = 14"
.br
.RI "a sound finished or looped "
.ti -1c
.RI "const \fBeventType_SpriteAnimate\fP = 17"
.br
.RI "a sprite finished an animation (\fIOptional\fP) "
.ti -1c
.RI "const \fBeventType_SpriteBreak\fP = 21"
.br
.RI "joined sprites broke apart (\fIChipmunk Physics only\fP) "
.ti -1c
.RI "const \fBeventType_SpriteCollide\fP = 20"
.br
.RI "a collision between sprites "
.ti -1c
.RI "const \fBeventType_SpriteLayer\fP = 18"
.br
.RI "something happening to a sprite layer "
.ti -1c
.RI "const \fBeventType_SpriteTouch\fP = 19"
.br
.RI "sprite touched event (\fIOptional\fP) "
.ti -1c
.RI "const \fBeventType_Timer\fP = 3"
.br
.RI "a timer fire event "
.ti -1c
.RI "\fBEventManager\fP \fBevt\fP"
.br
.ti -1c
.RI "const \fBfacing_East\fP = 64"
.br
.ti -1c
.RI "const \fBfacing_Ignore\fP = 256"
.br
.ti -1c
.RI "const \fBfacing_North\fP = 0"
.br
.ti -1c
.RI "const \fBfacing_South\fP = 128"
.br
.ti -1c
.RI "const \fBfacing_West\fP = 192"
.br
.ti -1c
.RI "const \fBfit_Clipped\fP = 6"
.br
.ti -1c
.RI "const \fBfit_Fill\fP = 1"
.br
.ti -1c
.RI "const \fBfit_Height\fP = 2"
.br
.ti -1c
.RI "const \fBfit_Inside\fP = 4"
.br
.ti -1c
.RI "const \fBfit_None\fP = 0"
.br
.ti -1c
.RI "const \fBfit_Overflow\fP = 5"
.br
.ti -1c
.RI "const \fBfit_Tile\fP = 9"
.br
.ti -1c
.RI "const \fBfit_TileX\fP = 7"
.br
.ti -1c
.RI "const \fBfit_TileY\fP = 8"
.br
.ti -1c
.RI "const \fBfit_Width\fP = 3"
.br
.ti -1c
.RI "const \fBflipped_Both\fP = 192"
.br
.ti -1c
.RI "const \fBflipped_Horizontal\fP = 64"
.br
.ti -1c
.RI "const \fBflipped_Ignore\fP = 256"
.br
.ti -1c
.RI "const \fBflipped_None\fP = 0"
.br
.ti -1c
.RI "const \fBflipped_Vertical\fP = 128"
.br
.ti -1c
.RI "\fBFileManager\fP \fBfs\fP"
.br
.ti -1c
.RI "\fBGraphicsManager\fP \fBgfx\fP"
.br
.ti -1c
.RI "const \fBgradientType_Linear\fP = 1"
.br
.ti -1c
.RI "const \fBgradientType_None\fP = 0"
.br
.ti -1c
.RI "const \fBgradientType_Radial\fP = 2"
.br
.ti -1c
.RI "boolean \fBhasGraphics\fP"
.br
.ti -1c
.RI "boolean \fBhasNetwork\fP"
.br
.ti -1c
.RI "boolean \fBhasSound\fP"
.br
.ti -1c
.RI "const \fBinit_AppendToExisting\fP = 2"
.br
.ti -1c
.RI "const \fBinit_CreateUniqueNewFile\fP = 0"
.br
.ti -1c
.RI "const \fBinit_OverwriteExisting\fP = 1"
.br
.ti -1c
.RI "const \fBinit_StdErr\fP = 4"
.br
.ti -1c
.RI "const \fBinit_StdOut\fP = 3"
.br
.ti -1c
.RI "const \fBkey_Backspace\fP = 8"
.br
.ti -1c
.RI "const \fBkey_Break\fP = 1"
.br
.ti -1c
.RI "const \fBkey_Clear\fP = 4"
.br
.ti -1c
.RI "const \fBkey_Delete\fP = 127"
.br
.ti -1c
.RI "const \fBkey_DownArrow\fP = 31"
.br
.ti -1c
.RI "const \fBkey_End\fP = 3"
.br
.ti -1c
.RI "const \fBkey_Enter\fP = 13"
.br
.ti -1c
.RI "const \fBkey_Escape\fP = 27"
.br
.ti -1c
.RI "const \fBkey_F1\fP = 14"
.br
.ti -1c
.RI "const \fBkey_F10\fP = 23"
.br
.ti -1c
.RI "const \fBkey_F11\fP = 24"
.br
.ti -1c
.RI "const \fBkey_F12\fP = 25"
.br
.ti -1c
.RI "const \fBkey_F2\fP = 15"
.br
.ti -1c
.RI "const \fBkey_F3\fP = 16"
.br
.ti -1c
.RI "const \fBkey_F4\fP = 17"
.br
.ti -1c
.RI "const \fBkey_F5\fP = 18"
.br
.ti -1c
.RI "const \fBkey_F6\fP = 19"
.br
.ti -1c
.RI "const \fBkey_F7\fP = 20"
.br
.ti -1c
.RI "const \fBkey_F8\fP = 21"
.br
.ti -1c
.RI "const \fBkey_F9\fP = 22"
.br
.ti -1c
.RI "const \fBkey_FirstF\fP = 14"
.br
.ti -1c
.RI "const \fBkey_FirstPrintable\fP = 32"
.br
.ti -1c
.RI "const \fBkey_Help\fP = 5"
.br
.ti -1c
.RI "const \fBkey_Home\fP = 2"
.br
.ti -1c
.RI "const \fBkey_Insert\fP = 26"
.br
.ti -1c
.RI "const \fBkey_LastF\fP = 25"
.br
.ti -1c
.RI "const \fBkey_LeftArrow\fP = 28"
.br
.ti -1c
.RI "const \fBkey_Mute\fP = 7"
.br
.ti -1c
.RI "const \fBkey_PageDown\fP = 12"
.br
.ti -1c
.RI "const \fBkey_PageUp\fP = 11"
.br
.ti -1c
.RI "const \fBkey_Pause\fP = 6"
.br
.ti -1c
.RI "const \fBkey_Return\fP = 13"
.br
.ti -1c
.RI "const \fBkey_RightArrow\fP = 29"
.br
.ti -1c
.RI "const \fBkey_Tab\fP = 9"
.br
.ti -1c
.RI "const \fBkey_UpArrow\fP = 30"
.br
.ti -1c
.RI "const \fBkeyCode_Alt\fP = 58"
.br
.RI "platform-specific keycode for the Alt/Option key (generic, may not distinguish left/right) "
.ti -1c
.RI "const \fBkeyCode_Control\fP = 59"
.br
.RI "platform-specific keycode for the Control key (generic, may not distinguish left/right) "
.ti -1c
.RI "const \fBkeyCode_LeftAlt\fP = 58"
.br
.RI "platform-specific keycode for the left Alt/Option key "
.ti -1c
.RI "const \fBkeyCode_LeftControl\fP = 59"
.br
.RI "platform-specific keycode for the left Control key "
.ti -1c
.RI "const \fBkeyCode_LeftMeta\fP = 55"
.br
.RI "platform-specific keycode for the left Meta/Command/Windows key "
.ti -1c
.RI "const \fBkeyCode_LeftShift\fP = 56"
.br
.RI "platform-specific keycode for the left Shift key "
.ti -1c
.RI "const \fBkeyCode_Meta\fP = 55"
.br
.RI "platform-specific keycode for the Meta/Command/Windows key (generic) "
.ti -1c
.RI "const \fBkeyCode_RightAlt\fP = 61"
.br
.RI "platform-specific keycode for the right Alt/Option key "
.ti -1c
.RI "const \fBkeyCode_RightControl\fP = 62"
.br
.RI "platform-specific keycode for the right Control key "
.ti -1c
.RI "const \fBkeyCode_RightMeta\fP = 54"
.br
.RI "platform-specific keycode for the right Meta/Command/Windows key "
.ti -1c
.RI "const \fBkeyCode_RightShift\fP = 60"
.br
.RI "platform-specific keycode for the right Shift key "
.ti -1c
.RI "const \fBkeyCode_Shift\fP = 56"
.br
.RI "platform-specific keycode for the Shift key (generic, may not distinguish left/right) "
.ti -1c
.RI "const \fBlftBot\fP = 3"
.br
.ti -1c
.RI "const \fBlftTop\fP = 0"
.br
.ti -1c
.RI "const \fBlinearTween\fP = 0"
.br
.ti -1c
.RI "const \fBlineStyle_Auto\fP = 0"
.br
.ti -1c
.RI "const \fBlineStyle_DashDot\fP = 5"
.br
.ti -1c
.RI "const \fBlineStyle_DashDotDot\fP = 6"
.br
.ti -1c
.RI "const \fBlineStyle_Dashed\fP = 3"
.br
.ti -1c
.RI "const \fBlineStyle_Dotted\fP = 4"
.br
.ti -1c
.RI "const \fBlineStyle_None\fP = 1"
.br
.ti -1c
.RI "const \fBlineStyle_Solid\fP = 2"
.br
.ti -1c
.RI "\fBLogManager\fP \fBlm\fP"
.br
.ti -1c
.RI "boolean \fBquitting\fP"
.br
.ti -1c
.RI "\fBResourceManager\fP \fBres\fP"
.br
.ti -1c
.RI "const \fBrgtBot\fP = 2"
.br
.ti -1c
.RI "const \fBrgtTop\fP = 1"
.br
.ti -1c
.RI "boolean \fBrunning\fP"
.br
.ti -1c
.RI "const \fBscreenPos_FaceDown\fP = 5"
.br
.ti -1c
.RI "const \fBscreenPos_FaceUp\fP = 4"
.br
.ti -1c
.RI "const \fBscreenPos_Normal\fP = 0"
.br
.ti -1c
.RI "const \fBscreenPos_Rotated180\fP = 1"
.br
.ti -1c
.RI "const \fBscreenPos_Rotated90Clockwise\fP = 2"
.br
.ti -1c
.RI "const \fBscreenPos_Rotated90CounterClockwise\fP = 3"
.br
.ti -1c
.RI "const \fBser_Animations\fP = 8"
.br
.ti -1c
.RI "const \fBser_Forces\fP = 32"
.br
.ti -1c
.RI "const \fBser_Full\fP = 18303"
.br
.RI "sprite layer serialization mode for recreating layer "
.ti -1c
.RI "const \fBser_HelperObjs\fP = 8192"
.br
.ti -1c
.RI "const \fBser_HelperRefs\fP = 1024"
.br
.ti -1c
.RI "const \fBser_ImageRefs\fP = 256"
.br
.ti -1c
.RI "const \fBser_InitialData\fP = 16384"
.br
.ti -1c
.RI "const \fBser_LayerDraw\fP = 128"
.br
.ti -1c
.RI "const \fBser_Micro\fP = 3"
.br
.RI "sprite layer serialization mode for minimal size "
.ti -1c
.RI "const \fBser_Motion\fP = 16"
.br
.ti -1c
.RI "const \fBser_Physics\fP = 64"
.br
.ti -1c
.RI "const \fBser_Positions\fP = 1"
.br
.ti -1c
.RI "const \fBser_SCMLRefs\fP = 512"
.br
.ti -1c
.RI "const \fBser_Sizes\fP = 4"
.br
.ti -1c
.RI "const \fBser_Update\fP = 127"
.br
.RI "sprite layer serialization mode for regular updates "
.ti -1c
.RI "const \fBser_ZOrder\fP = 2"
.br
.ti -1c
.RI "\fBSoundManager\fP \fBsnd\fP"
.br
.ti -1c
.RI "const \fBsoundEvent_DonePlaying\fP = 0"
.br
.RI "sound event type for completion of a sound "
.ti -1c
.RI "const \fBsoundEvent_FailedToPlay\fP = 2"
.br
.RI "sound event type for a sound error "
.ti -1c
.RI "const \fBsoundEvent_Looping\fP = 1"
.br
.RI "sound event type for a sound finishing and starting over "
.ti -1c
.RI "const \fBspline_Cardinal\fP = 2"
.br
.ti -1c
.RI "const \fBspline_CubicBezier\fP = 4"
.br
.ti -1c
.RI "const \fBspline_Hermite\fP = 1"
.br
.ti -1c
.RI "const \fBspline_NaturalCubic\fP = 6"
.br
.ti -1c
.RI "const \fBspline_TCB\fP = 5"
.br
.ti -1c
.RI "const \fBspline_UniformB\fP = 3"
.br
.ti -1c
.RI "const \fBstart_FromFirstFrame\fP = \-1"
.br
.ti -1c
.RI "const \fBstart_FromLastFrame\fP = \-2"
.br
.ti -1c
.RI "const \fBtextStyle_Bold\fP = 1"
.br
.ti -1c
.RI "const \fBtextStyle_Centered\fP = 16"
.br
.ti -1c
.RI "const \fBtextStyle_Italic\fP = 2"
.br
.ti -1c
.RI "const \fBtextStyle_LeftJustified\fP = 0"
.br
.ti -1c
.RI "const \fBtextStyle_Plain\fP = 0"
.br
.ti -1c
.RI "const \fBtextStyle_RightJustified\fP = 32"
.br
.ti -1c
.RI "const \fBtextStyle_Underline\fP = 4"
.br
.ti -1c
.RI "const \fBtimer_Never\fP = \-1"
.br
.ti -1c
.RI "const \fBtimer_OneShot\fP = true"
.br
.ti -1c
.RI "const \fBtimer_Repeating\fP = false"
.br
.ti -1c
.RI "\fBTimerManager\fP \fBtm\fP"
.br
.ti -1c
.RI "const \fBtouch_MouseClick\fP = 24"
.br
.ti -1c
.RI "const \fBtouch_MouseDown\fP = 22"
.br
.ti -1c
.RI "const \fBtouch_MouseEnter\fP = 20"
.br
.ti -1c
.RI "const \fBtouch_MouseLeave\fP = 21"
.br
.ti -1c
.RI "const \fBtouch_MouseUp\fP = 23"
.br
.ti -1c
.RI "const \fBtype_Arc\fP = 3"
.br
.ti -1c
.RI "const \fBtype_Drawing\fP = 10"
.br
.ti -1c
.RI "const \fBtype_Ellipse\fP = 7"
.br
.ti -1c
.RI "const \fBtype_Image\fP = 8"
.br
.ti -1c
.RI "const \fBtype_ImageStrip\fP = 9"
.br
.ti -1c
.RI "const \fBtype_Line\fP = 1"
.br
.ti -1c
.RI "const \fBtype_Polygon\fP = 6"
.br
.ti -1c
.RI "const \fBtype_Quad\fP = 5"
.br
.ti -1c
.RI "const \fBtype_Rect\fP = 4"
.br
.ti -1c
.RI "const \fBtype_Spline\fP = 2"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "captureConsole ()"

.SS "cleanupLayer (\fBSpriteLayer\fP layer)"

.SS "\fBDrawing\fP createDrawing ()"

.SS "\fBISerializable\fP createSerializableObject (object obj, uint classTag)"

.SS "\fBSpriteLayer\fP createSpriteLayer (\fBPort\fP port = \fRnull\fP)"

.PP
create a new \fBSpriteLayer\fP attached to a particular port 
.PP
\fBParameters\fP
.RS 4
\fIport\fP if passed, associate with a specific port, otherwise, associate with the main port
.RE
.PP
\fBSee also\fP
.RS 4
\fBpdg\&.Port\fP 

.PP
\fBpdg\&.GraphicsManager\&.getMainPort()\fP 
.RE
.PP

.SS "\fBSpriteLayer\fP createSpriteLayerFromSpriterFile (string layerSpriterFilename, boolean addSprites = \fRtrue\fP, \fBPort\fP port = \fRnull\fP)"

.PP
create a new \fBSpriteLayer\fP from an Spriter SCML file 
.PP
\fBParameters\fP
.RS 4
\fIlayerSpriterFilename\fP the path and name of the SCML file 
.br
\fIaddSprites\fP if true, all entities found in the SCML file will be added as sprites to the layer\&. If false, the SCML file will be loaded and all it's data will be cached for layer use by \fBpdg\&.SpriteLayer\&.createSpriteFromSpriterEntity()\fP 
.br
\fIport\fP if passed, associate with a specific port, otherwise, associate with the main port
.RE
.PP
\fBSee also\fP
.RS 4
\fBGraphicsManager\&.getMainPort()\fP 

.PP
SpriteLayer\&.createSpriteFromSCMLEntity() 
.RE
.PP

.SS "\fBTileLayer\fP createTileLayer (\fBPort\fP port = \fRnull\fP)"

.PP
create a new \fBTileLayer\fP attached to a particular port 
.PP
\fBParameters\fP
.RS 4
\fIport\fP if passed, associate with a specific port, otherwise, associate with the main port
.RE
.PP
\fBSee also\fP
.RS 4
\fBpdg\&.Port\fP 

.PP
\fBpdg\&.GraphicsManager\&.getMainPort()\fP 
.RE
.PP

.SS "debug (string msg)"

.SS "error (string msg)"

.SS "fatal (string msg)"

.SS "\fBConfigManager\fP getConfigManager ()"

.PP
get the singleton instance of the \fBConfigManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBConfigManager\fP singleton object 
.RE
.PP

.SS "\fBEventManager\fP getEventManager ()"

.PP
get the singleton instance of the \fBEventManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBEventManager\fP singleton object 
.RE
.PP

.SS "\fBFileManager\fP getFileManager ()"

.PP
get the singleton instance of the \fBFileManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBFileManager\fP singleton object 
.RE
.PP

.SS "\fBGraphicsManager\fP getGraphicsManager ()"

.PP
get the singleton instance of the \fBGraphicsManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBGraphicsManager\fP singleton object 
.RE
.PP

.SS "\fBLogManager\fP getLogManager ()"

.PP
get the singleton instance of the \fBLogManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBLogManager\fP singleton object 
.RE
.PP

.SS "\fBResourceManager\fP getResourceManager ()"

.PP
get the singleton instance of the \fBResourceManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBResourceManager\fP singleton object 
.RE
.PP

.SS "\fBSoundManager\fP getSoundManager ()"

.PP
get the singleton instance of the \fBSoundManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBSoundManager\fP singleton object 
.RE
.PP

.SS "\fBTimerManager\fP getTimerManager ()"

.PP
get the singleton instance of the \fBTimerManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBTimerManager\fP singleton object 
.RE
.PP

.SS "idle ()"

.SS "info (string msg)"

.SS "log (string msg)"

.SS "\fBIEventHandler\fP on (int eventType, function func)"

.SS "\fBIEventHandler\fP onKeyDown (function func)"

.SS "\fBIEventHandler\fP onKeyPress (function func)"

.SS "\fBIEventHandler\fP onKeyUp (function func)"

.SS "\fBIEventHandler\fP onMouseDown (function func)"

.SS "\fBIEventHandler\fP onMouseMove (function func)"

.SS "\fBIEventHandler\fP onMouseUp (function func)"

.SS "\fBIEventHandler\fP onShutdown (function func)"

.SS "\fBIEventHandler\fP onTimer (function func)"

.SS "openCommandPort (int port = \fR5757\fP)"

.SS "openConsole ()"

.SS "openDebugger ()"

.SS "quit ()"

.SS "number rand ()"

.SS "registerEasingFunction (function easingFunc)"

.SS "registerSerializableClass (function klass)"

.SS "run ()"

.SS "setSerializationDebugMode (bool debugMode)"

.SS "srand (uint seed)"

.SS "startRepl ()"

.SS "trace (string msg)"

.SS "warn (string msg)"

.SH "Variable Documentation"
.PP 
.SS "const all_Frames = 0"

.PP
Referenced by \fBSprite::addFramesImage()\fP, \fBSprite::offsetFrameCenters()\fP, and \fBSprite::startFrameAnimation()\fP\&.
.SS "const animate_Bidirectional = 2"

.SS "const animate_EndToStart = 1"

.SS "const animate_Looping = 4"

.PP
Referenced by \fBSprite::startFrameAnimation()\fP\&.
.SS "const animate_NoLooping = 0"

.SS "const animate_StartToEnd = 0"

.SS "const animate_Unidirectional = 0"

.SS "string [] argv"

.PP
contains the arguments passed on the command line If this was launched by being double-clicked, or on the command line with no arguments, then it will contain: 
.PP
.nf
[ "/path/to/pdg", "main\&.js" ]

.fi
.PP

.PP
\fBpdg\&.argv\fP[0] will always be the path to the pdg application\&. There will always be a \&.js file on the path, even if one wasn't specifically passed in main\&.js will be added\&. 
.SS "const blendMode_Additive = 1"

.SS "const blendMode_Darken = 4"

.SS "const blendMode_Lighten = 5"

.SS "const blendMode_Multiply = 2"

.SS "const blendMode_Normal = 0"

.SS "const blendMode_Screen = 3"

.SS "\fBConfigManager\fP cfg\fR [related]\fP"

.SS "const collide_AlphaChannel = 4"

.PP
Referenced by \fBSprite::enableCollisions()\fP\&.
.SS "const collide_BoundingBox = 2"

.PP
Referenced by \fBSprite::setMouseDetectMode()\fP\&.
.SS "const collide_CollisionRadius = 3"

.SS "const collide_Last = 5"

.SS "const collide_None = 0"

.SS "const collide_Point = 1"

.SS "const collide_SpriterCollisionBox = 5"

.SS "const duration_Constant = \-1"

.SS "const duration_Instantaneous = 0"

.PP
Referenced by \fBAnimated::accelerate()\fP, \fBAnimated::accelerateTo()\fP, \fBAnimated::applyForce()\fP, \fBAnimated::applyTorque()\fP, \fBAnimated::changeCenter()\fP, \fBAnimated::changeCenterTo()\fP, \fBAnimated::grow()\fP, \fBAnimated::move()\fP, \fBAnimated::moveTo()\fP, \fBAnimated::resize()\fP, \fBAnimated::resizeTo()\fP, \fBAnimated::rotate()\fP, \fBAnimated::rotateTo()\fP, and \fBAnimated::stretch()\fP\&.
.SS "const easeInBack = 25"

.SS "const easeInBounce = 22"

.SS "const easeInCirc = 19"

.SS "const easeInCubic = 4"

.SS "const easeInExpo = 16"

.SS "const easeInOutBack = 27"

.SS "const easeInOutBounce = 24"

.SS "const easeInOutCirc = 21"

.SS "const easeInOutCubic = 6"

.SS "const easeInOutExpo = 18"

.SS "const easeInOutQuad = 3"

.PP
Referenced by \fBAnimated::changeCenter()\fP, \fBAnimated::changeCenterTo()\fP, \fBSound::changePitch()\fP, \fBAnimated::grow()\fP, \fBAnimated::move()\fP, \fBAnimated::moveTo()\fP, \fBAnimated::resize()\fP, \fBAnimated::resizeTo()\fP, \fBAnimated::rotate()\fP, \fBAnimated::rotateTo()\fP, \fBAnimated::stretch()\fP, \fBSpriteLayer::zoom()\fP, and \fBSpriteLayer::zoomTo()\fP\&.
.SS "const easeInOutQuint = 12"

.SS "const easeInOutSine = 15"

.SS "const easeInQuad = 1"

.SS "const easeInQuart = 7"

.SS "const easeInQuint = 10"

.SS "const easeInSine = 13"

.SS "const easeOutBack = 26"

.SS "const easeOutBounce = 23"

.SS "const easeOutCirc = 20"

.SS "const easeOutCubic = 5"

.SS "const easeOutExpo = 17"

.SS "const easeOutQuad = 2"

.SS "const easeOutQuart = 8"

.SS "const easeOutQuint = 11"

.SS "const easeOutSine = 14"

.SS "\fBEventManager\fP evt\fR [related]\fP"

.SS "const facing_East = 64"

.SS "const facing_Ignore = 256"

.PP
Referenced by \fBTileLayer::setTileTypeAt()\fP\&.
.SS "const facing_North = 0"

.SS "const facing_South = 128"

.SS "const facing_West = 192"

.SS "const fit_Clipped = 6"

.SS "const fit_Fill = 1"

.SS "const fit_Height = 2"

.SS "const fit_Inside = 4"

.SS "const fit_None = 0"

.SS "const fit_Overflow = 5"

.SS "const fit_Tile = 9"

.SS "const fit_TileX = 7"

.SS "const fit_TileY = 8"

.SS "const fit_Width = 3"

.SS "const flipped_Both = 192"

.SS "const flipped_Horizontal = 64"

.SS "const flipped_Ignore = 256"

.SS "const flipped_None = 0"

.SS "const flipped_Vertical = 128"

.SS "\fBFileManager\fP fs\fR [related]\fP"

.SS "\fBGraphicsManager\fP gfx\fR [related]\fP"

.SS "const gradientType_Linear = 1"

.SS "const gradientType_None = 0"

.SS "const gradientType_Radial = 2"

.SS "boolean hasGraphics"

.SS "boolean hasNetwork"

.SS "boolean hasSound"

.SS "const init_AppendToExisting = 2"

.SS "const init_CreateUniqueNewFile = 0"

.SS "const init_OverwriteExisting = 1"

.SS "const init_StdErr = 4"

.SS "const init_StdOut = 3"

.SS "const lftBot = 3"

.SS "const lftTop = 0"

.SS "const linearTween = 0"

.PP
Referenced by \fBAnimated::accelerate()\fP, \fBAnimated::accelerateTo()\fP, \fBSound::changeOffsetX()\fP, \fBSound::changeVolume()\fP, \fBSound::fadeIn()\fP, \fBSprite::fadeIn()\fP, \fBSpriteLayer::fadeIn()\fP, \fBSound::fadeOut()\fP, \fBSprite::fadeOut()\fP, \fBSpriteLayer::fadeOut()\fP, and \fBSprite::fadeTo()\fP\&.
.SS "const lineStyle_Auto = 0"

.SS "const lineStyle_DashDot = 5"

.SS "const lineStyle_DashDotDot = 6"

.SS "const lineStyle_Dashed = 3"

.SS "const lineStyle_Dotted = 4"

.SS "const lineStyle_None = 1"

.SS "const lineStyle_Solid = 2"

.SS "\fBLogManager\fP lm"

.SS "boolean quitting"

.SS "\fBResourceManager\fP res\fR [related]\fP"

.SS "const rgtBot = 2"

.SS "const rgtTop = 1"

.SS "boolean running"

.SS "const screenPos_FaceDown = 5"

.SS "const screenPos_FaceUp = 4"

.SS "const screenPos_Normal = 0"

.SS "const screenPos_Rotated180 = 1"

.SS "const screenPos_Rotated90Clockwise = 2"

.SS "const screenPos_Rotated90CounterClockwise = 3"

.SS "const ser_Animations = 8"

.SS "const ser_Forces = 32"

.SS "const ser_Full = 18303"

.PP
sprite layer serialization mode for recreating layer Everything needed to completely recreate the sprite layer\&.

.PP
\fBSee also\fP
.RS 4
\fBser_Micro\fP 

.PP
\fBser_Update\fP 

.PP
\fBSpriteLayer\&.setSerializationFlags()\fP
.RE
.PP
\fBWarning\fP
.RS 4
Helpers are not recreated\&.
.RE
.PP

.SS "const ser_HelperObjs = 8192"

.SS "const ser_HelperRefs = 1024"

.SS "const ser_ImageRefs = 256"

.SS "const ser_InitialData = 16384"

.SS "const ser_LayerDraw = 128"

.SS "const ser_Micro = 3"

.PP
sprite layer serialization mode for minimal size Only sends position and z-order updates\&. Ideal for sprite layers that do no animation of their own and are completely driven frame by frame from a master sprite layer, or perhaps for recording the paths of objects in a sprite layer for a rewind/replay\&.

.PP
\fBSee also\fP
.RS 4
\fBser_Update\fP 

.PP
\fBser_Full\fP 

.PP
\fBSpriteLayer\&.setSerializationFlags()\fP 
.RE
.PP

.SS "const ser_Motion = 16"

.SS "const ser_Physics = 64"

.SS "const ser_Positions = 1"

.SS "const ser_SCMLRefs = 512"

.SS "const ser_Sizes = 4"

.SS "const ser_Update = 127"

.PP
sprite layer serialization mode for regular updates Used to update sprite layers that were created to be identical\&. Unlike the micro update, the updated info includes all the currently acting animations and forces, so it does not need to be updated every frame like the micro updates\&.

.PP
\fBSee also\fP
.RS 4
\fBser_Micro\fP 

.PP
\fBser_Full\fP 

.PP
\fBSpriteLayer\&.setSerializationFlags()\fP 
.RE
.PP

.SS "const ser_ZOrder = 2"

.SS "\fBSoundManager\fP snd\fR [related]\fP"

.SS "const spline_Cardinal = 2"

.SS "const spline_CubicBezier = 4"

.SS "const spline_Hermite = 1"

.SS "const spline_NaturalCubic = 6"

.SS "const spline_TCB = 5"

.SS "const spline_UniformB = 3"

.SS "const start_FromFirstFrame = \-1"

.PP
Referenced by \fBSprite::addFramesImage()\fP, \fBSprite::offsetFrameCenters()\fP, and \fBSprite::startFrameAnimation()\fP\&.
.SS "const start_FromLastFrame = \-2"

.SS "const textStyle_Bold = 1"

.SS "const textStyle_Centered = 16"

.SS "const textStyle_Italic = 2"

.SS "const textStyle_LeftJustified = 0"

.SS "const textStyle_Plain = 0"

.PP
Referenced by \fBPort::getCurrentFont()\fP, \fBFont::getFontAscent()\fP, \fBFont::getFontDescent()\fP, \fBFont::getFontHeight()\fP, \fBFont::getFontLeading()\fP, and \fBPort::getTextWidth()\fP\&.
.SS "const textStyle_RightJustified = 32"

.SS "const textStyle_Underline = 4"

.SS "const timer_Never = \-1"

.SS "const timer_OneShot = true"

.SS "const timer_Repeating = false"

.SS "\fBTimerManager\fP tm\fR [related]\fP"

.SS "const touch_MouseClick = 24"

.SS "const touch_MouseDown = 22"

.SS "const touch_MouseEnter = 20"

.SS "const touch_MouseLeave = 21"

.SS "const touch_MouseUp = 23"

.SS "const type_Arc = 3"

.SS "const type_Drawing = 10"

.SS "const type_Ellipse = 7"

.SS "const type_Image = 8"

.SS "const type_ImageStrip = 9"

.SS "const type_Line = 1"

.SS "const type_Polygon = 6"

.SS "const type_Quad = 5"

.SS "const type_Rect = 4"

.SS "const type_Spline = 2"

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
