.TH "CpSpace" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CpSpace \- container for simulating objects (\fIChipmunk Physics Only\fP)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "number \fBgetCollisionBias\fP ()"
.br
.RI "get the percentage of overlap between colliding bodies that is left unfixed after each step "
.ti -1c
.RI "number \fBgetCollisionPersistence\fP ()"
.br
.RI "get how many steps collision solutions are maintained to prevent jittering "
.ti -1c
.RI "number \fBgetCollisionSlop\fP ()"
.br
.RI "get allowed amount of overlap between shapes "
.ti -1c
.RI "number \fBgetIdleSpeedThreshold\fP ()"
.br
.RI "get speed threshold for a body to be considered idle "
.ti -1c
.RI "number \fBgetSleepTimeThreshold\fP ()"
.br
.RI "get time a group of bodies must remain idle in order to fall asleep "
.ti -1c
.RI "\fBreindexStatic\fP ()"
.br
.RI "Update the collision detection info for the all static shapes in the space\&. "
.ti -1c
.RI "\fBCpSpace\fP \fBsetCollisionBias\fP (number inCollisionBias)"
.br
.RI "set the percentage of overlap between colliding bodies that is left unfixed after each step "
.ti -1c
.RI "\fBCpSpace\fP \fBsetCollisionPersistence\fP (number inCollisionPersistence)"
.br
.RI "set how many steps collision solutions are maintained to prevent jittering "
.ti -1c
.RI "\fBCpSpace\fP \fBsetCollisionSlop\fP (number inCollisionSlop)"
.br
.RI "set allowed amount of overlap between shapes "
.ti -1c
.RI "\fBCpSpace\fP \fBsetIdleSpeedThreshold\fP (number inIdleSpeedThreshold)"
.br
.RI "set speed threshold for a body to be considered idle "
.ti -1c
.RI "\fBCpSpace\fP \fBsetSleepTimeThreshold\fP (number inSleepTimeThreshold)"
.br
.RI "set time a group of bodies must remain idle in order to fall asleep "
.ti -1c
.RI "\fBstep\fP (number dt)"
.br
.RI "step forward in time "
.ti -1c
.RI "\fBuseSpatialHash\fP (number dim, int count)"
.br
.RI "use the spacial hash algorithm for collision detection "
.in -1c
.SH "Detailed Description"
.PP 
container for simulating objects (\fIChipmunk Physics Only\fP) 


.PP
\fBWarning\fP
.RS 4
\fBAPI Stability: 1 - Experimental\fP\&. This API was introduced recently and gotten little or no real use\&. It may change or be removed in future versions\&. It may not be completely implemented and may be missing important pieces of functionality\&. Please try it out and provide feedback\&.
.RE
.PP
\fBSee also\fP
.RS 4
http://files.slembcke.net/chipmunk/release/ChipmunkLatest-Docs/#cpSpace 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "number getCollisionBias ()"

.PP
get the percentage of overlap between colliding bodies that is left unfixed after each step 
.SS "number getCollisionPersistence ()"

.PP
get how many steps collision solutions are maintained to prevent jittering 
.SS "number getCollisionSlop ()"

.PP
get allowed amount of overlap between shapes 
.SS "number getIdleSpeedThreshold ()"

.PP
get speed threshold for a body to be considered idle From Chipmunk cpSpace comments: 
.PP
.nf
The default value of 0 means to let the space guess a good threshold based on gravity\&.

.fi
.PP
 
.SS "number getSleepTimeThreshold ()"

.PP
get time a group of bodies must remain idle in order to fall asleep From Chipmunk cpSpace comments: 
.PP
.nf
Enabling sleeping also implicitly enables the the contact graph\&. The default value of INFINITY disables the sleeping algorithm\&.

.fi
.PP
 
.SS "reindexStatic ()"

.PP
Update the collision detection info for the all static shapes in the space\&. 
.SS "\fBCpSpace\fP setCollisionBias (number inCollisionBias)"

.PP
set the percentage of overlap between colliding bodies that is left unfixed after each step From cpSpace comments: 
.PP
.nf
Determines how fast overlapping shapes are pushed apart\&.
Expressed as a fraction of the error remaining after each second\&.
Defaults to pow(1\&.0 - 0\&.1, 60\&.0) meaning that Chipmunk fixes 10% of overlap each frame at 60Hz

.fi
.PP
 
.SS "\fBCpSpace\fP setCollisionPersistence (number inCollisionPersistence)"

.PP
set how many steps collision solutions are maintained to prevent jittering From the cpSpace comments: 
.PP
.nf
Defaults to 3\&. There is probably never a reason to change this value\&.

.fi
.PP
 
.SS "\fBCpSpace\fP setCollisionSlop (number inCollisionSlop)"

.PP
set allowed amount of overlap between shapes Amount of encouraged penetration between colliding shapes\&. Used to reduce oscillating contacts and keep the collision cache warm\&. Defaults to 0\&.1\&. If you have poor simulation quality, increase this number as much as possible without allowing visible amounts of overlap\&. 
.SS "\fBCpSpace\fP setIdleSpeedThreshold (number inIdleSpeedThreshold)"

.PP
set speed threshold for a body to be considered idle From Chipmunk cpSpace comments: 
.PP
.nf
The default value of 0 means to let the space guess a good threshold based on gravity\&.

.fi
.PP
 
.SS "\fBCpSpace\fP setSleepTimeThreshold (number inSleepTimeThreshold)"

.PP
set time a group of bodies must remain idle in order to fall asleep From Chipmunk cpSpace comments: 
.PP
.nf
Enabling sleeping also implicitly enables the the contact graph\&. The default value of INFINITY disables the sleeping algorithm\&.

.fi
.PP
 
.SS "step (number dt)"

.PP
step forward in time 
.PP
\fBParameters\fP
.RS 4
\fIdt\fP the number of seconds to shift
.RE
.PP
\fBNote\fP
.RS 4
calling this will correctly update the physics based objects, but will not not update animations of other kinds for sprites\&. 
.RE
.PP

.SS "useSpatialHash (number dim, int count)"

.PP
use the spacial hash algorithm for collision detection This can be more efficient when you have a lot of objects that are the same size\&. See the detailed documentation in Chipmunk docs for more info\&.

.PP
\fBSee also\fP
.RS 4
http://files.slembcke.net/chipmunk/release/ChipmunkLatest-Docs/#cpSpace-SpatialHash 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
