.TH "Rect" 3 "Version v1.2.0" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rect \- Rectangle for 2D coordinate system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.PP
Inherited by \fBRotatedRect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRect\fP ()"
.br
.ti -1c
.RI "\fBRect\fP (number left, number top, number right, number bottom)"
.br
.ti -1c
.RI "\fBRect\fP (number w, number h)"
.br
.ti -1c
.RI "\fBRect\fP (\fBPoint\fP leftTop, \fBPoint\fP rightBottom)"
.br
.ti -1c
.RI "\fBRect\fP (\fBPoint\fP topLeft, number w, number h)"
.br
.ti -1c
.RI "\fBRect\fP (Rect source)"
.br
.ti -1c
.RI "\fBRect\fP \fBadd\fP (\fBPoint\fP p)"
.br
.RI "add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates "
.ti -1c
.RI "\fBRect\fP \fBadd\fP (\fBRect\fP r2)"
.br
.RI "add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates "
.ti -1c
.RI "\fBRect\fP \fBassign\fP (\fBRect\fP r2)"
.br
.RI "set this rectangle equal to the given one "
.ti -1c
.RI "\fBRect\fP \fBcenter\fP (\fBPoint\fP p)"
.br
.RI "center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle "
.ti -1c
.RI "\fBRect\fP \fBcenter\fP (\fBRect\fP r)"
.br
.RI "center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle "
.ti -1c
.RI "\fBPoint\fP \fBcenterPoint\fP ()"
.br
.RI "get center point of this rectangle "
.ti -1c
.RI "boolean \fBcontains\fP (\fBPoint\fP p)"
.br
.RI "contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle "
.ti -1c
.RI "boolean \fBcontains\fP (\fBRect\fP r)"
.br
.RI "contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle "
.ti -1c
.RI "\fBRect\fP \fBdiv\fP (\fBPoint\fP p)"
.br
.RI "div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle "
.ti -1c
.RI "\fBRect\fP \fBdiv\fP (\fBRect\fP r2)"
.br
.RI "div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle "
.ti -1c
.RI "\fBRect\fP \fBdividedby\fP (\fBPoint\fP p)"
.br
.RI "Divide this rectangle by a point, returning a new rectangle with scaled dimensions\&. "
.ti -1c
.RI "\fBRect\fP \fBdividedby\fP (\fBRect\fP r2)"
.br
.RI "Divide this rectangle by another rectangle, returning a new rectangle with scaled dimensions\&. "
.ti -1c
.RI "boolean \fBempty\fP ()"
.br
.RI "return true if this rectangle is empty (no width or no height) "
.ti -1c
.RI "boolean \fBequals\fP (\fBRect\fP r2)"
.br
.RI "return true if this rectangle is equal to the given one "
.ti -1c
.RI "\fBRect\fP \fBgrow\fP (number delta)"
.br
.RI "increase the height and width of the rectangle while leaving the center point unchanged "
.ti -1c
.RI "number \fBheight\fP ()"
.br
.RI "get the height of this rectangle "
.ti -1c
.RI "\fBRect\fP \fBhorzGrow\fP (number delta)"
.br
.RI "increase the width of the rectangle while leaving the center point unchanged "
.ti -1c
.RI "\fBRect\fP \fBhorzScale\fP (number f)"
.br
.RI "change the x coordinates of the rectangle by a multiplier "
.ti -1c
.RI "\fBRect\fP \fBhorzShrink\fP (number delta)"
.br
.RI "reduce the width of the rectangle while leaving the center point unchanged "
.ti -1c
.RI "\fBRect\fP \fBintersection\fP (\fBRect\fP r)"
.br
.RI "get a new rectangle that is the overlapping area of the the rectangles "
.ti -1c
.RI "\fBPoint\fP \fBleftBottom\fP ()"
.br
.RI "get bottom left corner point of this rectangle "
.ti -1c
.RI "\fBPoint\fP \fBleftTop\fP ()"
.br
.RI "get top left corner point of this rectangle "
.ti -1c
.RI "\fBRect\fP \fBminus\fP (\fBPoint\fP p)"
.br
.RI "Subtract a point from this rectangle, shifting its position\&. "
.ti -1c
.RI "\fBRect\fP \fBminus\fP (\fBRect\fP r2)"
.br
.RI "Subtract another rectangle from this rectangle, returning the difference\&. "
.ti -1c
.RI "\fBRect\fP \fBmoveDown\fP (number delta)"
.br
.RI "move the rectangle down by some amount "
.ti -1c
.RI "\fBRect\fP \fBmoveLeft\fP (number delta)"
.br
.RI "move the rectangle to the left by some amount "
.ti -1c
.RI "\fBRect\fP \fBmoveRight\fP (number delta)"
.br
.RI "move the rectangle to the right by some amount "
.ti -1c
.RI "\fBRect\fP \fBmoveTo\fP (number x, number y)"
.br
.RI "moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point "
.ti -1c
.RI "\fBRect\fP \fBmoveTo\fP (\fBPoint\fP p)"
.br
.RI "moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point "
.ti -1c
.RI "\fBRect\fP \fBmoveUp\fP (number delta)"
.br
.RI "move the rectangle up by some amount "
.ti -1c
.RI "\fBRect\fP \fBmoveXTo\fP (number x)"
.br
.RI "move the rectangle to a particular x location, leaving y unchanged "
.ti -1c
.RI "\fBRect\fP \fBmoveYTo\fP (number y)"
.br
.RI "move the rectangle to a particular y location, leaving x unchanged "
.ti -1c
.RI "\fBRect\fP \fBmul\fP (\fBPoint\fP p)"
.br
.RI "mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle "
.ti -1c
.RI "\fBRect\fP \fBmul\fP (\fBRect\fP r2)"
.br
.RI "mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle "
.ti -1c
.RI "boolean \fBnotEquals\fP (\fBRect\fP r2)"
.br
.RI "return true if this rectangle is not equal to the given one "
.ti -1c
.RI "boolean \fBoverlaps\fP (\fBRect\fP r)"
.br
.RI "return true if this rectangle overlaps the other rectangle at all (sharing an edge is not overlapping) "
.ti -1c
.RI "\fBRect\fP \fBplus\fP (\fBPoint\fP p)"
.br
.RI "Add a point to this rectangle, shifting its position\&. "
.ti -1c
.RI "\fBRect\fP \fBplus\fP (\fBRect\fP r2)"
.br
.RI "Add another rectangle to this rectangle, returning the combined result\&. "
.ti -1c
.RI "\fBPoint\fP \fBrightBottom\fP ()"
.br
.RI "get bottom right corner point of this rectangle "
.ti -1c
.RI "\fBPoint\fP \fBrightTop\fP ()"
.br
.RI "get top right corner point of this rectangle "
.ti -1c
.RI "\fBRect\fP \fBround\fP ()"
.br
.RI "round the coordinates to closest whole number "
.ti -1c
.RI "\fBRect\fP \fBscale\fP (number f)"
.br
.RI "change the coordinates of the rectangle by a multiplier "
.ti -1c
.RI "\fBRect\fP \fBsetHeight\fP (number h)"
.br
.RI "Set the height of this rectangle, keeping the top edge fixed\&. "
.ti -1c
.RI "\fBRect\fP \fBsetSize\fP (number n)"
.br
.RI "set the size (width & height) of the rectangle "
.ti -1c
.RI "\fBRect\fP \fBsetWidth\fP (number w)"
.br
.RI "Set the width of this rectangle, keeping the left edge fixed\&. "
.ti -1c
.RI "\fBRect\fP \fBshrink\fP (number delta)"
.br
.RI "reduce the height and width of the rectangle while leaving the center point unchanged "
.ti -1c
.RI "\fBRect\fP \fBsub\fP (\fBPoint\fP p)"
.br
.RI "sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates "
.ti -1c
.RI "\fBRect\fP \fBsub\fP (\fBRect\fP r2)"
.br
.RI "sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates "
.ti -1c
.RI "\fBRect\fP \fBtimes\fP (\fBPoint\fP p)"
.br
.RI "Multiply this rectangle by a point, scaling its dimensions\&. "
.ti -1c
.RI "\fBRect\fP \fBtimes\fP (\fBRect\fP r2)"
.br
.RI "Multiply this rectangle by another rectangle, scaling its dimensions\&. "
.ti -1c
.RI "\fBQuad\fP \fBtoQuad\fP ()"
.br
.RI "convert rectangle to a \fBQuad\fP "
.ti -1c
.RI "\fBRect\fP \fBunionWith\fP (\fBRect\fP r)"
.br
.RI "get the smallest possible new rectangle that contains both rectangles "
.ti -1c
.RI "\fBRect\fP \fBvertGrow\fP (number delta)"
.br
.RI "increase the height of the rectangle while leaving the center point unchanged "
.ti -1c
.RI "\fBRect\fP \fBvertScale\fP (number f)"
.br
.RI "change the y coordinates of the rectangle by a multiplier "
.ti -1c
.RI "\fBRect\fP \fBvertShrink\fP (number delta)"
.br
.RI "reduce the height of the rectangle while leaving the center point unchanged "
.ti -1c
.RI "number \fBwidth\fP ()"
.br
.RI "get the width of this rectangle "
.ti -1c
.RI "number \fBx1\fP ()"
.br
.RI "alias for \fBRect\&.left\fP "
.ti -1c
.RI "number \fBx2\fP ()"
.br
.RI "alias for \fBRect\&.right\fP "
.ti -1c
.RI "number \fBy1\fP ()"
.br
.RI "alias for \fBRect\&.top\fP "
.ti -1c
.RI "number \fBy2\fP ()"
.br
.RI "alias for \fBRect\&.bottom\fP "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "number \fBbottom\fP"
.br
.ti -1c
.RI "number \fBleft\fP"
.br
.ti -1c
.RI "number \fBright\fP"
.br
.ti -1c
.RI "number \fBtop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Rectangle for 2D coordinate system\&. 


.PP
\fBNote\fP
.RS 4
\fBAPI Stability: 3 — Stable\fP\&. This public contract is established\&. Compatible changes are expected; intentional breaking changes require an announced breaking release and migration guidance\&. See \fBAPI stability\fP\&.
.RE
.PP
\fBRect\fP is a class that provides support for dealing with rectangles in 2 dimensional space\&. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point( width, height ); 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Rect ()"

.PP
Referenced by \fBRect()\fP, \fBRotatedRect::RotatedRect()\fP, \fBadd()\fP, \fBadd()\fP, \fBassign()\fP, \fBcenter()\fP, \fBcenter()\fP, \fBcontains()\fP, \fBdiv()\fP, \fBdiv()\fP, \fBdividedby()\fP, \fBdividedby()\fP, \fBequals()\fP, \fBgrow()\fP, \fBhorzGrow()\fP, \fBhorzScale()\fP, \fBhorzShrink()\fP, \fBintersection()\fP, \fBminus()\fP, \fBminus()\fP, \fBmoveDown()\fP, \fBmoveLeft()\fP, \fBmoveRight()\fP, \fBmoveTo()\fP, \fBmoveTo()\fP, \fBmoveUp()\fP, \fBmoveXTo()\fP, \fBmoveYTo()\fP, \fBmul()\fP, \fBmul()\fP, \fBnotEquals()\fP, \fBoverlaps()\fP, \fBplus()\fP, \fBplus()\fP, \fBround()\fP, \fBscale()\fP, \fBsetHeight()\fP, \fBsetSize()\fP, \fBsetWidth()\fP, \fBshrink()\fP, \fBsub()\fP, \fBsub()\fP, \fBtimes()\fP, \fBtimes()\fP, \fBunionWith()\fP, \fBvertGrow()\fP, \fBvertScale()\fP, and \fBvertShrink()\fP\&.
.SS "Rect (number w, number h)"

.SS "Rect (\fBPoint\fP topLeft, number w, number h)"

.SS "Rect (\fBPoint\fP leftTop, \fBPoint\fP rightBottom)"

.PP
References \fBleftTop()\fP, and \fBrightBottom()\fP\&.
.SS "Rect (number left, number top, number right, number bottom)"

.PP
References \fBbottom\fP, \fBleft\fP, \fBright\fP, and \fBtop\fP\&.
.SS "Rect (Rect source)"

.PP
References \fBRect()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRect\fP add (\fBPoint\fP p)"

.PP
add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP add (\fBRect\fP r2)"

.PP
add([Point] p): offset this rectangle's location by adding x & y coordinates of the point; add([Rect] r): add another rectangle to this one by adding corresponding coordinates 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP assign (\fBRect\fP r2)"

.PP
set this rectangle equal to the given one 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP center (\fBPoint\fP p)"

.PP
center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP center (\fBRect\fP r)"

.PP
center([Point] p): move the rectangle to be centered over a particular point; center([Rect] r): move the rectangle to be centered within/relative to another rectangle 
.PP
References \fBRect()\fP\&.
.SS "\fBPoint\fP centerPoint ()"

.PP
get center point of this rectangle 
.SS "boolean contains (\fBPoint\fP p)"

.PP
contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle 
.SS "boolean contains (\fBRect\fP r)"

.PP
contains([Point] p) return true if the point is inside this rectangle; contains([Rect] r) return true if the rectangle passed in is entirely inside this rectangle 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP div (\fBPoint\fP p)"

.PP
div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP div (\fBRect\fP r2)"

.PP
div([Point] p): change this rectangle's location by dividing by x & y coordinates of the point; div([Rect] r): change this rect by dividing by corresponding coordinates of another rectangle 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP dividedby (\fBPoint\fP p)"

.PP
Divide this rectangle by a point, returning a new rectangle with scaled dimensions\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP dividedby (\fBRect\fP r2)"

.PP
Divide this rectangle by another rectangle, returning a new rectangle with scaled dimensions\&. 
.PP
References \fBRect()\fP\&.
.SS "boolean empty ()"

.PP
return true if this rectangle is empty (no width or no height) 
.SS "boolean equals (\fBRect\fP r2)"

.PP
return true if this rectangle is equal to the given one 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP grow (number delta)"

.PP
increase the height and width of the rectangle while leaving the center point unchanged 
.PP
References \fBRect()\fP\&.
.SS "number height ()"

.PP
get the height of this rectangle 
.SS "\fBRect\fP horzGrow (number delta)"

.PP
increase the width of the rectangle while leaving the center point unchanged 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP horzScale (number f)"

.PP
change the x coordinates of the rectangle by a multiplier 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP horzShrink (number delta)"

.PP
reduce the width of the rectangle while leaving the center point unchanged 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP intersection (\fBRect\fP r)"

.PP
get a new rectangle that is the overlapping area of the the rectangles 
.PP
References \fBRect()\fP\&.
.SS "\fBPoint\fP leftBottom ()"

.PP
get bottom left corner point of this rectangle 
.SS "\fBPoint\fP leftTop ()"

.PP
get top left corner point of this rectangle 
.PP
Referenced by \fBRect()\fP\&.
.SS "\fBRect\fP minus (\fBPoint\fP p)"

.PP
Subtract a point from this rectangle, shifting its position\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP minus (\fBRect\fP r2)"

.PP
Subtract another rectangle from this rectangle, returning the difference\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveDown (number delta)"

.PP
move the rectangle down by some amount 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveLeft (number delta)"

.PP
move the rectangle to the left by some amount 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveRight (number delta)"

.PP
move the rectangle to the right by some amount 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveTo (number x, number y)"

.PP
moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveTo (\fBPoint\fP p)"

.PP
moveTo(x,y): the rectangle to a particular (x, y) location; moveTo([Point] p): move the rectangle to a particular point 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveUp (number delta)"

.PP
move the rectangle up by some amount 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveXTo (number x)"

.PP
move the rectangle to a particular x location, leaving y unchanged 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP moveYTo (number y)"

.PP
move the rectangle to a particular y location, leaving x unchanged 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP mul (\fBPoint\fP p)"

.PP
mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP mul (\fBRect\fP r2)"

.PP
mul([Point] p): change this rectangle's location by multiplying by x & y coordinates of the point; mul([Rect] r): change this rect by multiplying by corresponding coordinates of another rectangle 
.PP
References \fBRect()\fP\&.
.SS "boolean notEquals (\fBRect\fP r2)"

.PP
return true if this rectangle is not equal to the given one 
.PP
References \fBRect()\fP\&.
.SS "boolean overlaps (\fBRect\fP r)"

.PP
return true if this rectangle overlaps the other rectangle at all (sharing an edge is not overlapping) 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP plus (\fBPoint\fP p)"

.PP
Add a point to this rectangle, shifting its position\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP plus (\fBRect\fP r2)"

.PP
Add another rectangle to this rectangle, returning the combined result\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBPoint\fP rightBottom ()"

.PP
get bottom right corner point of this rectangle 
.PP
Referenced by \fBRect()\fP\&.
.SS "\fBPoint\fP rightTop ()"

.PP
get top right corner point of this rectangle 
.SS "\fBRect\fP round ()"

.PP
round the coordinates to closest whole number 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP scale (number f)"

.PP
change the coordinates of the rectangle by a multiplier 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP setHeight (number h)"

.PP
Set the height of this rectangle, keeping the top edge fixed\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP setSize (number n)"

.PP
set the size (width & height) of the rectangle 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP setWidth (number w)"

.PP
Set the width of this rectangle, keeping the left edge fixed\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP shrink (number delta)"

.PP
reduce the height and width of the rectangle while leaving the center point unchanged 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP sub (\fBPoint\fP p)"

.PP
sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP sub (\fBRect\fP r2)"

.PP
sub([Point] p): offset this rectangle's location by subtracting x & y coordinates of the point; sub([Rect] r): add another rectangle to this one by subtracting corresponding coordinates 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP times (\fBPoint\fP p)"

.PP
Multiply this rectangle by a point, scaling its dimensions\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP times (\fBRect\fP r2)"

.PP
Multiply this rectangle by another rectangle, scaling its dimensions\&. 
.PP
References \fBRect()\fP\&.
.SS "\fBQuad\fP toQuad ()"

.PP
convert rectangle to a \fBQuad\fP 
.SS "\fBRect\fP unionWith (\fBRect\fP r)"

.PP
get the smallest possible new rectangle that contains both rectangles 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP vertGrow (number delta)"

.PP
increase the height of the rectangle while leaving the center point unchanged 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP vertScale (number f)"

.PP
change the y coordinates of the rectangle by a multiplier 
.PP
References \fBRect()\fP\&.
.SS "\fBRect\fP vertShrink (number delta)"

.PP
reduce the height of the rectangle while leaving the center point unchanged 
.PP
References \fBRect()\fP\&.
.SS "number width ()"

.PP
get the width of this rectangle 
.SS "number x1 ()"

.PP
alias for \fBRect\&.left\fP 
.SS "number x2 ()"

.PP
alias for \fBRect\&.right\fP 
.SS "number y1 ()"

.PP
alias for \fBRect\&.top\fP 
.SS "number y2 ()"

.PP
alias for \fBRect\&.bottom\fP 
.SH "Member Data Documentation"
.PP 
.SS "number bottom"

.PP
Referenced by \fBRect()\fP\&.
.SS "number left"

.PP
Referenced by \fBRect()\fP\&.
.SS "number right"

.PP
Referenced by \fBRect()\fP\&.
.SS "number top"

.PP
Referenced by \fBRect()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
