.TH "ConfigManager" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigManager \- used for loading and saving application configuration info  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBgetConfigBool\fP (string inConfigItemName)"
.br
.RI "get boolean configuration value "
.ti -1c
.RI "number \fBgetConfigFloat\fP (string inConfigItemName)"
.br
.RI "get floating point numerical configuration value "
.ti -1c
.RI "number \fBgetConfigLong\fP (string inConfigItemName)"
.br
.RI "get integer numerical configuration value "
.ti -1c
.RI "string \fBgetConfigString\fP (string inConfigItemName)"
.br
.RI "get string configuration value "
.ti -1c
.RI "\fBsetConfigBool\fP (string inConfigItemName, boolean inValue)"
.br
.RI "set boolean configuration value "
.ti -1c
.RI "\fBsetConfigFloat\fP (string inConfigItemName, number inValue)"
.br
.RI "set floating point numerical configuration value "
.ti -1c
.RI "\fBsetConfigLong\fP (string inConfigItemName, int inValue)"
.br
.RI "set integer numerical configuration value "
.ti -1c
.RI "\fBsetConfigString\fP (string inConfigItemName, string inValue)"
.br
.RI "set string configuration value "
.ti -1c
.RI "boolean \fBuseConfig\fP (string inConfigName)"
.br
.RI "specify the abstract configuration "
.in -1c
.SS "Related Symbols"
(Note that these are not member symbols\&.) 
.in +1c
.ti -1c
.RI "\fBcfg\fP"
.br
.RI "the singleton instance of the \fBConfigManager\fP "
.ti -1c
.RI "\fBgetConfigManager\fP"
.br
.RI "get the singleton instance of the \fBConfigManager\fP used by the pdg framework "
.in -1c
.SH "Detailed Description"
.PP 
used for loading and saving application configuration info 


.PP
\fBPrecondition\fP
.RS 4
\fBAPI Stability: 3 - Stable\fP\&. The API has proven satisfactory, but cleanup in the underlying code may cause minor changes\&. Backwards-compatibility is guaranteed\&.
.RE
.PP
Interface to Save and Load game config values\&. This class provides simple platform neutral configuration management\&. It does the right thing on each platform to save and load values that need to persist between game sessions\&. It is not intended to be used to hold saved games\&.

.PP
\fBNote\fP
.RS 4
config item names are not case-sensitive, and case is not preserved in the internal implementation 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean getConfigBool (string inConfigItemName)"

.PP
get boolean configuration value Get the boolean value for a named configuration item\&. If the item does not exist, undefined will be returned rather than a boolean\&.

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item
.RE
.PP
\fBReturns\fP
.RS 4
a boolean value, \fIor\fP \fBundefined\fP if that config item was not set 
.RE
.PP

.SS "number getConfigFloat (string inConfigItemName)"

.PP
get floating point numerical configuration value Get the numerical value for a named configuration item\&. If the item does not exist, undefined will be returned rather than a number\&.

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item
.RE
.PP
\fBReturns\fP
.RS 4
a numerical value, \fIor\fP \fBundefined\fP if that config item was not set 
.RE
.PP

.SS "number getConfigLong (string inConfigItemName)"

.PP
get integer numerical configuration value Get the numerical value for a named configuration item\&. If the item does not exist, undefined will be returned rather than a number\&.

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item
.RE
.PP
\fBReturns\fP
.RS 4
a numerical value, \fIor\fP \fBundefined\fP if that config item was not set 
.RE
.PP

.SS "string getConfigString (string inConfigItemName)"

.PP
get string configuration value Get the string value for a named configuration item\&. If the item does not exist, undefined will be returned rather than a string\&.

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item
.RE
.PP
\fBReturns\fP
.RS 4
a string value, \fIor\fP \fBundefined\fP if that config item was not set 
.RE
.PP

.SS "setConfigBool (string inConfigItemName, boolean inValue)"

.PP
set boolean configuration value Set the boolean value for the named configuration item

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item 
.br
\fIinValue\fP the value for the config item 
.RE
.PP

.SS "setConfigFloat (string inConfigItemName, number inValue)"

.PP
set floating point numerical configuration value Set the numeric value for the named configuration item

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item 
.br
\fIinValue\fP the value for the config item 
.RE
.PP

.SS "setConfigLong (string inConfigItemName, int inValue)"

.PP
set integer numerical configuration value Set the integer value for the named configuration item

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item 
.br
\fIinValue\fP the value for the config item 
.RE
.PP

.SS "setConfigString (string inConfigItemName, string inValue)"

.PP
set string configuration value Set the string value for the named configuration item

.PP
\fBParameters\fP
.RS 4
\fIinConfigItemName\fP the name of the configuration item 
.br
\fIinValue\fP the value for the config item 
.RE
.PP

.SS "boolean useConfig (string inConfigName)"

.PP
specify the abstract configuration Specify an abstract name for the config to be used\&. Implementations will use this to build the name of a file on disk, a registry entry, or something else that's appropriate for the platform you are running on\&.

.PP
\fBParameters\fP
.RS 4
\fIinConfigName\fP Only alpha characters (uppercase and lowercase) are allowed, name is not case sensitive 
.RE
.PP
\fBReturns\fP
.RS 4
false if config not found, unusable or empty 
.RE
.PP

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "getConfigManager\fR [related]\fP"

.PP
get the singleton instance of the \fBConfigManager\fP used by the pdg framework 
.PP
\fBReturns\fP
.RS 4
\fBConfigManager\fP singleton object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
