.TH "Vector" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector \- vector (magnitude and direction) within a 2D coordinate system\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.PP
Inherits \fBOffset\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector\fP ()"
.br
.ti -1c
.RI "\fBVector\fP (number \fBx\fP, number \fBy\fP)"
.br
.ti -1c
.RI "\fBVector\fP (number[] xy)"
.br
.ti -1c
.RI "\fBVector\fP (object xy)"
.br
.ti -1c
.RI "number \fBdotProduct\fP (\fBVector\fP \fBvector\fP)"
.br
.RI "get dot product for this vector with a 2nd vector "
.ti -1c
.RI "\fBVector\fP \fBnormal\fP ()"
.br
.RI "get the normal of this vector, ie: A\&.normal() = (-A\&.y, A\&.x) "
.ti -1c
.RI "\fBPoint\fP \fBprojection\fP (\fBPoint\fP point)"
.br
.RI "do a projection of a point onto this vector "
.ti -1c
.RI "\fBVector\fP \fBunit\fP ()"
.br
.RI "get the unit vector of this vector, ie: A\&.unit() = (A\&.x / |A|, A\&.y / |A|) "
.ti -1c
.RI "number \fBvectorAngle\fP ()"
.br
.RI "get angle (in radians) for this vector "
.ti -1c
.RI "number \fBvectorLength\fP ()"
.br
.RI "get length as a vector (distance from origin) "
.in -1c

Public Member Functions inherited from \fBOffset\fP
.in +1c
.ti -1c
.RI "\fBOffset\fP ()"
.br
.ti -1c
.RI "\fBOffset\fP (number \fBx\fP, number \fBy\fP)"
.br
.ti -1c
.RI "\fBOffset\fP (number[] xy)"
.br
.ti -1c
.RI "\fBOffset\fP (object xy)"
.br
.ti -1c
.RI "\fBOffset\fP \fBadd\fP (\fBOffset\fP offset)"
.br
.RI "add an offset to this one "
.ti -1c
.RI "\fBOffset\fP \fBassign\fP (\fBOffset\fP offset)"
.br
.RI "set this offset equal to the given offset "
.ti -1c
.RI "\fBOffset\fP \fBdiv\fP (\fBOffset\fP offset)"
.br
.RI "divide this offset by the given one "
.ti -1c
.RI "\fBOffset\fP \fBdividedby\fP (\fBOffset\fP offset)"
.br
.RI "return new offset that is this offset divided by given offset "
.ti -1c
.RI "boolean \fBequals\fP (\fBOffset\fP offset)"
.br
.RI "return true if this point is equal to the other "
.ti -1c
.RI "\fBOffset\fP \fBminus\fP (\fBOffset\fP offset)"
.br
.RI "return new offset that is this offset minus given offset "
.ti -1c
.RI "\fBOffset\fP \fBmul\fP (\fBOffset\fP offset)"
.br
.RI "multiply this offset by the given one "
.ti -1c
.RI "boolean \fBnotEquals\fP (\fBOffset\fP offset)"
.br
.RI "return true if this point is not equal to the other "
.ti -1c
.RI "\fBOffset\fP \fBplus\fP (\fBOffset\fP offset)"
.br
.RI "return new offset that is this offset plus given offset "
.ti -1c
.RI "\fBOffset\fP \fBsub\fP (\fBOffset\fP offset)"
.br
.RI "subtract an offset from this one "
.ti -1c
.RI "\fBOffset\fP \fBtimes\fP (\fBOffset\fP offset)"
.br
.RI "return new offset that is this offset multiplied by given offset "
.ti -1c
.RI "\fBVector\fP \fBvector\fP ()"
.br
.RI "return a new vector from this offset "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "number \fBx\fP"
.br
.ti -1c
.RI "number \fBy\fP"
.br
.in -1c

Public Attributes inherited from \fBOffset\fP
.in +1c
.ti -1c
.RI "number \fBx\fP"
.br
.ti -1c
.RI "number \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
vector (magnitude and direction) within a 2D coordinate system\&. 

\fBPoint\fP provides support for dealing with vectors as x, y floating point values in 2 dimensional space\&. A vector is similar to an \fBOffset\fP but can be treated as a magnitude and direction where an \fBOffset\fP can't\&. The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point( width, height ); 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBVector\fP ()"

.PP
Referenced by \fBdotProduct()\fP, \fBnormal()\fP, and \fBunit()\fP\&.
.SS "\fBVector\fP (number x, number y)"

.PP
References \fBx\fP, and \fBy\fP\&.
.SS "\fBVector\fP (number[] xy)"

.SS "\fBVector\fP (object xy)"

.SH "Member Function Documentation"
.PP 
.SS "number dotProduct (\fBVector\fP vector)"

.PP
get dot product for this vector with a 2nd vector 
.PP
References \fBVector()\fP, and \fBOffset::vector()\fP\&.
.SS "\fBVector\fP normal ()"

.PP
get the normal of this vector, ie: A\&.normal() = (-A\&.y, A\&.x) 
.PP
References \fBVector()\fP\&.
.SS "\fBPoint\fP projection (\fBPoint\fP point)"

.PP
do a projection of a point onto this vector 
.SS "\fBVector\fP unit ()"

.PP
get the unit vector of this vector, ie: A\&.unit() = (A\&.x / |A|, A\&.y / |A|) 
.PP
References \fBVector()\fP\&.
.SS "number vectorAngle ()"

.PP
get angle (in radians) for this vector 
.SS "number vectorLength ()"

.PP
get length as a vector (distance from origin) 
.SH "Member Data Documentation"
.PP 
.SS "number x"

.PP
Referenced by \fBVector()\fP\&.
.SS "number y"

.PP
Referenced by \fBVector()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
