.TH "Color" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Color \- color in RGB space, with optional alpha  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP ()"
.br
.RI "create a color "
.ti -1c
.RI "\fBColor\fP (number c)"
.br
.RI "create a color from a single 32 bit A-RGB color value "
.ti -1c
.RI "\fBColor\fP (number r, number g, number b, number \fBalpha\fP=1)"
.br
.RI "create a color with RGB values "
.ti -1c
.RI "\fBColor\fP (string colorstr)"
.br
.RI "create a color by CSS color string "
.ti -1c
.RI "\fBColor\fP \fBassign\fP (\fBColor\fP color)"
.br
.RI "copy a color "
.ti -1c
.RI "\fBconvertToGrayscale\fP ()"
.br
.RI "convert the color to a matching shade of grey "
.ti -1c
.RI "boolean \fBequals\fP (\fBColor\fP color)"
.br
.RI "check if this color is the same as another "
.ti -1c
.RI "boolean \fBnotEquals\fP (\fBColor\fP color)"
.br
.RI "check if this color is different than another color "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "number \fBalpha\fP"
.br
.RI "alpha channel: 0\&.0 transparent \&.\&.\&. 1\&.0 solid "
.ti -1c
.RI "number \fBblue\fP"
.br
.RI "blue component: 0\&.0 no blue \&.\&.\&. 1\&.0 max blue "
.ti -1c
.RI "number \fBgreen\fP"
.br
.RI "green component: 0\&.0 no green \&.\&.\&. 1\&.0 max green "
.ti -1c
.RI "number \fBred\fP"
.br
.RI "red component: 0\&.0 no red \&.\&.\&. 1\&.0 max red "
.in -1c
.SH "Detailed Description"
.PP 
color in RGB space, with optional alpha 

\fBColor\fP is in the global namespace, so you don't need the pdg prefix, even though it will work if you use it

.PP
.PP
.nf
var c = new Color();        // this works
var c2 = new pdg\&.Color();   // this works too
.fi
.PP

.PP
RGB \fBColor\fP Space works by mixing red (R), green (G) and blue (B) light to form all possible colors\&. Here's a nice color wheel to illustrate\&.

.PP
    

.PP
The optional Alpha Channel is used to determine how translucent the color is, ie: how much the underlying colors show through\&. For Alpha, 1\&.0 is completely solid/opaque, and 0\&.0 is completely transparent\&. Whenever an Alpha value is not given, 1\&.0 is assumed\&.

.PP
\fBColor\fP Support:** PDG supports comprehensive color creation through multiple methods:
.IP "\(bu" 2
\fBRGB values\fP: Direct RGB component specification
.IP "\(bu" 2
\fBHex strings\fP: CSS-style hex color strings (#RGB, #RRGGBB)
.IP "\(bu" 2
\fBNamed colors\fP: All 147 standard CSS3 color names (aliceblue, tomato, steelblue, etc\&.)
.IP "\(bu" 2
\fB32-bit values\fP: Single integer color values
.PP

.PP
All color systems are standardized across PDG platforms (V8, JSC, JavaScript) for consistent behavior\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBColor\fP ()"

.PP
create a color Creates a color with all RGB values set to zero, and Alpha channel set to 1, ie: solid black\&. 
.PP
Referenced by \fBassign()\fP, \fBequals()\fP, and \fBnotEquals()\fP\&.
.SS "\fBColor\fP (number c)"

.PP
create a color from a single 32 bit A-RGB color value Creates a color from a single 32 bit RGB value with an Alpha channel\&. It's usually most convenient to express the number in hexadecimal, since it's easier to see the components:

.PP
.PP
.nf
var col = new pdg\&.Color(0xff004488);
.fi
.PP

.PP
In the example above, the A-RGB component values are represented as: 
.PP
.nf
ff 00 44 88
A  R  G  B

.fi
.PP

.PP
\fBSee also\fP
.RS 4
\fBColor(string)\fP 

.PP
\fBColor(number, number, number, number)\fP 
.RE
.PP

.SS "\fBColor\fP (string colorstr)"

.PP
create a color by CSS color string Creates a color from a CSS color value string (ie: #FFF or #FFFFFF); or from a color name\&. For example:

.PP
.PP
.nf
var gray = new pdg\&.Color('#888');  // a gray color (RGB 888888)
var green = new pdg\&.Color('#008800');  // a green color (RGB 008800)
var teal = new pdg\&.Color('teal');  // the CSS teal color
.fi
.PP

.PP
Supported \fBColor\fP names:**

.PP
PDG supports all 147 standard CSS3 color names\&. Here are some examples:

.PP
Basic Colors:**
.IP "\(bu" 2
\fRblack\fP, \fRwhite\fP, \fRred\fP, \fRgreen\fP, \fRblue\fP, \fRyellow\fP, \fRcyan\fP, \fRmagenta\fP

.PP
Extended Colors:**
.IP "\(bu" 2
\fRaliceblue\fP, \fRantiquewhite\fP, \fRaqua\fP, \fRaquamarine\fP, \fRazure\fP, \fRbeige\fP, \fRbisque\fP
.IP "\(bu" 2
\fRblanchedalmond\fP, \fRblueviolet\fP, \fRbrown\fP, \fRburlywood\fP, \fRcadetblue\fP, \fRchartreuse\fP
.IP "\(bu" 2
\fRchocolate\fP, \fRcoral\fP, \fRcornflowerblue\fP, \fRcornsilk\fP, \fRcrimson\fP

.PP
Dark Colors:**
.IP "\(bu" 2
\fRdarkblue\fP, \fRdarkcyan\fP, \fRdarkgreen\fP, \fRdarkred\fP, \fRdarksalmon\fP, \fRdarkseagreen\fP
.IP "\(bu" 2
\fRdarkslateblue\fP, \fRdarkslategray\fP, \fRdarkturquoise\fP, \fRdarkviolet\fP

.PP
Light Colors:**
.IP "\(bu" 2
\fRlightblue\fP, \fRlightcoral\fP, \fRlightcyan\fP, \fRlightgreen\fP, \fRlightpink\fP, \fRlightsalmon\fP
.IP "\(bu" 2
\fRlightseagreen\fP, \fRlightskyblue\fP, \fRlightsteelblue\fP, \fRlightyellow\fP

.PP
Medium Colors:**
.IP "\(bu" 2
\fRmediumblue\fP, \fRmediumorchid\fP, \fRmediumpurple\fP, \fRmediumseagreen\fP
.IP "\(bu" 2
\fRmediumslateblue\fP, \fRmediumspringgreen\fP, \fRmediumturquoise\fP, \fRmediumvioletred\fP

.PP
Special Colors:**
.IP "\(bu" 2
\fRtomato\fP, \fRsalmon\fP, \fRsteelblue\fP, \fRturquoise\fP, \fRlimegreen\fP, \fRforestgreen\fP
.IP "\(bu" 2
\fRgold\fP, \fRgoldenrod\fP, \fRindigo\fP, \fRivory\fP, \fRkhaki\fP, \fRlavender\fP, \fRlinen\fP
.IP "\(bu" 2
\fRmaroon\fP, \fRnavy\fP, \fRolive\fP, \fRorange\fP, \fRorchid\fP, \fRpink\fP, \fRplum\fP, \fRpurple\fP
.IP "\(bu" 2
\fRrosybrown\fP, \fRroyalblue\fP, \fRsaddlebrown\fP, \fRsandybrown\fP, \fRseagreen\fP
.IP "\(bu" 2
\fRsienna\fP, \fRsilver\fP, \fRskyblue\fP, \fRslateblue\fP, \fRslategray\fP, \fRsnow\fP
.IP "\(bu" 2
\fRspringgreen\fP, \fRtan\fP, \fRteal\fP, \fRthistle\fP, \fRviolet\fP, \fRwheat\fP, \fRwhitesmoke\fP
.IP "\(bu" 2
\fRyellowgreen\fP

.PP
Note:** All color names are case-insensitive and follow the CSS3 specification\&. The complete list includes 147 standard CSS3 colors\&.
.PP

.PP
    

.PP
\fBSee also\fP
.RS 4
\fBColor(number)\fP 

.PP
\fBColor(number, number, number, number)\fP 
.RE
.PP

.SS "\fBColor\fP (number r, number g, number b, number alpha = \fR1\fP)"

.PP
create a color with RGB values Create a color by giving the Red, Green and Blue values separately, with an optional alpha channel\&. Values can be given either in the range of 0\&.0 to 1\&.0\&. If no alpha value is given, 1\&.0 is used, making the color completely solid\&.

.PP
.PP
.nf
var white = new Color(1\&.0, 1\&.0, 1\&.0);
var translucentWhite = new Color(1\&.0, 1\&.0, 1\&.0, 0\&.5);
.fi
.PP

.PP
\fBSee also\fP
.RS 4
\fBColor(number)\fP 

.PP
\fBColor(string)\fP 
.RE
.PP

.PP
References \fBalpha\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBColor\fP assign (\fBColor\fP color)"

.PP
copy a color Sets this color to be the same as another color

.PP
.PP
.nf
var c1 = new Color('teal');
var c2 = new Color('black');

c1\&.assign(c2);
console\&.log('c1 is now '+c1);
.fi
.PP

.PP
Output: 
.PP
.nf
c1 is now Color(0,0,0)

.fi
.PP

.PP
\fBReturns\fP
.RS 4
the color (c1 in the example)
.RE
.PP
\fBNote\fP
.RS 4
Unlike a simple assignment (c1 = c2), \fBassign()\fP copies the values but leaves c1 and c2 independent\&. Simple assignment causes c1 and c2 to point to the same data, so changing one changes the other\&. 
.RE
.PP

.PP
References \fBColor()\fP\&.
.SS "convertToGrayscale ()"

.PP
convert the color to a matching shade of grey      
.SS "boolean equals (\fBColor\fP color)"

.PP
check if this color is the same as another 
.PP
\fBReturns\fP
.RS 4
true if the colors are the same, false if not 
.RE
.PP

.PP
References \fBColor()\fP\&.
.SS "boolean notEquals (\fBColor\fP color)"

.PP
check if this color is different than another color 
.PP
\fBReturns\fP
.RS 4
true if the colors are different, false if not 
.RE
.PP

.PP
References \fBColor()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "number alpha"

.PP
alpha channel: 0\&.0 transparent \&.\&.\&. 1\&.0 solid 
.PP
Referenced by \fBColor()\fP\&.
.SS "number blue"

.PP
blue component: 0\&.0 no blue \&.\&.\&. 1\&.0 max blue 
.SS "number green"

.PP
green component: 0\&.0 no green \&.\&.\&. 1\&.0 max green 
.SS "number red"

.PP
red component: 0\&.0 no red \&.\&.\&. 1\&.0 max red 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
