.TH "Sound" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sound \- handles both short sounds and music (\fIGUI Only\fP)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.PP
Inherits \fBEventEmitter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBchangeOffsetX\fP (int targetOffset, int msDuration, int easing=\fBlinearTween\fP)"
.br
.RI "change the left/right positioning of the sound's origin over time "
.ti -1c
.RI "\fBchangePitch\fP (number targetOffset, int msDuration, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "change the pitch of a sound over time (NOT IMPLEMENTED) "
.ti -1c
.RI "\fBchangeVolume\fP (number level, uint fadeMs, int easing=\fBlinearTween\fP)"
.br
.RI "change sounds volume to target level over time "
.ti -1c
.RI "\fBfadeIn\fP (uint fadeMs, int easing=\fBlinearTween\fP)"
.br
.RI "fade the sound in from zero to full volume over time "
.ti -1c
.RI "\fBfadeOut\fP (uint fadeMs, int easing=\fBlinearTween\fP)"
.br
.RI "fade the sound out to silence over time "
.ti -1c
.RI "number \fBgetVolume\fP ()"
.br
.RI "get the current volume level for this sound "
.ti -1c
.RI "boolean \fBisLooping\fP ()"
.br
.RI "find out if this sound is set to loop "
.ti -1c
.RI "boolean \fBisPaused\fP ()"
.br
.RI "find out if a sound is paused "
.ti -1c
.RI "\fBIEventHandler\fP \fBon\fP (int eventCode, function func)"
.br
.RI "set a handler for a particular sound event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonDonePlaying\fP (function func)"
.br
.RI "set a handler for when the sound finishes playing "
.ti -1c
.RI "\fBIEventHandler\fP \fBonFailedToPlay\fP (function func)"
.br
.RI "set a handler for if the sound fails to play "
.ti -1c
.RI "\fBIEventHandler\fP \fBonLooping\fP (function func)"
.br
.RI "set a handler for when the sound reaches the end and loops "
.ti -1c
.RI "\fBpause\fP ()"
.br
.RI "stop a sound playing until resumed "
.ti -1c
.RI "\fBplay\fP (number vol=1\&.0, int offsetX=0, number pitch=0, uint fromMs=0, int lenMs=ENTIRE_LENGTH)"
.br
.RI "play a sound once with given settings "
.ti -1c
.RI "\fBresume\fP ()"
.br
.RI "unpause a sound that was paused "
.ti -1c
.RI "\fBSound\fP \fBsetLooping\fP (boolean loopingOn)"
.br
.RI "set if the sound should loop or not "
.ti -1c
.RI "\fBSound\fP \fBsetOffsetX\fP (int offsetX)"
.br
.RI "set the left/right positioning of the sound's origin "
.ti -1c
.RI "\fBSound\fP \fBsetPitch\fP (number pitchOffset)"
.br
.RI "set the pitch of a sound "
.ti -1c
.RI "\fBSound\fP \fBsetVolume\fP (number inVolume)"
.br
.RI "set the volume level for a sound "
.ti -1c
.RI "\fBSound\fP \fBskip\fP (int skipMilliseconds)"
.br
.RI "skip ahead or back in a sound "
.ti -1c
.RI "\fBSound\fP \fBskipTo\fP (uint timeMs)"
.br
.RI "skipTo a particular time position in a sound "
.ti -1c
.RI "\fBstart\fP ()"
.br
.RI "start playing a sound "
.ti -1c
.RI "\fBstop\fP ()"
.br
.RI "stop a sound from playing "
.in -1c

Public Member Functions inherited from \fBEventEmitter\fP
.in +1c
.ti -1c
.RI "\fBaddHandler\fP (\fBIEventHandler\fP inHandler, int inEventType=\fBall_events\fP)"
.br
.RI "add a new handler for some event type, or for all events if no type specified\&. "
.ti -1c
.RI "\fBblockEvent\fP (int inEventType)"
.br
.RI "temporarily ignore all events of a particular type\&. "
.ti -1c
.RI "\fBclear\fP ()"
.br
.RI "remove all handlers "
.ti -1c
.RI "\fBremoveHandler\fP (\fBIEventHandler\fP inHandler, int inEventType=\fBall_events\fP)"
.br
.RI "remove a handler for some event type, or for all events (see note) if no type specified\&. "
.ti -1c
.RI "\fBunblockEvent\fP (int inEventType)"
.br
.RI "stop ignoring events of a particular type "
.in -1c
.SH "Detailed Description"
.PP 
handles both short sounds and music (\fIGUI Only\fP) 


.PP
\fBNote\fP
.RS 4
\fBAPI Stability: 2 - Unstable\fP\&. The API is in the process of settling, but has not yet had sufficient real-world testing to be considered stable\&. Backwards-compatibility will be maintained if reasonable\&.
.RE
.PP
.SS "Fire and Forget Playback"
This mode is typically used for short sound effects, like a footstep, an explosion, a single note of music, or some other momentary sound that doesn't need to be altered while playing\&. Use \fBplay()\fP for that sort of fire and forget sound\&.

.PP
Fire and Forget Example:**

.PP
.PP
.nf
PDG terminal v0\&.9\&.4
> pdg\&.run();  // must be running for sounds to play
> var snd = new pdg\&.Sound("test/clink1\&.mp3");
> snd\&.play();
> snd\&.play(0\&.3);
.fi
.PP
.SS "Dynamic Playback"
For longer sound effects and music, you will often want more dynamic control over the sound as it plays\&. The hum of a motor might change pitch and location as the sprite that generates it moves around on the screen\&. Background music may need to be paused or have it's volume changed independent of other sounds as it plays\&. Use \fBstart()\fP to play those sorts of sounds, then call other methods as needed to alter the sound playback\&.

.PP
Dynamic Playback Example:**

.PP
.PP
.nf
PDG terminal v0\&.9\&.4
> pdg\&.run();  // must be running for sounds to play
> var snd = new pdg\&.Sound("test/Peppy_The\-Firing\-Squad_YMXB\&.mp3");
> snd\&.start();
> snd\&.setVolume(0\&.3);
> snd\&.skip(2000);
> snd\&.setPitch(1\&.0);  // doesn't work on Windows
> snd\&.setPitch(0);
> snd\&.setOffsetX(1000); // full right 
> snd\&.setOffsetX(\-500); // half left 
> snd\&.setOffsetX(0); // center
> snd\&.fadeOut(10000); // fade out over 10 seconds
.fi
.PP

.PP
\fBSee also\fP
.RS 4
\fBplay\fP 

.PP
\fBstart\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "changeOffsetX (int targetOffset, int msDuration, int easing = \fR\fBlinearTween\fP\fP)"

.PP
change the left/right positioning of the sound's origin over time Adjust the apparent left/right positioning of the sound over a period of time to make the sound appear to be coming from a particular location in the view port\&.

.PP
\fBNote\fP
.RS 4
since different speaker setups and screen sizes can change the apparent location, this is a relative location only\&.
.RE
.PP
\fBWarning\fP
.RS 4
On Mac OS X this only works if the sound is in stereo, and the OS is version 10\&.7 (aka Lion) or later\&. It will fail silently on earlier versions or with mono or multichannel sounds; and the sound will play with center balance\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fItargetOffset\fP the target X offset from the center of the main view port 
.br
\fImsDuration\fP the amount of time to get there 
.br
\fIeasing\fP the function for calculating the movement rate\&. Defaults to linearTween (smooth movement with no acceleration or deceleration)\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBsetOffsetX\fP 

.PP
\fBGraphicsManager\&.getMainPort\fP 

.PP
Easing 
.RE
.PP

.PP
References \fBpdg::linearTween\fP\&.
.SS "changePitch (number targetOffset, int msDuration, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
change the pitch of a sound over time (NOT IMPLEMENTED) 
.PP
References \fBpdg::easeInOutQuad\fP\&.
.SS "changeVolume (number level, uint fadeMs, int easing = \fR\fBlinearTween\fP\fP)"

.PP
change sounds volume to target level over time The change can go in either direction, louder or quieter\&.

.PP
\fBParameters\fP
.RS 4
\fIlevel\fP the target level 
.br
\fIfadeMs\fP the time to take for sound to reach the new volume level 
.br
\fIeasing\fP the function that describes how the volume change should happen, defaults to linearTween (constant rate of change)
.RE
.PP
\fBSee also\fP
.RS 4
Easing 

.PP
\fBlinearTween\fP 
.RE
.PP

.PP
References \fBpdg::linearTween\fP\&.
.SS "fadeIn (uint fadeMs, int easing = \fR\fBlinearTween\fP\fP)"

.PP
fade the sound in from zero to full volume over time 
.PP
\fBParameters\fP
.RS 4
\fIfadeMs\fP the time to take for sound to reach full volume 
.br
\fIeasing\fP the function that describes how the fading should happen, defaults to linearTween (constant rate of change)
.RE
.PP
\fBSee also\fP
.RS 4
\fBfadeOut\fP 

.PP
\fBchangeVolume\fP 

.PP
Easing 

.PP
\fBlinearTween\fP 
.RE
.PP

.PP
References \fBpdg::linearTween\fP\&.
.SS "fadeOut (uint fadeMs, int easing = \fR\fBlinearTween\fP\fP)"

.PP
fade the sound out to silence over time The sound is stopped once it fades out completely\&.

.PP
\fBParameters\fP
.RS 4
\fIfadeMs\fP the time to take for sound to fade out completely 
.br
\fIeasing\fP the function that describes how the fading should happen, defaults to linearTween (constant rate of change)
.RE
.PP
\fBSee also\fP
.RS 4
\fBfadeIn\fP 

.PP
\fBchangeVolume\fP 

.PP
Easing 

.PP
\fBlinearTween\fP 
.RE
.PP

.PP
References \fBpdg::linearTween\fP\&.
.SS "number getVolume ()"

.PP
get the current volume level for this sound 
.PP
\fBReturns\fP
.RS 4
a number from 0\&.0 to 1\&.0 representing the volume level for this sound\&.
.RE
.PP
\fBNote\fP
.RS 4
This is not the absolute volume of the sound, since even at full volume (1\&.0) the sound's volume is scaled by the \fBSoundManager\fP's master volume
.RE
.PP
\fBSee also\fP
.RS 4
\fBSoundManager\&.setVolume\fP 
.RE
.PP

.SS "boolean isLooping ()"

.PP
find out if this sound is set to loop 
.PP
\fBReturns\fP
.RS 4
true if the sound will loop when it reaches the end, false if it will not 
.RE
.PP

.SS "boolean isPaused ()"

.PP
find out if a sound is paused 
.PP
\fBReturns\fP
.RS 4
true if the sound is currently paused, false if not
.RE
.PP
\fBNote\fP
.RS 4
a sound that was never started is not considered paused 
.RE
.PP

.SS "\fBIEventHandler\fP on (int eventCode, function func)"

.PP
set a handler for a particular sound event 
.PP
\fBRemarks\fP
.RS 4
Generally you should use the specific on{Event} calls\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBonDonePlaying()\fP 

.PP
\fBonFailedToPlay()\fP 

.PP
\fBonLooping()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onDonePlaying (function func)"

.PP
set a handler for when the sound finishes playing 
.SS "\fBIEventHandler\fP onFailedToPlay (function func)"

.PP
set a handler for if the sound fails to play 
.SS "\fBIEventHandler\fP onLooping (function func)"

.PP
set a handler for when the sound reaches the end and loops 
.SS "pause ()"

.PP
stop a sound playing until resumed 
.SS "play (number vol = \fR1\&.0\fP, int offsetX = \fR0\fP, number pitch = \fR0\fP, uint fromMs = \fR0\fP, int lenMs = \fRENTIRE_LENGTH\fP)"

.PP
play a sound once with given settings Can be called multiple times on same sound object, creating overlapping sounds\&. Internally, \fBplay()\fP creates a new sound instance that is automatically cleaned up when the sound has finished playing\&.

.PP
\fBNote\fP
.RS 4
Once you've called \fBplay()\fP, the sound will play without interruption as specified\&. Calling \fBstop()\fP, \fBpause()\fP, \fBsetVolume()\fP, etc\&.\&. will have no effect; because they operate on the sound you actually have a reference to, not the internally created instance that is actually playing\&. Only \fBSoundManager\&.setVolume()\fP and \fBSoundManager\&.setMute()\fP will affect it\&. Use \fBstart()\fP if you need to affect the sound after it is playing\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIvol\fP the volume level from 0\&.0 to 1\&.0, defaults to 1\&.0 
.br
\fIoffsetX\fP the left/right position offset from the center of the screen for the sound source\&. The pan/balance for the sound is adjusted accordingly\&. Negative numbers are from the left, positive to the right\&. Defaults to zero (no balance adjustment)\&. 
.br
\fIpitch\fP the amount to shift the pitch -1\&.0 is down one octave, +1\&.0 is up one octave\&. 
.br
\fIfromMs\fP start the sound from a particular ms time mark 
.br
\fIlenMs\fP the maximum number of ms to play the sound\&. If longer than the length of the sound this parameter is ignored\&. Defaults to playing the entire length of the sound\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBstart\fP
.RE
.PP

.SS "resume ()"

.PP
unpause a sound that was paused Play continues from where it was before it was paused\&. 
.SS "\fBSound\fP setLooping (boolean loopingOn)"

.PP
set if the sound should loop or not 
.PP
\fBNote\fP
.RS 4
Sounds started with \fBplay()\fP never loop 
.RE
.PP

.SS "\fBSound\fP setOffsetX (int offsetX)"

.PP
set the left/right positioning of the sound's origin Set the apparent left/right positioning of the sound to make the sound appear to be coming from a particular location in the view port\&.

.PP
\fBNote\fP
.RS 4
Since different speaker setups and screen sizes can change the apparent location, this is a relative location only\&.
.RE
.PP
\fBWarning\fP
.RS 4
On Mac OS X this only works if the sound is in stereo, and the OS is version 10\&.7 (aka Lion) or later\&. It will fail silently on earlier versions or with mono or multichannel sounds; and the sound will play with center balance\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIoffsetX\fP the target X offset from the center of the main view port
.RE
.PP
\fBSee also\fP
.RS 4
\fBchangeOffsetX\fP 

.PP
\fBGraphicsManager\&.getMainPort\fP 
.RE
.PP

.SS "\fBSound\fP setPitch (number pitchOffset)"

.PP
set the pitch of a sound Raise or lower the pitch of a sound by up to an octave\&.

.PP
\fBParameters\fP
.RS 4
\fIpitchOffset\fP a value between -1\&.0 and 1\&.0, with -1\&.0 meaning down an octave, and +1\&.0 being up an octave\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBchangePitch\fP
.RE
.PP

.SS "\fBSound\fP setVolume (number inVolume)"

.PP
set the volume level for a sound Sets the volume level for this specific sound\&.

.PP
\fBParameters\fP
.RS 4
\fIinVolume\fP a value between 0\&.0 and 1\&.0, where 0 is silent and 1\&.0 is the max volume allowed by the master volume\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBgetVolume\fP 

.PP
\fBSoundManager\&.setVolume\fP 

.PP
\fBSoundManager\&.setMute\fP 
.RE
.PP

.SS "\fBSound\fP skip (int skipMilliseconds)"

.PP
skip ahead or back in a sound 
.PP
\fBParameters\fP
.RS 4
\fIskipMilliseconds\fP the amount of time to skip\&. Negative values are backwards\&. 
.RE
.PP

.SS "\fBSound\fP skipTo (uint timeMs)"

.PP
skipTo a particular time position in a sound 
.PP
\fBParameters\fP
.RS 4
\fItimeMs\fP the location within the sound to skip to 
.RE
.PP

.SS "start ()"

.PP
start playing a sound Starts the sound playing\&. Use \fBstart()\fP instead of \fBplay()\fP when you want to manipulate the sound as it is playing, since this call allows the use of \fBsetVolume()\fP, \fBskip()\fP, \fBskipTo()\fP, \fBpause()\fP, set/changePitch(), and set/changeXOffset() to actually affect playback\&.

.PP
\fBSee also\fP
.RS 4
\fBplay\fP 

.PP
\fBstop\fP 
.RE
.PP

.SS "stop ()"

.PP
stop a sound from playing This will free buffers and deallocate other memory, so use \fBpause()\fP if you want to restart the sound again\&.

.PP
\fBSee also\fP
.RS 4
\fBstart\fP 

.PP
\fBpause\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
