.TH "Animated" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animated \- something that can be automatically moved, spun or resized over time\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.PP
Inherited by \fBSprite\fP, and \fBSpriteLayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaccelerate\fP (number deltaSpeed, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBlinearTween\fP)"
.br
.RI "change the object's speed over time "
.ti -1c
.RI "\fBaccelerateTo\fP (number speed, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBlinearTween\fP)"
.br
.RI "change the object's speed to a particular value over time "
.ti -1c
.RI "\fBaddAnimationHelper\fP (\fBIAnimationHelper\fP helper)"
.br
.RI "setup a helper to handle custom animation "
.ti -1c
.RI "boolean \fBanimate\fP (int msElapsed)"
.br
.RI "animate based on the passage of time "
.ti -1c
.RI "\fBapplyForce\fP (\fBVector\fP force, int msDuration=\fBduration_Instantaneous\fP)"
.br
.RI "apply a force to the object over time "
.ti -1c
.RI "\fBapplyTorque\fP (number forceSpin, int msDuration=\fBduration_Instantaneous\fP)"
.br
.RI "apply torque to the object over time "
.ti -1c
.RI "\fBchangeCenter\fP (\fBOffset\fP offset, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "shift the center point of the object over time "
.ti -1c
.RI "\fBchangeCenterTo\fP (\fBOffset\fP offset, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "shift the center point of the object to a particular offset from true center over time "
.ti -1c
.RI "\fBclearAnimationHelpers\fP ()"
.br
.RI "remove all previously added animation helpers "
.ti -1c
.RI "\fBAnimated\fP \fBflipX\fP ()"
.br
.RI "flips the object horizontally, center offset is flipped too\&. Applied before other transformations\&. "
.ti -1c
.RI "\fBAnimated\fP \fBflipY\fP ()"
.br
.RI "flips the object vertically, center offset is flipped too\&. Applied before other transformations\&. "
.ti -1c
.RI "\fBRect\fP \fBgetBoundingBox\fP ()"
.br
.RI "get the rectangle that completely encloses the object "
.ti -1c
.RI "\fBOffset\fP \fBgetCenterOffset\fP ()"
.br
.RI "get the current offset of the center relative to the true center point "
.ti -1c
.RI "number \fBgetHeight\fP ()"
.br
.RI "get height of the object "
.ti -1c
.RI "\fBPoint\fP \fBgetLocation\fP ()"
.br
.RI "get the position of the object "
.ti -1c
.RI "number \fBgetMass\fP ()"
.br
.RI "get the mass of the object "
.ti -1c
.RI "number \fBgetMoveFriction\fP ()"
.br
.RI "get the amount of friction for movement "
.ti -1c
.RI "number \fBgetMovementDirectionInRadians\fP ()"
.br
.RI "get the direction the object is moving "
.ti -1c
.RI "\fBRotatedRect\fP \fBgetRotatedBounds\fP ()"
.br
.RI "get the bounds with rotation "
.ti -1c
.RI "number \fBgetRotation\fP ()"
.br
.RI "get how much the object is rotated "
.ti -1c
.RI "number \fBgetSizeFriction\fP ()"
.br
.RI "get the friction applied to size changes (growing or shrinking) "
.ti -1c
.RI "number \fBgetSpeed\fP ()"
.br
.RI "get how fast the object is moving in pixels/sec "
.ti -1c
.RI "number \fBgetSpin\fP ()"
.br
.RI "get how fast the object is spinning in radians per second "
.ti -1c
.RI "number \fBgetSpinFriction\fP ()"
.br
.RI "get the friction applied toward spinning "
.ti -1c
.RI "\fBVector\fP \fBgetVelocity\fP ()"
.br
.RI "get the vector that expresses magnitude and direction of the object's movement in pixels/sec "
.ti -1c
.RI "number \fBgetWidth\fP ()"
.br
.RI "get the width of the object "
.ti -1c
.RI "\fBgrow\fP (number factor, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "change size of the object by a factor over time "
.ti -1c
.RI "boolean \fBisFlippedX\fP ()"
.br
.RI "returns true if the object is flipped horizontally "
.ti -1c
.RI "boolean \fBisFlippedY\fP ()"
.br
.RI "returns true if the object is flipped vertically "
.ti -1c
.RI "\fBmove\fP (\fBOffset\fP delta, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "move the object by a certain amount over time "
.ti -1c
.RI "\fBmoveTo\fP (\fBPoint\fP where, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "move the object to a particular location over time "
.ti -1c
.RI "\fBremoveAnimationHelper\fP (\fBIAnimationHelper\fP helper)"
.br
.RI "remove a specific animation helper "
.ti -1c
.RI "\fBresize\fP (number deltaWidth, number deltaHeight, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "change the size of an object by a given amount over time "
.ti -1c
.RI "\fBresizeTo\fP (number width, number height, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "resize the object to a specific size over time "
.ti -1c
.RI "\fBrotate\fP (number radians, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "rotate the object by a specific amount over time "
.ti -1c
.RI "\fBrotateTo\fP (number radiansRotation, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "rotate the object to face a particular direction over time "
.ti -1c
.RI "\fBAnimated\fP \fBsetCenterOffset\fP (\fBOffset\fP inCenterOffset)"
.br
.RI "set the offset of the center point relative to the true center "
.ti -1c
.RI "\fBAnimated\fP \fBsetFlipX\fP (boolean inFlipX)"
.br
.RI "sets whether the object is flipped horizontally "
.ti -1c
.RI "\fBAnimated\fP \fBsetFlipY\fP (boolean inFlipY)"
.br
.RI "sets whether the object is flipped vertically "
.ti -1c
.RI "\fBAnimated\fP \fBsetFriction\fP (number frictionCoefficient)"
.br
.RI "set friction for movement, rotation and resizing all at once "
.ti -1c
.RI "\fBAnimated\fP \fBsetHeight\fP (number inHeight)"
.br
.RI "set the object's height "
.ti -1c
.RI "\fBAnimated\fP \fBsetLocation\fP (\fBPoint\fP inLocation)"
.br
.RI "place the object at a particular location "
.ti -1c
.RI "\fBAnimated\fP \fBsetMass\fP (number inMass)"
.br
.RI "set the object's mass, used when forces are applied "
.ti -1c
.RI "\fBAnimated\fP \fBsetMoveFriction\fP (number inMoveFriction)"
.br
.RI "set the object's friction for movement "
.ti -1c
.RI "\fBAnimated\fP \fBsetRotation\fP (number inRotation)"
.br
.RI "set the direction the object is facing in radians "
.ti -1c
.RI "\fBAnimated\fP \fBsetSize\fP (number width, number height)"
.br
.RI "set the size of the object "
.ti -1c
.RI "\fBAnimated\fP \fBsetSizeFriction\fP (number inSizeFriction)"
.br
.RI "set the friction applied for object resizing "
.ti -1c
.RI "\fBAnimated\fP \fBsetSpeed\fP (number inSpeed)"
.br
.RI "set the speed the object is moving in its current direction of motion "
.ti -1c
.RI "\fBAnimated\fP \fBsetSpin\fP (number inSpin)"
.br
.RI "set the rate at which the object is spinning, in radians/sec "
.ti -1c
.RI "\fBAnimated\fP \fBsetSpinFriction\fP (number inSpinFriction)"
.br
.RI "set the friction the object faces for spinning "
.ti -1c
.RI "\fBAnimated\fP \fBsetVelocity\fP (number deltaXPerSec, number deltaYPerSec)"
.br
.RI "set the speed and direction the object is moving "
.ti -1c
.RI "\fBAnimated\fP \fBsetVelocity\fP (\fBVector\fP deltaPerSec)"
.br
.RI "set the speed and direction the object is moving "
.ti -1c
.RI "\fBAnimated\fP \fBsetVelocityInRadians\fP (number speed, number direction)"
.br
.RI "set the speed and direction the object is moving "
.ti -1c
.RI "\fBAnimated\fP \fBsetWidth\fP (number inWidth)"
.br
.RI "set the width of the object "
.ti -1c
.RI "\fBstartGrowing\fP (number amountPerSecond)"
.br
.RI "set the growth rate of the object in pixels/sec "
.ti -1c
.RI "\fBstartStretching\fP (number widthPerSecond, number heightPerSecond)"
.br
.RI "set the growth rate of the object in pixels/sec, with varied rates for width and height "
.ti -1c
.RI "\fBstopAllForces\fP ()"
.br
.RI "remove all forces that were acting on the object (except friction) "
.ti -1c
.RI "\fBstopGrowing\fP ()"
.br
.RI "stop any size change "
.ti -1c
.RI "\fBstopMoving\fP ()"
.br
.RI "stop any movement the object was doing (except spinning) "
.ti -1c
.RI "\fBstopSpinning\fP ()"
.br
.RI "stop any spinning the object was doing "
.ti -1c
.RI "\fBstopStretching\fP ()"
.br
.RI "stop any stretching the object was doing "
.ti -1c
.RI "\fBstretch\fP (number widthFactor, number heightFactor, int msDuration=\fBduration_Instantaneous\fP, int easing=\fBeaseInOutQuad\fP)"
.br
.RI "change the dimensions of the object over time "
.ti -1c
.RI "\fBAnimated\fP \fBwait\fP (int msDuration)"
.br
.RI "wait before beginning the next animation call that operates over time "
.in -1c
.SH "Detailed Description"
.PP 
something that can be automatically moved, spun or resized over time\&. 


.PP
\fBNote\fP
.RS 4
\fBAPI Stability: 2 - Unstable\fP\&. The API is in the process of settling, but has not yet had sufficient real-world testing to be considered stable\&. Backwards-compatibility will be maintained if reasonable\&.
.RE
.PP
It has no drawing capabilities, so it is not intended to be used directly in most cases, but rather as a base class for items that can be animated\&. It could be used on a server to drive animation that is rendered on the client\&.

.PP
\fBSee also\fP
.RS 4
\fBSprite\fP 

.PP
\fBSpriteLayer\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "accelerate (number deltaSpeed, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBlinearTween\fP\fP)"

.PP
change the object's speed over time Change the speed of an object in the current direction of motion\&.

.PP
Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::linearTween\fP\&.
.SS "accelerateTo (number speed, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBlinearTween\fP\fP)"

.PP
change the object's speed to a particular value over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::linearTween\fP\&.
.SS "addAnimationHelper (\fBIAnimationHelper\fP helper)"

.PP
setup a helper to handle custom animation 
.PP
\fBSee also\fP
.RS 4
\fBIAnimationHelper\fP 
.RE
.PP

.SS "boolean animate (int msElapsed)"

.PP
animate based on the passage of time 
.PP
\fBReturns\fP
.RS 4
true if anything (position, size, movement, etc\&.\&.\&.) changed 
.RE
.PP

.SS "applyForce (\fBVector\fP force, int msDuration = \fR\fBduration_Instantaneous\fP\fP)"

.PP
apply a force to the object over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP\&.
.SS "applyTorque (number forceSpin, int msDuration = \fR\fBduration_Instantaneous\fP\fP)"

.PP
apply torque to the object over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP\&.
.SS "changeCenter (\fBOffset\fP offset, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
shift the center point of the object over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "changeCenterTo (\fBOffset\fP offset, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
shift the center point of the object to a particular offset from true center over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "clearAnimationHelpers ()"

.PP
remove all previously added animation helpers 
.PP
\fBSee also\fP
.RS 4
\fBaddAnimationHelper\fP 
.RE
.PP

.SS "\fBAnimated\fP flipX ()"

.PP
flips the object horizontally, center offset is flipped too\&. Applied before other transformations\&. 
.SS "\fBAnimated\fP flipY ()"

.PP
flips the object vertically, center offset is flipped too\&. Applied before other transformations\&. 
.SS "\fBRect\fP getBoundingBox ()"

.PP
get the rectangle that completely encloses the object 
.SS "\fBOffset\fP getCenterOffset ()"

.PP
get the current offset of the center relative to the true center point 
.SS "number getHeight ()"

.PP
get height of the object 
.SS "\fBPoint\fP getLocation ()"

.PP
get the position of the object 
.SS "number getMass ()"

.PP
get the mass of the object 
.SS "number getMoveFriction ()"

.PP
get the amount of friction for movement 
.SS "number getMovementDirectionInRadians ()"

.PP
get the direction the object is moving 
.SS "\fBRotatedRect\fP getRotatedBounds ()"

.PP
get the bounds with rotation 
.PP
\fBReturns\fP
.RS 4
\fBRotatedRect\fP 
.RE
.PP

.SS "number getRotation ()"

.PP
get how much the object is rotated 
.SS "number getSizeFriction ()"

.PP
get the friction applied to size changes (growing or shrinking) 
.SS "number getSpeed ()"

.PP
get how fast the object is moving in pixels/sec 
.SS "number getSpin ()"

.PP
get how fast the object is spinning in radians per second 
.SS "number getSpinFriction ()"

.PP
get the friction applied toward spinning 
.SS "\fBVector\fP getVelocity ()"

.PP
get the vector that expresses magnitude and direction of the object's movement in pixels/sec 
.SS "number getWidth ()"

.PP
get the width of the object 
.SS "grow (number factor, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
change size of the object by a factor over time If factor is greater than 1\&.0, the object will grow, if less than 1\&.0, the object will shrink\&.

.PP
Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "boolean isFlippedX ()"

.PP
returns true if the object is flipped horizontally 
.SS "boolean isFlippedY ()"

.PP
returns true if the object is flipped vertically 
.SS "move (\fBOffset\fP delta, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
move the object by a certain amount over time Honors delay given by \fBwait()\fP 
.PP
.nf
myAnimated\&.wait(10)\&.move(offset); // waits 10 ms before move

myAnimated\&.move(offset); // move immediately

.fi
.PP
 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "moveTo (\fBPoint\fP where, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
move the object to a particular location over time Honors delay given by \fBwait()\fP 
.PP
.nf
myAnimated\&.wait(10)\&.moveTo(p); // waits 10 ms before move

myAnimated\&.moveTo(p); // move immediately

.fi
.PP
 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "removeAnimationHelper (\fBIAnimationHelper\fP helper)"

.PP
remove a specific animation helper 
.PP
\fBSee also\fP
.RS 4
\fBaddAnimationHelper\fP 
.RE
.PP

.SS "resize (number deltaWidth, number deltaHeight, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
change the size of an object by a given amount over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "resizeTo (number width, number height, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
resize the object to a specific size over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "rotate (number radians, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
rotate the object by a specific amount over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "rotateTo (number radiansRotation, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
rotate the object to face a particular direction over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "\fBAnimated\fP setCenterOffset (\fBOffset\fP inCenterOffset)"

.PP
set the offset of the center point relative to the true center 
.SS "\fBAnimated\fP setFlipX (boolean inFlipX)"

.PP
sets whether the object is flipped horizontally 
.SS "\fBAnimated\fP setFlipY (boolean inFlipY)"

.PP
sets whether the object is flipped vertically 
.SS "\fBAnimated\fP setFriction (number frictionCoefficient)"

.PP
set friction for movement, rotation and resizing all at once 
.SS "\fBAnimated\fP setHeight (number inHeight)"

.PP
set the object's height 
.SS "\fBAnimated\fP setLocation (\fBPoint\fP inLocation)"

.PP
place the object at a particular location 
.SS "\fBAnimated\fP setMass (number inMass)"

.PP
set the object's mass, used when forces are applied 
.SS "\fBAnimated\fP setMoveFriction (number inMoveFriction)"

.PP
set the object's friction for movement 
.SS "\fBAnimated\fP setRotation (number inRotation)"

.PP
set the direction the object is facing in radians 
.SS "\fBAnimated\fP setSize (number width, number height)"

.PP
set the size of the object 
.SS "\fBAnimated\fP setSizeFriction (number inSizeFriction)"

.PP
set the friction applied for object resizing 
.SS "\fBAnimated\fP setSpeed (number inSpeed)"

.PP
set the speed the object is moving in its current direction of motion 
.SS "\fBAnimated\fP setSpin (number inSpin)"

.PP
set the rate at which the object is spinning, in radians/sec 
.SS "\fBAnimated\fP setSpinFriction (number inSpinFriction)"

.PP
set the friction the object faces for spinning 
.SS "\fBAnimated\fP setVelocity (number deltaXPerSec, number deltaYPerSec)"

.PP
set the speed and direction the object is moving 
.SS "\fBAnimated\fP setVelocity (\fBVector\fP deltaPerSec)"

.PP
set the speed and direction the object is moving 
.SS "\fBAnimated\fP setVelocityInRadians (number speed, number direction)"

.PP
set the speed and direction the object is moving 
.SS "\fBAnimated\fP setWidth (number inWidth)"

.PP
set the width of the object 
.SS "startGrowing (number amountPerSecond)"

.PP
set the growth rate of the object in pixels/sec 
.SS "startStretching (number widthPerSecond, number heightPerSecond)"

.PP
set the growth rate of the object in pixels/sec, with varied rates for width and height 
.SS "stopAllForces ()"

.PP
remove all forces that were acting on the object (except friction) 
.SS "stopGrowing ()"

.PP
stop any size change 
.PP
\fBSee also\fP
.RS 4
\fBstartGrowing\fP 
.RE
.PP

.SS "stopMoving ()"

.PP
stop any movement the object was doing (except spinning) 
.SS "stopSpinning ()"

.PP
stop any spinning the object was doing 
.SS "stopStretching ()"

.PP
stop any stretching the object was doing 
.SS "stretch (number widthFactor, number heightFactor, int msDuration = \fR\fBduration_Instantaneous\fP\fP, int easing = \fR\fBeaseInOutQuad\fP\fP)"

.PP
change the dimensions of the object over time Honors delay given by \fBwait()\fP 
.PP
References \fBpdg::duration_Instantaneous\fP, and \fBpdg::easeInOutQuad\fP\&.
.SS "\fBAnimated\fP wait (int msDuration)"

.PP
wait before beginning the next animation call that operates over time Only applies to the next call, and only applies to calls where a duration can be passed in

.PP
Works with: \fBmove()\fP, \fBmoveTo()\fP, \fBaccelerateTo()\fP, \fBresize()\fP, \fBstretch()\fP, \fBgrow()\fP, \fBresizeTo()\fP, \fBrotate()\fP, \fBrotateTo()\fP, \fBchangeCenter()\fP, \fBchangeCenterTo()\fP, \fBapplyForce()\fP, \fBapplyTorque()\fP, 

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
