.TH "Quad" 3 "Version v0.9.5" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quad \- 4 point polygon in 2D system  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuad\fP ()"
.br
.ti -1c
.RI "\fBQuad\fP (\fBPoint\fP p1, \fBPoint\fP p2, \fBPoint\fP p3, \fBPoint\fP p4)"
.br
.ti -1c
.RI "\fBQuad\fP (\fBPoint\fP[] p)"
.br
.ti -1c
.RI "\fBQuad\fP (\fBQuad\fP q)"
.br
.ti -1c
.RI "\fBQuad\fP (\fBRect\fP r)"
.br
.ti -1c
.RI "\fBQuad\fP (\fBRotatedRect\fP r)"
.br
.ti -1c
.RI "\fBPoint\fP \fBcenterPoint\fP ()"
.br
.RI "return the calculated centerpoint of the quad "
.ti -1c
.RI "boolean \fBcontains\fP (\fBPoint\fP p)"
.br
.RI "returns true if the point is contained within this quad "
.ti -1c
.RI "boolean \fBequals\fP (\fBQuad\fP q2)"
.br
.RI "return true if this quad is equal to the given one "
.ti -1c
.RI "\fBRect\fP \fBgetBounds\fP ()"
.br
.RI "return a rectangle that bounds the quad "
.ti -1c
.RI "\fBmoveDown\fP (number delta)"
.br
.RI "move the quad down by some amount "
.ti -1c
.RI "\fBmoveLeft\fP (number delta)"
.br
.RI "move the quad to the left by some amount "
.ti -1c
.RI "\fBmoveRight\fP (number delta)"
.br
.RI "move the quad to the right by some amount "
.ti -1c
.RI "\fBmoveUp\fP (number delta)"
.br
.RI "move the quad up by some amount "
.ti -1c
.RI "boolean \fBnotEquals\fP (\fBQuad\fP q2)"
.br
.RI "return true if this quad is not equal to the given one "
.ti -1c
.RI "\fBrotate\fP (number rotationRadians, \fBOffset\fP centerPtOffset=\fBPoint\fP(0, 0))"
.br
.RI "rotate(n): rotate the quad by a rotation in radians (around the calculated center point of the quad); rotate(n, [Offset] o): rotate the quad by a rotation in radians around an offset center point "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP[] \fBpoints\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
4 point polygon in 2D system 

\fBQuad\fP is a class that provides support for dealing with 4 point ploygons in 2 dimensional space The PDG coordinate space starts with the top left corner of the drawing port at Point(0,0) and the bottom left corner at Point( width, height ); 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBQuad\fP ()"

.PP
Referenced by \fBQuad()\fP, \fBequals()\fP, and \fBnotEquals()\fP\&.
.SS "\fBQuad\fP (\fBQuad\fP q)"

.PP
References \fBQuad()\fP\&.
.SS "\fBQuad\fP (\fBRect\fP r)"

.SS "\fBQuad\fP (\fBRotatedRect\fP r)"

.SS "\fBQuad\fP (\fBPoint\fP p1, \fBPoint\fP p2, \fBPoint\fP p3, \fBPoint\fP p4)"

.SS "\fBQuad\fP (\fBPoint\fP[] p)"

.SH "Member Function Documentation"
.PP 
.SS "\fBPoint\fP centerPoint ()"

.PP
return the calculated centerpoint of the quad 
.SS "boolean contains (\fBPoint\fP p)"

.PP
returns true if the point is contained within this quad 
.SS "boolean equals (\fBQuad\fP q2)"

.PP
return true if this quad is equal to the given one 
.PP
References \fBQuad()\fP\&.
.SS "\fBRect\fP getBounds ()"

.PP
return a rectangle that bounds the quad 
.SS "moveDown (number delta)"

.PP
move the quad down by some amount 
.SS "moveLeft (number delta)"

.PP
move the quad to the left by some amount 
.SS "moveRight (number delta)"

.PP
move the quad to the right by some amount 
.SS "moveUp (number delta)"

.PP
move the quad up by some amount 
.SS "boolean notEquals (\fBQuad\fP q2)"

.PP
return true if this quad is not equal to the given one 
.PP
References \fBQuad()\fP\&.
.SS "rotate (number rotationRadians, \fBOffset\fP centerPtOffset = \fR\fBPoint\fP(0,0)\fP)"

.PP
rotate(n): rotate the quad by a rotation in radians (around the calculated center point of the quad); rotate(n, [Offset] o): rotate the quad by a rotation in radians around an offset center point 
.SH "Member Data Documentation"
.PP 
.SS "\fBPoint\fP [] points"


.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
