.TH "SpriteLayer" 3 "Version v1.2.0" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteLayer \- creates and tracks collections of sprites  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.PP
Inherits \fBEventEmitter\fP, and \fBISerializable\fP\&.
.PP
Inherited by \fBTileLayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddParticle\fP (\fBParticle\fP value)"
.br
.RI "Add a live detached particle\&. "
.ti -1c
.RI "\fBaddSprite\fP (\fBSprite\fP newSprite)"
.br
.RI "Add a \fBSprite\fP and its mounted descendants to this layer\&. "
.ti -1c
.RI "\fBapplyCharacterMapToAll\fP (string mapName)"
.br
.RI "Applies a character map to all Spriter sprites in this layer\&. "
.ti -1c
.RI "\fBParticle\fP \fBcreateParticle\fP ()"
.br
.RI "Create a layer-owned particle\&. "
.ti -1c
.RI "\fBParticleEmitter\fP \fBcreateParticleEmitter\fP ()"
.br
.RI "Create a layer-owned point emitter\&. "
.ti -1c
.RI "\fBSprite\fP \fBcreateSprite\fP ()"
.br
.RI "create a sprite that belongs to this layer "
.ti -1c
.RI "\fBSprite\fP \fBcreateSpriteFromSpriterEntity\fP (string inEntityName)"
.br
.RI "create a sprite from SCML data that was previously loaded "
.ti -1c
.RI "\fBSprite\fP \fBcreateSpriteFromSpriterFile\fP (string inFileName, string inEntityName=null)"
.br
.RI "create a single sprite from SCML data "
.ti -1c
.RI "\fBdeserialize\fP (\fBDeserializer\fP deserializer)"
.br
.RI "Restore Layer state or apply an incremental update\&. "
.ti -1c
.RI "\fBdisableCollisions\fP ()"
.br
.RI "stop checking for collisions between objects in this layer "
.ti -1c
.RI "\fBdisableCollisionsWithLayer\fP (\fBSpriteLayer\fP otherLayer)"
.br
.RI "remove layer from list of layers that do collisions between layers "
.ti -1c
.RI "\fBenableCollisions\fP ()"
.br
.RI "allow collision checking for sprites in this layer "
.ti -1c
.RI "\fBenableCollisionsWithLayer\fP (\fBSpriteLayer\fP otherLayer)"
.br
.RI "start collision checking with sprites in another layer "
.ti -1c
.RI "\fBenableSpriterEvents\fP (boolean enable=true)"
.br
.RI "Enables or disables Spriter animation events for this layer\&. "
.ti -1c
.RI "\fBSpriteLayer\fP \fBfadeIn\fP (number durationSeconds, int easing=\fBlinearTween\fP)"
.br
.RI "fade entire layer to full opacity over time "
.ti -1c
.RI "\fBSpriteLayer\fP \fBfadeOut\fP (number durationSeconds, int easing=\fBlinearTween\fP)"
.br
.RI "fade out the entire layer to full transparency over time "
.ti -1c
.RI "\fBSprite\fP \fBfindSprite\fP (int id)"
.br
.RI "find a sprite in this layer by user assigned id "
.ti -1c
.RI "\fBCamera\fP \fBgetCamera\fP ()"
.br
.ti -1c
.RI "\fBCamera\fP \fBgetEffectiveCamera\fP ()"
.br
.ti -1c
.RI "uint \fBgetMaxParticles\fP ()"
.br
.RI "Read the layer particle budget\&. "
.ti -1c
.RI "number \fBgetMyClassTag\fP ()"
.br
.RI "returns class tag for \fBSpriteLayer\fP, used for serialization "
.ti -1c
.RI "\fBParticle\fP \fBgetNthParticle\fP (uint value)"
.br
.RI "Read a particle by creation order\&. "
.ti -1c
.RI "\fBSprite\fP \fBgetNthSprite\fP (int index)"
.br
.RI "get a sprite by z-order "
.ti -1c
.RI "uint \fBgetParticleCount\fP ()"
.br
.RI "Count live layer particles\&. "
.ti -1c
.RI "number \fBgetParticleTrailCount\fP ()"
.br
.RI "Count live unexpired histories and retained fading tails\&. "
.ti -1c
.RI "uint \fBgetQueryBits\fP ()"
.br
.ti -1c
.RI "uint \fBgetSerializedSize\fP (\fBSerializer\fP serializer)"
.br
.RI "Measure selected Layer state and shared \fBSprite\fP resources\&. "
.ti -1c
.RI "\fBCpSpace\fP \fBgetSpace\fP ()"
.br
.RI "get the Chipmunk Physics \fBCpSpace\fP for the layer "
.ti -1c
.RI "\fBPort\fP \fBgetSpritePort\fP ()"
.br
.RI "get the \fBPort\fP the layer renders into "
.ti -1c
.RI "int \fBgetSpriteZOrder\fP (\fBSprite\fP sprite)"
.br
.RI "get the z-order of a sprite in this layer "
.ti -1c
.RI "\fBRect\fP \fBgetWorldBounds\fP ()"
.br
.ti -1c
.RI "int \fBgetZOrder\fP ()"
.br
.RI "get the z-order of this layer compared to all others "
.ti -1c
.RI "boolean \fBhasSprite\fP (\fBSprite\fP sprite)"
.br
.RI "see if a particular sprite belongs to this layer "
.ti -1c
.RI "\fBhide\fP ()"
.br
.RI "stop rendering this layer\&. "
.ti -1c
.RI "boolean \fBisHidden\fP ()"
.br
.RI "true if layer is hidden, false if it is visible "
.ti -1c
.RI "boolean \fBisSpriteBehind\fP (\fBSprite\fP sprite, \fBSprite\fP otherSprite)"
.br
.RI "returns true if sprite will be drawn before otherSprite "
.ti -1c
.RI "\fBOffset\fP \fBlayerToPortOffset\fP (\fBOffset\fP o)"
.br
.RI "adjust the offset to account for the effective camera "
.ti -1c
.RI "\fBPoint\fP \fBlayerToPortPoint\fP (\fBPoint\fP p)"
.br
.RI "translate the point to account for the effective camera "
.ti -1c
.RI "\fBQuad\fP \fBlayerToPortQuad\fP (\fBQuad\fP q)"
.br
.RI "translate the \fBQuad\fP to account for the effective camera "
.ti -1c
.RI "\fBRotatedRect\fP \fBlayerToPortRect\fP (\fBRect\fP r)"
.br
.RI "translate the rectangle (or \fBRotatedRect\fP) to account for the effective camera "
.ti -1c
.RI "\fBVector\fP \fBlayerToPortVector\fP (\fBVector\fP v)"
.br
.RI "translate the point to account for the effective camera "
.ti -1c
.RI "\fBmoveBehind\fP (\fBSpriteLayer\fP layer)"
.br
.RI "change the z-order of this layer to draw it before the given layer "
.ti -1c
.RI "\fBmoveInFrontOf\fP (\fBSpriteLayer\fP layer)"
.br
.RI "change the z-order of this layer to draw it after the given layer "
.ti -1c
.RI "\fBmoveToBack\fP ()"
.br
.RI "move this layer behind all other layers "
.ti -1c
.RI "\fBmoveToFront\fP ()"
.br
.RI "move this layer in front of all other layers "
.ti -1c
.RI "\fBIEventHandler\fP \fBon\fP (int eventCode, function func)"
.br
.RI "set event handler for all different sprite and spritelayer events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationComplete\fP (function func)"
.br
.RI "set event handler for layer animation complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationEnd\fP (function func)"
.br
.RI "set event handler for sprite animation end events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationLoop\fP (function func)"
.br
.RI "set event handler for sprite animation loop events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationStart\fP (function func)"
.br
.RI "set event handler for layer animation complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonCollideSprite\fP (function func)"
.br
.RI "set event handler for sprite-to-sprite collision events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonCollideWall\fP (function func)"
.br
.RI "set event handler for sprite-wall collision events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonDrawPortComplete\fP (function func)"
.br
.RI "set event handler for rendering complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonErasePort\fP (function func)"
.br
.RI "set event handler for rendering starting events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonExitLayer\fP (function func)"
.br
.RI "set event handler for sprite out of bounds event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonFadeComplete\fP (function func)"
.br
.RI "set event handler for sprite fade event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonFadeInComplete\fP (function func)"
.br
.RI "set event handler for sprite fade in event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonFadeOutComplete\fP (function func)"
.br
.RI "set event handler for sprite fade out event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonLayerFadeInComplete\fP (function func)"
.br
.RI "set event handler for layer fade in event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonLayerFadeOutComplete\fP (function func)"
.br
.RI "set event handler for layer fade out event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseClick\fP (function func)"
.br
.RI "set event handler for tap or mouse click in a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseDown\fP (function func)"
.br
.RI "set event handler for finger down or mouse down in a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseEnter\fP (function func)"
.br
.RI "set event handler for mouse pointer over a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseLeave\fP (function func)"
.br
.RI "set event handler for mouse pointer leaving a sprite it was over "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseUp\fP (function func)"
.br
.RI "set event handler for finger up or mouse up in a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonOffscreen\fP (function func)"
.br
.RI "set event handler for sprite offscreen event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonOnscreen\fP (function func)"
.br
.RI "set event handler for sprite onscreen event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPostAnimateLayer\fP (function func)"
.br
.RI "set event handler for layer animation finished events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPostDrawLayer\fP (function func)"
.br
.RI "set event handler for layer rendering complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPreAnimateLayer\fP (function func)"
.br
.RI "set event handler for layer animation start events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPreDrawLayer\fP (function func)"
.br
.RI "set event handler for layer rendering start events "
.ti -1c
.RI "\fBOffset\fP \fBportToLayerOffset\fP (\fBOffset\fP o)"
.br
.RI "adjust the offset to account for the effective camera "
.ti -1c
.RI "\fBPoint\fP \fBportToLayerPoint\fP (\fBPoint\fP p)"
.br
.RI "adjust the point to account for the effective camera "
.ti -1c
.RI "\fBQuad\fP \fBportToLayerQuad\fP (\fBQuad\fP q)"
.br
.RI "adjust the quad to account for the effective camera "
.ti -1c
.RI "\fBRotatedRect\fP \fBportToLayerRect\fP (\fBRect\fP r)"
.br
.RI "adjust the rectangle to account for the effective camera "
.ti -1c
.RI "\fBVector\fP \fBportToLayerVector\fP (\fBVector\fP v)"
.br
.RI "adjust the vector to account for the effective camera "
.ti -1c
.RI "\fBremoveAllParticleEmitters\fP ()"
.br
.RI "Remove all standalone emitters\&. "
.ti -1c
.RI "\fBremoveAllParticles\fP ()"
.br
.RI "Detach every particle\&. "
.ti -1c
.RI "\fBremoveAllSprites\fP ()"
.br
.RI "remove all sprites in the layer "
.ti -1c
.RI "\fBremoveCharacterMapFromAll\fP (string mapName)"
.br
.RI "Removes a character map from all Spriter sprites in this layer\&. "
.ti -1c
.RI "\fBremoveParticle\fP (\fBParticle\fP value)"
.br
.RI "Detach a particle from this layer\&. "
.ti -1c
.RI "\fBremoveParticleEmitter\fP (\fBParticleEmitter\fP value)"
.br
.RI "Stop and remove a standalone emitter\&. "
.ti -1c
.RI "\fBremoveSprite\fP (\fBSprite\fP oldSprite)"
.br
.RI "Remove a \fBSprite\fP and its mounted descendants from this layer\&. "
.ti -1c
.RI "\fBserialize\fP (\fBSerializer\fP serializer)"
.br
.RI "Save selected Layer state and its ordered sprites\&. "
.ti -1c
.RI "\fBsetCamera\fP (\fBCamera\fP camera=null)"
.br
.ti -1c
.RI "\fBsetCameraParallax\fP (number movementRatio=1, number zoomRatio=1)"
.br
.RI "Adjust camera scrolling and zoom for this layer\&. "
.ti -1c
.RI "\fBsetDamping\fP (number damping)"
.br
.RI "set the overall resistance to motion over time (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "\fBsetGravity\fP (number gravity)"
.br
.RI "set the force of gravity pulling everything downward (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "\fBSpriteLayer\fP \fBsetMaxParticles\fP (uint value)"
.br
.RI "Set the shared particle budget\&. "
.ti -1c
.RI "\fBsetQueryBits\fP (uint bits)"
.br
.ti -1c
.RI "\fBSpriteLayer\fP \fBsetSerializationFlags\fP (uint flags)"
.br
.RI "set the mode for sprite layer serialization "
.ti -1c
.RI "\fBsetSpritePort\fP (\fBPort\fP port)"
.br
.RI "set the port this layer is rendered into "
.ti -1c
.RI "\fBsetStaticLayer\fP (boolean isStatic=true)"
.br
.RI "make objects in this layer not subject to physics forces (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "\fBsetUseChipmunkPhysics\fP (boolean useIt=true)"
.br
.RI "enable or disable use of Chipmunk Physics for a particular layer "
.ti -1c
.RI "\fBsetWorldBounds\fP (\fBRect\fP bounds)"
.br
.RI "Set world bounds for sprite boundary checks\&. "
.ti -1c
.RI "\fBshow\fP ()"
.br
.RI "start rendering this layer if it was previously hidden "
.ti -1c
.RI "\fBstartAnimations\fP ()"
.br
.RI "restart doing animation calculations for this layer if they were stopped "
.ti -1c
.RI "\fBstopAnimations\fP ()"
.br
.RI "stop doing animation calculations for this layer "
.in -1c

Public Member Functions inherited from \fBEventEmitter\fP
.in +1c
.ti -1c
.RI "\fBEventEmitter\fP ()"
.br
.ti -1c
.RI "\fBaddHandler\fP (\fBIEventHandler\fP inHandler, int inEventType=\fBall_events\fP)"
.br
.RI "add a new handler for some event type, or for all events if no type specified\&. "
.ti -1c
.RI "\fBblockEvent\fP (int inEventType)"
.br
.RI "temporarily ignore all events of a particular type\&. "
.ti -1c
.RI "\fBclear\fP ()"
.br
.RI "remove all handlers "
.ti -1c
.RI "\fBremoveHandler\fP (\fBIEventHandler\fP inHandler, int inEventType=\fBall_events\fP)"
.br
.RI "remove a handler for some event type, or for all events (see note) if no type specified\&. "
.ti -1c
.RI "\fBunblockEvent\fP (int inEventType)"
.br
.RI "stop ignoring events of a particular type "
.in -1c

Public Member Functions inherited from \fBISerializable\fP
.in +1c
.ti -1c
.RI "\fBISerializable\fP (function getSerializedSize, function serialize, function deserialize, function getMyClassTag)"
.br
.in -1c
.SS "Related Symbols"
(Note that these are not member symbols\&.) 
.in +1c
.ti -1c
.RI "\fBcleanupLayer\fP"
.br
.RI "free all the memory used by a \fBpdg\&.SpriteLayer\fP or \fBpdg\&.TileLayer\fP "
.ti -1c
.RI "\fBcreateSpriteLayer\fP (\fBPort\fP port=nullptr)"
.br
.RI "create a new \fBSpriteLayer\fP attached to a particular port "
.ti -1c
.RI "\fBcreateSpriteLayerFromSpriterFile\fP (string layerSpriterFilename, boolean addSprites=true, \fBPort\fP port=null)"
.br
.RI "create a new \fBSpriteLayer\fP from an Spriter SCML file "
.in -1c

Related Symbols inherited from \fBISerializable\fP
.in +1c
.ti -1c
.RI "\fBregisterSerializableClass\fP"
.br
.RI "register a particular class as implementing \fBISerializable\fP interface "
.in -1c
.SH "Detailed Description"
.PP 
creates and tracks collections of sprites 


.PP
\fBNote\fP
.RS 4
\fBAPI Stability: 2 — Evolving\fP\&. This API is implemented and supported, but its contract is still settling\&. Compatibility is preserved where practical; breaking changes are documented in release notes\&. See \fBAPI stability\fP\&.
.RE
.PP
Layers own contents, visibility, world bounds and simulation controls\&. They do not inherit \fBAnimated\fP\&. Attach an \fBAnimated\fP \fBCamera\fP with \fBsetCamera()\fP, or inherit the current sprite \fBPort\fP camera by leaving the explicit attachment null\&. Multiple layers can share a camera; see \fBCamera\fP for coordinate and animation semantics\&.
.SS "Events"
Things that happen to a sprite that might require intervention, such as collisions, completed animations, going offscreen, etc\&.\&.\&. will generate events\&. Events generated by sprites first go to any handlers attached directly to the \fBSprite\fP, then propagate up to the \fBSpriteLayer\fP and then the \fBEventManager\fP until they are handled\&.

.PP
Things that happen to a sprite layer go to the layer's handlers first, then propagate to the \fBEventManager\fP's handlers if they weren't handled by the layer\&. 
.SH "Member Function Documentation"
.PP 
.SS "addParticle (\fBParticle\fP value)"

.PP
Add a live detached particle\&. Rejects expired particles, particles owned by another layer and a full budget\&. Adding a particle already in this layer is harmless\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Object to add/remove; JavaScript parameter is named value\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "addSprite (\fBSprite\fP newSprite)"

.PP
Add a \fBSprite\fP and its mounted descendants to this layer\&. Transfers the group from its previous layer when necessary, preserving its layer-coordinate transforms and mounting relationships\&. Inserts the host first, followed by descendants, in front of existing sprites\&. A \fBSprite\fP already in this layer is unchanged\&. Use \fBSprite::moveBehind()\fP or \fBSprite::moveInFrontOf()\fP to change one member's draw order\&.

.PP
\fBParameters\fP
.RS 4
\fInewSprite\fP The \fBSprite\fP to add\&. An attached child must first be detached with \fBPart::detachSprite()\fP; otherwise the call throws without changing either layer\&.
.RE
.PP
\fBNote\fP
.RS 4
Transfer must occur outside animation modifiers and locked physics callbacks\&. Root constraints and physical animation rigs are disconnected on removal; ordinary Parts, artwork and modifiers remain associated\&. Imported Spriter sprites retain their shared model and artwork independently of the source layer\&. Destroying that layer preserves transferred or retained sprites, including their playback, bone bindings and modifiers\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBremoveSprite()\fP, \fBPart::attachSprite()\fP 
.RE
.PP

.SS "applyCharacterMapToAll (string mapName)"

.PP
Applies a character map to all Spriter sprites in this layer\&. 
.SS "\fBParticle\fP createParticle ()"

.PP
Create a layer-owned particle\&. Age starts at zero\&. Native references are borrowed\&. 
.PP
\fBReturns\fP
.RS 4
\fBParticle\fP, or null when the budget is full\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "\fBParticleEmitter\fP createParticleEmitter ()"

.PP
Create a layer-owned point emitter\&. Initially stopped, at local origin with facing zero\&. Native references are borrowed\&. 
.PP
\fBReturns\fP
.RS 4
The new emitter\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "\fBSprite\fP createSprite ()"

.PP
create a sprite that belongs to this layer 
.SS "\fBSprite\fP createSpriteFromSpriterEntity (string inEntityName)"

.PP
create a sprite from SCML data that was previously loaded \fBcreateSpriteLayerFromSpriterFile()\fP and \fBcreateSpriteFromSpriterFile()\fP both cache their file data for this purpose 
.SS "\fBSprite\fP createSpriteFromSpriterFile (string inFileName, string inEntityName = \fRnull\fP)"

.PP
create a single sprite from SCML data 
.SS "deserialize (\fBDeserializer\fP deserializer)"

.PP
Restore Layer state or apply an incremental update\&. 
.PP
\fBParameters\fP
.RS 4
\fIdeserializer\fP Reader positioned at a record written by \fBSpriteLayer::serialize()\fP\&. An initial record restores sprites, independent/authored Parts, shared artwork, order, transforms and active state into an empty or populated Layer\&. Loading validates records and resources before replacing the existing collection, including mount endpoint, cycle and duplicate-owner checks\&. Old sprites retained by script are detached; new bodies join the destination solver after validation\&. Tween channels are rebound to the destination Layer, including zoom\&.
.RE
.PP
The Layer keeps its \fBPort\fP, application event handlers and caller-selected serialization flags\&. Its saved identities and state replace their previous values\&. A record/resource validation error leaves the existing Layer collection and state intact; discard the failed reader\&. Incremental updates modify existing sprites and require matching identities/order\&. They are not staged scene replacement\&.

.PP
\fBNote\fP
.RS 4
Call outside animation modifiers and a physics solve\&. The shared physical world is not recreated; configure its gravity and damping in the application\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBSpriteLayer::serialize()\fP, \fBSpriteLayer::setSerializationFlags()\fP 
.RE
.PP

.SS "disableCollisions ()"

.PP
stop checking for collisions between objects in this layer 
.SS "disableCollisionsWithLayer (\fBSpriteLayer\fP otherLayer)"

.PP
remove layer from list of layers that do collisions between layers 
.PP
\fBNote\fP
.RS 4
Layers that have Chipmunk Physics enabled handle layer-to-layer collisions differently, they collide automatically even between layers unless you put them in collide groups\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBenableCollisionsWithLayer\fP 

.PP
Sprite\&.setCollideGroup() 

.PP
\fBSprite\&.setupCollider()\fP 

.PP
Sprite\&.setCollisionHelper() 
.RE
.PP

.SS "enableCollisions ()"

.PP
allow collision checking for sprites in this layer 
.SS "enableCollisionsWithLayer (\fBSpriteLayer\fP otherLayer)"

.PP
start collision checking with sprites in another layer 
.PP
\fBNote\fP
.RS 4
Layers that have Chipmunk Physics enabled handle layer-to-layer collisions differently, they collide automatically even between layers unless you put them in collide groups\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBdisableCollisionsWithLayer\fP 
.RE
.PP

.SS "enableSpriterEvents (boolean enable = \fRtrue\fP)"

.PP
Enables or disables Spriter animation events for this layer\&. 
.SS "\fBSpriteLayer\fP fadeIn (number durationSeconds, int easing = \fR\fBlinearTween\fP\fP)"

.PP
fade entire layer to full opacity over time 
.PP
\fBNote\fP
.RS 4
Parameter \fReasing:\fP \fBEasingFunction\fP\&.
.RE
.PP
Generates an \fBeventType_SpriteLayer\fP \fBaction_LayerFadeInComplete\fP event when done\&.

.PP
\fBWarning\fP
.RS 4
does not honor delay specified by wait() 
.RE
.PP

.PP
References \fBpdg::linearTween\fP\&.
.SS "\fBSpriteLayer\fP fadeOut (number durationSeconds, int easing = \fR\fBlinearTween\fP\fP)"

.PP
fade out the entire layer to full transparency over time 
.PP
\fBNote\fP
.RS 4
Parameter \fReasing:\fP \fBEasingFunction\fP\&.
.RE
.PP
Generates an \fBeventType_SpriteLayer\fP \fBaction_LayerFadeOutComplete\fP event when done\&.

.PP
\fBWarning\fP
.RS 4
does not honor delay specified by wait() 
.RE
.PP

.PP
References \fBpdg::linearTween\fP\&.
.SS "\fBSprite\fP findSprite (int id)"

.PP
find a sprite in this layer by user assigned id 
.SS "\fBCamera\fP getCamera ()"

.SS "\fBCamera\fP getEffectiveCamera ()"

.SS "uint getMaxParticles ()"

.PP
Read the layer particle budget\&. 
.PP
\fBReturns\fP
.RS 4
Maximum permitted count; default 10000\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "number getMyClassTag ()"

.PP
returns class tag for \fBSpriteLayer\fP, used for serialization 
.SS "\fBParticle\fP getNthParticle (uint value)"

.PP
Read a particle by creation order\&. Indices may change after removals; retain the particle rather than storing its index\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Zero-based index; JavaScript parameter is named value\&. 
.RE
.PP
\fBReturns\fP
.RS 4
\fBParticle\fP, or null when out of range\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "\fBSprite\fP getNthSprite (int index)"

.PP
get a sprite by z-order index 0 is furthest back 
.SS "uint getParticleCount ()"

.PP
Count live layer particles\&. 
.PP
\fBReturns\fP
.RS 4
Current count, excluding templates\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "number getParticleTrailCount ()"

.PP
Count live unexpired histories and retained fading tails\&. 
.PP
\fBReturns\fP
.RS 4
Trail count, including one-point histories not yet visible\&. 
.RE
.PP

.SS "uint getQueryBits ()"

.SS "uint getSerializedSize (\fBSerializer\fP serializer)"

.PP
Measure selected Layer state and shared \fBSprite\fP resources\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializer\fP Writer used for resource policy and shared-object size tracking\&. 
.RE
.PP
\fBReturns\fP
.RS 4
Record size in bytes, excluding the stream header and enclosing object tag/length\&. Uses this Layer's serialization flags\&. Initial records validate supported state and resource availability during sizing\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBSpriteLayer::serialize()\fP, \fBSpriteLayer::setSerializationFlags()\fP 
.RE
.PP

.SS "\fBCpSpace\fP getSpace ()"

.PP
get the Chipmunk Physics \fBCpSpace\fP for the layer Layers generally share the same Chipmunk space so the sprites within them can collide

.PP
\fBSee also\fP
.RS 4
\fBCpSpace\fP 
.RE
.PP

.SS "\fBPort\fP getSpritePort ()"

.PP
get the \fBPort\fP the layer renders into 
.SS "int getSpriteZOrder (\fBSprite\fP sprite)"

.PP
get the z-order of a sprite in this layer 0 means furthest back (drawn first)

.PP
\fBSee also\fP
.RS 4
\fBgetNthSprite\fP 
.RE
.PP

.SS "\fBRect\fP getWorldBounds ()"

.SS "int getZOrder ()"

.PP
get the z-order of this layer compared to all others 0 means furthest back (drawn first) 
.SS "boolean hasSprite (\fBSprite\fP sprite)"

.PP
see if a particular sprite belongs to this layer 
.SS "hide ()"

.PP
stop rendering this layer\&. Layer continues doing animation calculations and generating events from animation\&. 
.SS "boolean isHidden ()"

.PP
true if layer is hidden, false if it is visible 
.SS "boolean isSpriteBehind (\fBSprite\fP sprite, \fBSprite\fP otherSprite)"

.PP
returns true if sprite will be drawn before otherSprite 
.SS "\fBOffset\fP layerToPortOffset (\fBOffset\fP o)"

.PP
adjust the offset to account for the effective camera Since an offset is relative rather than fixed in coordinate space, this means only rotating it around 0,0 to match the effective camera rotation, and changing the offset length by the camera zoom\&. The camera translation is not factored in\&.

.PP
\fBParameters\fP
.RS 4
\fIo\fP \fBOffset\fP in layer coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBOffset\fP in port coordinates 
.RE
.PP

.SS "\fBPoint\fP layerToPortPoint (\fBPoint\fP p)"

.PP
translate the point to account for the effective camera Adjusts for the effective camera view and port anchor to get drawing coordinates\&.

.PP
\fBParameters\fP
.RS 4
\fIp\fP \fBPoint\fP in layer coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBPoint\fP in port coordinates 
.RE
.PP

.SS "\fBQuad\fP layerToPortQuad (\fBQuad\fP q)"

.PP
translate the \fBQuad\fP to account for the effective camera Adjusts for the effective camera view and port anchor to get drawing coordinates\&.

.PP
\fBParameters\fP
.RS 4
\fIq\fP \fBQuad\fP in layer coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBQuad\fP in port coordinates 
.RE
.PP

.SS "\fBRotatedRect\fP layerToPortRect (\fBRect\fP r)"

.PP
translate the rectangle (or \fBRotatedRect\fP) to account for the effective camera Adjusts for the effective camera view and port anchor to get drawing coordinates\&.

.PP
Nonuniform scale or reflection returns enclosing bounds\&. For exact transformed corners, use the \fBQuad\fP conversion\&.

.PP
\fBParameters\fP
.RS 4
\fIr\fP \fBRect\fP or \fBRotatedRect\fP in layer coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBRotatedRect\fP in port coordinates 
.RE
.PP

.SS "\fBVector\fP layerToPortVector (\fBVector\fP v)"

.PP
translate the point to account for the effective camera Adjusts for the effective camera rotation, zoom and scale to get drawing coordinates\&. As with offset, vectors are not fixed in space, so translation is not considered\&.

.PP
\fBParameters\fP
.RS 4
\fIv\fP \fBVector\fP in layer coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBVector\fP in port coordinates 
.RE
.PP

.SS "moveBehind (\fBSpriteLayer\fP layer)"

.PP
change the z-order of this layer to draw it before the given layer 
.SS "moveInFrontOf (\fBSpriteLayer\fP layer)"

.PP
change the z-order of this layer to draw it after the given layer 
.SS "moveToBack ()"

.PP
move this layer behind all other layers 
.SS "moveToFront ()"

.PP
move this layer in front of all other layers 
.SS "\fBIEventHandler\fP on (int eventCode, function func)"

.PP
set event handler for all different sprite and spritelayer events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBEventCallback\fP\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onAnimationComplete (function func)"

.PP
set event handler for layer animation complete events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens when all sprite layers are done calculating animation changes

.PP
\fBSee also\fP
.RS 4
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onAnimationEnd (function func)"

.PP
set event handler for sprite animation end events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite finishes a particular frame animation sequence

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onAnimationLoop (function func)"

.PP
set event handler for sprite animation loop events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite finishes a particular frame animation sequence and is restarting it because it is set to loop

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onAnimationStart (function func)"

.PP
set event handler for layer animation complete events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens just before the sprite system starts calculating animation changes for the layers

.PP
\fBSee also\fP
.RS 4
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onCollideSprite (function func)"

.PP
set event handler for sprite-to-sprite collision events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteCollisionEventCallback\fP\&.
.RE
.PP
These happen when a sprite collides with another sprite\&. Collisions must be enabled for the sprite and the layer\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteCollideEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onCollideWall (function func)"

.PP
set event handler for sprite-wall collision events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteCollisionEventCallback\fP\&.
.RE
.PP
These happen when a sprite collides with the boundaries of the layer, but only if setWantsCollideWallEvents(true) is called for that sprite\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteCollideEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onDrawPortComplete (function func)"

.PP
set event handler for rendering complete events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens each frame when all layers have finished rendering that frame

.PP
\fBSee also\fP
.RS 4
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onErasePort (function func)"

.PP
set event handler for rendering starting events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens each frame before any layers start rendering for that frame

.PP
\fBSee also\fP
.RS 4
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onExitLayer (function func)"

.PP
set event handler for sprite out of bounds event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite moves completely outside the boundaries of the layer, but only if setWantsCollideWallEvents(true) is called for that sprite\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsCollideWallEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onFadeComplete (function func)"

.PP
set event handler for sprite fade event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite completes a fade over time done by fadeTo()

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.fadeTo()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onFadeInComplete (function func)"

.PP
set event handler for sprite fade in event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite completes a fade in over time done by \fBSprite\&.fadeIn()\fP

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.fadeIn()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onFadeOutComplete (function func)"

.PP
set event handler for sprite fade out event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite completes a fade out over time done by \fBSprite\&.fadeOut()\fP

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.fadeOut()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onLayerFadeInComplete (function func)"

.PP
set event handler for layer fade in event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
These happen when this layer completes a fade in over time done by \fBfadeIn()\fP

.PP
\fBSee also\fP
.RS 4
\fBfadeIn()\fP 

.PP
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onLayerFadeOutComplete (function func)"

.PP
set event handler for layer fade out event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
These happen when this layer completes a fade out over time done by \fBfadeOut()\fP

.PP
\fBSee also\fP
.RS 4
\fBfadeOut()\fP 

.PP
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onMouseClick (function func)"

.PP
set event handler for tap or mouse click in a sprite 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteTouchNotificationCallback\fP\&.
.RE
.PP
Only works for Sprites that have setWantsClickEvents(true)\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteTouchEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsClickEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onMouseDown (function func)"

.PP
set event handler for finger down or mouse down in a sprite 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteTouchNotificationCallback\fP\&.
.RE
.PP
Only works for Sprites that have setWantsClickEvents(true)\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteTouchEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsClickEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onMouseEnter (function func)"

.PP
set event handler for mouse pointer over a sprite 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteTouchNotificationCallback\fP\&.
.RE
.PP
Only works for Sprites that have setWantsMouseOverEvents(true)\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteTouchEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsMouseOverEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onMouseLeave (function func)"

.PP
set event handler for mouse pointer leaving a sprite it was over 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteTouchNotificationCallback\fP\&.
.RE
.PP
Only works for Sprites that have setWantsMouseOverEvents(true)\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteTouchEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsMouseOverEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onMouseUp (function func)"

.PP
set event handler for finger up or mouse up in a sprite 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteTouchNotificationCallback\fP\&.
.RE
.PP
Only works for Sprites that have setWantsClickEvents(true)\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteTouchEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsClickEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onOffscreen (function func)"

.PP
set event handler for sprite offscreen event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite moves completely outside the visible area of the port the layer is being rendered in, but only if setWantsOffscreenEvents(true) is called for that sprite\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsOffscreenEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onOnscreen (function func)"

.PP
set event handler for sprite onscreen event 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteAnimationEventCallback\fP\&.
.RE
.PP
These happen when a sprite moves into the visible area of the port the layer is being rendered into, but only if Sprite\&.setWantsOffscreenEvents(true) is called for that sprite\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteAnimateEvent\fP 

.PP
\fBIEventHandler\fP 

.PP
\fBSprite\&.setWantsOffscreenEvents()\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onPostAnimateLayer (function func)"

.PP
set event handler for layer animation finished events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens each frame when this particular layer is has finished calculating the changes for the animation step\&.

.PP
\fBSee also\fP
.RS 4
\fBonPreAnimateLayer()\fP 

.PP
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onPostDrawLayer (function func)"

.PP
set event handler for layer rendering complete events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens each frame when a this particular layer has finished rendering that frame

.PP
\fBSee also\fP
.RS 4
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onPreAnimateLayer (function func)"

.PP
set event handler for layer animation start events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens each frame when this particular layer is about to start calculating the changes for the animation step\&.

.PP
\fBSee also\fP
.RS 4
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBIEventHandler\fP onPreDrawLayer (function func)"

.PP
set event handler for layer rendering start events 
.PP
\fBNote\fP
.RS 4
Parameter \fRfunc:\fP \fBSpriteLayerEventCallback\fP\&.
.RE
.PP
This happens each frame before this particular layer starts rendering that frame

.PP
\fBSee also\fP
.RS 4
\fBSpriteLayerEvent\fP 

.PP
\fBIEventHandler\fP 
.RE
.PP

.SS "\fBOffset\fP portToLayerOffset (\fBOffset\fP o)"

.PP
adjust the offset to account for the effective camera Since an offset is relative rather than fixed in coordinate space, this means only rotating it around 0,0 to match the effective camera rotation, and changing the offset length by the camera zoom\&. The camera translation is not factored in\&.

.PP
\fBParameters\fP
.RS 4
\fIo\fP \fBOffset\fP in port coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBOffset\fP in layer coordinates 
.RE
.PP

.SS "\fBPoint\fP portToLayerPoint (\fBPoint\fP p)"

.PP
adjust the point to account for the effective camera Adjusts for the effective camera view and port anchor to get layer coordinates for a point on the screen\&.

.PP
\fBParameters\fP
.RS 4
\fIp\fP \fBPoint\fP in port coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBPoint\fP in layer coordinates 
.RE
.PP

.SS "\fBQuad\fP portToLayerQuad (\fBQuad\fP q)"

.PP
adjust the quad to account for the effective camera Adjusts for the effective camera view and port anchor to get layer coordinates for the quad on the screen\&.

.PP
\fBParameters\fP
.RS 4
\fIq\fP \fBQuad\fP in port coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBQuad\fP in layer coordinates 
.RE
.PP

.SS "\fBRotatedRect\fP portToLayerRect (\fBRect\fP r)"

.PP
adjust the rectangle to account for the effective camera Adjusts for the effective camera view and port anchor to get layer coordinates for a rectangle on the screen\&.

.PP
Nonuniform scale or reflection returns enclosing bounds\&. For exact transformed corners, use the \fBQuad\fP conversion\&.

.PP
\fBParameters\fP
.RS 4
\fIr\fP \fBRect\fP in port coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBRect\fP in layer coordinates 
.RE
.PP

.SS "\fBVector\fP portToLayerVector (\fBVector\fP v)"

.PP
adjust the vector to account for the effective camera Since a vector is relative rather than fixed in coordinate space, this means only rotating it around 0,0 to match the effective camera rotation, and changing the vector length by the camera zoom\&. The camera translation is not factored in\&.

.PP
\fBParameters\fP
.RS 4
\fIv\fP \fBVector\fP in port coordinates
.RE
.PP
\fBReturns\fP
.RS 4
\fBVector\fP in layer coordinates 
.RE
.PP

.SS "removeAllParticleEmitters ()"

.PP
Remove all standalone emitters\&. Previous emissions remain alive\&. 
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "removeAllParticles ()"

.PP
Detach every particle\&. Retained particles remain valid; owned emitters stop\&. Standalone emitters remain configured\&. 
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "removeAllSprites ()"

.PP
remove all sprites in the layer 
.SS "removeCharacterMapFromAll (string mapName)"

.PP
Removes a character map from all Spriter sprites in this layer\&. 
.SS "removeParticle (\fBParticle\fP value)"

.PP
Detach a particle from this layer\&. Stops its emitter and shared physics participation\&. Does not mark it expired\&. Removing an unrelated particle is harmless\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Object to add/remove; JavaScript parameter is named value\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "removeParticleEmitter (\fBParticleEmitter\fP value)"

.PP
Stop and remove a standalone emitter\&. Does not remove a Particle-owned emitter; use \fBParticle::removeParticleEmitter()\fP\&. Previous emissions remain alive\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Object to add/remove; JavaScript parameter is named value\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "removeSprite (\fBSprite\fP oldSprite)"

.PP
Remove a \fBSprite\fP and its mounted descendants from this layer\&. Preserves mount relationships and layer-coordinate transforms\&. Retained groups can be animated off-layer and added to another layer\&. Removing a mounted child independently throws; detach it first\&. Sprites outside this layer are unchanged\&. Physics bodies leave the shared solver and retain their state for basic integration; root constraints and physical animation rigs are disconnected\&.

.PP
\fBParameters\fP
.RS 4
\fIoldSprite\fP The root of the group to remove\&.
.RE
.PP
\fBNote\fP
.RS 4
Native callers must retain the host with addRef()/release() to keep it alive after removal\&. JavaScript handles retain automatically\&. Removal from a locked physics callback is deferred until the solve ends\&. Animation modifiers cannot change layer membership\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBaddSprite()\fP, \fBPart::detachSprite()\fP, \fBremoveAllSprites()\fP 
.RE
.PP

.SS "serialize (\fBSerializer\fP serializer)"

.PP
Save selected Layer state and its ordered sprites\&. 
.PP
\fBParameters\fP
.RS 4
\fIserializer\fP Destination writer; select its resource mode before writing\&. \fBsetSerializationFlags()\fP selects state\&. The default \fR\fBpdg\&.ser_Full\fP\fP includes Layer draw transforms, initial identities, frame artwork, playback, programmed tweens, root and \fBPart\fP \fBPhysicsBody\fP state and active drives\&. Remaining Layer fade completion delays are stored in seconds\&. Shared images are written once and use the writer's embedded-resource or external-reference policy\&.
.RE
.PP
Updates with \fR\fBser_Animations\fP\fP (including \fR\fBser_Update\fP\fP) transfer sampled local \fBPart\fP transforms, reflection, constant movement and scheduled animations by \fBPart\fP ID\&. They preserve existing \fBPart\fP identities, parent links and artwork\&. This includes poses already solved by \fBPart\fP IK\&. The receiver can stop Layer animations and disable collisions to display only the received state\&. \fBPart\fP creation/removal, reparenting, artwork changes, IK controller configuration and \fBPart\fP body/constraint state require another initial snapshot; incremental \fBPart\fP records are not full physics checkpoints\&. A changed \fBPart\fP ID set is rejected\&.

.PP
Independent Parts retain IDs/names, parent links, transforms, tweens and shared Image/Drawing content\&. Parent links resolve before body publication\&. Nested \fBDrawing\fP geometry/attributes are embedded; referenced images use the save policy\&. Rigid mounts retain their mounting \fBPart\fP, child \fBSprite\fP, sampled child grip frame, error/held pose and nested relationships\&. Children retain their independent layer draw order\&. Mount links resolve after all Sprite/Part identities exist; nonphysical and kinematic children retain the same ownership and command restrictions\&.

.PP
\fBDrawing\fP colors and image transparency colors use eight-bit channels, with opaque alpha omitted\&. Floating-point colors can change by less than one channel step (1/255) when restored\&. \fBImage\fP pixel data is preserved exactly\&. \fBDrawing\fP geometry, pixel-space attributes (including thickness, text size, offsets and transform translation), and image subsections use the compact coordinate serializers\&. These can discard a fractional remainder smaller than 0\&.001 per encoded coordinate component\&. Rectangles encode their origin and size, so those small errors can accumulate at the opposite edge\&. Physics state, collision geometry, constraint anchors, IK inputs and Sprite/Part transforms retain their existing floating-point precision\&.

.PP
Packed boolean flags omit default values and absent payloads\&. Repeated images, \fBDrawing\fP storage and imported animation assets use shared object references within the same serializer stream\&. This preserves shared identity and avoids writing the same resource again; independently created objects remain distinct\&.

.PP
Imported SCML animations retain their shared model, selected entity/clip, floating-point playback time, pause/events, character maps, reference pose, bone overrides, blends and interrupted transitions\&. Bone-, artwork- and socket-bound Parts resolve against the restored rig\&. Built-in rig IK modifiers and retained \fBDrawing\fP registrations preserve their IDs, options and enabled state\&. Animation colliders continue following the restored pose\&.

.PP
Complete saves embed the imported document and its images and can load without the source files\&. Embedded XML is compressed losslessly with zlib when that makes it smaller; decompression is automatic\&. Documents are limited to 64 MiB before compression, and corrupt payloads or mismatched lengths cause a load error\&. External-reference saves omit the XML, resolve the original document path and verify that its contents have not changed; images use the selected resource policy\&. Missing or changed dependencies cause a load error\&.

.PP
Initial records preserve \fBCollider\fP shapes and shape IDs, frame/animation-source options, material overrides, collision filters, sensor/enabled state and contact-event opt-in\&. Compound-body associations, all \fBPhysicsConstraint\fP types, linked IK limits and active physical \fBPart\fP IK controllers resolve after all owners exist\&. Captured IK offsets and sampled drives survive; offsets are not recaptured from a deformed pose\&. Geometry is stored in both resource modes; frame images follow the resource policy\&. Restored colliders receive new process-wide IDs\&.

.PP
Callback collision filters/handlers are rejected; reinstall application handlers after loading\&. Solver contact caches and pending contact events are not saved, so loading rebuilds contacts and can produce new Begin events\&. A resumed simulation is not guaranteed to be bit-for-bit identical to an uninterrupted one\&.

.PP
\fBNote\fP
.RS 4
Initial saves support frame-based and imported \fBSprite\fP collections with Parts, colliders, constraints, physical \fBPart\fP IK and rigid mounts\&. Active imported physical rigs, older attachSprite() associations, modifier/drawing callbacks, custom easing/helpers, \fBFont\fP attributes, custom \fBDrawing\fP implementations and links to other layers are rejected\&. \fBDrawing\fP content requires a GUI-capable build\&. \fBPort\fP assignment, event handlers and the shared physics world's gravity/damping configuration belong to the receiving application\&. Discard the writer after a save error\&.
.RE
.PP
.PP
.nf
// layer contains sprites with no unsupported graph associations\&.
const writer = new pdg\&.Serializer();
writer\&.setResourceMode(pdg\&.serialization_Complete);
layer\&.setSerializationFlags(pdg\&.ser_Full);
layer\&.serialize(writer);
const reader = new pdg\&.Deserializer();
reader\&.setDataPtr(writer\&.getDataPtr());
const restored = pdg\&.createSpriteLayer();
restored\&.deserialize(reader);
// Use restored, then pdg\&.cleanupLayer(restored) when finished\&.
.fi
.PP
 
.PP
\fBSee also\fP
.RS 4
\fBSpriteLayer::deserialize()\fP, \fBSpriteLayer::getSerializedSize()\fP, \fBSerializer::setResourceMode()\fP 
.RE
.PP

.SS "setCamera (\fBCamera\fP camera = \fRnull\fP)"

.SS "setCameraParallax (number movementRatio = \fR1\fP, number zoomRatio = \fR1\fP)"

.PP
Adjust camera scrolling and zoom for this layer\&. 
.PP
\fBParameters\fP
.RS 4
\fImovementRatio\fP Finite factor multiplying camera location\&. 
.br
\fIzoomRatio\fP Finite exponent applied to camera zoom\&. Zero ignores that component\&. Rotation, scale, reflection and pivot still apply\&. The destination port's anchor remains the same for explicit and inherited cameras\&. Layer bounds, fades, visibility, physics and simulation pause remain independent\&. 
.RE
.PP

.SS "setDamping (number damping)"

.PP
set the overall resistance to motion over time (\fIChipmunk Physics Only\fP) 
.SS "setGravity (number gravity)"

.PP
set the force of gravity pulling everything downward (\fIChipmunk Physics Only\fP) If keepItDownward is true (the default), then direction of gravity will be automatically be adjusted to point downward relative to the port if the layer is rotated\&. 
.SS "\fBSpriteLayer\fP setMaxParticles (uint value)"

.PP
Set the shared particle budget\&. Default 10000\&. Zero prevents creation/emission; lowering the budget does not remove existing particles\&. Applies to manual creation and nested emissions\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Unsigned maximum count; JavaScript parameter is named value\&. 
.RE
.PP
\fBReturns\fP
.RS 4
This \fBSpriteLayer\fP\&. 
.RE
.PP
\fBSee also\fP
.RS 4
ParticleEffects 
.RE
.PP

.SS "setQueryBits (uint bits)"

.SS "\fBSpriteLayer\fP setSerializationFlags (uint flags)"

.PP
set the mode for sprite layer serialization 
.PP
\fBSee also\fP
.RS 4
\fBser_Micro\fP 

.PP
\fBser_Update\fP 

.PP
\fBser_Full\fP 
.RE
.PP

.SS "setSpritePort (\fBPort\fP port)"

.PP
set the port this layer is rendered into 
.SS "setStaticLayer (boolean isStatic = \fRtrue\fP)"

.PP
make objects in this layer not subject to physics forces (\fIChipmunk Physics Only\fP) Other objects can still collide with static object, but they are treated as having infinite mass\&.

.PP
\fBWarning\fP
.RS 4
This must be called before you start adding Sprites to the layer 
.RE
.PP

.SS "setUseChipmunkPhysics (boolean useIt = \fRtrue\fP)"

.PP
enable or disable use of Chipmunk Physics for a particular layer Layers that don't use Chipmunk Physics can still use the cruder physics system offered by the \fBAnimated\fP class\&. 
.SS "setWorldBounds (\fBRect\fP bounds)"

.PP
Set world bounds for sprite boundary checks\&. 
.PP
\fBParameters\fP
.RS 4
\fIbounds\fP Finite ordered rectangle independent of camera and viewport\&. Tile-layer map dimensions initialize its bounds\&. \fBCamera\fP motion never changes them\&. 
.RE
.PP

.SS "show ()"

.PP
start rendering this layer if it was previously hidden 
.SS "startAnimations ()"

.PP
restart doing animation calculations for this layer if they were stopped 
.SS "stopAnimations ()"

.PP
stop doing animation calculations for this layer 
.PP
\fBNote\fP
.RS 4
this does not stop it from rendering, but all motion in the layer will cease
.RE
.PP
\fBWarning\fP
.RS 4
Chipmunk Physics based movement will continue if this is a layer using Chipmunk Physics 
.RE
.PP

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "cleanupLayer\fR [related]\fP"

.PP
free all the memory used by a \fBpdg\&.SpriteLayer\fP or \fBpdg\&.TileLayer\fP 
.SS "createSpriteLayer (\fBPort\fP port = \fRnullptr\fP)\fR [related]\fP"

.PP
create a new \fBSpriteLayer\fP attached to a particular port 
.PP
\fBParameters\fP
.RS 4
\fIport\fP if passed, associate with a specific port, otherwise, associate with the main port
.RE
.PP
\fBSee also\fP
.RS 4
\fBpdg\&.Port\fP 

.PP
\fBpdg\&.GraphicsManager\&.getMainPort()\fP 
.RE
.PP

.PP
References \fBcreateSpriteLayer()\fP\&.
.PP
Referenced by \fBcreateSpriteLayer()\fP\&.
.SS "createSpriteLayerFromSpriterFile (string layerSpriterFilename, boolean addSprites = \fRtrue\fP, \fBPort\fP port = \fRnull\fP)\fR [related]\fP"

.PP
create a new \fBSpriteLayer\fP from an Spriter SCML file 
.PP
\fBParameters\fP
.RS 4
\fIlayerSpriterFilename\fP the path and name of the SCML file 
.br
\fIaddSprites\fP if true, all entities found in the SCML file will be added as sprites to the layer\&. If false, the SCML file will be loaded and all it's data will be cached for layer use by \fBpdg\&.SpriteLayer\&.createSpriteFromSpriterEntity()\fP 
.br
\fIport\fP if passed, associate with a specific port, otherwise, associate with the main port
.RE
.PP
\fBSee also\fP
.RS 4
\fBGraphicsManager\&.getMainPort()\fP 

.PP
SpriteLayer\&.createSpriteFromSCMLEntity() 
.RE
.PP

.PP
References \fBcreateSpriteLayerFromSpriterFile()\fP\&.
.PP
Referenced by \fBcreateSpriteLayerFromSpriterFile()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
