.TH "TileLayer" 3 "Version v1.2.0" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileLayer \- efficiently handles large tile datasets, useful for backgrounds, terrains, etc\&.\&.\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pdg\-js\&.h>\fP
.PP
Inherits \fBSpriteLayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "number \fBcheckCollision\fP (\fBSprite\fP movingSprite, uint alphaThreshold=128, boolean shortCircuit=true)"
.br
.RI "see if a sprite has collided with tiles in a layer "
.ti -1c
.RI "\fBdefineTileSet\fP (int tileWidth, int tileHeight, \fBImage\fP tiles, boolean hasTransparency=true, boolean flipTiles=false)"
.br
.RI "define image and dimensions for the tiles used by this layer "
.ti -1c
.RI "\fBMemBlock\fP \fBgetMapData\fP (int mapWidth=worldWidth, int mapHeight=worldHeight, int srcX=0, int srcY=0)"
.br
.RI "Extract a rectangular region of tile data from the layer\&. "
.ti -1c
.RI "\fBImage\fP \fBgetTileSetImage\fP ()"
.br
.RI "get the \fBImage\fP currently being used as a tile set "
.ti -1c
.RI "\fBPoint\fP \fBgetTileSize\fP ()"
.br
.RI "get size of a tile in the image "
.ti -1c
.RI "\fBTileInfo\fP \fBgetTileTypeAndFacingAt\fP (int x, int y)"
.br
.RI "get the tile type and the facing/flipped state of the tile "
.ti -1c
.RI "number \fBgetTileTypeAt\fP (int x, int y)"
.br
.RI "get the tile type at a particular spot on the map "
.ti -1c
.RI "\fBRect\fP \fBgetWorldSize\fP ()"
.br
.RI "get the number of tiles in the map "
.ti -1c
.RI "\fBloadMapData\fP (\fBMemBlock\fP data, int mapWidth=0, int mapHeight=0, int dstX=0, int dstY=0)"
.br
.RI "Load tile data from a \fBMemBlock\fP into the specified region of the layer\&. "
.ti -1c
.RI "\fBloadMapData\fP (Uint8Array data, int mapWidth=0, int mapHeight=0, int dstX=0, int dstY=0)"
.br
.RI "Load tile data from a Uint8Array into the specified region of the layer\&. "
.ti -1c
.RI "\fBsetTileTypeAt\fP (int x, int y, uint t, uint facing=\fBfacing_Ignore\fP)"
.br
.RI "sets the type of tile at a given location on the map "
.ti -1c
.RI "\fBsetWorldSize\fP (int width, int height, boolean repeatingX=false, boolean repeatingY=false)"
.br
.RI "sets the number of tiles in the world map "
.in -1c

Public Member Functions inherited from \fBSpriteLayer\fP
.in +1c
.ti -1c
.RI "\fBaddParticle\fP (\fBParticle\fP value)"
.br
.RI "Add a live detached particle\&. "
.ti -1c
.RI "\fBaddSprite\fP (\fBSprite\fP newSprite)"
.br
.RI "Add a \fBSprite\fP and its mounted descendants to this layer\&. "
.ti -1c
.RI "\fBapplyCharacterMapToAll\fP (string mapName)"
.br
.RI "Applies a character map to all Spriter sprites in this layer\&. "
.ti -1c
.RI "\fBParticle\fP \fBcreateParticle\fP ()"
.br
.RI "Create a layer-owned particle\&. "
.ti -1c
.RI "\fBParticleEmitter\fP \fBcreateParticleEmitter\fP ()"
.br
.RI "Create a layer-owned point emitter\&. "
.ti -1c
.RI "\fBSprite\fP \fBcreateSprite\fP ()"
.br
.RI "create a sprite that belongs to this layer "
.ti -1c
.RI "\fBSprite\fP \fBcreateSpriteFromSpriterEntity\fP (string inEntityName)"
.br
.RI "create a sprite from SCML data that was previously loaded "
.ti -1c
.RI "\fBSprite\fP \fBcreateSpriteFromSpriterFile\fP (string inFileName, string inEntityName=null)"
.br
.RI "create a single sprite from SCML data "
.ti -1c
.RI "\fBdeserialize\fP (\fBDeserializer\fP deserializer)"
.br
.RI "Restore Layer state or apply an incremental update\&. "
.ti -1c
.RI "\fBdisableCollisions\fP ()"
.br
.RI "stop checking for collisions between objects in this layer "
.ti -1c
.RI "\fBdisableCollisionsWithLayer\fP (\fBSpriteLayer\fP otherLayer)"
.br
.RI "remove layer from list of layers that do collisions between layers "
.ti -1c
.RI "\fBenableCollisions\fP ()"
.br
.RI "allow collision checking for sprites in this layer "
.ti -1c
.RI "\fBenableCollisionsWithLayer\fP (\fBSpriteLayer\fP otherLayer)"
.br
.RI "start collision checking with sprites in another layer "
.ti -1c
.RI "\fBenableSpriterEvents\fP (boolean enable=true)"
.br
.RI "Enables or disables Spriter animation events for this layer\&. "
.ti -1c
.RI "\fBSpriteLayer\fP \fBfadeIn\fP (number durationSeconds, int easing=\fBlinearTween\fP)"
.br
.RI "fade entire layer to full opacity over time "
.ti -1c
.RI "\fBSpriteLayer\fP \fBfadeOut\fP (number durationSeconds, int easing=\fBlinearTween\fP)"
.br
.RI "fade out the entire layer to full transparency over time "
.ti -1c
.RI "\fBSprite\fP \fBfindSprite\fP (int id)"
.br
.RI "find a sprite in this layer by user assigned id "
.ti -1c
.RI "\fBCamera\fP \fBgetCamera\fP ()"
.br
.ti -1c
.RI "\fBCamera\fP \fBgetEffectiveCamera\fP ()"
.br
.ti -1c
.RI "uint \fBgetMaxParticles\fP ()"
.br
.RI "Read the layer particle budget\&. "
.ti -1c
.RI "number \fBgetMyClassTag\fP ()"
.br
.RI "returns class tag for \fBSpriteLayer\fP, used for serialization "
.ti -1c
.RI "\fBParticle\fP \fBgetNthParticle\fP (uint value)"
.br
.RI "Read a particle by creation order\&. "
.ti -1c
.RI "\fBSprite\fP \fBgetNthSprite\fP (int index)"
.br
.RI "get a sprite by z-order "
.ti -1c
.RI "uint \fBgetParticleCount\fP ()"
.br
.RI "Count live layer particles\&. "
.ti -1c
.RI "number \fBgetParticleTrailCount\fP ()"
.br
.RI "Count live unexpired histories and retained fading tails\&. "
.ti -1c
.RI "uint \fBgetQueryBits\fP ()"
.br
.ti -1c
.RI "uint \fBgetSerializedSize\fP (\fBSerializer\fP serializer)"
.br
.RI "Measure selected Layer state and shared \fBSprite\fP resources\&. "
.ti -1c
.RI "\fBCpSpace\fP \fBgetSpace\fP ()"
.br
.RI "get the Chipmunk Physics \fBCpSpace\fP for the layer "
.ti -1c
.RI "\fBPort\fP \fBgetSpritePort\fP ()"
.br
.RI "get the \fBPort\fP the layer renders into "
.ti -1c
.RI "int \fBgetSpriteZOrder\fP (\fBSprite\fP sprite)"
.br
.RI "get the z-order of a sprite in this layer "
.ti -1c
.RI "\fBRect\fP \fBgetWorldBounds\fP ()"
.br
.ti -1c
.RI "int \fBgetZOrder\fP ()"
.br
.RI "get the z-order of this layer compared to all others "
.ti -1c
.RI "boolean \fBhasSprite\fP (\fBSprite\fP sprite)"
.br
.RI "see if a particular sprite belongs to this layer "
.ti -1c
.RI "\fBhide\fP ()"
.br
.RI "stop rendering this layer\&. "
.ti -1c
.RI "boolean \fBisHidden\fP ()"
.br
.RI "true if layer is hidden, false if it is visible "
.ti -1c
.RI "boolean \fBisSpriteBehind\fP (\fBSprite\fP sprite, \fBSprite\fP otherSprite)"
.br
.RI "returns true if sprite will be drawn before otherSprite "
.ti -1c
.RI "\fBOffset\fP \fBlayerToPortOffset\fP (\fBOffset\fP o)"
.br
.RI "adjust the offset to account for the effective camera "
.ti -1c
.RI "\fBPoint\fP \fBlayerToPortPoint\fP (\fBPoint\fP p)"
.br
.RI "translate the point to account for the effective camera "
.ti -1c
.RI "\fBQuad\fP \fBlayerToPortQuad\fP (\fBQuad\fP q)"
.br
.RI "translate the \fBQuad\fP to account for the effective camera "
.ti -1c
.RI "\fBRotatedRect\fP \fBlayerToPortRect\fP (\fBRect\fP r)"
.br
.RI "translate the rectangle (or \fBRotatedRect\fP) to account for the effective camera "
.ti -1c
.RI "\fBVector\fP \fBlayerToPortVector\fP (\fBVector\fP v)"
.br
.RI "translate the point to account for the effective camera "
.ti -1c
.RI "\fBmoveBehind\fP (\fBSpriteLayer\fP layer)"
.br
.RI "change the z-order of this layer to draw it before the given layer "
.ti -1c
.RI "\fBmoveInFrontOf\fP (\fBSpriteLayer\fP layer)"
.br
.RI "change the z-order of this layer to draw it after the given layer "
.ti -1c
.RI "\fBmoveToBack\fP ()"
.br
.RI "move this layer behind all other layers "
.ti -1c
.RI "\fBmoveToFront\fP ()"
.br
.RI "move this layer in front of all other layers "
.ti -1c
.RI "\fBIEventHandler\fP \fBon\fP (int eventCode, function func)"
.br
.RI "set event handler for all different sprite and spritelayer events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationComplete\fP (function func)"
.br
.RI "set event handler for layer animation complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationEnd\fP (function func)"
.br
.RI "set event handler for sprite animation end events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationLoop\fP (function func)"
.br
.RI "set event handler for sprite animation loop events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonAnimationStart\fP (function func)"
.br
.RI "set event handler for layer animation complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonCollideSprite\fP (function func)"
.br
.RI "set event handler for sprite-to-sprite collision events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonCollideWall\fP (function func)"
.br
.RI "set event handler for sprite-wall collision events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonDrawPortComplete\fP (function func)"
.br
.RI "set event handler for rendering complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonErasePort\fP (function func)"
.br
.RI "set event handler for rendering starting events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonExitLayer\fP (function func)"
.br
.RI "set event handler for sprite out of bounds event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonFadeComplete\fP (function func)"
.br
.RI "set event handler for sprite fade event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonFadeInComplete\fP (function func)"
.br
.RI "set event handler for sprite fade in event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonFadeOutComplete\fP (function func)"
.br
.RI "set event handler for sprite fade out event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonLayerFadeInComplete\fP (function func)"
.br
.RI "set event handler for layer fade in event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonLayerFadeOutComplete\fP (function func)"
.br
.RI "set event handler for layer fade out event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseClick\fP (function func)"
.br
.RI "set event handler for tap or mouse click in a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseDown\fP (function func)"
.br
.RI "set event handler for finger down or mouse down in a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseEnter\fP (function func)"
.br
.RI "set event handler for mouse pointer over a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseLeave\fP (function func)"
.br
.RI "set event handler for mouse pointer leaving a sprite it was over "
.ti -1c
.RI "\fBIEventHandler\fP \fBonMouseUp\fP (function func)"
.br
.RI "set event handler for finger up or mouse up in a sprite "
.ti -1c
.RI "\fBIEventHandler\fP \fBonOffscreen\fP (function func)"
.br
.RI "set event handler for sprite offscreen event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonOnscreen\fP (function func)"
.br
.RI "set event handler for sprite onscreen event "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPostAnimateLayer\fP (function func)"
.br
.RI "set event handler for layer animation finished events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPostDrawLayer\fP (function func)"
.br
.RI "set event handler for layer rendering complete events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPreAnimateLayer\fP (function func)"
.br
.RI "set event handler for layer animation start events "
.ti -1c
.RI "\fBIEventHandler\fP \fBonPreDrawLayer\fP (function func)"
.br
.RI "set event handler for layer rendering start events "
.ti -1c
.RI "\fBOffset\fP \fBportToLayerOffset\fP (\fBOffset\fP o)"
.br
.RI "adjust the offset to account for the effective camera "
.ti -1c
.RI "\fBPoint\fP \fBportToLayerPoint\fP (\fBPoint\fP p)"
.br
.RI "adjust the point to account for the effective camera "
.ti -1c
.RI "\fBQuad\fP \fBportToLayerQuad\fP (\fBQuad\fP q)"
.br
.RI "adjust the quad to account for the effective camera "
.ti -1c
.RI "\fBRotatedRect\fP \fBportToLayerRect\fP (\fBRect\fP r)"
.br
.RI "adjust the rectangle to account for the effective camera "
.ti -1c
.RI "\fBVector\fP \fBportToLayerVector\fP (\fBVector\fP v)"
.br
.RI "adjust the vector to account for the effective camera "
.ti -1c
.RI "\fBremoveAllParticleEmitters\fP ()"
.br
.RI "Remove all standalone emitters\&. "
.ti -1c
.RI "\fBremoveAllParticles\fP ()"
.br
.RI "Detach every particle\&. "
.ti -1c
.RI "\fBremoveAllSprites\fP ()"
.br
.RI "remove all sprites in the layer "
.ti -1c
.RI "\fBremoveCharacterMapFromAll\fP (string mapName)"
.br
.RI "Removes a character map from all Spriter sprites in this layer\&. "
.ti -1c
.RI "\fBremoveParticle\fP (\fBParticle\fP value)"
.br
.RI "Detach a particle from this layer\&. "
.ti -1c
.RI "\fBremoveParticleEmitter\fP (\fBParticleEmitter\fP value)"
.br
.RI "Stop and remove a standalone emitter\&. "
.ti -1c
.RI "\fBremoveSprite\fP (\fBSprite\fP oldSprite)"
.br
.RI "Remove a \fBSprite\fP and its mounted descendants from this layer\&. "
.ti -1c
.RI "\fBserialize\fP (\fBSerializer\fP serializer)"
.br
.RI "Save selected Layer state and its ordered sprites\&. "
.ti -1c
.RI "\fBsetCamera\fP (\fBCamera\fP camera=null)"
.br
.ti -1c
.RI "\fBsetCameraParallax\fP (number movementRatio=1, number zoomRatio=1)"
.br
.RI "Adjust camera scrolling and zoom for this layer\&. "
.ti -1c
.RI "\fBsetDamping\fP (number damping)"
.br
.RI "set the overall resistance to motion over time (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "\fBsetGravity\fP (number gravity)"
.br
.RI "set the force of gravity pulling everything downward (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "\fBSpriteLayer\fP \fBsetMaxParticles\fP (uint value)"
.br
.RI "Set the shared particle budget\&. "
.ti -1c
.RI "\fBsetQueryBits\fP (uint bits)"
.br
.ti -1c
.RI "\fBSpriteLayer\fP \fBsetSerializationFlags\fP (uint flags)"
.br
.RI "set the mode for sprite layer serialization "
.ti -1c
.RI "\fBsetSpritePort\fP (\fBPort\fP port)"
.br
.RI "set the port this layer is rendered into "
.ti -1c
.RI "\fBsetStaticLayer\fP (boolean isStatic=true)"
.br
.RI "make objects in this layer not subject to physics forces (\fIChipmunk Physics Only\fP) "
.ti -1c
.RI "\fBsetUseChipmunkPhysics\fP (boolean useIt=true)"
.br
.RI "enable or disable use of Chipmunk Physics for a particular layer "
.ti -1c
.RI "\fBsetWorldBounds\fP (\fBRect\fP bounds)"
.br
.RI "Set world bounds for sprite boundary checks\&. "
.ti -1c
.RI "\fBshow\fP ()"
.br
.RI "start rendering this layer if it was previously hidden "
.ti -1c
.RI "\fBstartAnimations\fP ()"
.br
.RI "restart doing animation calculations for this layer if they were stopped "
.ti -1c
.RI "\fBstopAnimations\fP ()"
.br
.RI "stop doing animation calculations for this layer "
.in -1c

Public Member Functions inherited from \fBEventEmitter\fP
.in +1c
.ti -1c
.RI "\fBEventEmitter\fP ()"
.br
.ti -1c
.RI "\fBaddHandler\fP (\fBIEventHandler\fP inHandler, int inEventType=\fBall_events\fP)"
.br
.RI "add a new handler for some event type, or for all events if no type specified\&. "
.ti -1c
.RI "\fBblockEvent\fP (int inEventType)"
.br
.RI "temporarily ignore all events of a particular type\&. "
.ti -1c
.RI "\fBclear\fP ()"
.br
.RI "remove all handlers "
.ti -1c
.RI "\fBremoveHandler\fP (\fBIEventHandler\fP inHandler, int inEventType=\fBall_events\fP)"
.br
.RI "remove a handler for some event type, or for all events (see note) if no type specified\&. "
.ti -1c
.RI "\fBunblockEvent\fP (int inEventType)"
.br
.RI "stop ignoring events of a particular type "
.in -1c

Public Member Functions inherited from \fBISerializable\fP
.in +1c
.ti -1c
.RI "\fBISerializable\fP (function getSerializedSize, function serialize, function deserialize, function getMyClassTag)"
.br
.in -1c
.SS "Related Symbols"
(Note that these are not member symbols\&.) 
.in +1c
.ti -1c
.RI "\fBcreateTileLayer\fP (\fBPort\fP port=nullptr)"
.br
.RI "create a new \fBTileLayer\fP attached to a particular port "
.in -1c

Related Symbols inherited from \fBSpriteLayer\fP
.in +1c
.ti -1c
.RI "\fBcleanupLayer\fP"
.br
.RI "free all the memory used by a \fBpdg\&.SpriteLayer\fP or \fBpdg\&.TileLayer\fP "
.ti -1c
.RI "\fBcreateSpriteLayer\fP (\fBPort\fP port=nullptr)"
.br
.RI "create a new \fBSpriteLayer\fP attached to a particular port "
.ti -1c
.RI "\fBcreateSpriteLayerFromSpriterFile\fP (string layerSpriterFilename, boolean addSprites=true, \fBPort\fP port=null)"
.br
.RI "create a new \fBSpriteLayer\fP from an Spriter SCML file "
.in -1c

Related Symbols inherited from \fBISerializable\fP
.in +1c
.ti -1c
.RI "\fBregisterSerializableClass\fP"
.br
.RI "register a particular class as implementing \fBISerializable\fP interface "
.in -1c
.SH "Detailed Description"
.PP 
efficiently handles large tile datasets, useful for backgrounds, terrains, etc\&.\&.\&. 


.PP
\fBNote\fP
.RS 4
\fBAPI Stability: 2 — Evolving\fP\&. This API is implemented and supported, but its contract is still settling\&. Compatibility is preserved where practical; breaking changes are documented in release notes\&. See \fBAPI stability\fP\&.
.RE
.PP
.SS "Capabilities"
Each \fBTileLayer\fP has a tile set, a set of equal size tiles taken from a single image\&. There can be at most 256 tiles in an image\&.

.PP
Tile sets can contain transparency, either through a transparent color or via an alpha channel\&. If a tile set does not contain transparency, then the entire tile world will be filled in solid, there is no way to leave out a tile\&. In tile sets with transparency, tile type 0 is considered empty, even if the there is no transparency in the actual image\&.

.PP
Tile sets can support tile rotation (facing) or tile flipping (vertical, horizontal, or both)\&. You cannot use both rotation and flipping in the same layer\&.

.PP
Tile rendering uses the effective \fBCamera\fP, including rotation, zoom, nonuniform scale and reflection\&.
.SS "Getting the Results you Want"
For truly impressive maps, you will rarely use just a single \fBTileLayer\fP\&. Because TileLayers are highly optimized for large areas of transparent/empty tiles, you can use a number of linked TileLayers that each focus on different details: water, terrain, ground cover, flowers and shrubs, trees, etc\&.\&.\&.

.PP
You can intersperse regular SpriteLayers in between TileLayers to provided animated effects to make your characters move at the right layer (underneath the tree-tops, for example)\&.

.PP
Attach a shared \fBCamera\fP to the destination \fBPort\fP or individual layers\&. Layers inherit their port camera unless explicitly overridden; \fBSpriteLayer\&.setCameraParallax()\fP can give backgrounds different motion\&.

.PP
\fBSee also\fP
.RS 4
\fBdefineTileSet\fP 

.PP
\fBImage\&.setTransparentColor\fP 

.PP
\fBSpriteLayer\&.setCamera\fP 

.PP
\fBSpriteLayer\&.setCameraParallax\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "number checkCollision (\fBSprite\fP movingSprite, uint alphaThreshold = \fR128\fP, boolean shortCircuit = \fRtrue\fP)"

.PP
see if a sprite has collided with tiles in a layer 
.SS "defineTileSet (int tileWidth, int tileHeight, \fBImage\fP tiles, boolean hasTransparency = \fRtrue\fP, boolean flipTiles = \fRfalse\fP)"

.PP
define image and dimensions for the tiles used by this layer Each \fBTileLayer\fP has a set of equal size tiles taken from a single image\&. The tileWidth and tileHeight specify the size of each individual tile in the image, and the image should divide evenly into tiles with no left-over space\&. There can be at most 256 tiles in an image\&.

.PP
Tile sets can contain transparency, either through a transparent color or via an alpha channel (See \fBImage\fP for more details on transparency)\&.

.PP
Tile sets can support tile rotation (facing) or tile flipping (vertical, horizontal, or both)\&. You cannot use both rotation and flipping in the same layer\&.

.PP
To support rotation, you must have a maximum of 64 tiles in your tile set\&. Typically the tiles would be arranged in an 8x8 grid, with the top left corner tile being considered tile 0 and then counting left to right, top to bottom\&.

.PP
To support flipping in both directions, your tile set should be laid out just like for rotation, 64 tiles in an 8x8 grid\&. For horizontal flipping only, you should have 128 tiles in an 8x16 grid, and for vertical flipping only you should have 128 tile in a 16x8 grid\&. For all kinds of flipping you must pass true for the flipTiles parameter when you call \fBdefineTileSet()\fP\&. 
.SS "\fBMemBlock\fP getMapData (int mapWidth = \fRworldWidth\fP, int mapHeight = \fRworldHeight\fP, int srcX = \fR0\fP, int srcY = \fR0\fP)"

.PP
Extract a rectangular region of tile data from the layer\&. This function extracts a rectangular region of tile data from the \fBTileLayer\fP and returns it as a \fBMemBlock\fP containing the tile indices\&.

.PP
\fBParameters\fP
.RS 4
\fImapWidth\fP The width of the region to extract in tiles\&. Defaults to the layer's current world width\&. 
.br
\fImapHeight\fP The height of the region to extract in tiles\&. Defaults to the layer's current world height\&. 
.br
\fIsrcX\fP The X coordinate of the top-left corner of the region to extract\&. Defaults to zero\&. 
.br
\fIsrcY\fP The Y coordinate of the top-left corner of the region to extract\&. Defaults to zero\&.
.RE
.PP
The function returns a \fBMemBlock\fP containing tile indices arranged in row-major order (left to right, top to bottom)\&. Each byte in the returned data represents a tile index from the specified region\&.

.PP
The extracted data can be used with \fBTileLayer::loadMapData()\fP to copy tile data between layers or save it for later use\&.

.PP
\fBReturns\fP
.RS 4
A \fBMemBlock\fP containing the tile indices from the specified region
.RE
.PP
\fBExceptions\fP
.RS 4
\fIRangeError\fP If the requested width or height, including the source offset, exceeds the layer's world dimensions\&. 
.RE
.PP
\fBNote\fP
.RS 4
The returned data format is compatible with \fBTileLayer::loadMapData(Uint8Array, int, int, int, int)\fP
.RE
.PP
\fBSee also\fP
.RS 4
\fBTileLayer::loadMapData(Uint8Array, int, int, int, int)\fP 

.PP
\fBTileLayer::loadMapData(MemBlock, int, int, int, int)\fP 

.PP
\fBMemBlock\fP 
.RE
.PP

.SS "\fBImage\fP getTileSetImage ()"

.PP
get the \fBImage\fP currently being used as a tile set 
.SS "\fBPoint\fP getTileSize ()"

.PP
get size of a tile in the image 
.PP
\fBReturns\fP
.RS 4
\fBPoint\fP with x (width) and y (height) values 
.RE
.PP

.SS "\fBTileInfo\fP getTileTypeAndFacingAt (int x, int y)"

.PP
get the tile type and the facing/flipped state of the tile 
.PP
\fBParameters\fP
.RS 4
\fIx\fP component of x,y coordinates on the map 
.br
\fIy\fP component of x,y coordinates on the map
.RE
.PP
\fBReturns\fP
.RS 4
a JavaScript object with tileType and facing\&. Unlike \fBgetTileTypeAt()\fP, this separates the facing/flipping information from the raw tile type, so the tile type is the actual index into your tile set\&.
.RE
.PP
.RS 4
console\&.log(myTileLayer\&.getTileTypeAndFacingAt(0,0); { tileType: 61, facing: 128 } 
.RE
.PP

.PP
\fBSee also\fP
.RS 4
\fBsetTileTypeAt\fP 

.PP
\fBgetTileTypeAt\fP 
.RE
.PP

.SS "number getTileTypeAt (int x, int y)"

.PP
get the tile type at a particular spot on the map 
.PP
\fBParameters\fP
.RS 4
\fIx\fP component of x,y coordinates on the map 
.br
\fIy\fP component of x,y coordinates on the map
.RE
.PP
\fBReturns\fP
.RS 4
the tile type\&. This is the raw data as stored in the \fBTileLayer\fP, so it includes rotation/flipping information in the high bits\&. It can only be used directly as the index into your tile set on TileLayers that aren't using tile rotation or flipping\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBgetTileTypeAndFacingAt\fP 

.PP
\fBsetTileTypeAt\fP 
.RE
.PP

.SS "\fBRect\fP getWorldSize ()"

.PP
get the number of tiles in the map 
.PP
\fBReturns\fP
.RS 4
a rectangle with the dimensions of the world map in number of tiles\&. If you want to get the pixel size for drawing use \fBgetWorldBounds()\fP instead\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBgetWorldBounds\fP 

.PP
\fBsetWorldSize\fP 
.RE
.PP

.SS "loadMapData (\fBMemBlock\fP data, int mapWidth = \fR0\fP, int mapHeight = \fR0\fP, int dstX = \fR0\fP, int dstY = \fR0\fP)"

.PP
Load tile data from a \fBMemBlock\fP into the specified region of the layer\&. This function loads tile data from a \fBMemBlock\fP into a specific rectangular region of the \fBTileLayer\fP\&. The data is interpreted as a 2D array of tile indices\&.

.PP
\fBParameters\fP
.RS 4
\fIdata\fP The \fBMemBlock\fP containing the tile data to load 
.br
\fImapWidth\fP The width of the tile map in the data (number of tiles horizontally) 
.br
\fImapHeight\fP The height of the tile map in the data (number of tiles vertically) 
.br
\fIdstX\fP The X coordinate where to place the top-left corner of the loaded data in the layer 
.br
\fIdstY\fP The Y coordinate where to place the top-left corner of the loaded data in the layer
.RE
.PP
The \fBMemBlock\fP data should contain tile indices arranged in row-major order (left to right, top to bottom)\&. Each tile index corresponds to a tile in the \fBTileLayer\fP's tile set\&.

.PP
The function will load the specified rectangular region from the data into the layer starting at the destination coordinates (dstX, dstY)\&.

.PP
\fBWarning\fP
.RS 4
The function will overwrite existing tile data in the destination region 

.PP
If the data size doesn't match mapWidth * mapHeight, the behavior is undefined 
.RE
.PP
\fBNote\fP
.RS 4
Tile indices in the data should be valid for the layer's tile set
.RE
.PP
\fBSee also\fP
.RS 4
\fBTileLayer::loadMapData(Uint8Array, int, int, int, int)\fP 

.PP
\fBTileLayer::getMapData()\fP 

.PP
\fBMemBlock\fP 
.RE
.PP

.SS "loadMapData (Uint8Array data, int mapWidth = \fR0\fP, int mapHeight = \fR0\fP, int dstX = \fR0\fP, int dstY = \fR0\fP)"

.PP
Load tile data from a Uint8Array into the specified region of the layer\&. This function loads tile data from a Uint8Array into a specific rectangular region of the \fBTileLayer\fP\&. The data is interpreted as a 2D array of tile indices\&.

.PP
\fBParameters\fP
.RS 4
\fIdata\fP The Uint8Array containing the tile data to load 
.br
\fImapWidth\fP The width of the tile map in the data (number of tiles horizontally) 
.br
\fImapHeight\fP The height of the tile map in the data (number of tiles vertically) 
.br
\fIdstX\fP The X coordinate where to place the top-left corner of the loaded data in the layer 
.br
\fIdstY\fP The Y coordinate where to place the top-left corner of the loaded data in the layer
.RE
.PP
The Uint8Array data should contain tile indices arranged in row-major order (left to right, top to bottom)\&. Each tile index corresponds to a tile in the \fBTileLayer\fP's tile set\&.

.PP
The function will load the specified rectangular region from the data into the layer starting at the destination coordinates (dstX, dstY)\&.

.PP
\fBWarning\fP
.RS 4
The function will overwrite existing tile data in the destination region 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIRangeError\fP If the array contains fewer than mapWidth * mapHeight bytes\&. 
.br
\fITypeError\fP If data is not an attached, non-shared Uint8Array or \fBMemBlock\fP\&. 
.RE
.PP
\fBNote\fP
.RS 4
Tile indices in the data should be valid for the layer's tile set
.RE
.PP
\fBSee also\fP
.RS 4
\fBTileLayer::loadMapData(MemBlock, int, int, int, int)\fP 

.PP
\fBTileLayer::getMapData()\fP 

.PP
\fBMemBlock\fP 
.RE
.PP

.SS "setTileTypeAt (int x, int y, uint t, uint facing = \fR\fBfacing_Ignore\fP\fP)"

.PP
sets the type of tile at a given location on the map 
.PP
\fBParameters\fP
.RS 4
\fIx\fP the horizontal tile position on the map (not pixels) 
.br
\fIy\fP the vertical tile position on the map (not pixels) 
.br
\fIt\fP the type of tile (the tile index in the tile set image) 
.br
\fIfacing\fP the rotation (or flipping) to use for this tile, defaults to none, ignored on layers that aren't using facing or flipping 
.RE
.PP

.PP
References \fBpdg::facing_Ignore\fP\&.
.SS "setWorldSize (int width, int height, boolean repeatingX = \fRfalse\fP, boolean repeatingY = \fRfalse\fP)"

.PP
sets the number of tiles in the world map 
.PP
\fBParameters\fP
.RS 4
\fIwidth\fP how many tiles wide the world should be 
.br
\fIheight\fP how many tiles high the world should be 
.br
\fIrepeatingX\fP true if the map should wrap around horizontally to appear infinite, defaults to false 
.br
\fIrepeatingY\fP true if the map should wrap around vertically to appear infinite, defaults to false 
.RE
.PP

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "createTileLayer (\fBPort\fP port = \fRnullptr\fP)\fR [related]\fP"

.PP
create a new \fBTileLayer\fP attached to a particular port 
.PP
\fBParameters\fP
.RS 4
\fIport\fP if passed, associate with a specific port, otherwise, associate with the main port
.RE
.PP
\fBSee also\fP
.RS 4
\fBpdg\&.Port\fP 

.PP
\fBpdg\&.GraphicsManager\&.getMainPort()\fP 
.RE
.PP

.PP
References \fBcreateTileLayer()\fP\&.
.PP
Referenced by \fBcreateTileLayer()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
