.TH "Sprites" 3 "Version v1.2.0" "Pixel Dust Game Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sprites \- Sprites and layers
.PP
 \- Sprite and tile layers, drawing helpers, and collision helpers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBISpriteDrawHelper\fP"
.br
.RI "helper for drawing sprite overlays and add-on effects "
.ti -1c
.RI "class \fBSprite\fP"
.br
.RI "animated, moving image that is automatically moved, animated, and drawn "
.ti -1c
.RI "struct \fBSpriteAnimateEvent\fP"
.br
.RI "a Sprite did some animation (\fIOptional\fP) "
.ti -1c
.RI "class \fBSpriteLayer\fP"
.br
.RI "creates and tracks collections of sprites "
.ti -1c
.RI "struct \fBSpriteTriggerEvent\fP"
.br
.RI "\fBSpriteTriggerEvent\fP\&. "
.ti -1c
.RI "class \fBTileLayer\fP"
.br
.RI "efficiently handles large tile datasets, useful for backgrounds, terrains, etc\&.\&.\&. "
.in -1c
.SH "Detailed Description"
.PP 
Sprite and tile layers, drawing helpers, and collision helpers\&. 

See \fBAuthored Spriter triggers\fP for authored Spriter notifications and their \fBpdg::SpriteTriggerEvent\fP payload\&. 
.SH "Class Documentation"
.PP 
.SH "struct pdg::SpriteAnimateEvent"
.PP 
a Sprite did some animation (\fIOptional\fP) 

A Sprite will generate one of these events when it completes an animation including fades (opacity animations), and moving on/offscreen or outside of the layer\&.

.PP
For frame based animations -- that is, calls to \fBpdg\&.Sprite\&.startFrameAnimation()\fP -- if it reaches the last frame and is not set to loop, action will be \fBpdg\&.action_AnimationEnd\fP\&. For looping animations \fBpdg\&.action_AnimationLoop\fP will be received each time the animation completes and starts over with the first frame\&.

.PP
When a Spriter animation blend started by \fBpdg::Sprite::blendToAnimation()\fP or \fBpdg::Sprite::transitionToAnimation()\fP completes, action is \fBpdg::action_AnimationBlendComplete\fP\&.

.PP
Authored Spriter triggers are delivered as \fBpdg::eventType_SpriteTriggerEvent\fP with a \fBpdg::SpriteTriggerEvent\fP payload\&. Subscribe to that event type for triggers\&.

.PP
For fades, one of three action types are possible: \fBpdg\&.action_FadeComplete\fP for calls to \fBpdg\&.Sprite\&.fadeTo()\fP, \fBpdg\&.action_FadeInComplete\fP for calls to \fBpdg\&.Sprite\&.fadeIn()\fP, and \fBpdg\&.action_FadeOutComplete\fP for calls to \fBpdg\&.Sprite\&.fadeOut()\fP\&.

.PP
When a Sprite has setWantsOffscreenEvents(true), \fBpdg\&.action_Offscreen\fP and \fBpdg\&.action_Onscreen\fP events will be generated for that sprite whenever it enters or departs the visible area of the port the layer is being rendered into\&.

.PP
When a Sprite has setWantsCollideWallEvents(true), \fBpdg\&.action_ExitLayer\fP events will be generated for that sprite whenever it moves completely outside the boundaries of the layer\&. (It will also get a \fBSpriteCollideEvent\fP when it hits the boundary)\&. 
.PP
.nf
{
    emitter: {},       // the emitter that generated this event
    eventType: 17,     // the event type (eventType_SpriteAnimate)
    action: 0,         // what happened (action_AnimationEnd/Loop or action_Fade/In/OutComplete)
    actingSprite: {},  // the Sprite that was animating
    inLayer: {}        // the SpriteLayer that contains the Sprite
}

.fi
.PP

.PP
\fBNote\fP
.RS 4
Spriter eventline notifications require pdg::Sprite::enableSpriterEvents(true)\&. See \fBAuthored Spriter triggers\fP for crossing, looping, seek, and transition rules\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBpdg\&.eventType_SpriteAnimate\fP 

.PP
\fBpdg\&.Sprite\&.startFrameAnimation()\fP 

.PP
\fBpdg\&.Sprite\&.blendToAnimation()\fP 

.PP
\fBpdg\&.Sprite\&.startAnimation()\fP 

.PP
\fBpdg\&.Sprite\&.fadeTo()\fP 

.PP
\fBpdg\&.Sprite\&.fadeIn()\fP 

.PP
\fBpdg\&.Sprite\&.fadeOut()\fP 

.PP
\fBpdg\&.Sprite\&.setWantsOffscreenEvents()\fP 

.PP
\fBpdg\&.Sprite\&.setWantsCollideWallEvents()\fP 
.RE
.PP

.SH "struct pdg::SpriteTriggerEvent"
.PP 
\fBSpriteTriggerEvent\fP\&. 

Payload for an authored Spriter trigger delivered as eventType_SpriteTriggerEvent\&.

.PP
\fBNote\fP
.RS 4
Documentation-only JavaScript shape, not a runtime constructor\&.
.RE
.PP
 
.PP
\fBFields\fP
.RS 4
Field  Type  Required/default  Meaning  actingSprite  \fR\fBSprite\fP\fP or \fRnull\fP  Required  action  \fRnumber\fP  Required  clipName  \fRstring\fP  Required  emitter  \fR\fBEventEmitter\fP\fP  Required  entityName  \fRstring\fP  Required  eventType  \fRnumber\fP  Required  inLayer  \fR\fBSpriteLayer\fP\fP or \fRnull\fP  Required  offsetSeconds  \fRnumber\fP  Required  timeSeconds  \fRnumber\fP  Required  triggerName  \fRstring\fP  Required  
.RE
.PP
The common JavaScript payload contains:

.PP
Field  Meaning  \fR\fBemitter\fP\fP  \fBEvent\fP emitter delivering the notification  \fR\fBeventType\fP\fP  \fBpdg::eventType_SpriteTriggerEvent\fP  \fR\fBactingSprite\fP\fP  \fBSprite\fP whose animation crossed the trigger  \fR\fBinLayer\fP\fP  \fBSpriteLayer\fP containing that \fBSprite\fP  \fR\fBtriggerName\fP\fP  Authored eventline name  \fR\fBclipName\fP\fP  Clip containing the eventline key  \fR\fBentityName\fP\fP  Spriter entity containing the clip  \fR\fBtimeSeconds\fP\fP  Authored key position from clip start, in floating-point seconds  \fR\fBoffsetSeconds\fP\fP  Occurrence offset from the start of the update, in floating-point seconds  

.PP
Subscribe by event type and inspect \fR\fBtriggerName\fP\fP to distinguish authored triggers\&. An \fR\fBaction\fP\fP field is not a portable trigger discriminator\&. The native compatibility field \fRframeTime\fP uses integer milliseconds and is omitted from JavaScript\&. The native event ID is currently exposed by the browser bridge but not the V8/JavaScriptCore bridges\&.

.PP
\fBSee also\fP
.RS 4
\fBpdg::Sprite::enableSpriterEvents\fP 

.PP
\fBpdg::eventType_SpriteTriggerEvent\fP 

.PP
\fBAuthored Spriter triggers\fP 
.RE
.PP

.PP
\fBClass Members:\fP
.RS 4
\fBSprite\fP \fIactingSprite\fP actingSprite Type: \fR\fBSprite\fP\fP or \fRnull\fP\&. Required\&. 
.br
.PP
number \fIaction\fP action Type: \fRnumber\fP\&. Required\&. 
.br
.PP
string \fIclipName\fP clipName Type: \fRstring\fP\&. Required\&. 
.br
.PP
\fBEventEmitter\fP \fIemitter\fP emitter Type: \fR\fBEventEmitter\fP\fP\&. Required\&. 
.br
.PP
string \fIentityName\fP entityName Type: \fRstring\fP\&. Required\&. 
.br
.PP
number \fIeventType\fP eventType Type: \fRnumber\fP\&. Required\&. 
.br
.PP
\fBSpriteLayer\fP \fIinLayer\fP inLayer Type: \fR\fBSpriteLayer\fP\fP or \fRnull\fP\&. Required\&. 
.br
.PP
number \fIoffsetSeconds\fP offsetSeconds Type: \fRnumber\fP\&. Required\&. 
.br
.PP
number \fItimeSeconds\fP timeSeconds Type: \fRnumber\fP\&. Required\&. 
.br
.PP
string \fItriggerName\fP triggerName Type: \fRstring\fP\&. Required\&. 
.br
.PP
.RE
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Pixel Dust Game Engine from the source code\&.
