// this file was automatically generated by "pdg tools/make-idl.js --doxygen-h-format"


namespace pdg
{

    const all_events = 0;
    const eventType_Shutdown = 2;
    const eventType_Timer = 3;
    const eventType_KeyDown = 4;
    const eventType_KeyUp = 5;
    const eventType_KeyPress = 6;
    const eventType_MouseDown = 7;
    const eventType_MouseUp = 8;
    const eventType_MouseMove = 9;
    const eventType_MouseEnter = 22;
    const eventType_MouseLeave = 23;
    const eventType_PortResized = 15;
    const eventType_ScrollWheel = 16;
    const eventType_SpriteTouch = 19;
    const eventType_SpriteAnimate = 17;
    const eventType_SpriteTriggerEvent = 25;
    const eventType_SpriteLayer = 18;
    const eventType_SpriteCollide = 20;
    const collisionShape_Polygon = 3;
    const collisionShape_ImageMask = 4;
    const collisionShape_Capsule = 5;
    const colliderSource_Explicit = 0;
    const colliderSource_Frame = 1;
    const colliderSource_Animation = 2;
    const frameCollider_Bounds = 0;
    const frameCollider_AlphaMask = 1;
    const eventType_ColliderContact = 26;
    const eventType_ParticleBreak = 27;
    const eventType_SpriteBreak = 21;
    const eventType_SoundEvent = 14;
    const eventType_PortDraw = 24;
    const soundEvent_DonePlaying = 0;
    const soundEvent_Looping = 1;
    const soundEvent_FailedToPlay = 2;
    const key_Break = 1;
    const key_Home = 2;
    const key_End = 3;
    const key_Clear = 4;
    const key_Help = 5;
    const key_Pause = 6;
    const key_Mute = 7;
    const key_Backspace = 8;
    const key_Delete = 127;
    const key_Tab = 9;
    const key_PageUp = 11;
    const key_PageDown = 12;
    const key_Return = 13;
    const key_Enter = 13;
    const key_F1 = 14;
    const key_F2 = 15;
    const key_F3 = 16;
    const key_F4 = 17;
    const key_F5 = 18;
    const key_F6 = 19;
    const key_F7 = 20;
    const key_F8 = 21;
    const key_F9 = 22;
    const key_F10 = 23;
    const key_F11 = 24;
    const key_F12 = 25;
    const key_FirstF = 14;
    const key_LastF = 25;
    const key_Insert = 26;
    const key_Escape = 27;
    const key_LeftArrow = 28;
    const key_RightArrow = 29;
    const key_UpArrow = 30;
    const key_DownArrow = 31;
    const key_FirstPrintable = 32;
    const keyCode_LeftShift = 56;
    const keyCode_RightShift = 60;
    const keyCode_LeftControl = 59;
    const keyCode_RightControl = 62;
    const keyCode_LeftAlt = 58;
    const keyCode_RightAlt = 61;
    const keyCode_LeftMeta = 55;
    const keyCode_RightMeta = 54;
    const keyCode_Shift = 56;
    const keyCode_Control = 59;
    const keyCode_Alt = 58;
    const keyCode_Meta = 55;
    const screenPos_Normal = 0;
    const screenPos_Rotated180 = 1;
    const screenPos_Rotated90Clockwise = 2;
    const screenPos_Rotated90CounterClockwise = 3;
    const screenPos_FaceUp = 4;
    const screenPos_FaceDown = 5;
    const textStyle_Plain = 0;
    const textStyle_Bold = 1;
    const textStyle_Italic = 2;
    const textStyle_Underline = 4;
    const textStyle_Centered = 16;
    const textStyle_LeftJustified = 0;
    const textStyle_RightJustified = 32;
    const lineStyle_Auto = 0;
    const lineStyle_None = 1;
    const lineStyle_Solid = 2;
    const lineStyle_Dashed = 3;
    const lineStyle_Dotted = 4;
    const lineStyle_DashDot = 5;
    const lineStyle_DashDotDot = 6;
    const blendMode_Normal = 0;
    const blendMode_Additive = 1;
    const blendMode_Multiply = 2;
    const blendMode_Screen = 3;
    const blendMode_Darken = 4;
    const blendMode_Lighten = 5;
    const type_Line = 1;
    const type_Spline = 2;
    const type_Arc = 3;
    const type_Rect = 4;
    const type_Quad = 5;
    const type_Polygon = 6;
    const type_Ellipse = 7;
    const type_Image = 8;
    const type_ImageStrip = 9;
    const type_Drawing = 10;
    const gradientType_None = 0;
    const gradientType_Linear = 1;
    const gradientType_Radial = 2;
    const fit_None = 0;
    const fit_Fill = 1;
    const fit_Height = 2;
    const fit_Width = 3;
    const fit_Inside = 4;
    const fit_Overflow = 5;
    const fit_Clipped = 6;
    const fit_TileX = 7;
    const fit_TileY = 8;
    const fit_Tile = 9;
    const init_CreateUniqueNewFile = 0;
    const init_OverwriteExisting = 1;
    const init_AppendToExisting = 2;
    const init_StdOut = 3;
    const init_StdErr = 4;
    const partId_None = 4294967295;
    const boneId_None = 4294967295;
    const physicsBody_None = 0;
    const physicsBody_Dynamic = 1;
    const physicsBody_Kinematic = 2;
    const physicsBody_Static = 3;
    const physicsSolver_None = 0;
    const physicsSolver_Basic = 1;
    const physicsSolver_Chipmunk = 2;
    const physicsForce_None = 0;
    const collisionShape_None = 0;
    const collisionShape_Circle = 1;
    const collisionShape_Convex = 2;
    const collision_Begin = 0;
    const collision_Stay = 1;
    const collision_End = 2;
    const constraint_Pin = 1;
    const constraint_Slide = 2;
    const constraint_Pivot = 3;
    const constraint_Groove = 4;
    const constraint_Spring = 5;
    const constraint_RotarySpring = 6;
    const constraint_RotaryLimit = 7;
    const constraint_Ratchet = 8;
    const constraint_Gear = 9;
    const constraint_Motor = 10;
    const partSpace_Local = 0;
    const partSpace_Sprite = 1;
    const partSpace_World = 2;
    const partPlacement_Snap = 0;
    const partPlacement_PreserveWorld = 1;
    const rotationDirection_AsSpecified = 0;
    const rotationDirection_Shortest = 1;
    const rotationDirection_Clockwise = 2;
    const rotationDirection_CounterClockwise = 3;
    const animate_StartToEnd = 0;
    const animate_EndToStart = 1;
    const animate_Unidirectional = 0;
    const animate_Bidirectional = 2;
    const animate_NoLooping = 0;
    const animate_Looping = 4;
    const start_FromFirstFrame = -1;
    const start_FromLastFrame = -2;
    const all_Frames = 0;
    const action_CollideSprite = 0;
    const action_CollideWall = 1;
    const action_Offscreen = 2;
    const action_Onscreen = 3;
    const action_ExitLayer = 4;
    const action_AnimationLoop = 8;
    const action_AnimationEnd = 9;
    const action_FadeComplete = 10;
    const action_FadeInComplete = 11;
    const action_FadeOutComplete = 12;
    const action_JointBreak = 13;
    const action_BodyBreak = 16;
    const physicsBreak_Force = 0;
    const physicsBreak_AngularSpeed = 1;
    const action_AnimationBlendComplete = 15;
    const action_AnimationPhysicsRecoveryComplete = 17;
    const animationPhysics_Kinematic = 0;
    const animationPhysics_Dynamic = 1;
    const animationPhysics_Driven = 2;
    const animationPhysics_Mixed = 3;
    const touch_MouseEnter = 20;
    const touch_MouseLeave = 21;
    const touch_MouseDown = 22;
    const touch_MouseUp = 23;
    const touch_MouseClick = 24;
    const collide_None = 0;
    const collide_Point = 1;
    const collide_BoundingBox = 2;
    const collide_CollisionRadius = 3;
    const collide_AlphaChannel = 4;
    const collide_SpriterCollisionBox = 5;
    const collide_Last = 5;
    const animationSpace_Local = 0;
    const animationSpace_Rig = 1;
    const animationSpace_World = 2;
    const animationDebug_None = 0;
    const animationDebug_Bones = 1;
    const animationDebug_Sockets = 2;
    const animationDebug_Boxes = 4;
    const animationDebug_All = 7;
    const animationBinding_Image = 0;
    const animationBinding_Point = 1;
    const animationBinding_Box = 2;
    const animationVariable_Float = 0;
    const animationVariable_Int = 1;
    const animationVariable_String = 2;
    const animationStage_PreConstraint = 0;
    const animationStage_Constraint = 1;
    const animationStage_PostConstraint = 2;
    const animationSource_Clip = 0;
    const animationSource_Reference = 1;
    const animationSource_Procedural = 2;
    const animationBody_Dynamic = 0;
    const animationBody_Kinematic = 1;
    const animationRoot_Fixed = 0;
    const animationRoot_Follow = 1;
    const animationDraw_BeforeAll = 0;
    const animationDraw_AfterAll = 1;
    const animationDraw_BeforeSlot = 2;
    const animationDraw_AfterSlot = 3;
    const animationDraw_ReplaceSlot = 4;
    const animationStroke_PortPixels = 0;
    const animationStroke_Local = 1;
    const animationIK_NoStretch = 0;
    const animationIK_Stretch = 1;
    const action_ErasePort = 40;
    const action_PreDrawLayer = 41;
    const action_PostDrawLayer = 42;
    const action_DrawPortComplete = 43;
    const action_AnimationStart = 44;
    const action_PreAnimateLayer = 45;
    const action_PostAnimateLayer = 46;
    const action_AnimationComplete = 47;
    const action_ZoomComplete = 48;
    const action_LayerFadeInComplete = 49;
    const action_LayerFadeOutComplete = 50;
    const facing_North = 0;
    const facing_East = 64;
    const facing_South = 128;
    const facing_West = 192;
    const facing_Ignore = 256;
    const flipped_None = 0;
    const flipped_Horizontal = 64;
    const flipped_Vertical = 128;
    const flipped_Both = 192;
    const flipped_Ignore = 256;
    const timer_OneShot = true;
    const timer_Repeating = false;
    const timer_Never = -1;
    const linearTween = 0;
    const easeInQuad = 1;
    const easeOutQuad = 2;
    const easeInOutQuad = 3;
    const easeInCubic = 4;
    const easeOutCubic = 5;
    const easeInOutCubic = 6;
    const easeInQuart = 7;
    const easeOutQuart = 8;
    const easeInQuint = 10;
    const easeOutQuint = 11;
    const easeInOutQuint = 12;
    const easeInSine = 13;
    const easeOutSine = 14;
    const easeInOutSine = 15;
    const easeInExpo = 16;
    const easeOutExpo = 17;
    const easeInOutExpo = 18;
    const easeInCirc = 19;
    const easeOutCirc = 20;
    const easeInOutCirc = 21;
    const easeInBounce = 22;
    const easeOutBounce = 23;
    const easeInOutBounce = 24;
    const easeInBack = 25;
    const easeOutBack = 26;
    const easeInOutBack = 27;
    const ser_Positions = 1;
    const ser_ZOrder = 2;
    const ser_Sizes = 4;
    const ser_Animations = 8;
    const ser_Motion = 16;
    const ser_Forces = 32;
    const ser_Physics = 64;
    const ser_LayerDraw = 128;
    const ser_ImageRefs = 256;
    const ser_SCMLRefs = 512;
    const ser_HelperRefs = 1024;
    const ser_HelperObjs = 8192;
    const ser_InitialData = 16384;
    const ser_Micro = 3;
    const ser_Update = 127;
    const ser_Full = 18431;
    const serialization_Complete = 0;
    const serialization_ExternalReferences = 1;
    const spline_Hermite = 1;
    const spline_Cardinal = 2;
    const spline_UniformB = 3;
    const spline_CubicBezier = 4;
    const spline_TCB = 5;
    const spline_NaturalCubic = 6;
    boolean running;
    boolean quitting;
    const lftTop = 0;
    const rgtTop = 1;
    const rgtBot = 2;
    const lftBot = 3;
    boolean hasNetwork;
    FileManager fs;
    EventManager evt;
    TimerManager tm;
    ResourceManager res;
    ConfigManager cfg;
    LogManager lm;
    const CopyPixels = true;
    const SharedSurface = false;
    GraphicsManager gfx;
    boolean hasGraphics;
    SoundManager snd;
    boolean hasSound;
    string[] argv;
    number rand ();
    srand (uint seed);
    setSerializationDebugMode (bool debugMode);
    int registerEasingFunction (function easingFunc);
    FileManager getFileManager ();
    LogManager getLogManager ();
    ConfigManager getConfigManager ();
    ResourceManager getResourceManager ();
    EventManager getEventManager ();
    TimerManager getTimerManager ();
    registerSerializableClass (function klass);
    GraphicsManager getGraphicsManager ();
    SoundManager getSoundManager ();
    SpriteLayer createSpriteLayer (Port port = null);
    SpriteLayer createSpriteLayerFromSpriterFile (string layerSpriterFilename, boolean addSprites = true, Port port = null);
    cleanupLayer (SpriteLayer layer);
    TileLayer createTileLayer (Port port = null);
    Drawing createDrawing ();
    quit ();
    run ();
    idle ();
    openDebugger ();
    openConsole ();
    openCommandPort (int port = 5757);
    log (string msg);
    info (string msg);
    warn (string msg);
    fatal (string msg);
    error (string msg);
    debug (string msg);
    trace (string msg);
    captureConsole ();
    ISerializable createSerializableObject (object obj, uint classTag);
    IEventHandler on (int eventType, function func);
    IEventHandler onShutdown (function func);
    IEventHandler onTimer (function func);
    IEventHandler onKeyDown (function func);
    IEventHandler onKeyUp (function func);
    IEventHandler onKeyPress (function func);
    IEventHandler onMouseDown (function func);
    IEventHandler onMouseUp (function func);
    IEventHandler onMouseMove (function func);
    boolean animationHasTag (object pose, string object, string tag);

    class MemBlock
    {
        public:
            BinaryString getData ();
            number getDataSize ();
            number getByte (uint i);
            BinaryString getBytes (uint start, uint len);
            Buffer toBuffer ();
    };

    class FileManager
    {
        public:
            object findFirst (string inFindName);
            object findNext (object inFindData);
            findClose (object inFindData);
            string getApplicationDataDirectory ();
            string getApplicationDirectory ();
            string getApplicationResourceDirectory ();
            string[] findFiles (string name);
            string[] findDirs (string name);
    };

    class LogManager
    {
        public:
            const init_CreateUniqueNewFile = 0;
            const init_OverwriteExisting = 1;
            const init_AppendToExisting = 2;
            const init_StdOut = 3;
            const init_StdErr = 4;
            number getLogLevel ();
            LogManager setLogLevel (int inLogLevel);
            initialize (string inLogNameBase, int initMode = LogManager.init_StdOut);
            writeLogEntry (int level, string category, string message);
            string binaryDump (BinaryString inData, int length = 0, int bytesPerLine = 20);
            string binaryDump (MemBlock inData, int length = 0, int bytesPerLine = 20);
    };

    class ConfigManager
    {
        public:
            boolean useConfig (string inConfigName);
            string getConfigString (string inConfigItemName);
            number getConfigLong (string inConfigItemName);
            number getConfigFloat (string inConfigItemName);
            boolean getConfigBool (string inConfigItemName);
            setConfigString (string inConfigItemName, string inValue);
            setConfigLong (string inConfigItemName, int inValue);
            setConfigFloat (string inConfigItemName, number inValue);
            setConfigBool (string inConfigItemName, boolean inValue);
    };

    class ResourceManager
    {
        public:
            string getLanguage ();
            ResourceManager setLanguage (string inLanguage);
            number openResourceFile (string filename);
            closeResourceFile (int refNum);
            Image getImage (string imageName);
            ImageStrip getImageStrip (string imageName);
            Sound getSound (string soundName);
            string getString (int id, int substring = -1);
            number getResourceSize (string resourceName);
            BinaryString getResource (string resourceName);
            string getResourcePaths ();
    };

    class Serializer
    {
        public:
            Serializer setResourceMode (int mode);
            int getResourceMode ();
            serialize_8 (number val);
            serialize_8u (number val);
            uint sizeof_8 (int val);
            uint sizeof_8u (uint val);
            serialize_d (number val);
            serialize_f (number val);
            serialize_4 (int val);
            serialize_4u (uint val);
            serialize_3u (uint val);
            serialize_2 (int val);
            serialize_2u (uint val);
            serialize_1 (int val);
            serialize_1u (uint val);
            serialize_bool (boolean val);
            serialize_uint (uint val);
            serialize_color (Color val);
            serialize_offset (Offset val);
            serialize_point (Point val);
            serialize_vector (Vector val);
            serialize_rect (Rect val);
            serialize_rotr (RotatedRect val);
            serialize_quad (Quad val);
            serialize_str (string str);
            serialize_mem (BinaryString mem);
            serialize_mem (MemBlock mem);
            serialize_obj (ISerializable obj);
            serialize_ref (object obj);
            uint sizeof_d (number val);
            uint sizeof_f (number val);
            uint sizeof_4 (int val);
            uint sizeof_4u (uint val);
            uint sizeof_3u (uint val);
            uint sizeof_2 (int val);
            uint sizeof_2u (uint val);
            uint sizeof_1 (int val);
            uint sizeof_1u (uint val);
            uint sizeof_bool (boolean val);
            uint sizeof_uint (uint val);
            uint sizeof_color (Color val);
            uint sizeof_offset (Offset val);
            uint sizeof_point (Point val);
            uint sizeof_vector (Vector val);
            uint sizeof_rect (Rect val);
            uint sizeof_rotr (RotatedRect val);
            uint sizeof_quad (Quad val);
            uint sizeof_str (string val);
            uint sizeof_mem (BinaryString mem);
            uint sizeof_mem (MemBlock mem);
            uint sizeof_obj (ISerializable obj);
            uint sizeof_ref (object val);
            number getDataSize ();
            MemBlock getDataPtr ();
    };

    class Deserializer
    {
        public:
            number deserialize_8 ();
            number deserialize_8u ();
            number deserialize_d ();
            number deserialize_f ();
            number deserialize_4 ();
            number deserialize_4u ();
            number deserialize_3u ();
            number deserialize_2 ();
            number deserialize_2u ();
            number deserialize_1 ();
            number deserialize_1u ();
            boolean deserialize_bool ();
            number deserialize_uint ();
            Color deserialize_color ();
            Offset deserialize_offset ();
            Point deserialize_point ();
            Vector deserialize_vector ();
            Rect deserialize_rect ();
            RotatedRect deserialize_rotr ();
            Quad deserialize_quad ();
            string deserialize_str ();
            MemBlock deserialize_mem ();
            number deserialize_memGetLen ();
            ISerializable deserialize_obj ();
            object deserialize_ref ();
            setDataPtr (BinaryString data);
            setDataPtr (MemBlock data);
    };

    class ISerializable
    {
        public:
    };

    class IEventHandler
    {
        public:
    };

    class EventEmitter
    {
        public:
            addHandler (IEventHandler inHandler, int inEventType = all_events);
            removeHandler (IEventHandler inHandler, int inEventType = all_events);
            clear ();
            blockEvent (int inEventType);
            unblockEvent (int inEventType);
    };

    class EventManager : public EventEmitter
    {
        public:
            boolean isKeyDown (string unicodeChar);
            boolean isKeyDown (uint utf16CharCode);
            boolean isRawKeyDown (int keyCode);
            boolean isButtonDown (int buttonNumber = 0);
            object getDeviceOrientation (boolean absolute = false);
    };

    class TimerManager : public EventEmitter
    {
        public:
            startTimer (int id, uint delay, boolean oneShot = true);
            cancelTimer (int id);
            cancelAllTimers ();
            delayTimer (int id, uint delay);
            delayTimerUntil (int id, int msTime);
            pause ();
            unpause ();
            boolean isPaused ();
            pauseTimer (int id);
            unpauseTimer (int id);
            boolean isTimerPaused (int id);
            number getWhenTimerFiresNext (int id);
            number getMilliseconds ();
            IEventHandler onTimeout (function func, int delay);
            IEventHandler onInterval (function func, int interval);
    };

    class IAnimationHelper
    {
        public:
    };

    class Animated
    {
        public:
            Rect getBoundingBox ();
            RotatedRect getRotatedBounds ();
            Point getLocation ();
            Offset getMovement ();
            Offset getSize ();
            number getWidth ();
            number getHeight ();
            Offset getScale ();
            Offset getStretching ();
            number getRotation ();
            Offset getCenterOffset ();
            number getSpin ();
            Animated setLocation (Point value);
            Animated setLocation (number x, number y);
            Animated moveTo (Point value, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveTo (number x, number y, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveBy (Offset value, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveBy (number x, number y, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated setMovement (Vector value);
            Animated setMovement (number xPerSecond, number yPerSecond);
            Animated changeMovementTo (Vector value, number durationSeconds, int easing = linearTween);
            Animated changeMovementTo (number xPerSecond, number yPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeMovementBy (Vector value, number durationSeconds, int easing = linearTween);
            Animated changeMovementBy (number xPerSecond, number yPerSecond, number durationSeconds, int easing = linearTween);
            Animated setSize (Offset value);
            Animated setSize (number width, number height);
            Animated changeCenterOffsetTo (Offset value, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetTo (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetBy (Offset value, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetBy (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated setWidth (number value);
            Animated setHeight (number value);
            Animated setRotation (number value);
            Animated setSpin (number value);
            Animated setGrowing (number value);
            Animated setStretching (number widthPerSecond, number heightPerSecond);
            Animated setScale (number x, number y = x);
            Animated changeSpinTo (number radiansPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeSpinBy (number radiansPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeGrowingTo (number amountPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeGrowingBy (number amountPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeStretchingTo (number widthPerSecond, number heightPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeStretchingBy (number widthPerSecond, number heightPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeScaleTo (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated changeScaleBy (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated grow (number factor, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated stretch (number widthFactor, number heightFactor, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated resizeBy (number deltaWidth, number deltaHeight, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated resizeTo (number width, number height, number durationSeconds, int easing = easeInOutQuad);
            Animated rotateBy (number radians, number durationSeconds = 0, int easing = easeInOutQuad, int direction = rotationDirection_AsSpecified);
            Animated rotateTo (number radians, number durationSeconds = 0, int easing = easeInOutQuad, int direction = rotationDirection_AsSpecified);
            Animated setCenterOffset (Offset offset);
            Animated setFlipX (boolean flip);
            Animated setFlipY (boolean flip);
            Animated stopMovement ();
            Animated stopSpinning ();
            Animated stopGrowing ();
            Animated stopStretching ();
            Animated pauseSchedule ();
            Animated resumeSchedule ();
            Animated cancelSchedule ();
            Animated flipX ();
            Animated flipY ();
            Animated andThen ();
            boolean isFlippedX ();
            boolean isFlippedY ();
            boolean isSchedulePaused ();
            boolean hasScheduledAnimations ();
            Animated wait (number durationSeconds);
            Animated addAnimationHelper (IAnimationHelper helper);
            Animated removeAnimationHelper (IAnimationHelper helper);
            Animated clearAnimationHelpers ();
            boolean animate (number deltaSeconds);
    };

    class Part : public Animated
    {
        public:
            /** Read-only property. */
            Collider collider;
            /** Read-only property. */
            PhysicsBody physics;
            Rect getBoundingBox ();
            RotatedRect getRotatedBounds ();
            Point getLocation ();
            Offset getMovement ();
            Offset getSize ();
            number getWidth ();
            number getHeight ();
            Offset getScale ();
            Offset getStretching ();
            number getRotation ();
            Offset getCenterOffset ();
            number getSpin ();
            Animated setLocation (Point value);
            Animated setLocation (number x, number y);
            Animated moveTo (Point value, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveTo (number x, number y, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveBy (Offset value, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveBy (number x, number y, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated setMovement (Vector value);
            Animated setMovement (number xPerSecond, number yPerSecond);
            Animated changeMovementTo (Vector value, number durationSeconds, int easing = linearTween);
            Animated changeMovementTo (number xPerSecond, number yPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeMovementBy (Vector value, number durationSeconds, int easing = linearTween);
            Animated changeMovementBy (number xPerSecond, number yPerSecond, number durationSeconds, int easing = linearTween);
            Animated setSize (Offset value);
            Animated setSize (number width, number height);
            Animated changeCenterOffsetTo (Offset value, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetTo (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetBy (Offset value, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetBy (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated setWidth (number value);
            Animated setHeight (number value);
            Animated setRotation (number value);
            Animated setSpin (number value);
            Animated setGrowing (number value);
            Animated setStretching (number widthPerSecond, number heightPerSecond);
            Animated setScale (number x, number y = x);
            Animated changeSpinTo (number radiansPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeSpinBy (number radiansPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeGrowingTo (number amountPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeGrowingBy (number amountPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeStretchingTo (number widthPerSecond, number heightPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeStretchingBy (number widthPerSecond, number heightPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeScaleTo (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated changeScaleBy (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated grow (number factor, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated stretch (number widthFactor, number heightFactor, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated resizeBy (number deltaWidth, number deltaHeight, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated resizeTo (number width, number height, number durationSeconds, int easing = easeInOutQuad);
            Animated rotateBy (number radians, number durationSeconds = 0, int easing = easeInOutQuad, int direction = rotationDirection_AsSpecified);
            Animated rotateTo (number radians, number durationSeconds = 0, int easing = easeInOutQuad, int direction = rotationDirection_AsSpecified);
            Animated setCenterOffset (Offset offset);
            Animated setFlipX (boolean flip);
            Animated setFlipY (boolean flip);
            Animated stopMovement ();
            Animated stopSpinning ();
            Animated stopGrowing ();
            Animated stopStretching ();
            Animated pauseSchedule ();
            Animated resumeSchedule ();
            Animated cancelSchedule ();
            Animated flipX ();
            Animated flipY ();
            Animated andThen ();
            boolean isFlippedX ();
            boolean isFlippedY ();
            boolean isSchedulePaused ();
            boolean hasScheduledAnimations ();
            Animated wait (number durationSeconds);
            Animated addAnimationHelper (IAnimationHelper helper);
            Animated removeAnimationHelper (IAnimationHelper helper);
            Animated clearAnimationHelpers ();
            Collider setupCollider ();
            Collider setupFrameCollider (int mode = frameCollider_AlphaMask, int alphaThreshold = 128);
            Collider setupAnimationCollider (string boxName);
            removeCollider ();
            PhysicsBody setupPhysicsBody (number mass = 1, number momentOfInertia = 1);
            removePhysicsBody ();
            boolean animate (number deltaSeconds);
            uint getId ();
            string getName ();
            Sprite getSprite ();
            boolean isAttached ();
            uint getBoneId ();
            boolean isBoundToBone ();
            Part bindToBone (uint boneId);
            Part unbindFromBone ();
            Part getParentPart ();
            Part setParentPart ();
            Part setParentPart (Part parent);
            boolean solveIK (Part middle, Part tip, Point target, int space = partSpace_World, int bendDirection = 1, number influence = 1);
            Part setIKTarget (Part middle, Part tip, Point target, int space = partSpace_World, int bendDirection = 1, number influence = 1);
            Part clearIKTarget ();
            boolean hasIKTarget ();
            boolean isIKTargetReached ();
            string getIKError ();
            Part setIKLimits (number minAngle, number maxAngle);
            Part setIKLimits (PhysicsConstraint constraint);
            Part clearIKLimits ();
            boolean hasIKLimits ();
            number getIKMinAngle ();
            number getIKMaxAngle ();
            Part setIKDriveTarget (Part middle, Part tip, Point target, number maxForce, number maxTorque, int space = partSpace_World, int bendDirection = 1, number influence = 1, number frequency = 4, number dampingRatio = 1);
            boolean isIKDriven ();
            Part attachSprite (Sprite child, int placement = partPlacement_Snap);
            Part attachSprite (Sprite child, int placement, Part childMount);
            Sprite getAttachedSprite ();
            Part detachSprite ();
            string getAttachmentError ();
            object getTransform (int space = partSpace_Local);
            Part bindToAnimationBinding (string name);
            Part bindToAnimationSocket (string name);
            string getAnimationBindingName ();
            string getAnimationSocketName ();
            Part clearContent ();
            boolean hasContent ();
            Rect getContentBounds (int space = partSpace_Local);
            Part setDrawing (Drawing drawing);
            Part setImage (Image image, Rect localBounds);
    };

    class Particle : public Animated, public EventEmitter
    {
        public:
            /** Read-only property. */
            ParticleEmitter emitter;
            /** Read-only property. */
            Collider collider;
            /** Read-only property. */
            PhysicsBody physics;
            PhysicsBody setupPhysicsBody (number mass = 1, number momentOfInertia = 1);
            removePhysicsBody ();
            Collider setupCollider ();
            removeCollider ();
            ParticleEmitter setupParticleEmitter ();
            ParticleEmitter getParticleEmitter ();
            removeParticleEmitter ();
            Particle clearContent ();
            boolean hasContent ();
            Particle setOpacity (number value);
            number getOpacity ();
            Particle fadeTo (number opacity, number seconds, int easing = linearTween);
            Particle setLifetime (number value);
            number getLifetime ();
            number getAge ();
            boolean isAlive ();
            expire ();
            SpriteLayer getLayer ();
            Particle setImage (Image content);
            Particle setDrawing (Drawing content);
    };

    class ParticleEmitter : public Animated
    {
        public:
            ParticleEmitter setParticleTemplate (Particle particle);
            boolean hasParticleTemplate ();
            ParticleEmitter setEmissionRate (number value);
            number getEmissionRate ();
            ParticleEmitter setParticleSpeed (number minimum, number maximum = minimum);
            number getMinParticleSpeed ();
            number getMaxParticleSpeed ();
            ParticleEmitter setSpread (number value);
            number getSpread ();
            ParticleEmitter setVelocityInheritance (number value);
            number getVelocityInheritance ();
            ParticleEmitter setSeed (uint seed);
            number getSeed ();
            ParticleEmitter startEmitting ();
            ParticleEmitter stopEmitting ();
            boolean isEmitting ();
            number emit (uint count = 1);
            SpriteLayer getLayer ();
            Particle getParticle ();
    };

    class PhysicsBody
    {
        public:
            static const PhysicsBody NoPhysics;
            number getConstraintCount ();
            PhysicsConstraint createPinJoint (PhysicsBody other, Point anchor = Point(0,0), Point otherAnchor = Point(0,0));
            PhysicsConstraint createPivotJoint (PhysicsBody other, Point anchor = Point(0,0), Point otherAnchor = Point(0,0));
            PhysicsConstraint createSlideJoint (PhysicsBody other, Point anchor, Point otherAnchor, number minDistance, number maxDistance);
            PhysicsConstraint createGrooveJoint (PhysicsBody other, Point start, Point end, Point otherAnchor);
            PhysicsConstraint createSpring (PhysicsBody other, Point anchor, Point otherAnchor, number restLength, number stiffness, number damping);
            PhysicsConstraint createRotarySpring (PhysicsBody other, number restAngle, number stiffness, number damping);
            PhysicsConstraint createRotaryLimit (PhysicsBody other, number minAngle, number maxAngle);
            PhysicsConstraint createRatchet (PhysicsBody other, number interval, number phase = 0);
            PhysicsConstraint createGear (PhysicsBody other, number ratio, number phase = 0);
            PhysicsConstraint createMotor (PhysicsBody other, number radiansPerSecond, number maxTorque);
            PhysicsConstraint getConstraint (uint index);
            PhysicsBody disconnect (PhysicsBody other = null);
            PhysicsBody setDriveTarget (Point position, number radians, number maxForce, number maxTorque, number frequency = 4, number dampingRatio = 1, int direction = rotationDirection_Shortest);
            PhysicsBody clearDrive ();
            boolean isDriveEnabled ();
            object getDriveState ();
            number getMode ();
            PhysicsBody setMode (number value);
            number getMass ();
            PhysicsBody setMass (number value);
            number getMomentOfInertia ();
            PhysicsBody setMomentOfInertia (number value);
            number getLinearDamping ();
            PhysicsBody setLinearDamping (number value);
            number getAngularDamping ();
            PhysicsBody setAngularDamping (number value);
            number getFriction ();
            PhysicsBody setFriction (number value);
            number getRestitution ();
            PhysicsBody setRestitution (number value);
            PhysicsBody setBreakAngularSpeed (number radiansPerSecond);
            PhysicsBody setBreakAngularSpeed (number radiansPerSecond, PhysicsBody referenceBody);
            number getBreakAngularSpeed ();
            PhysicsBody getBreakAngularSpeedReference ();
            number getAngularVelocity ();
            PhysicsBody setAngularVelocity (number value);
            number getSpeed ();
            PhysicsBody setSpeed (number value);
            number getSolver ();
            number getAngularMomentum ();
            number getMovementDirectionInRadians ();
            boolean isPresent ();
            boolean isAttached ();
            object getState ();
            Vector getVelocity ();
            PhysicsBody setVelocity (Vector velocity);
            PhysicsBody setVelocity (number xPerSecond, number yPerSecond);
            PhysicsBody setVelocityInRadians (number speed, number direction);
            PhysicsBody teleport (Point position, number radians);
            PhysicsBody applyImpulse (Vector impulse);
            PhysicsBody applyImpulse (Vector impulse, Point worldPoint);
            PhysicsBody applyAngularImpulse (number impulse);
            uint applyForce (Vector force, number durationSeconds, number delaySeconds = 0);
            uint applyForce (Vector force, number durationSeconds, number delaySeconds, Point worldPoint);
            uint applyTorque (number torque, number durationSeconds, number delaySeconds = 0);
            uint addContinuousForce (Vector force);
            uint addContinuousTorque (number torque);
            boolean removeForce (uint id);
            PhysicsBody stopAllForces ();
            PhysicsBody stopMoving ();
            PhysicsBody stopSpinning ();
            step (number deltaSeconds);
    };

    class Collider
    {
        public:
            static const Collider NoCollider;
            Collider setWantsContactEvents (boolean wanted);
            boolean getWantsContactEvents ();
            Collider setFriction (number value);
            Collider setRestitution (number value);
            number getFriction ();
            number getRestitution ();
            Collider useBodyMaterial ();
            boolean isPresent ();
            boolean isAttached ();
            boolean isEnabled ();
            boolean isSensor ();
            number getId ();
            number getCategory ();
            number getCollisionMask ();
            number getGroup ();
            number getShapeCount ();
            Collider setEnabled (boolean value);
            Collider setSensor (boolean value);
            Collider setCategory (uint value);
            Collider setCollisionMask (uint value);
            Collider setGroup (uint value);
            PhysicsBody getPhysicsBody ();
            Collider setCircle (number radius, Point center = Point(0,0));
            uint addCircle (number radius, Point center = Point(0,0));
            Collider setCapsule (Point start, Point end, number radius);
            uint addCapsule (Point start, Point end, number radius);
            Point getCapsuleStart (uint shapeId);
            Point getCapsuleEnd (uint shapeId);
            number getCapsuleRadius (uint shapeId);
            Collider setBox (Rect bounds);
            uint addBox (Rect bounds);
            Collider clearShapes ();
            Collider useOwnerPhysics ();
            Collider setPhysicsBody (PhysicsBody body);
            Rect getBounds ();
            boolean contains (Point worldPoint);
            boolean overlaps (Collider other);
            boolean removeShape (uint id);
            uint getShapeId (uint id);
            string getContactError ();
            uint addPolygon (array vertices);
            uint addPolygon (Polygon polygon);
            Collider setPolygon (array vertices);
            Collider setPolygon (Polygon polygon);
            Collider setImageMask (Image image, Rect localBounds, int alphaThreshold = 128);
            uint addImageMask (Image image, Rect localBounds, int alphaThreshold = 128);
            number getGeometrySource ();
            boolean isSourceShape (uint shapeId);
            string getShapeName (uint shapeId);
            number getShapeType (uint shapeId);
            number getCircleRadius (uint shapeId);
            Collider setContactHandler (function callback);
            Collider setCollisionFilter (function callback);
    };

    class PhysicsConstraint
    {
        public:
            boolean isActive ();
            boolean isBroken ();
            boolean getCollideBodies ();
            number getType ();
            number getMaxForce ();
            number getBreakForce ();
            number getImpulse ();
            number getForce ();
            PhysicsConstraint setCollideBodies (boolean value);
            PhysicsConstraint setMaxForce (number value);
            PhysicsConstraint setBreakForce (number value);
            PhysicsBody getBodyA ();
            PhysicsBody getBodyB ();
            Point getAnchorA ();
            Point getAnchorB ();
            PhysicsConstraint setAnchorA (Point anchor);
            PhysicsConstraint setAnchorB (Point anchor);
            PhysicsConstraint setAnchors (Point anchorA, Point anchorB);
            Point getGrooveStart ();
            Point getGrooveEnd ();
            PhysicsConstraint setGroove (Point start, Point end);
            number getMinAngle ();
            number getMaxAngle ();
            PhysicsConstraint setAngleLimits (number minAngle, number maxAngle);
            disconnect ();
    };

    class CpArbiter
    {
        public:
            boolean isFirstContact ();
            number getCount ();
            Vector getNormal ();
            Point getPointA (int i);
            Point getPointB (int i);
            number getDepth (int i);
    };

    class CpConstraint
    {
        public:
            string getType ();
            activateBodies ();
            number getImpulse ();
            number getMaxForce ();
            CpConstraint setMaxForce (number inMaxForce);
            number getErrorBias ();
            CpConstraint setErrorBias (number inErrorBias);
            number getMaxBias ();
            CpConstraint setMaxBias (number inMaxBias);
            Sprite getSprite ();
            Sprite getOtherSprite ();
            Offset getAnchor ();
            CpConstraint setAnchor (Offset inAnchor);
            Offset getOtherAnchor ();
            CpConstraint setOtherAnchor (Offset inOtherAnchor);
            number getPinDist ();
            CpConstraint setPinDist (number inPinDist);
            number getSpringStiffness ();
            CpConstraint setSpringStiffness (number inSpringStiffness);
            number getSpringDamping ();
            CpConstraint setSpringDamping (number inSpringDamping);
            number getSlideMinDist ();
            CpConstraint setSlideMinDist (number inSlideMinDist);
            number getSlideMaxDist ();
            CpConstraint setSlideMaxDist (number inSlideMaxDist);
            Offset getGrooveStart ();
            CpConstraint setGrooveStart (Offset inGrooveStart);
            Offset getGrooveEnd ();
            CpConstraint setGrooveEnd (Offset inGrooveEnd);
            number getSpringRestLength ();
            CpConstraint setSpringRestLength (number inSpringRestLength);
            number getRotarySpringRestAngle ();
            CpConstraint setRotarySpringRestAngle (number inRotarySpringRestAngle);
            number getMinAngle ();
            CpConstraint setMinAngle (number inMinAngle);
            number getMaxAngle ();
            CpConstraint setMaxAngle (number inMaxAngle);
            number getRatchetAngle ();
            CpConstraint setRatchetAngle (number inRatchetAngle);
            number getRatchetPhase ();
            CpConstraint setRatchetPhase (number inRatchetPhase);
            number getRatchetInterval ();
            CpConstraint setRatchetInterval (number inRatchetInterval);
            number getGearRatio ();
            CpConstraint setGearRatio (number inGearRatio);
            number getGearInitialAngle ();
            CpConstraint setGearInitialAngle (number inGearInitialAngle);
            number getMotorSpinRate ();
            CpConstraint setMotorSpinRate (number inMotorSpinRate);
    };

    class CpSpace
    {
        public:
            useSpatialHash (number dim, int count);
            reindexStatic ();
            step (number dt);
            number getIdleSpeedThreshold ();
            CpSpace setIdleSpeedThreshold (number inIdleSpeedThreshold);
            number getSleepTimeThreshold ();
            CpSpace setSleepTimeThreshold (number inSleepTimeThreshold);
            number getCollisionSlop ();
            CpSpace setCollisionSlop (number inCollisionSlop);
            number getCollisionBias ();
            CpSpace setCollisionBias (number inCollisionBias);
            number getCollisionPersistence ();
            CpSpace setCollisionPersistence (number inCollisionPersistence);
    };

    class ISpriteDrawHelper
    {
        public:
    };

    class Sprite : public Animated, public EventEmitter, public ISerializable
    {
        public:
            /** Read-only property. */
            Collider collider;
            /** Read-only property. */
            PhysicsBody physics;
            Part getAttachmentPart ();
            Part createPart (string name);
            Part transferPart (Part part, boolean includeDescendants = true);
            Collider setupFrameCollider (int mode = frameCollider_AlphaMask, int alphaThreshold = 128);
            Collider setupAnimationCollider ();
            Sprite setFrameCollisionMask (Image frameImage, Image maskImage);
            Part getPart (uint id);
            Part findPart (string name);
            uint getPartCount ();
            Array getPartNames ();
            boolean removePart (uint id);
            clearParts ();
            Collider setupCollider ();
            removeCollider ();
            PhysicsBody setupPhysicsBody (number mass = 1, number momentOfInertia = 1);
            removePhysicsBody ();
            number getMyClassTag ();
            uint getSerializedSize (Serializer serializer);
            serialize (Serializer serializer);
            deserialize (Deserializer deserializer);
            RotatedRect getFrameRotatedBounds (int frameNum = -1);
            Sprite setFrame (int frame);
            number getCurrentFrame ();
            number getFrameCount ();
            startFrameAnimation (number fps, int startingFrame = start_FromFirstFrame, int numFrames = all_Frames, int animateFlags = animate_Looping);
            stopFrameAnimation ();
            boolean getWantsAnimLoopEvents ();
            Sprite setWantsAnimLoopEvents (boolean wantsThem = true);
            boolean getWantsAnimEndEvents ();
            Sprite setWantsAnimEndEvents (boolean wantsThem = true);
            boolean getWantsCollideWallEvents ();
            Sprite setWantsCollideWallEvents (boolean wantsThem = true);
            addFramesImage (Image image, int startingFrame = start_FromFirstFrame, int numFrames = all_Frames);
            seekAnimation (string clip, number timeSeconds);
            transitionToAnimation (string clip, number timeSeconds, number durationSeconds);
            boolean isAnimationTransitioning ();
            number getAnimationTransitionProgress ();
            boolean supportsAnimationPhysics ();
            setupAnimationPhysics (object definition);
            Sprite setupPhysicsFromAnimationRig (number totalMass, number unitsPerMeter = 1);
            Sprite attachAnimationPhysicsPart (Part part, Part parent = null);
            Sprite detachAnimationPhysicsPart (Part part, boolean includeDescendants = true);
            boolean isAnimationPhysicsPartAttached (Part part);
            Sprite setAnimationPhysicsRoot (number bone);
            Sprite setAnimationPhysicsRoot (string bone);
            uint getAnimationPhysicsRoot ();
            Sprite clearAnimationPhysicsRoot ();
            Array getAnimationPhysicsSetupWarnings ();
            Sprite setAnimationPhysicsMode (int mode, string bone = undefined, boolean includeDescendants = false, number recoveryTime = 0.5, int direction = rotationDirection_AsSpecified);
            Sprite setAnimationPhysicsMode (int mode, uint bone = undefined, boolean includeDescendants = false, number recoveryTime = 0.5, int direction = rotationDirection_AsSpecified);
            int getAnimationPhysicsMode (string bone = undefined, boolean includeDescendants = false);
            int getAnimationPhysicsMode (uint bone = undefined, boolean includeDescendants = false);
            Sprite setAnimationPhysicsDriveSettings (object settings, string bone = undefined, boolean includeDescendants = false);
            Sprite setAnimationPhysicsDriveSettings (object settings, uint bone = undefined, boolean includeDescendants = false);
            object getAnimationPhysicsDriveSettings (string bone);
            object getAnimationPhysicsDriveSettings (uint bone);
            disableAnimationPhysics (number recoveryTime = 0.5, int direction = rotationDirection_AsSpecified);
            boolean isAnimationPhysicsEnabled ();
            uint addAnimationDrawable (Drawing drawing, object options);
            uint addAnimationDrawable (function callback, object options);
            removeAnimationDrawable (uint id);
            clearAnimationDrawables ();
            setAnimationDrawableEnabled (uint id, boolean enabled);
            string getAnimationDrawableError (uint id);
            object getAnimationDrawBounds ();
            uint addAnimationIK (object config, int order = 0);
            setAnimationIKTarget (uint id, number x, number y, int space = animationSpace_Rig);
            object getAnimationIKResult (uint id);
            uint addAnimationModifier (function callback, int stage = animationStage_PreConstraint, int order = 0);
            removeAnimationModifier (uint id);
            clearAnimationModifiers ();
            string getAnimationModifierError (uint id);
            setAnimationSource (int source);
            int getAnimationSource ();
            boolean isAnimationDrawingSupported ();
            setAnimationDebugDraw (int flags);
            int getAnimationDebugDraw ();
            boolean enableAnimationPose (string referenceAnimation);
            disableAnimationPose ();
            boolean isAnimationPoseEnabled ();
            string getAnimationRigError ();
            Array getAnimationBoneNames ();
            Array getAnimationBindingNames ();
            object getAnimationBoneTransform (string name, int space = animationSpace_Local);
            object getAnimationBindingTransform (string name, int space = animationSpace_Local);
            setAnimationBoneTransform (string name, object transform);
            clearAnimationBoneTransforms ();
            object getAnimationPose ();
            object sampleAnimationPose (string clip, number timeSeconds);
            boolean hasAnimation (int animationId);
            boolean hasAnimation (string animationName);
            startAnimation (int animationId);
            startAnimation (string animationName);
            applyCharacterMap (string mapName);
            removeCharacterMap (string mapName);
            removeAllCharacterMaps ();
            Array getAppliedCharacterMaps ();
            enableSpriterEvents (boolean enable = true);
            boolean areSpriterEventsEnabled ();
            blendToAnimation (int animationId, number blendTime);
            blendToAnimation (string animationName, number blendTime);
            boolean isBlending ();
            number getBlendProgress ();
            pauseAnimation ();
            resumeAnimation ();
            stopAnimation ();
            boolean isAnimationPlaying ();
            boolean isAnimationPaused ();
            number getAnimationProgress ();
            boolean hasAttachPoint (string attachPointName);
            Offset getAttachPoint (string attachPointName);
            attachSprite (Sprite sprite, string attachPointName);
            activateSubEntity (string entityName, string animationName = "idle");
            detachSprite (Sprite sprite);
            Sprite getAttachedSprite (string attachPointName);
            RotatedRect getSpriterCollisionBox (string boxName);
            boolean isSpriterCollisionActive (string boxName);
            number getSpriterCollisionBoxCount ();
            string getSpriterCollisionBoxName (number index);
            changeFramesImage (Image oldImage, Image newImage);
            offsetFrameCenters (int offsetX, int offsetY, Image image = null, int startingFrame = start_FromFirstFrame, int numFrames = all_Frames);
            Offset getFrameCenterOffset (Image image = null, int frameNum = 0);
            number getOpacity ();
            Sprite setOpacity (number opacity);
            fadeTo (number targetOpacity, number durationSeconds, int easing = linearTween);
            fadeIn (number durationSeconds, int easing = linearTween);
            fadeOut (number durationSeconds, int easing = linearTween);
            boolean isBehind (Sprite sprite);
            int getZOrder ();
            Sprite moveBehind (Sprite sprite);
            Sprite moveInFrontOf (Sprite sprite);
            Sprite moveToFront ();
            Sprite moveToBack ();
            SpriteLayer getLayer ();
            setDrawHelper (ISpriteDrawHelper helper);
            setPostDrawHelper (ISpriteDrawHelper helper);
            boolean getWantsMouseOverEvents ();
            Sprite setWantsMouseOverEvents (boolean wantsThem = true);
            boolean getWantsClickEvents ();
            Sprite setWantsClickEvents (boolean wantsThem = true);
            number getMouseDetectMode ();
            Sprite setMouseDetectMode (int collisionType = collide_BoundingBox);
            boolean getWantsOffscreenEvents ();
            Sprite setWantsOffscreenEvents (boolean wantsThem = true);
            IEventHandler on (int eventCode, function func);
            IEventHandler onCollideSprite (function func);
            IEventHandler onCollideWall (function func);
            IEventHandler onOffscreen (function func);
            IEventHandler onOnscreen (function func);
            IEventHandler onExitLayer (function func);
            IEventHandler onAnimationLoop (function func);
            IEventHandler onAnimationEnd (function func);
            IEventHandler onAnimationPhysicsRecoveryComplete (function func);
            IEventHandler onAnimationBlendComplete (function func);
            IEventHandler onFadeComplete (function func);
            IEventHandler onFadeInComplete (function func);
            IEventHandler onFadeOutComplete (function func);
            IEventHandler onMouseEnter (function func);
            IEventHandler onMouseLeave (function func);
            IEventHandler onMouseDown (function func);
            IEventHandler onMouseUp (function func);
            IEventHandler onMouseClick (function func);
    };

    class SpriteLayer : public Animated, public EventEmitter, public ISerializable
    {
        public:
            number getMyClassTag ();
            uint getSerializedSize (Serializer serializer);
            serialize (Serializer serializer);
            deserialize (Deserializer deserializer);
            Particle createParticle ();
            addParticle (Particle value);
            removeParticle (Particle value);
            removeAllParticles ();
            uint getParticleCount ();
            Particle getNthParticle (uint value);
            SpriteLayer setMaxParticles (uint value);
            uint getMaxParticles ();
            ParticleEmitter createParticleEmitter ();
            removeParticleEmitter (ParticleEmitter value);
            removeAllParticleEmitters ();
            SpriteLayer setSerializationFlags (uint flags);
            startAnimations ();
            stopAnimations ();
            hide ();
            show ();
            boolean isHidden ();
            fadeIn (number durationSeconds, int easing = linearTween);
            fadeOut (number durationSeconds, int easing = linearTween);
            moveBehind (SpriteLayer layer);
            moveInFrontOf (SpriteLayer layer);
            moveToFront ();
            moveToBack ();
            int getZOrder ();
            moveWith (SpriteLayer layer, number moveRatio = 1.0, number zoomRatio = 1.0);
            Sprite findSprite (int id);
            Sprite getNthSprite (int index);
            int getSpriteZOrder (Sprite sprite);
            boolean isSpriteBehind (Sprite sprite, Sprite otherSprite);
            boolean hasSprite (Sprite sprite);
            addSprite (Sprite newSprite);
            removeSprite (Sprite oldSprite);
            removeAllSprites ();
            enableCollisions ();
            disableCollisions ();
            enableCollisionsWithLayer (SpriteLayer otherLayer);
            disableCollisionsWithLayer (SpriteLayer otherLayer);
            Sprite createSprite ();
            Port getSpritePort ();
            setSpritePort (Port port);
            setOrigin (Point origin);
            Point getOrigin ();
            setAutoCenter (boolean autoCenter = true);
            setFixedMoveAxis (boolean fixedAxis = true);
            setZoom (number zoomLevel);
            number getZoom ();
            zoomTo (number zoomLevel, number durationSeconds, int easing = easeInOutQuad, Rect keepInRect = Rect(0,0), Point centerOn = Point(0,0));
            zoom (number deltaZoomLevel, number durationSeconds, int easing = easeInOutQuad, Rect keepInRect = Rect(0,0), Point centerOn = Point(0,0));
            Point layerToPortPoint (Point p);
            Offset layerToPortOffset (Offset o);
            Vector layerToPortVector (Vector v);
            RotatedRect layerToPortRect (Rect r);
            Quad layerToPortQuad (Quad q);
            Point portToLayerPoint (Point p);
            Offset portToLayerOffset (Offset o);
            Vector portToLayerVector (Vector v);
            RotatedRect portToLayerRect (Rect r);
            Quad portToLayerQuad (Quad q);
            setGravity (number gravity, boolean keepItDownward = true);
            setUseChipmunkPhysics (boolean useIt = true);
            setStaticLayer (boolean isStatic = true);
            setKeepGravityDownward (boolean keepItDownward = true);
            setDamping (number damping);
            CpSpace getSpace ();
            Sprite createSpriteFromSpriterFile (string inFileName, string inEntityName = null);
            Sprite createSpriteFromSpriterEntity (string inEntityName);
            applyCharacterMapToAll (string mapName);
            removeCharacterMapFromAll (string mapName);
            enableSpriterEvents (boolean enable = true);
            IEventHandler on (int eventCode, function func);
            IEventHandler onCollideSprite (function func);
            IEventHandler onCollideWall (function func);
            IEventHandler onOffscreen (function func);
            IEventHandler onOnscreen (function func);
            IEventHandler onExitLayer (function func);
            IEventHandler onAnimationLoop (function func);
            IEventHandler onAnimationEnd (function func);
            IEventHandler onFadeComplete (function func);
            IEventHandler onFadeInComplete (function func);
            IEventHandler onFadeOutComplete (function func);
            IEventHandler onMouseEnter (function func);
            IEventHandler onMouseLeave (function func);
            IEventHandler onMouseDown (function func);
            IEventHandler onMouseUp (function func);
            IEventHandler onMouseClick (function func);
            IEventHandler onErasePort (function func);
            IEventHandler onPreDrawLayer (function func);
            IEventHandler onPostDrawLayer (function func);
            IEventHandler onDrawPortComplete (function func);
            IEventHandler onAnimationStart (function func);
            IEventHandler onPreAnimateLayer (function func);
            IEventHandler onPostAnimateLayer (function func);
            IEventHandler onAnimationComplete (function func);
            IEventHandler onZoomComplete (function func);
            IEventHandler onLayerFadeInComplete (function func);
            IEventHandler onLayerFadeOutComplete (function func);
    };

    class TileLayer : public SpriteLayer
    {
        public:
            setWorldSize (int width, int height, boolean repeatingX = false, boolean repeatingY = false);
            Rect getWorldSize ();
            Rect getWorldBounds ();
            defineTileSet (int tileWidth, int tileHeight, Image tiles, boolean hasTransparency = true, boolean flipTiles = false);
            loadMapData (BinaryString data, int mapWidth = 0, int mapHeight = 0, int dstX, int dstY);
            loadMapData (MemBlock data, int mapWidth = 0, int mapHeight = 0, int dstX, int dstY);
            MemBlock getMapData (int mapWidth = 0, int mapHeight = 0, int srcX, int srcY);
            Image getTileSetImage ();
            Point getTileSize ();
            number getTileTypeAt (int x, int y);
            object getTileTypeAndFacingAt (int x, int y);
            setTileTypeAt (int x, int y, uint t, uint facing = facing_Ignore);
            number checkCollision (Sprite movingSprite, uint alphaThreshold = 128, boolean shortCircuit = true);
    };

    class Image
    {
        public:
            Image (string filename);
            Image (Port port, boolean copyPixels = CopyPixels);
            number getWidth ();
            number getHeight ();
            Rect getImageBounds (Point at);
            Image getSubsection (Quad quad);
            Image getSubsection (Rect quad);
            Image setTransparentColor (Color inTransparentColor);
            number getOpacity ();
            setOpacity (number opacity);
            setEdgeClamping (boolean inUseEdgeClamp);
            Color getTransparentColor ();
            retainData ();
            retainAlpha ();
            number prepareToRasterize ();
            number getAlphaValue (Point p);
            number getAlphaValue (int x, int y);
            Color getPixel (Point p);
            Color getPixel (int x, int y);
            number getMyClassTag ();
            uint getSerializedSize (Serializer serializer);
            serialize (Serializer serializer);
            deserialize (Deserializer deserializer);
    };

    class ImageStrip : public Image
    {
        public:
            Image getFrame (int frameNum);
            number getFrameWidth ();
            ImageStrip setFrameWidth (int inFrameWidth);
            number getNumFrames ();
            ImageStrip setNumFrames (int inNumFrames);
    };

    class Spline
    {
        public:
            Point getFirstOrder (number u);
            Point getSecondOrder (number u);
            addSegment (Point p1, Point p2, Point p3, Point p4);
            addPoint (Point point);
            Point getPoint (number pointIndex);
            setPoint (number pointIndex, Point point);
            number getPointCount ();
            number getMaxU ();
            Rect getBounds ();
    };

    class Polygon
    {
        public:
            addPoint (Point point);
            addSpline (Spline spline);
            insertPoint (uint index, Point point);
            removePoint (uint index);
            uint getPointCount ();
            Point getPoint (uint index);
            setPoint (uint index, Point point);
            clearPoints ();
            Rect getBounds ();
            Point centerPoint ();
            boolean contains (Point point);
            boolean empty ();
            boolean equals (Polygon other);
            Polygon move (Offset offset);
            moveLeft (number delta);
            Polygon moveRight (number delta);
            Polygon moveUp (number delta);
            Polygon moveDown (number delta);
            moveXTo (number x);
            moveYTo (number y);
            moveTo (number x, number y);
            center (Point point);
            scale (number factor);
            horzScale (number factor);
            vertScale (number factor);
            scaleAround (number factor, Point centerPoint);
            rotate (number radians);
            rotateAround (number radians, Point centerPoint);
            Polygon intersection (Polygon other);
            Polygon unionWith (Polygon other);
    };

    class Attributes
    {
        public:
            Attributes withAppearance (Attributes overrides, boolean textOnly = false);
            lineColor (Color color);
            lineThickness (number float thickness);
            lineOpacity (number float opacity);
            lineStyle (int lineStyle);
            fillColor (Color color);
            fillOpacity (number float opacity);
            fillGradient (Point start, Color startColor, Point end, Color endColor);
            fillRadialGradient (Point center, Color centerColor, number float radius, Color endColor);
            roundedCorners (number float radius);
            translation (Offset offset);
            rotation (number float radians, Point center = Point(0,0));
            scale (number float xFactor, number float yFactor = xFactor, Point center = Point(0,0));
            skew (number float xSkew, number float ySkew, Point center = Point(0,0));
            transform (array number matrix);
            Attributes setTransform (array number matrix);
            blendMode (int blendMode);
            textSize (number float size);
            textStyle (int style);
            font (Font font);
            frame (int frame);
            fitType (int fit);
            Attributes clipOverflow (boolean clip);
            subsection (Rect section);
            sphereRotation (number float rotation);
            polarOffset (Offset offset);
            lightOffset (Offset offset);
            ambientLight (Color color);
            texture (Image texture);
            Color getLineColor ();
            number float getLineThickness ();
            number float getLineOpacity ();
            uint getLineStyle ();
            Color getFillColor ();
            number float getFillOpacity ();
            number float getRoundedCornerRadius ();
            int getGradientType ();
            Point getGradientStart ();
            Point getGradientEnd ();
            Color getGradientStartColor ();
            Color getGradientEndColor ();
            Point getRadialGradientCenter ();
            number float getRadialGradientRadius ();
            Color getRadialGradientCenterColor ();
            Color getRadialGradientEndColor ();
            array number getTransform ();
            int getBlendMode ();
            number float getTextSize ();
            int getTextStyle ();
            Font getFont ();
            int getFrame ();
            int getFitType ();
            boolean getClipOverflow ();
            Rect getSubsection ();
            number float getSphereRotation ();
            Offset getPolarOffset ();
            Offset getLightOffset ();
            Color getAmbientLight ();
            Image getTexture ();
    };

    class AnimatedAttributes : public Animated
    {
        public:
            Rect getBoundingBox ();
            RotatedRect getRotatedBounds ();
            Point getLocation ();
            Offset getMovement ();
            Offset getSize ();
            number getWidth ();
            number getHeight ();
            Offset getScale ();
            Offset getStretching ();
            number getRotation ();
            Offset getCenterOffset ();
            number getSpin ();
            Animated setLocation (Point value);
            Animated setLocation (number x, number y);
            Animated moveTo (Point value, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveTo (number x, number y, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveBy (Offset value, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated moveBy (number x, number y, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated setMovement (Vector value);
            Animated setMovement (number xPerSecond, number yPerSecond);
            Animated changeMovementTo (Vector value, number durationSeconds, int easing = linearTween);
            Animated changeMovementTo (number xPerSecond, number yPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeMovementBy (Vector value, number durationSeconds, int easing = linearTween);
            Animated changeMovementBy (number xPerSecond, number yPerSecond, number durationSeconds, int easing = linearTween);
            Animated setSize (Offset value);
            Animated setSize (number width, number height);
            Animated changeCenterOffsetTo (Offset value, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetTo (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetBy (Offset value, number durationSeconds, int easing = easeInOutQuad);
            Animated changeCenterOffsetBy (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated setWidth (number value);
            Animated setHeight (number value);
            Animated setRotation (number value);
            Animated setSpin (number value);
            Animated setGrowing (number value);
            Animated setStretching (number widthPerSecond, number heightPerSecond);
            Animated setScale (number x, number y = x);
            Animated changeSpinTo (number radiansPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeSpinBy (number radiansPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeGrowingTo (number amountPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeGrowingBy (number amountPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeStretchingTo (number widthPerSecond, number heightPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeStretchingBy (number widthPerSecond, number heightPerSecond, number durationSeconds, int easing = linearTween);
            Animated changeScaleTo (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated changeScaleBy (number x, number y, number durationSeconds, int easing = easeInOutQuad);
            Animated grow (number factor, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated stretch (number widthFactor, number heightFactor, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated resizeBy (number deltaWidth, number deltaHeight, number durationSeconds = 0, int easing = easeInOutQuad);
            Animated resizeTo (number width, number height, number durationSeconds, int easing = easeInOutQuad);
            Animated rotateBy (number radians, number durationSeconds = 0, int easing = easeInOutQuad, int direction = rotationDirection_AsSpecified);
            Animated rotateTo (number radians, number durationSeconds = 0, int easing = easeInOutQuad, int direction = rotationDirection_AsSpecified);
            Animated setCenterOffset (Offset offset);
            Animated setFlipX (boolean flip);
            Animated setFlipY (boolean flip);
            Animated stopMovement ();
            Animated stopSpinning ();
            Animated stopGrowing ();
            Animated stopStretching ();
            Animated pauseSchedule ();
            Animated resumeSchedule ();
            Animated cancelSchedule ();
            Animated flipX ();
            Animated flipY ();
            Animated andThen ();
            boolean isFlippedX ();
            boolean isFlippedY ();
            boolean isSchedulePaused ();
            boolean hasScheduledAnimations ();
            Animated wait (number durationSeconds);
            Animated addAnimationHelper (IAnimationHelper helper);
            Animated removeAnimationHelper (IAnimationHelper helper);
            Animated clearAnimationHelpers ();
            Attributes withAppearance (Attributes overrides, boolean textOnly = false);
            lineColor (Color color);
            lineThickness (number float thickness);
            lineOpacity (number float opacity);
            lineStyle (int lineStyle);
            fillColor (Color color);
            fillOpacity (number float opacity);
            fillGradient (Point start, Color startColor, Point end, Color endColor);
            fillRadialGradient (Point center, Color centerColor, number float radius, Color endColor);
            roundedCorners (number float radius);
            translation (Offset offset);
            rotation (number float radians, Point center = Point(0,0));
            scale (number float xFactor, number float yFactor = xFactor, Point center = Point(0,0));
            skew (number float xSkew, number float ySkew, Point center = Point(0,0));
            transform (array number matrix);
            AnimatedAttributes setTransform (array number matrix);
            blendMode (int blendMode);
            textSize (number float size);
            textStyle (int style);
            font (Font font);
            frame (int frame);
            fitType (int fit);
            AnimatedAttributes clipOverflow (boolean clip);
            subsection (Rect section);
            sphereRotation (number float rotation);
            polarOffset (Offset offset);
            lightOffset (Offset offset);
            ambientLight (Color color);
            texture (Image texture);
            Color getLineColor ();
            number float getLineThickness ();
            number float getLineOpacity ();
            uint getLineStyle ();
            Color getFillColor ();
            number float getFillOpacity ();
            number float getRoundedCornerRadius ();
            int getGradientType ();
            Point getGradientStart ();
            Point getGradientEnd ();
            Color getGradientStartColor ();
            Color getGradientEndColor ();
            Point getRadialGradientCenter ();
            number float getRadialGradientRadius ();
            Color getRadialGradientCenterColor ();
            Color getRadialGradientEndColor ();
            array number getTransform ();
            int getBlendMode ();
            number float getTextSize ();
            int getTextStyle ();
            Font getFont ();
            int getFrame ();
            int getFitType ();
            boolean getClipOverflow ();
            Rect getSubsection ();
            number float getSphereRotation ();
            Offset getPolarOffset ();
            Offset getLightOffset ();
            Color getAmbientLight ();
            Image getTexture ();
            boolean animate (number deltaSeconds);
            AnimatedAttributes changeLineColor (Color target, number seconds, int easing = linearTween);
            AnimatedAttributes changeLineThickness (number target, number seconds, int easing = linearTween);
            AnimatedAttributes changeLineOpacity (number target, number seconds, int easing = linearTween);
            AnimatedAttributes changeFillColor (Color target, number seconds, int easing = linearTween);
            AnimatedAttributes changeFillOpacity (number target, number seconds, int easing = linearTween);
            AnimatedAttributes changeRoundedCorners (number target, number seconds, int easing = linearTween);
            AnimatedAttributes changeTextSize (number target, number seconds, int easing = linearTween);
            AnimatedAttributes changeSubsection (Rect target, number seconds, int easing = linearTween);
            AnimatedAttributes changePolarOffset (Offset target, number seconds, int easing = linearTween);
            AnimatedAttributes changeLightOffset (Offset target, number seconds, int easing = linearTween);
            AnimatedAttributes changeAmbientLight (Color target, number seconds, int easing = linearTween);
            AnimatedAttributes changeFillGradient (Point start, Color startColor, Point end, Color endColor, number seconds, int easing = linearTween);
            AnimatedAttributes changeFillRadialGradient (Point center, Color centerColor, number radius, Color endColor, number seconds, int easing = linearTween);
            AnimatedAttributes changeSphereRotation (number radians, number seconds, int easing = linearTween, int direction = rotationDirection_AsSpecified);
            AnimatedAttributes changeFrames (int first, int last, number seconds, int easing = linearTween);
            AnimatedAttributes changeSkew (number x, number y, number seconds, int easing = linearTween);
            AnimatedAttributes changeTransform (array number matrix, number seconds, int easing = linearTween);
    };

    class ElementRef
    {
        public:
            uint type ();
            array getControlPoints ();
            Point getControlPoint (uint controlPointIndex);
            changeControlPoint (uint controlPointIndex, Point controlPoint);
            Attributes getAttributes ();
            setAttributes (Attributes attrs);
            setLiveAttributes (Attributes attrs);
            clearLiveAttributes ();
            boolean hasLiveAttributes ();
            moveForward ();
            moveBackward ();
            moveToFront ();
            moveToBack ();
            remove ();
    };

    class Drawing
    {
        public:
            ElementRef addLine (Point from, Point to, Attributes attrs);
            ElementRef addSpline (Spline spline, Attributes attrs);
            ElementRef addRect (Rect rect, Attributes attrs);
            ElementRef addArc (Point center, number xRadius, number yRadius, number startAngle, number endAngle, Attributes attrs);
            ElementRef addQuad (Quad quad, Attributes attrs);
            ElementRef addPolygon (Polygon polygon, Attributes attrs);
            ElementRef addEllipse (Point center, number xRadius, number yRadius, Attributes attrs);
            ElementRef addImage (Rect rect, Image image, Attributes attrs);
            ElementRef addImageStrip (Rect rect, ImageStrip imageStrip, Attributes attrs);
            ElementRef addDrawing (Rect rect, Drawing drawing, Attributes attrs);
            uint getElementCount ();
            ElementRef getElement (uint index);
            ElementRef getElementHitBy (Point point);
            Rect getBounds ();
            Point centerPoint ();
            boolean empty ();
            draw (Port port);
    };

    class Font
    {
        public:
            string getFontName ();
            number getFontHeight (number size, int style = textStyle_Plain);
            number getFontLeading (number size, int style = textStyle_Plain);
            number getFontCapHeight (number size, int style = textStyle_Plain);
            number getFontAscent (number size, int style = textStyle_Plain);
            number getFontDescent (number size, int style = textStyle_Plain);
    };

    class Port
    {
        public:
            Rect getClipRect ();
            Port setClipRect (Rect inClipRect);
            resetClipRect ();
            clear (Color color = TRANSPARENT_COLOR);
            setDrawingOrigin (Point origin);
            Image getCursor ();
            setCursor (Image cursorImage, Point hotSpot);
            Rect getDrawingArea ();
            drawLine (Point from, Point to, Attributes attrs);
            drawSpline (Spline spline, Attributes attrs);
            drawText (string text, Point loc, Attributes attrs);
            drawText (string text, Rect rect, Attributes attrs);
            drawImage (Image img, Point loc, Attributes attrs);
            drawImage (Image img, Rect rect, Attributes attrs);
            drawImage (Image img, Quad quad, Attributes attrs);
            number getTextWidth (string text, int size, uint style = textStyle_Plain, int len = -1);
            Font getCurrentFont (uint style = textStyle_Plain);
            setFont (Font font = DEFAULT_FONT);
            setFontForStyle (uint style, Font font = DEFAULT_FONT);
            setFontScalingFactor (number scaleBy);
            number startTrackingMouse (Rect rect);
            stopTrackingMouse (int trackingRef);
            resetCursor ();
            drawRect (Rect rect, Attributes attrs);
            drawQuad (Quad quad, Attributes attrs);
            drawPolygon (Polygon polygon, Attributes attrs);
            drawEllipse (Point center, number float xRadius, number float yRadius, Attributes attrs);
            drawArc (Point center, number float xRadius, number float yRadius, number float startAngle, number float endAngle, Attributes attrs);
            drawBezier (Point from, Point control1, Point control2, Point to, Attributes attrs);
            drawCircle (Point center, number float radius, Attributes attrs);
            drawVector (Vector vector, Attributes attrs);
            drawRoundedRect (Rect rect, number float radius, Attributes attrs);
            drawDrawing (Drawing drawing, Point loc, Attributes attrs);
            drawDrawing (Drawing drawing, Rect rect, Attributes attrs);
            drawSphere (Point center, number float radius, Attributes attrs);
    };

    class GraphicsManager
    {
        public:
            number getNumScreens ();
            number getFPS ();
            number getTargetFPS ();
            GraphicsManager setTargetFPS (number inTargetFPS);
            Point getMouse (int mouseNumber = 0);
            object getCurrentScreenMode (int screenNum = PRIMARY_SCREEN);
            Rect getScreenBounds (int screenNum = PRIMARY_SCREEN);
            number getNumSupportedScreenModes (int screen = PRIMARY_SCREEN);
            object getNthSupportedScreenMode (int n, int screenNum = PRIMARY_SCREEN);
            setScreenMode (int width, int height, int screenNum = PRIMARY_SCREEN, int bpp = 0);
            Port createWindowPort (Rect rect, string windName = "", int bpp = 0);
            Port createOffscreenPort (Rect rect);
            Port createFullScreenPort (Rect rect, int screenNum = PRIMARY_SCREEN, boolean allowResChange = true, int bpp = 0);
            closeGraphicsPort (Port port = MAIN_PORT);
            closeAllGraphicsPorts ();
            Font createFont (string fontName, number scalingFactor = 1.0);
            Port getMainPort ();
            boolean switchToFullScreenMode (boolean allowResChange = false, Port port = MAIN_PORT);
            boolean switchToWindowMode (Port port = MAIN_PORT, string windName = "");
            boolean inFullScreenMode ();
    };

    class Sound : public EventEmitter
    {
        public:
            number getVolume ();
            Sound setVolume (number inVolume);
            play (number vol = 1.0, int offsetX = 0, number pitch = 0, uint fromMs = 0, int lenMs = ENTIRE_LENGTH);
            start ();
            stop ();
            pause ();
            resume ();
            boolean isPaused ();
            Sound setLooping (boolean loopingOn);
            boolean isLooping ();
            Sound setPitch (number pitchOffset);
            changePitch (number targetOffset, int msDuration, int easing = easeInOutQuad);
            Sound setOffsetX (int offsetX);
            changeOffsetX (int targetOffset, int msDuration, int easing = linearTween);
            fadeOut (uint fadeMs, int easing = linearTween);
            fadeIn (uint fadeMs, int easing = linearTween);
            changeVolume (number level, uint fadeMs, int easing = linearTween);
            Sound skip (int skipMilliseconds);
            Sound skipTo (uint timeMs);
            IEventHandler on (int eventCode, function func);
            IEventHandler onDonePlaying (function func);
            IEventHandler onLooping (function func);
            IEventHandler onFailedToPlay (function func);
    };

    class SoundManager
    {
        public:
            setVolume (number level);
            setMute (boolean muted);
            IEventHandler on (int eventCode, function func);
            IEventHandler onDonePlaying (function func);
            IEventHandler onLooping (function func);
            IEventHandler onFailedToPlay (function func);
    };

    class Point : public Offset
    {
        public:
            number x;
            number y;
            Point ();
            Point (number x, number y);
            Point (number[] xy);
            Point (object xy);
            number distance (Point point);
            Offset offset (Point point);
    };

    class Offset
    {
        public:
            number x;
            number y;
            Offset ();
            Offset (number x, number y);
            Offset (number[] xy);
            Offset (object xy);
            boolean equals (Offset offset);
            boolean notEquals (Offset offset);
            Offset assign (Offset offset);
            Offset add (Offset offset);
            Offset sub (Offset offset);
            Offset mul (Offset offset);
            Offset div (Offset offset);
            Offset plus (Offset offset);
            Offset minus (Offset offset);
            Offset times (Offset offset);
            Offset dividedby (Offset offset);
            Vector vector ();
    };

    class Vector : public Offset
    {
        public:
            number x;
            number y;
            Vector ();
            Vector (number x, number y);
            Vector (number[] xy);
            Vector (object xy);
            Vector unit ();
            Vector normal ();
            number dotProduct (Vector vector);
            number vectorLength ();
            number vectorAngle ();
            Point projection (Point point);
    };

    class Rect
    {
        public:
            number left;
            number top;
            number right;
            number bottom;
            Rect ();
            Rect (number w, number h);
            Rect (Point topLeft, number w, number h);
            Rect (Point leftTop, Point rightBottom);
            Rect (number left, number top, number right, number bottom);
            boolean empty ();
            boolean contains (Rect r);
            boolean contains (Point p);
            boolean overlaps (Rect r);
            Point leftTop ();
            Point rightTop ();
            Point leftBottom ();
            Point rightBottom ();
            Point centerPoint ();
            number x1 ();
            number y1 ();
            number x2 ();
            number y2 ();
            number width ();
            number height ();
            Rect intersection (Rect r);
            Rect unionWith (Rect r);
            moveLeft (number delta);
            moveRight (number delta);
            moveUp (number delta);
            moveDown (number delta);
            moveXTo (number x);
            moveYTo (number y);
            moveTo (number x, number y);
            moveTo (Point p);
            center (Rect r);
            center (Point p);
            setSize (number n);
            setWidth (number w);
            setHeight (number h);
            horzShrink (number delta);
            vertShrink (number delta);
            horzGrow (number delta);
            vertGrow (number delta);
            shrink (number delta);
            grow (number delta);
            horzScale (number f);
            vertScale (number f);
            scale (number f);
            round ();
            Quad toQuad ();
            boolean equals (Rect r2);
            boolean notEquals (Rect r2);
            Rect assign (Rect r2);
            Rect add (Rect r2);
            Rect add (Point p);
            Rect sub (Rect r2);
            Rect sub (Point p);
            Rect mul (Rect r2);
            Rect mul (Point p);
            Rect div (Rect r2);
            Rect div (Point p);
            Rect plus (Rect r2);
            Rect plus (Point p);
            Rect minus (Rect r2);
            Rect minus (Point p);
            Rect times (Rect r2);
            Rect times (Point p);
            Rect dividedby (Rect r2);
            Rect dividedby (Point p);
    };

    class Quad
    {
        public:
            Point[] points;
            Quad ();
            Quad (Quad q);
            Quad (Rect r);
            Quad (RotatedRect r);
            Quad (Point p1, Point p2, Point p3, Point p4);
            Quad (Point[] p);
            Rect getBounds ();
            Point centerPoint ();
            boolean equals (Quad q2);
            boolean notEquals (Quad q2);
            boolean contains (Point p);
            moveLeft (number delta);
            moveRight (number delta);
            moveUp (number delta);
            moveDown (number delta);
            rotate (number rotationRadians, Offset centerPtOffset = Point(0,0));
    };

    class RotatedRect : public Rect
    {
        public:
            number left;
            number top;
            number right;
            number bottom;
            number radians;
            Point centerOffset;
            RotatedRect (Rect rect = Rect(0,0), number rotationRadians = 0.0, Offset cpOffset = null);
            setCenterOffset (Offset cpOffset);
            setRotation (number rotationRadians, Offset cpOffset = null);
            rotate (number rotateRadians);
            Quad getQuad ();
    };

    class Color
    {
        public:
            number alpha;
            number red;
            number green;
            number blue;
            Color ();
            Color (number c);
            Color (string colorstr);
            Color (number r, number g, number b, number alpha = 1);
            boolean equals (Color color);
            boolean notEquals (Color color);
            Color assign (Color color);
            convertToGrayscale ();
    };

    class NetConnection
    {
        public:
            string localAddr;
            number localPort;
            string remoteAddr;
            number remotePort;
            boolean hasDgram;
            NetConnection (object socket);
            close (boolean kill);
            NetConnection onClose (function callback);
            NetConnection onMessage (function callback);
            send (string message);
            send (MemBlock message);
            send (ISerializable message);
            send (object message);
            sendDgram (string message);
            sendDgram (MemBlock message);
            sendDgram (ISerializable message);
            sendDgram (object message);
    };

    class NetClient
    {
        public:
            boolean connection;
            NetClient (object opts = null);
            NetClient connect (object serverInfo, function callback, string clientKey = "");
            NetClient onError (function callback);
    };

    class NetServer
    {
        public:
            object serverInfo;
            number serverPort;
            string serverAddr;
            number handshakeTimeout;
            boolean reservationRequired;
            boolean allowDatagram;
            boolean listening;
            NetConnection[] connections;
            NetServer (object opts = null);
            NetServer listen (function callback);
            number broadcast (object message, function filter = null);
            NetServer expectClient (string clientKey, string clientIpAddr = '*', int reservationTTL = FOREVER, boolean singleUse = false);
            NetServer onError (function callback);
            shutdown (boolean closeExisting = true, boolean kill = false);
    };

    class AnimationSpringTarget
    {
        public:
            AnimationSpringTarget (number mass = 1, number stiffness = 100, number damping = 20);
            object getState ();
            setState (object state);
            applyImpulse (number x, number y);
            object update (number targetX, number targetY, number deltaSeconds);
    };

    class AnimationContactTarget
    {
        public:
            AnimationContactTarget ();
            object getState ();
            lockWorld (number x, number y);
            lockPlatform (number x, number y, number support, object frame);
            release (number fadeSeconds = 0);
            object update (number deltaSeconds, boolean contactActive, boolean withinReach, number support = 0, object frame = undefined, number releaseSeconds = 0);
    };

}
