// this file was automatically generated by "pdg tools/make-idl.js --doxygen-h-format --mvc"

/**
\page javascript_mvc_inventory JavaScript MVC module inventory
These exports belong to the separate MVC module, not to the pdg root object.
See \ref javascript_mvc_guide for imports, lifecycle, and a View example.
\note API stability: Evolving. Exports and own prototype/static members only. Unresolved signatures and instance fields require explicit contracts.
| Export | Kind | Base classes |
| --- | --- | --- |
| CLIP_TEXT | string |  |
| DESCRIPTION | string |  |
| FLICK_DECAY_FACTOR | number |  |
| FLICK_FRAME_RATE | number |  |
| FLICK_MAX_MOUSE_UNMOVED_MS | number |  |
| HIGHLIGHT_AREA_MARGIN | number |  |
| HOT_ITEM_NONE | number |  |
| IMAGE_HEIGHT_OFFSET | number |  |
| ITEM_DOWN_ARROW | number |  |
| ITEM_SIZE_OFFSET | number |  |
| ITEM_UP_ARROW | number |  |
| LEFT_MARGIN | number |  |
| MAX_ARROW_IMAGES | number |  |
| MAX_BUTTON_IMAGES | number |  |
| MAX_MENU_WIDTH | number |  |
| MAX_RADIO_IMAGES | number |  |
| RES_MENU_IMAGES | number |  |
| RES_PULL_ARROW | number |  |
| RIGHT_MARGIN | number |  |
| START_INDEX_NONE | number |  |
| TEXT_HEIGHT_OFFSET | number |  |
| TEXT_LEFT_MARGIN | number |  |
| TEXT_RESOURCE_ID_NONE | number |  |
| TEXT_WIDTH_OFFSET | number |  |
| VERSION | string |  |
| VIEW_HEIGHT_OFFSET | number |  |
| VIEW_HSHIFT_OFFSET | number |  |
| VIEW_WIDTH_OFFSET | number |  |
| Application | object |  |
| Application.AppStates | object |  |
| Application.AppStates.state_Cleanup | number |  |
| Application.AppStates.state_FirstUserState | number |  |
| Application.AppStates.state_Initializing | number |  |
| Application.AppStates.state_Running | number |  |
| Application.Application | class |  |
| Application.NoManagerError | class | Error |
| AppStates | object |  |
| AppStates.state_Cleanup | number |  |
| AppStates.state_FirstUserState | number |  |
| AppStates.state_Initializing | number |  |
| AppStates.state_Running | number |  |
| Button | object |  |
| Button.MAX_BUTTON_IMAGES | number |  |
| Button.RES_DEFAULT_BUTTON_IMAGE_NAMES | object |  |
| Button.RES_DEFAULT_BUTTON_IMAGE_NAMES.0 | string |  |
| Button.RES_DEFAULT_BUTTON_IMAGE_NAMES.1 | string |  |
| Button.RES_DEFAULT_BUTTON_IMAGE_NAMES.2 | string |  |
| Button.RES_DEFAULT_BUTTON_IMAGE_NAMES.length | number |  |
| Button.Button | class | View |
| CBImages | object |  |
| CBImages.CLOSED | number |  |
| CBImages.NUM_CHECKBOX_IMAGES | number |  |
| CBImages.OPEN | number |  |
| Checkbox | object |  |
| Checkbox.CBImages | object |  |
| Checkbox.CBImages.CLOSED | number |  |
| Checkbox.CBImages.NUM_CHECKBOX_IMAGES | number |  |
| Checkbox.CBImages.OPEN | number |  |
| Checkbox.CheckboxClickIDs | object |  |
| Checkbox.CheckboxClickIDs.CLICK_ID_CHECKBOX | number |  |
| Checkbox.Checkbox | class | View |
| CheckboxClickIDs | object |  |
| CheckboxClickIDs.CLICK_ID_CHECKBOX | number |  |
| ClickablePartsIDs | object |  |
| ClickablePartsIDs.CLICKED_PART_NONE | number |  |
| ControlAttributes | object |  |
| ControlAttributes.ControlState | object |  |
| ControlAttributes.ControlState.Count | number |  |
| ControlAttributes.ControlState.Decrement | number |  |
| ControlAttributes.ControlState.DecrementPressed | number |  |
| ControlAttributes.ControlState.Disabled | number |  |
| ControlAttributes.ControlState.Hovered | number |  |
| ControlAttributes.ControlState.Increment | number |  |
| ControlAttributes.ControlState.IncrementPressed | number |  |
| ControlAttributes.ControlState.Normal | number |  |
| ControlAttributes.ControlState.Pressed | number |  |
| ControlAttributes.ControlState.Selected | number |  |
| ControlAttributes.ControlState.SelectedDisabled | number |  |
| ControlAttributes.ControlState.Thumb | number |  |
| ControlAttributes.ControlType | object |  |
| ControlAttributes.ControlType.Button | number |  |
| ControlAttributes.ControlType.Checkbox | number |  |
| ControlAttributes.ControlType.Dialog | number |  |
| ControlAttributes.ControlType.Other | number |  |
| ControlAttributes.ControlType.RadioButton | number |  |
| ControlAttributes.ControlType.Scrollbar | number |  |
| ControlAttributes.ControlAttributes | class |  |
| ControlAttributes.ControlStateAttributes | class |  |
| Controller | object |  |
| Controller.ControllerPreferences | object |  |
| Controller.ControllerPreferences.kDontDrawWhileInactive | boolean |  |
| Controller.ControllerPreferences.kDontWantAllEvents | boolean |  |
| Controller.ControllerPreferences.kDontWantKeyPressEvents | boolean |  |
| Controller.ControllerPreferences.kDontWantKeyUpDownEvents | boolean |  |
| Controller.ControllerPreferences.kDontWantMouseEnterLeaveEvents | boolean |  |
| Controller.ControllerPreferences.kDrawWhileInactive | boolean |  |
| Controller.ControllerPreferences.kWantAllEvents | boolean |  |
| Controller.ControllerPreferences.kWantKeyPressEvents | boolean |  |
| Controller.ControllerPreferences.kWantKeyUpDownEvents | boolean |  |
| Controller.ControllerPreferences.kWantMouseEnterLeaveEvents | boolean |  |
| Controller.Controller | class |  |
| ControllerPreferences | object |  |
| ControllerPreferences.kDontDrawWhileInactive | boolean |  |
| ControllerPreferences.kDontWantAllEvents | boolean |  |
| ControllerPreferences.kDontWantKeyPressEvents | boolean |  |
| ControllerPreferences.kDontWantKeyUpDownEvents | boolean |  |
| ControllerPreferences.kDontWantMouseEnterLeaveEvents | boolean |  |
| ControllerPreferences.kDrawWhileInactive | boolean |  |
| ControllerPreferences.kWantAllEvents | boolean |  |
| ControllerPreferences.kWantKeyPressEvents | boolean |  |
| ControllerPreferences.kWantKeyUpDownEvents | boolean |  |
| ControllerPreferences.kWantMouseEnterLeaveEvents | boolean |  |
| ControlState | object |  |
| ControlState.Count | number |  |
| ControlState.Decrement | number |  |
| ControlState.DecrementPressed | number |  |
| ControlState.Disabled | number |  |
| ControlState.Hovered | number |  |
| ControlState.Increment | number |  |
| ControlState.IncrementPressed | number |  |
| ControlState.Normal | number |  |
| ControlState.Pressed | number |  |
| ControlState.Selected | number |  |
| ControlState.SelectedDisabled | number |  |
| ControlState.Thumb | number |  |
| ControlType | object |  |
| ControlType.Button | number |  |
| ControlType.Checkbox | number |  |
| ControlType.Dialog | number |  |
| ControlType.Other | number |  |
| ControlType.RadioButton | number |  |
| ControlType.Scrollbar | number |  |
| Dialog | object |  |
| Dialog.DIALOG_BACKGROUND_VIEW_ID | number |  |
| Dialog.DialogFlags | object |  |
| Dialog.DialogFlags.dialog_Centered | number |  |
| Dialog.DialogFlags.dialog_CreateBackground | number |  |
| Dialog.DialogFlags.dialog_NonModal | number |  |
| Dialog.DialogFlags.dialog_ReservedFlag | number |  |
| Dialog.DialogFlags.dialog_Standard | number |  |
| Dialog.DialogResult | object |  |
| Dialog.DialogResult.kAccepted | boolean |  |
| Dialog.DialogResult.kCancelled | boolean |  |
| Dialog.Dialog | class | Controller |
| Dialog.DialogBackgroundView | class | View |
| DialogBorderView | undefined |  |
| DialogFlags | object |  |
| DialogFlags.dialog_Centered | number |  |
| DialogFlags.dialog_CreateBackground | number |  |
| DialogFlags.dialog_NonModal | number |  |
| DialogFlags.dialog_ReservedFlag | number |  |
| DialogFlags.dialog_Standard | number |  |
| DialogResult | object |  |
| DialogResult.kAccepted | boolean |  |
| DialogResult.kCancelled | boolean |  |
| EditText | object |  |
| EditText.LEFT_MARGIN | number |  |
| EditText.RIGHT_MARGIN | number |  |
| EditText.TEXT_HEIGHT_OFFSET | number |  |
| EditText.EditTextClickIDs | object |  |
| EditText.EditTextClickIDs.CLICK_ID_EDITBOXVIEW | number |  |
| EditText.EditText | class | View |
| EditTextClickIDs | object |  |
| EditTextClickIDs.CLICK_ID_EDITBOXVIEW | number |  |
| ListBox | object |  |
| ListBox.ListBoxClickIDs | object |  |
| ListBox.ListBoxClickIDs.VIEW_ID_LIST_BOX_SCROLLBAR | number |  |
| ListBox.ListBoxClickIDs.VIEW_ID_SELECTION_START | number |  |
| ListBox.ListBoxSelectionIDs | object |  |
| ListBox.ListBoxSelectionIDs.NO_SELECTION | number |  |
| ListBox.ListBox | class | View |
| ListBox.ListBoxLine | class |  |
| ListBoxClickIDs | object |  |
| ListBoxClickIDs.VIEW_ID_LIST_BOX_SCROLLBAR | number |  |
| ListBoxClickIDs.VIEW_ID_SELECTION_START | number |  |
| ListBoxSelectionIDs | object |  |
| ListBoxSelectionIDs.NO_SELECTION | number |  |
| MessageDialog | object |  |
| MessageDialog.MessageDialogButtonText | object |  |
| MessageDialog.MessageDialogButtonText.CANCEL | number |  |
| MessageDialog.MessageDialogButtonText.LOAD | number |  |
| MessageDialog.MessageDialogButtonText.NO | number |  |
| MessageDialog.MessageDialogButtonText.NONE | number |  |
| MessageDialog.MessageDialogButtonText.OK | number |  |
| MessageDialog.MessageDialogButtonText.SAVE | number |  |
| MessageDialog.MessageDialogButtonText.YES | number |  |
| MessageDialog.MessageDialogViewIDs | object |  |
| MessageDialog.MessageDialogViewIDs.VIEW_FIRST_BUTTON_ID | number |  |
| MessageDialog.MessageDialogViewIDs.VIEW_ID_BORDER | number |  |
| MessageDialog.MessageDialogViewIDs.VIEW_ID_BUTTON_1 | number |  |
| MessageDialog.MessageDialogViewIDs.VIEW_ID_BUTTON_2 | number |  |
| MessageDialog.MessageDialogViewIDs.VIEW_ID_MESSAGE_VIEW | number |  |
| MessageDialog.MessageDialogViewIDs.VIEW_LAST_BUTTON_ID | number |  |
| MessageDialog.MessageDialog | class | Dialog |
| MessageDialog.MessageDialogBorderView | class | View |
| MessageDialog.MessageDialogView | class | View |
| MessageDialogButtonText | object |  |
| MessageDialogButtonText.CANCEL | number |  |
| MessageDialogButtonText.LOAD | number |  |
| MessageDialogButtonText.NO | number |  |
| MessageDialogButtonText.NONE | number |  |
| MessageDialogButtonText.OK | number |  |
| MessageDialogButtonText.SAVE | number |  |
| MessageDialogButtonText.YES | number |  |
| MessageDialogViewIDs | object |  |
| MessageDialogViewIDs.VIEW_FIRST_BUTTON_ID | number |  |
| MessageDialogViewIDs.VIEW_ID_BORDER | number |  |
| MessageDialogViewIDs.VIEW_ID_BUTTON_1 | number |  |
| MessageDialogViewIDs.VIEW_ID_BUTTON_2 | number |  |
| MessageDialogViewIDs.VIEW_ID_MESSAGE_VIEW | number |  |
| MessageDialogViewIDs.VIEW_LAST_BUTTON_ID | number |  |
| MessageView | object |  |
| MessageView.MessageView | class | View |
| ModalController | object |  |
| ModalController.ModalController | class | Controller |
| Observer | object |  |
| Observer.IObserver | class |  |
| Observer.Subject | class |  |
| PopupMenu | object |  |
| PopupMenu.CLIP_TEXT | string |  |
| PopupMenu.HIGHLIGHT_AREA_MARGIN | number |  |
| PopupMenu.HOT_ITEM_NONE | number |  |
| PopupMenu.IMAGE_HEIGHT_OFFSET | number |  |
| PopupMenu.ITEM_DOWN_ARROW | number |  |
| PopupMenu.ITEM_SIZE_OFFSET | number |  |
| PopupMenu.ITEM_UP_ARROW | number |  |
| PopupMenu.MAX_ARROW_IMAGES | number |  |
| PopupMenu.MAX_MENU_WIDTH | number |  |
| PopupMenu.RES_MENU_IMAGES | number |  |
| PopupMenu.RES_PULL_ARROW | number |  |
| PopupMenu.START_INDEX_NONE | number |  |
| PopupMenu.TEXT_LEFT_MARGIN | number |  |
| PopupMenu.TEXT_RESOURCE_ID_NONE | number |  |
| PopupMenu.TEXT_WIDTH_OFFSET | number |  |
| PopupMenu.VIEW_HEIGHT_OFFSET | number |  |
| PopupMenu.VIEW_HSHIFT_OFFSET | number |  |
| PopupMenu.VIEW_WIDTH_OFFSET | number |  |
| PopupMenu.ItemInfo | class |  |
| PopupMenu.PopupMenu | class | View |
| RadioButton | object |  |
| RadioButton.MAX_RADIO_IMAGES | number |  |
| RadioButton.RadioButton | class | View |
| RES_DEFAULT_BUTTON_IMAGE_NAMES | object |  |
| RES_DEFAULT_BUTTON_IMAGE_NAMES.0 | string |  |
| RES_DEFAULT_BUTTON_IMAGE_NAMES.1 | string |  |
| RES_DEFAULT_BUTTON_IMAGE_NAMES.2 | string |  |
| RES_DEFAULT_BUTTON_IMAGE_NAMES.length | number |  |
| Scrollbar | object |  |
| Scrollbar.ScrollbarClickIDs | object |  |
| Scrollbar.ScrollbarClickIDs.CLICK_ID_SCROLL_DOWN | number |  |
| Scrollbar.ScrollbarClickIDs.CLICK_ID_SCROLL_UP | number |  |
| Scrollbar.ScrollbarClickIDs.CLICK_ID_SLIDER_AREA | number |  |
| Scrollbar.ScrollbarImages | object |  |
| Scrollbar.ScrollbarImages.MAX_SCROLL_BAR_IMAGES | number |  |
| Scrollbar.ScrollbarImages.SCROLL_DOWN | number |  |
| Scrollbar.ScrollbarImages.SCROLL_DOWN_CLICKED | number |  |
| Scrollbar.ScrollbarImages.SCROLL_SLIDER | number |  |
| Scrollbar.ScrollbarImages.SCROLL_UP | number |  |
| Scrollbar.ScrollbarImages.SCROLL_UP_CLICKED | number |  |
| Scrollbar.ScrollbarOrientation | object |  |
| Scrollbar.ScrollbarOrientation.HORIZONTAL | number |  |
| Scrollbar.ScrollbarOrientation.VERTICAL | number |  |
| Scrollbar.ScrollbarOrientation.VERTICAL_UP_IS_BIGGER | number |  |
| Scrollbar.Scrollbar | class | View |
| ScrollbarClickIDs | object |  |
| ScrollbarClickIDs.CLICK_ID_SCROLL_DOWN | number |  |
| ScrollbarClickIDs.CLICK_ID_SCROLL_UP | number |  |
| ScrollbarClickIDs.CLICK_ID_SLIDER_AREA | number |  |
| ScrollbarImages | object |  |
| ScrollbarImages.MAX_SCROLL_BAR_IMAGES | number |  |
| ScrollbarImages.SCROLL_DOWN | number |  |
| ScrollbarImages.SCROLL_DOWN_CLICKED | number |  |
| ScrollbarImages.SCROLL_SLIDER | number |  |
| ScrollbarImages.SCROLL_UP | number |  |
| ScrollbarImages.SCROLL_UP_CLICKED | number |  |
| ScrollbarOrientation | object |  |
| ScrollbarOrientation.HORIZONTAL | number |  |
| ScrollbarOrientation.VERTICAL | number |  |
| ScrollbarOrientation.VERTICAL_UP_IS_BIGGER | number |  |
| ScrollingView | object |  |
| ScrollingView.ScrollingViewBindType | object |  |
| ScrollingView.ScrollingViewBindType.bind_Bottom | number |  |
| ScrollingView.ScrollingViewBindType.bind_Centers | number |  |
| ScrollingView.ScrollingViewBindType.bind_CenterX | number |  |
| ScrollingView.ScrollingViewBindType.bind_CenterY | number |  |
| ScrollingView.ScrollingViewBindType.bind_Default | number |  |
| ScrollingView.ScrollingViewBindType.bind_Left | number |  |
| ScrollingView.ScrollingViewBindType.bind_LimitX | number |  |
| ScrollingView.ScrollingViewBindType.bind_LimitXY | number |  |
| ScrollingView.ScrollingViewBindType.bind_LimitY | number |  |
| ScrollingView.ScrollingViewBindType.bind_None | number |  |
| ScrollingView.ScrollingViewBindType.bind_Right | number |  |
| ScrollingView.ScrollingViewBindType.bind_Top | number |  |
| ScrollingView.ScrollingView | class | View |
| ScrollingViewBindType | object |  |
| ScrollingViewBindType.bind_Bottom | number |  |
| ScrollingViewBindType.bind_Centers | number |  |
| ScrollingViewBindType.bind_CenterX | number |  |
| ScrollingViewBindType.bind_CenterY | number |  |
| ScrollingViewBindType.bind_Default | number |  |
| ScrollingViewBindType.bind_Left | number |  |
| ScrollingViewBindType.bind_LimitX | number |  |
| ScrollingViewBindType.bind_LimitXY | number |  |
| ScrollingViewBindType.bind_LimitY | number |  |
| ScrollingViewBindType.bind_None | number |  |
| ScrollingViewBindType.bind_Right | number |  |
| ScrollingViewBindType.bind_Top | number |  |
| TouchController | object |  |
| TouchController.FLICK_DECAY_FACTOR | number |  |
| TouchController.FLICK_FRAME_RATE | number |  |
| TouchController.FLICK_MAX_MOUSE_UNMOVED_MS | number |  |
| TouchController.TouchController | class | ModalController |
| View | object |  |
| View.ClickablePartsIDs | object |  |
| View.ClickablePartsIDs.CLICKED_PART_NONE | number |  |
| View.ViewBinding | object |  |
| View.ViewBinding.bind_Bottom | number |  |
| View.ViewBinding.bind_Left | number |  |
| View.ViewBinding.bind_Right | number |  |
| View.ViewBinding.bind_Top | number |  |
| View.ViewBinding.grow | number |  |
| View.ViewBinding.grow_Horz | number |  |
| View.ViewBinding.grow_Vert | number |  |
| View.View | class | AnimatedAttributes |
| ViewBinding | object |  |
| ViewBinding.bind_Bottom | number |  |
| ViewBinding.bind_Left | number |  |
| ViewBinding.bind_Right | number |  |
| ViewBinding.bind_Top | number |  |
| ViewBinding.grow | number |  |
| ViewBinding.grow_Horz | number |  |
| ViewBinding.grow_Vert | number |  |
| ControlStateAttributes | class |  |
| IObserver | class |  |
| ItemInfo | class |  |
| ListBoxLine | class |  |
| MessageViewStandalone | class | View |
| NoManagerError | class | Error |
| Subject | class |  |
\section mvc_export_Application_Application Application.Application
Constructor signatures and instance properties are not inferred by constructing objects.
- \c cleanup (function).
- \c destroy (function).
- \c enterState (function).
- \c getConfigManager (function).
- \c getEventManager (function).
- \c getGraphicsManager (function).
- \c getLogManager (function).
- \c getNetworkManager (function).
- \c getResourceManager (function).
- \c getSoundManager (function).
- \c getState (function).
- \c getTimerManager (function).
- \c initialize (function).
- \c leaveState (function).
- \c onShutdown (function).
- \c preloadResources (function).
- \c setState (function).
- \c setupControllers (function).
- \c setupGraphics (function).
\section mvc_export_Application_NoManagerError Application.NoManagerError
Constructor signatures and instance properties are not inferred by constructing objects.
\section mvc_export_Button_Button Button.Button
Constructor signatures and instance properties are not inferred by constructing objects.
- \c destroy (function).
- \c doLeftClick (function).
- \c doMouseDown (function).
- \c doMouseEnter (function).
- \c doMouseLeave (function).
- \c doMouseMove (function).
- \c doMouseUp (function).
- \c drawSelf (function).
- \c drawStandardButtonBackground (function).
- \c drawText (function).
- \c drawWithImages (function).
- \c finishInitButton (function).
- \c getAttributes (function).
- \c getButtonID (function).
- \c getText (function).
- \c initializeButton (function).
- \c isMouseInToolArea (function).
- \c isPressed (function).
- \c loadImages (function).
- \c setAttributes (function).
- \c setClickSound (function).
- \c setClickState (function).
- \c setText (function).
- \c setTextFromResource (function).
- \c setTextSize (function).
- \c setToolTipText (function).
- \c showToolTip (function).
- \c updateLayout (function).
- \c viewAreaChanged (function).
\section mvc_export_Checkbox_Checkbox Checkbox.Checkbox
Constructor signatures and instance properties are not inferred by constructing objects.
- \c calcClickableAreas (function).
- \c createPlaceholderImages (function).
- \c destroy (function).
- \c doClick (function).
- \c doLeftClick (function).
- \c drawCheckmark (function).
- \c drawSelf (function).
- \c drawStandardCheckbox (function).
- \c drawText (function).
- \c drawWithImages (function).
- \c getAttributes (function).
- \c getClickSound (function).
- \c getString (function).
- \c getTextMetrics (function).
- \c getTextSize (function).
- \c isChecked (function).
- \c loadImages (function).
- \c setAttributes (function).
- \c setChecked (function).
- \c setClickSound (function).
- \c setEnabled (function).
- \c setString (function).
- \c setTextSize (function).
- \c toggle (function).
\section mvc_export_ControlAttributes_ControlAttributes ControlAttributes.ControlAttributes
Constructor signatures and instance properties are not inferred by constructing objects.
- \c clickRoutine (function).
- \c clickSound (function).
- \c draw (function).
- \c getClickSound (function).
- \c getClickVolume (function).
- \c hasClickRoutine (function).
- \c hasClickSound (function).
- \c merge (function).
- \c playClick (function).
- \c state (function).
- \c stateAttributes (function).
- \c stateDrawRoutine (function).
- \c stateForeground (function).
- \c stateImage (function).
\section mvc_export_ControlAttributes_ControlStateAttributes ControlAttributes.ControlStateAttributes
Constructor signatures and instance properties are not inferred by constructing objects.
- \c backgroundImage (function).
- \c customDraw (function).
- \c drawAttributes (function).
- \c foregroundColor (function).
- \c merge (function).
\section mvc_export_Controller_Controller Controller.Controller
Constructor signatures and instance properties are not inferred by constructing objects.
- \c addChild (function).
- \c addView (function).
- \c addViewBehind (function).
- \c animateViews (function).
- \c attemptChildClose (function).
- \c cancelMousePress (function).
- \c childActivated (function).
- \c destroy (function).
- \c doDoubleClick (function).
- \c doDragComplete (function).
- \c doDragIn (function).
- \c doDragMove (function).
- \c doDragOut (function).
- \c doKeyDown (function).
- \c doKeyPress (function).
- \c doKeyUp (function).
- \c doLeftClick (function).
- \c doMouseDown (function).
- \c doMouseEnter (function).
- \c doMouseLeave (function).
- \c doMouseMove (function).
- \c doMouseUp (function).
- \c doRightClick (function).
- \c drawViews (function).
- \c getApplication (function).
- \c getControlAttributes (function).
- \c getHitView (function).
- \c getTopController (function).
- \c getUntypedView (function).
- \c getView (function).
- \c handleEvent (function).
- \c isActive (function).
- \c isViewWithin (function).
- \c onKeyDown (function).
- \c onKeyPress (function).
- \c onKeyUp (function).
- \c onMouseDown (function).
- \c onMouseEnter (function).
- \c onMouseLeave (function).
- \c onMouseMove (function).
- \c onMouseUp (function).
- \c onPortDraw (function).
- \c onPortResized (function).
- \c onScrollWheel (function).
- \c portWasResized (function).
- \c removeAllViews (function).
- \c removeChild (function).
- \c removeView (function).
- \c removeViewById (function).
- \c setActive (function).
- \c setParent (function).
- \c setPort (function).
- \c setupViews (function).
- \c startBeingDragTarget (function).
- \c stopBeingDragTarget (function).
\section mvc_export_Dialog_Dialog Dialog.Dialog
Constructor signatures and instance properties are not inferred by constructing objects.
- \c childActivated (function).
- \c destroy (function).
- \c doClose (function).
- \c doKeyPress (function).
- \c doLeftClick (function).
- \c doMouseDown (function).
- \c doMouseUp (function).
- \c getCancelButtonId (function).
- \c getDialogRect (function).
- \c getFlags (function).
- \c getOkButtonId (function).
- \c hideDialog (function).
- \c isCentered (function).
- \c isModal (function).
- \c isVisible (function).
- \c portWasResized (function).
- \c setDialogRect (function).
- \c showDialog (function).
\section mvc_export_Dialog_DialogBackgroundView Dialog.DialogBackgroundView
Constructor signatures and instance properties are not inferred by constructing objects.
- \c drawSelf (function).
\section mvc_export_EditText_EditText EditText.EditText
Constructor signatures and instance properties are not inferred by constructing objects.
- \c calcClickableAreas (function).
- \c canFitInDisplayArea (function).
- \c clearSelection (function).
- \c deleteSelection (function).
- \c destroy (function).
- \c doDoubleClick (function).
- \c doKeyPress (function).
- \c doMouseDown (function).
- \c doMouseMove (function).
- \c doMouseUp (function).
- \c drawBorder (function).
- \c drawCaret (function).
- \c drawSelection (function).
- \c drawSelf (function).
- \c drawText (function).
- \c getBufMax (function).
- \c getCaretPositionFromPoint (function).
- \c getSelectedText (function).
- \c getText (function).
- \c getTextWidth (function).
- \c handleBackspace (function).
- \c handleDelete (function).
- \c handleEvent (function).
- \c handleLeftArrow (function).
- \c handlePrintableChar (function).
- \c handleRightArrow (function).
- \c hasFocus (function).
- \c hasSelection (function).
- \c isCharAllowed (function).
- \c isPrintableChar (function).
- \c loadString (function).
- \c replaceSelection (function).
- \c selectAll (function).
- \c setBackgroundColor (function).
- \c setBufMax (function).
- \c setFilter (function).
- \c setFocus (function).
- \c setFontSize (function).
- \c setText (function).
- \c setTextColor (function).
\section mvc_export_ListBox_ListBox ListBox.ListBox
Constructor signatures and instance properties are not inferred by constructing objects.
- \c addToList (function).
- \c calcClickableAreas (function).
- \c clear (function).
- \c clearSelection (function).
- \c createScrollbar (function).
- \c destroy (function).
- \c doClick (function).
- \c doDoubleClick (function).
- \c doKeyPress (function).
- \c doMouseDown (function).
- \c doScrollWheel (function).
- \c drawListItems (function).
- \c drawSelf (function).
- \c ensureItemVisible (function).
- \c findItem (function).
- \c getItem (function).
- \c getItemCount (function).
- \c getLineIndexFromPoint (function).
- \c getSelectedIndex (function).
- \c getSelectedText (function).
- \c getTextFromIndex (function).
- \c loadImages (function).
- \c moveSelection (function).
- \c needsScrollbar (function).
- \c notify (function).
- \c onItemDoubleClick (function).
- \c removeItem (function).
- \c setBackgroundColor (function).
- \c setHighlightColor (function).
- \c setItemColors (function).
- \c setItemText (function).
- \c setSelectedIndex (function).
- \c viewAreaChanged (function).
\section mvc_export_ListBox_ListBoxLine ListBox.ListBoxLine
Constructor signatures and instance properties are not inferred by constructing objects.
\section mvc_export_MessageDialog_MessageDialog MessageDialog.MessageDialog
Constructor signatures and instance properties are not inferred by constructing objects.
- Static \c createOKCancelDialog (function).
- Static \c createOKDialog (function).
- Static \c createSaveCancelDialog (function).
- Static \c createYesNoDialog (function).
- \c doClose (function).
- \c doLeftClick (function).
- \c getButtonClickedId (function).
- \c getMessageCode (function).
- Static \c getTextForButton (function).
- \c setMessageCode (function).
- \c setupDialog (function).
- \c showModal (function).
- Static \c showOKCancelDialog (function).
- Static \c showOKDialog (function).
- Static \c showSaveCancelDialog (function).
- Static \c showYesNoDialog (function).
- Static \c withCustomButtons (function).
\section mvc_export_MessageDialog_MessageDialogBorderView MessageDialog.MessageDialogBorderView
Constructor signatures and instance properties are not inferred by constructing objects.
- \c drawSelf (function).
- \c setBorderColor (function).
- \c setBorderWidth (function).
\section mvc_export_MessageDialog_MessageDialogView MessageDialog.MessageDialogView
Constructor signatures and instance properties are not inferred by constructing objects.
- \c drawSelf (function).
- \c setMessage (function).
- \c setTextColor (function).
- \c setTextSize (function).
\section mvc_export_MessageView_MessageView MessageView.MessageView
Constructor signatures and instance properties are not inferred by constructing objects.
- \c append (function).
- \c clear (function).
- \c destroy (function).
- \c doKeyPress (function).
- \c doMouseWheel (function).
- \c drawMessageText (function).
- \c drawSelf (function).
- \c getBackgroundColor (function).
- \c getCharAt (function).
- \c getLength (function).
- \c getLine (function).
- \c getLineCount (function).
- \c getLineSpacing (function).
- \c getMargins (function).
- \c getMaxLines (function).
- \c getMessage (function).
- \c getScrollOffset (function).
- \c getScrollPercentage (function).
- \c getTextAlignment (function).
- \c getTextColor (function).
- \c getTextSize (function).
- \c getTextStyle (function).
- \c getTextX (function).
- \c getWordWrap (function).
- \c getWrappedLines (function).
- \c insert (function).
- \c isEmpty (function).
- \c isNotEmpty (function).
- \c isScrollingNeeded (function).
- \c prepend (function).
- \c remove (function).
- \c replace (function).
- \c scrollDown (function).
- \c scrollUp (function).
- \c setBackgroundColor (function).
- \c setLineSpacing (function).
- \c setMargins (function).
- \c setMaxLines (function).
- \c setMessage (function).
- \c setScrollOffset (function).
- \c setScrollPercentage (function).
- \c setTextAlignment (function).
- \c setTextColor (function).
- \c setTextSize (function).
- \c setTextStyle (function).
- \c setWordWrap (function).
- \c updateScrollLimits (function).
- \c wrapText (function).
\section mvc_export_ModalController_ModalController ModalController.ModalController
Constructor signatures and instance properties are not inferred by constructing objects.
- \c activateModal (function).
- \c addChild (function).
- \c attemptChildClose (function).
- \c closeModal (function).
- \c deactivateModal (function).
- \c destroy (function).
- \c doKeyDown (function).
- \c doKeyPress (function).
- \c doKeyUp (function).
- \c doMouseDown (function).
- \c doMouseUp (function).
- \c getModalStack (function).
- \c handleClickOutside (function).
- \c handleEscapeKey (function).
- \c handleEvent (function).
- \c handleModalEvents (function).
- \c hideModal (function).
- \c isModal (function).
- \c isModalActive (function).
- \c isPointInModalArea (function).
- \c isTopModal (function).
- \c removeChild (function).
- \c setModal (function).
- \c showModal (function).
\section mvc_export_Observer_IObserver Observer.IObserver
Constructor signatures and instance properties are not inferred by constructing objects.
- \c notify (function).
\section mvc_export_Observer_Subject Observer.Subject
Constructor signatures and instance properties are not inferred by constructing objects.
- \c addObserver (function).
- \c clearObservers (function).
- \c getObserverCount (function).
- \c hasObserver (function).
- \c notifyObservers (function).
- \c removeObserver (function).
\section mvc_export_PopupMenu_ItemInfo PopupMenu.ItemInfo
Constructor signatures and instance properties are not inferred by constructing objects.
- \c equals (function).
\section mvc_export_PopupMenu_PopupMenu PopupMenu.PopupMenu
Constructor signatures and instance properties are not inferred by constructing objects.
- \c addDrawableItemPart (function).
- \c addMenuItem (function).
- \c calcClickableAreas (function).
- \c deleteAllMenuItems (function).
- \c deleteMenuItemByIndex (function).
- \c deleteMenuItemByItemID (function).
- \c destroy (function).
- \c doMouseEnter (function).
- \c doMouseLeave (function).
- \c doMouseMove (function).
- \c drawArrow (function).
- \c drawMenuItems (function).
- \c drawScrollArrows (function).
- \c drawSelf (function).
- \c getHotItem (function).
- \c getIndex (function).
- \c getIndexByText (function).
- \c getItemCount (function).
- \c getItemStringByIndex (function).
- \c getItemStringByItemID (function).
- \c getPartClicked (function).
- \c hide (function).
- \c loadImages (function).
- \c loadString (function).
- \c sanitiseViewArea (function).
- \c scrollMenu (function).
- \c setHotItem (function).
- \c setLongestText (function).
- \c setStringByIndex (function).
- \c setStringByItemID (function).
- \c setTextSize (function).
- \c showSelf (function).
- \c viewAreaChanged (function).
\section mvc_export_RadioButton_RadioButton RadioButton.RadioButton
Constructor signatures and instance properties are not inferred by constructing objects.
- \c addString (function).
- \c calcClickableAreas (function).
- \c clearStrings (function).
- \c destroy (function).
- \c doClick (function).
- \c doKeyPress (function).
- \c doLeftClick (function).
- \c doMouseDown (function).
- \c drawRadioCircle (function).
- \c drawRadioOptions (function).
- \c drawSelf (function).
- \c findString (function).
- \c getAllStrings (function).
- \c getAttributes (function).
- \c getOptionCount (function).
- \c getSelectedIndex (function).
- \c getSelectedText (function).
- \c getString (function).
- \c getTextSize (function).
- \c isOptionSelected (function).
- \c loadImages (function).
- \c loadStrings (function).
- \c moveSelection (function).
- \c removeString (function).
- \c selectFirst (function).
- \c selectLast (function).
- \c selectNext (function).
- \c selectPrevious (function).
- \c setAllStrings (function).
- \c setAttributes (function).
- \c setClickSound (function).
- \c setSelectedIndex (function).
- \c setString (function).
- \c setTextSize (function).
\section mvc_export_Scrollbar_Scrollbar Scrollbar.Scrollbar
Constructor signatures and instance properties are not inferred by constructing objects.
- \c addObserver (function).
- \c calcClickableAreas (function).
- \c createPlaceholderImages (function).
- \c decrementExtent (function).
- \c destroy (function).
- \c doMouseDown (function).
- \c doMouseLeave (function).
- \c doMouseMove (function).
- \c doMouseUp (function).
- \c doScrollWheel (function).
- \c drawArrow (function).
- \c drawButton (function).
- \c drawScrollBar (function).
- \c drawSelf (function).
- \c drawSlider (function).
- \c getAttributes (function).
- \c getCurrentPosition (function).
- \c getDownButtonRect (function).
- \c getOrientation (function).
- \c getScrollRange (function).
- \c getSliderRect (function).
- \c getUpButtonRect (function).
- \c handleEvent (function).
- \c incrementExtent (function).
- \c isButtonPressed (function).
- \c loadImages (function).
- \c notifyObservers (function).
- \c removeObserver (function).
- \c scrollDown (function).
- \c scrollDownFullWindow (function).
- \c scrollDownPressed (function).
- \c scrollDownReleased (function).
- \c scrollSliderAreaPressed (function).
- \c scrollSliderAreaReleased (function).
- \c scrollUp (function).
- \c scrollUpFullWindow (function).
- \c scrollUpPressed (function).
- \c scrollUpReleased (function).
- \c setAttributes (function).
- \c setCurrentPosition (function).
- \c setMaxRange (function).
- \c setMinRange (function).
- \c setPageSize (function).
- \c setStepSize (function).
- \c setVisibleAmount (function).
- \c thumbDimensions (function).
- \c trackScrollSlider (function).
- \c updateSliderPosition (function).
- \c viewAreaChanged (function).
\section mvc_export_ScrollingView_ScrollingView ScrollingView.ScrollingView
Constructor signatures and instance properties are not inferred by constructing objects.
- \c adjustViewAreaToFrame (function).
- \c applyAutoAdjust (function).
- \c draw (function).
- \c getAutoAdjust (function).
- \c getMaxScrollOffset (function).
- \c getMinScrollOffset (function).
- \c getModifiableViewFrameRect (function).
- \c getScrollOffset (function).
- \c getScrollPercentage (function).
- \c getViewFrame (function).
- \c getVisibleArea (function).
- \c getVisibleFrame (function).
- \c isAtBottom (function).
- \c isAtLeft (function).
- \c isAtRight (function).
- \c isAtTop (function).
- \c isScrollingNeeded (function).
- \c isViewWithinFrame (function).
- \c moveView (function).
- \c pointInViewFrame (function).
- \c pointInViewVisibleArea (function).
- \c portResized (function).
- \c scrollBy (function).
- \c scrollTo (function).
- \c scrollToBottom (function).
- \c scrollToLeft (function).
- \c scrollToRight (function).
- \c scrollToTop (function).
- \c setAutoAdjust (function).
- \c setScrollOffset (function).
- \c setScrollPercentage (function).
- \c setViewFrame (function).
- Static \c withPort (function).
\section mvc_export_TouchController_TouchController TouchController.TouchController
Constructor signatures and instance properties are not inferred by constructing objects.
- \c calculateDistance (function).
- \c calculateFlickVelocity (function).
- \c destroy (function).
- \c doMouseDown (function).
- \c doMouseMove (function).
- \c doMouseUp (function).
- \c doPinchMove (function).
- \c doSnapback (function).
- \c doSwipeMove (function).
- \c doTap (function).
- \c doTouch (function).
- \c doTouchMove (function).
- \c getFlickVelocity (function).
- \c getTouchDuration (function).
- \c getTouchMovePoints (function).
- \c getTouchStartPoint (function).
- \c handleEvent (function).
- \c handleTap (function).
- \c handleTouchMove (function).
- \c isFlickGesture (function).
- \c isTouchActive (function).
- \c removeView (function).
- \c setFlickVelocity (function).
- \c startFlick (function).
- \c stopFlick (function).
- \c updateFlick (function).
\section mvc_export_View_View View.View
Constructor signatures and instance properties are not inferred by constructing objects.
- \c viewArea (accessor).
- \c addClickablePart (function).
- \c animate (function).
- \c destroy (function).
- \c doDoubleClick (function).
- \c doDragComplete (function).
- \c doDragIn (function).
- \c doDragMove (function).
- \c doDragOut (function).
- \c doLeftClick (function).
- \c doMouseDown (function).
- \c doMouseEnter (function).
- \c doMouseLeave (function).
- \c doMouseMove (function).
- \c doMouseUp (function).
- \c doPinchMove (function).
- \c doRightClick (function).
- \c doScrollWheel (function).
- \c doSwipeMove (function).
- \c doTap (function).
- \c doTouchMove (function).
- \c draw (function).
- \c drawClickableParts (function).
- \c drawSelf (function).
- \c getClickableRectFromID (function).
- \c getController (function).
- \c getDrawingAttributes (function).
- \c getHitView (function).
- \c getID (function).
- \c getLayoutTransform (function).
- \c getParentView (function).
- \c getPartClicked (function).
- \c getPort (function).
- \c getViewArea (function).
- \c getVisibleFrame (function).
- \c globalToLocal (function).
- \c globalToLocalRect (function).
- \c hide (function).
- \c hideSelf (function).
- \c isDraggable (function).
- \c isEnabled (function).
- \c isVisible (function).
- \c localToGlobal (function).
- \c localToGlobalRect (function).
- \c pointInViewArea (function).
- \c pointInViewVisibleArea (function).
- \c portResized (function).
- \c removeClickablePart (function).
- \c setDraggable (function).
- \c setEnabled (function).
- \c setID (function).
- \c setMaxSize (function).
- \c setMinSize (function).
- \c setParentView (function).
- \c setPort (function).
- \c setViewArea (function).
- \c setWantsMouseOvers (function).
- \c show (function).
- \c showSelf (function).
- \c startBeingDragTarget (function).
- \c stopBeingDragTarget (function).
- \c viewAreaChanged (function).
- \c wantsMouseOvers (function).
- Static \c withPort (function).
\section mvc_export_ControlStateAttributes ControlStateAttributes
Constructor signatures and instance properties are not inferred by constructing objects.
- \c backgroundImage (function).
- \c customDraw (function).
- \c drawAttributes (function).
- \c foregroundColor (function).
- \c merge (function).
\section mvc_export_IObserver IObserver
Constructor signatures and instance properties are not inferred by constructing objects.
- \c notify (function).
\section mvc_export_ItemInfo ItemInfo
Constructor signatures and instance properties are not inferred by constructing objects.
- \c equals (function).
\section mvc_export_ListBoxLine ListBoxLine
Constructor signatures and instance properties are not inferred by constructing objects.
\section mvc_export_MessageViewStandalone MessageViewStandalone
Constructor signatures and instance properties are not inferred by constructing objects.
- \c append (function).
- \c clear (function).
- \c destroy (function).
- \c doKeyPress (function).
- \c doMouseWheel (function).
- \c drawMessageText (function).
- \c drawSelf (function).
- \c getBackgroundColor (function).
- \c getCharAt (function).
- \c getLength (function).
- \c getLine (function).
- \c getLineCount (function).
- \c getLineSpacing (function).
- \c getMargins (function).
- \c getMaxLines (function).
- \c getMessage (function).
- \c getScrollOffset (function).
- \c getScrollPercentage (function).
- \c getTextAlignment (function).
- \c getTextColor (function).
- \c getTextSize (function).
- \c getTextStyle (function).
- \c getTextX (function).
- \c getWordWrap (function).
- \c getWrappedLines (function).
- \c insert (function).
- \c isEmpty (function).
- \c isNotEmpty (function).
- \c isScrollingNeeded (function).
- \c prepend (function).
- \c remove (function).
- \c replace (function).
- \c scrollDown (function).
- \c scrollUp (function).
- \c setBackgroundColor (function).
- \c setLineSpacing (function).
- \c setMargins (function).
- \c setMaxLines (function).
- \c setMessage (function).
- \c setScrollOffset (function).
- \c setScrollPercentage (function).
- \c setTextAlignment (function).
- \c setTextColor (function).
- \c setTextSize (function).
- \c setTextStyle (function).
- \c setWordWrap (function).
- \c updateScrollLimits (function).
- \c wrapText (function).
\section mvc_export_NoManagerError NoManagerError
Constructor signatures and instance properties are not inferred by constructing objects.
\section mvc_export_Subject Subject
Constructor signatures and instance properties are not inferred by constructing objects.
- \c addObserver (function).
- \c clearObservers (function).
- \c getObserverCount (function).
- \c hasObserver (function).
- \c notifyObservers (function).
- \c removeObserver (function).
*/
