// -----------------------------------------------
// animation_bindings.h
//
// Header file that contains animation-related interface declarations
// for pdg classes that are exposed to scripting languages
//
// Written by Ed Zavada, 2013
// Copyright (c) 2013, Dream Rock Studios, LLC
// All Rights Reserved Worldwide
// -----------------------------------------------

// Include the interface declarations for animation classes

#ifdef PDG_GENERATING_DOCS
#include "../../tools/js_docs_macros.h"
namespace pdg {
#else

#undef THIS // eliminate warning about Windows duplicate Macro
#include "pdg_script_macros.h"
#include "animation_macros.h"
#include "../core/core_macros.h"
#include "../data/data_macros.h"

%#ifndef PDG_ANIMATION_BINDINGS_H_INCLUDED
%#define PDG_ANIMATION_BINDINGS_H_INCLUDED

%#include "pdg_project.h"

%#include "pdg_script_impl.h"
%#include "pdg_script_interface.h"

%#ifndef PDG_NO_APP_FRAMEWORK
%#define PDG_NO_APP_FRAMEWORK
%#endif
%#include "pdg/framework.h"

%#include <cstdlib>

namespace pdg {

#endif //!PDG_GENERATING_DOCS

BINDING_CLASS(IAnimationHelper)
DECL_END


BINDING_CLASS(AnimatedBase)
  ANIMATED_METHODS(AnimatedBase)
	METHOD(AnimatedBase, Animate)
// 	METHOD(AnimatedBase, OnLocationChanged)
// 	METHOD(AnimatedBase, OnSizeChanged)
// 	METHOD(AnimatedBase, OnRotationChanged)
// 	METHOD(AnimatedBase, OnCenterChanged)
DECL_END

BINDING_CLASS(Troupe)
    METHOD(Troupe, RecordCommand)
    ANIMATED_METHODS(Troupe)
    METHOD(Troupe, Animate)
    METHOD(Troupe, Add)
    METHOD(Troupe, Remove)
    METHOD(Troupe, Clear)
    METHOD(Troupe, Contains)
    METHOD(Troupe, GetMemberCount)
DECL_END

BINDING_CLASS(AnimationScript)
    METHOD(AnimationScript, RecordCommand)
    ANIMATED_METHODS(AnimationScript)
    METHOD(AnimationScript, EndScript)
DECL_END

%#ifdef PDG_SPRITER_SUPPORT
BINDING_CLASS(Bone)
    METHOD(Bone, DiminishInfluence)
    METHOD(Bone, Animate)
    ANIMATED_METHODS(Bone)
    METHOD(Bone, GetId)
    METHOD(Bone, GetName)
    METHOD(Bone, GetSprite)
    METHOD(Bone, IsAttached)
    METHOD(Bone, GetInfluence)
    METHOD(Bone, SetIKLimits)
    METHOD(Bone, ClearIKLimits)
    METHOD(Bone, HasIKLimits)
    METHOD(Bone, GetIKMinAngle)
    METHOD(Bone, GetIKMaxAngle)
DECL_END

%#endif // PDG_SPRITER_SUPPORT

BINDING_CLASS(CollisionQueryBuffer)
    METHOD(CollisionQueryBuffer, GetPointX)
    METHOD(CollisionQueryBuffer, GetPointY)
    METHOD(CollisionQueryBuffer, GetNormalX)
    METHOD(CollisionQueryBuffer, GetNormalY)
    METHOD(CollisionQueryBuffer, GetCapacity)
    METHOD(CollisionQueryBuffer, GetCount)
    METHOD(CollisionQueryBuffer, IsOverflowed)
    METHOD(CollisionQueryBuffer, Clear)
    METHOD(CollisionQueryBuffer, GetCollider)
    METHOD(CollisionQueryBuffer, GetShapeId)
    METHOD(CollisionQueryBuffer, GetPoint)
    METHOD(CollisionQueryBuffer, GetNormal)
    METHOD(CollisionQueryBuffer, GetFraction)
    METHOD(CollisionQueryBuffer, GetDistance)
    METHOD(CollisionQueryBuffer, GetInitialOverlap)
    METHOD(CollisionQueryBuffer, Configure)
    METHOD(CollisionQueryBuffer, SelectLayers)
    METHOD(CollisionQueryBuffer, AddLayer)
    METHOD(CollisionQueryBuffer, ExcludeCollider)
    METHOD(CollisionQueryBuffer, ExcludeBody)
    METHOD(CollisionQueryBuffer, SetPredicate)
DECL_END

BINDING_CLASS(Scene)
    EMITTER_METHODS(Scene)
    METHOD(Scene, Raycast)
    METHOD(Scene, SweepCircle)
    METHOD(Scene, OverlapPoint)
    METHOD(Scene, OverlapCircle)
    METHOD(Scene, OverlapBox)
    METHOD(Scene, OverlapCapsule)
    METHOD(Scene, NearestPoint)
    METHOD(Scene, AddLayer)
    METHOD(Scene, RemoveLayer)
    METHOD(Scene, DisposeLayer)
    METHOD(Scene, CreateSpriteLayer)
    METHOD(Scene, GetLayer)
    METHOD(Scene, Pause)
    METHOD(Scene, Resume)
    METHOD(Scene, Dispose)
    METHOD(Scene, CancelAllTimers)
    METHOD(Scene, IsPaused)
    METHOD(Scene, IsDisposed)
    METHOD(Scene, GetLayerCount)
    METHOD(Scene, GetTimeScale)
    METHOD(Scene, GetFixedStep)
    METHOD(Scene, GetSimulationTime)
    METHOD(Scene, GetDroppedTime)
    METHOD(Scene, GetInterpolationAlpha)
    METHOD(Scene, GetTick)
    METHOD(Scene, IsInputEnabled)
    METHOD(Scene, IsManual)
    METHOD(Scene, IsInterpolationEnabled)
    METHOD(Scene, SetTimeScale)
    METHOD(Scene, SetFixedStep)
    METHOD(Scene, Advance)
    METHOD(Scene, SetManual)
    METHOD(Scene, SetInputEnabled)
    METHOD(Scene, SetInterpolation)
    METHOD(Scene, GetCamera)
    METHOD(Scene, SetCamera)
    METHOD(Scene, StartTimer)
    METHOD(Scene, CancelTimer)
    METHOD(Scene, PauseTimer)
    METHOD(Scene, UnpauseTimer)
    METHOD(Scene, DelayTimer)
    METHOD(Scene, IsTimerPaused)
    METHOD(Scene, GetWhenTimerFiresNext)
DECL_END

BINDING_CLASS(Camera)
    ANIMATED_METHODS(Camera)
    EMITTER_METHODS(Camera)
    PROPERTY(Camera, Zoom)
    PROPERTY(Camera, PixelSnapping)
    METHOD(Camera, Zoom)
    METHOD(Camera, ZoomTo)
    METHOD(Camera, Animate)
    METHOD(Camera, Follow)
    METHOD(Camera, StopFollowing)
    METHOD(Camera, IsFollowing)
    METHOD(Camera, SetSmoothing)
    METHOD(Camera, GetSmoothing)
    METHOD(Camera, SetLookAhead)
    METHOD(Camera, GetLookAhead)
    METHOD(Camera, SetDeadzone)
    METHOD(Camera, GetDeadzone)
    METHOD(Camera, SetFollowOffset)
    METHOD(Camera, GetFollowOffset)
    METHOD(Camera, SetViewBounds)
    METHOD(Camera, ClearViewBounds)
    METHOD(Camera, HasViewBounds)
    METHOD(Camera, GetViewBounds)
    METHOD(Camera, SetViewport)
    METHOD(Camera, GetViewport)
    METHOD(Camera, WorldToView)
    METHOD(Camera, ViewToWorld)
    METHOD(Camera, GetEffects)
    METHOD(Camera, Flash)
    METHOD(Camera, GetFlashOpacity)
    METHOD(Camera, Show)
    METHOD(Camera, Hide)
    METHOD(Camera, IsHidden)
    METHOD(Camera, SetOpacity)
    METHOD(Camera, GetOpacity)
    METHOD(Camera, FadeTo)
    METHOD(Camera, FadeIn)
    METHOD(Camera, FadeOut)
    METHOD(Camera, CutTo)
    METHOD(Camera, MatchCutTo)
    METHOD(Camera, MatchFadeTo)
    METHOD(Camera, TransitionTo)
    METHOD(Camera, LumaFadeTo)
    METHOD(Camera, WhipPanTo)
%#ifndef PDG_NO_GUI
%#endif
DECL_END

BINDING_CLASS(Particle)
    ANIMATED_METHODS(Particle)
    EMITTER_METHODS(Particle)
    METHOD(Particle, ReadPhysics)
    METHOD(Particle, SetupPhysicsBody)
    METHOD(Particle, RemovePhysicsBody)
    METHOD(Particle, ReadCollider)
    METHOD(Particle, SetupCollider)
    METHOD(Particle, RemoveCollider)
    METHOD(Particle, SetupParticleEmitter)
    METHOD(Particle, GetParticleEmitter)
    METHOD(Particle, RemoveParticleEmitter)
    METHOD(Particle, SetTrail)
    METHOD(Particle, ClearTrail)
    METHOD(Particle, BreakTrail)
    METHOD(Particle, HasTrail)
    METHOD(Particle, GetTrailPointCount)
    METHOD(Particle, ClearContent)
    METHOD(Particle, HasContent)
    METHOD(Particle, SetOpacity)
    METHOD(Particle, GetOpacity)
    METHOD(Particle, FadeTo)
    METHOD(Particle, SetLifetime)
    METHOD(Particle, GetLifetime)
    METHOD(Particle, GetAge)
    METHOD(Particle, IsAlive)
    METHOD(Particle, Expire)
    METHOD(Particle, GetLayer)
    METHOD(Particle, Animate)
%#ifndef PDG_NO_GUI
    METHOD(Particle, SetImage)
    METHOD(Particle, SetDrawing)
%#endif
DECL_END

BINDING_CLASS(ParticleEmitter)
    ANIMATED_METHODS(ParticleEmitter)
    METHOD(ParticleEmitter, SetParticleTemplate)
    METHOD(ParticleEmitter, HasParticleTemplate)
    METHOD(ParticleEmitter, SetEmissionRate)
    METHOD(ParticleEmitter, GetEmissionRate)
    METHOD(ParticleEmitter, SetParticleSpeed)
    METHOD(ParticleEmitter, GetMinParticleSpeed)
    METHOD(ParticleEmitter, GetMaxParticleSpeed)
    METHOD(ParticleEmitter, SetSpread)
    METHOD(ParticleEmitter, GetSpread)
    METHOD(ParticleEmitter, SetVelocityInheritance)
    METHOD(ParticleEmitter, GetVelocityInheritance)
    METHOD(ParticleEmitter, SetSeed)
    METHOD(ParticleEmitter, GetSeed)
    METHOD(ParticleEmitter, StartEmitting)
    METHOD(ParticleEmitter, StopEmitting)
    METHOD(ParticleEmitter, IsEmitting)
    METHOD(ParticleEmitter, Emit)
    METHOD(ParticleEmitter, GetLayer)
    METHOD(ParticleEmitter, GetParticle)
    METHOD(ParticleEmitter, Animate)
DECL_END

BINDING_CLASS(Collider)
    METHOD(Collider, SetFriction)
    METHOD(Collider, SetRestitution)
    METHOD(Collider, GetFriction)
    METHOD(Collider, GetRestitution)
    METHOD(Collider, UseBodyMaterial)

    METHOD(Collider, SetWantsContactEvents)
    METHOD(Collider, GetWantsContactEvents)
    METHOD(Collider, IsPresent)
    METHOD(Collider, IsAttached)
    METHOD(Collider, IsEnabled)
    METHOD(Collider, IsSensor)
    METHOD(Collider, GetId)
    METHOD(Collider, GetCategory)
    METHOD(Collider, GetCollisionMask)
    METHOD(Collider, GetGroup)
    METHOD(Collider, GetShapeCount)
    METHOD(Collider, SetEnabled)
    METHOD(Collider, SetSensor)
    METHOD(Collider, SetCategory)
    METHOD(Collider, SetCollisionMask)
    METHOD(Collider, SetGroup)
    METHOD(Collider, GetPhysicsBody)
    METHOD(Collider, SetCircle)
    METHOD(Collider, AddCircle)
    METHOD(Collider, SetCapsule)
    METHOD(Collider, AddCapsule)
    METHOD(Collider, GetCapsuleStart)
    METHOD(Collider, GetCapsuleEnd)
    METHOD(Collider, GetCapsuleRadius)
    METHOD(Collider, SetBox)
    METHOD(Collider, AddBox)
    METHOD(Collider, ClearShapes)
    METHOD(Collider, UseOwnerPhysics)
    METHOD(Collider, SetPhysicsBody)
    METHOD(Collider, GetBounds)
    METHOD(Collider, Contains)
    METHOD(Collider, Overlaps)
    METHOD(Collider, RemoveShape)
    METHOD(Collider, GetShapeId)
    METHOD(Collider, GetContactError)
    METHOD(Collider, AddPolygon)
    METHOD(Collider, SetPolygon)
    METHOD(Collider, SetImageMask)
    METHOD(Collider, AddImageMask)
    METHOD(Collider, GetGeometrySource)
    METHOD(Collider, IsSourceShape)
    METHOD(Collider, GetShapeName)
    METHOD(Collider, GetShapeType)
    METHOD(Collider, GetCircleRadius)
    METHOD(Collider, SetContactHandler)
    METHOD(Collider, SetCollisionFilter)

DECL_END

BINDING_CLASS(PhysicsConstraint)
    METHOD(PhysicsConstraint, IsActive)
    METHOD(PhysicsConstraint, IsBroken)
    METHOD(PhysicsConstraint, GetCollideBodies)
    METHOD(PhysicsConstraint, GetType)
    METHOD(PhysicsConstraint, GetMaxForce)
    METHOD(PhysicsConstraint, GetBreakForce)
    METHOD(PhysicsConstraint, GetImpulse)
    METHOD(PhysicsConstraint, GetForce)
    METHOD(PhysicsConstraint, SetCollideBodies)
    METHOD(PhysicsConstraint, SetMaxForce)
    METHOD(PhysicsConstraint, SetBreakForce)
    METHOD(PhysicsConstraint, GetBodyA)
    METHOD(PhysicsConstraint, GetBodyB)
    METHOD(PhysicsConstraint, GetAnchorA)
    METHOD(PhysicsConstraint, GetAnchorB)
    METHOD(PhysicsConstraint, SetAnchorA)
    METHOD(PhysicsConstraint, SetAnchorB)
    METHOD(PhysicsConstraint, SetAnchors)
    METHOD(PhysicsConstraint, GetGrooveStart)
    METHOD(PhysicsConstraint, GetGrooveEnd)
    METHOD(PhysicsConstraint, SetGroove)
    METHOD(PhysicsConstraint, GetMinAngle)
    METHOD(PhysicsConstraint, GetMaxAngle)
    METHOD(PhysicsConstraint, SetAngleLimits)
    METHOD(PhysicsConstraint, Disconnect)
DECL_END

BINDING_CLASS(PhysicsBody)
    METHOD(PhysicsBody, GetConstraintCount)
    METHOD(PhysicsBody, CreatePinJoint)
    METHOD(PhysicsBody, CreatePivotJoint)
    METHOD(PhysicsBody, CreateSlideJoint)
    METHOD(PhysicsBody, CreateGrooveJoint)
    METHOD(PhysicsBody, CreateSpring)
    METHOD(PhysicsBody, CreateRotarySpring)
    METHOD(PhysicsBody, CreateRotaryLimit)
    METHOD(PhysicsBody, CreateRatchet)
    METHOD(PhysicsBody, CreateGear)
    METHOD(PhysicsBody, CreateMotor)
    METHOD(PhysicsBody, GetConstraint)
    METHOD(PhysicsBody, Disconnect)
    METHOD(PhysicsBody, SetDriveTarget)
    METHOD(PhysicsBody, ClearDrive)
    METHOD(PhysicsBody, IsDriveEnabled)
    METHOD(PhysicsBody, GetDriveState)
    METHOD(PhysicsBody, GetMode)
    METHOD(PhysicsBody, SetMode)
    METHOD(PhysicsBody, GetMass)
    METHOD(PhysicsBody, SetMass)
    METHOD(PhysicsBody, GetMomentOfInertia)
    METHOD(PhysicsBody, SetMomentOfInertia)
    METHOD(PhysicsBody, GetLinearDamping)
    METHOD(PhysicsBody, SetLinearDamping)
    METHOD(PhysicsBody, GetAngularDamping)
    METHOD(PhysicsBody, SetAngularDamping)
    METHOD(PhysicsBody, GetFriction)
    METHOD(PhysicsBody, SetFriction)
    METHOD(PhysicsBody, GetRestitution)
    METHOD(PhysicsBody, SetRestitution)
    METHOD(PhysicsBody, SetBreakAngularSpeed)
    METHOD(PhysicsBody, GetBreakAngularSpeed)
    METHOD(PhysicsBody, GetBreakAngularSpeedReference)
    METHOD(PhysicsBody, GetAngularVelocity)
    METHOD(PhysicsBody, SetAngularVelocity)
    METHOD(PhysicsBody, GetSpeed)
    METHOD(PhysicsBody, SetSpeed)
    METHOD(PhysicsBody, GetSolver)
    METHOD(PhysicsBody, GetAngularMomentum)
    METHOD(PhysicsBody, GetMovementDirectionInRadians)
    METHOD(PhysicsBody, IsPresent)
    METHOD(PhysicsBody, IsAttached)
    METHOD(PhysicsBody, GetState)
    METHOD(PhysicsBody, GetVelocity)
    METHOD(PhysicsBody, SetVelocity)
    METHOD(PhysicsBody, SetVelocityInRadians)
    METHOD(PhysicsBody, Teleport)
    METHOD(PhysicsBody, ApplyImpulse)
    METHOD(PhysicsBody, ApplyAngularImpulse)
    METHOD(PhysicsBody, ApplyForce)
    METHOD(PhysicsBody, ApplyTorque)
    METHOD(PhysicsBody, AddContinuousForce)
    METHOD(PhysicsBody, AddContinuousTorque)
    METHOD(PhysicsBody, RemoveForce)
    METHOD(PhysicsBody, StopAllForces)
    METHOD(PhysicsBody, StopMoving)
    METHOD(PhysicsBody, StopSpinning)
    METHOD(PhysicsBody, Step)
DECL_END

BINDING_CLASS(Part)
    METHOD(Part, ReadCollider)
    METHOD(Part, SetupCollider)
    METHOD(Part, SetupFrameCollider)
    METHOD(Part, SetupAnimationCollider)
    METHOD(Part, RemoveCollider)
    METHOD(Part, ReadPhysics)
    METHOD(Part, SetupPhysicsBody)
    METHOD(Part, RemovePhysicsBody)

  ANIMATED_METHODS(Part)
    METHOD(Part, Animate)
    METHOD(Part, GetId)
    METHOD(Part, GetName)
    METHOD(Part, GetSprite)
    METHOD(Part, IsAttached)
    METHOD(Part, GetBoneId)
    METHOD(Part, IsBoundToBone)
    METHOD(Part, BindToBone)
    METHOD(Part, UnbindFromBone)
    METHOD(Part, GetParentPart)
    METHOD(Part, SetParentPart)
    METHOD(Part, GetTransform)
    METHOD(Part, ProceduralControl)
    METHOD(Part, SolveIK)
    METHOD(Part, SetIKTarget)
    METHOD(Part, ClearIKTarget)
    METHOD(Part, HasIKTarget)
    METHOD(Part, IsIKTargetReached)
    METHOD(Part, GetIKError)
    METHOD(Part, GetJiggleError)
    METHOD(Part, SetIKLimits)
    METHOD(Part, ClearIKLimits)
    METHOD(Part, HasIKLimits)
    METHOD(Part, GetIKMinAngle)
    METHOD(Part, GetIKMaxAngle)
    METHOD(Part, SetIKDriveTarget)
    METHOD(Part, IsIKDriven)
    METHOD(Part, AttachSprite)
    METHOD(Part, GetAttachedSprite)
    METHOD(Part, DetachSprite)
    METHOD(Part, GetAttachmentError)
    METHOD(Part, BindToAnimationBinding)
    METHOD(Part, BindToAnimationSocket)
    METHOD(Part, GetAnimationBindingName)
    METHOD(Part, GetAnimationSocketName)
    METHOD(Part, ClearContent)
    METHOD(Part, HasContent)
    METHOD(Part, GetContentBounds)
%#ifndef PDG_NO_GUI
    METHOD(Part, SetDrawing)
    METHOD(Part, SetImage)
%#endif
DECL_END


%#ifndef PDG_NO_GUI
BINDING_CLASS(ISpriteDrawHelper)
DECL_END
%#endif //!PDG_NO_GUI

BINDING_CLASS(Sprite)
    METHOD(Sprite, ReadCollider)
    METHOD(Sprite, SetupCollider)
    METHOD(Sprite, RemoveCollider)
    METHOD(Sprite, ReadPhysics)
    METHOD(Sprite, SetupPhysicsBody)
    METHOD(Sprite, RemovePhysicsBody)

    METHOD(Sprite, GetAttachmentPart)
    METHOD(Sprite, SetupFrameCollider)
    METHOD(Sprite, SetupAnimationCollider)
    METHOD(Sprite, SetFrameCollisionMask)
    METHOD(Sprite, CreatePart)
    METHOD(Sprite, TransferPart)
    METHOD(Sprite, GetPart)
    METHOD(Sprite, FindPart)
    METHOD(Sprite, GetPartCount)
    METHOD(Sprite, GetPartNames)
    METHOD(Sprite, RemovePart)
    METHOD(Sprite, ClearParts)
  EMITTER_METHODS(Sprite)
  ANIMATED_METHODS(Sprite)
  SERIALIZABLE_METHODS(Sprite)
	PROPERTY(Sprite, WantsAnimLoopEvents)
	PROPERTY(Sprite, WantsAnimEndEvents)
	PROPERTY(Sprite, Opacity)
	PROPERTY(Sprite, WantsCollideWallEvents)
	METHOD(Sprite, GetFrameRotatedBounds)
	METHOD(Sprite, SetFrame)
	METHOD(Sprite, GetCurrentFrame)
    METHOD(Sprite, GetFrameCount)
	METHOD(Sprite, StartFrameAnimation)
	METHOD(Sprite, StopFrameAnimation)
	METHOD(Sprite, AddFramesImage)
%#ifdef PDG_SPRITER_SUPPORT
	METHOD(Sprite, SeekAnimation)
METHOD(Sprite, TransitionToAnimation)
METHOD(Sprite, IsAnimationTransitioning)
METHOD(Sprite, GetAnimationTransitionProgress)
METHOD(Sprite, ProceduralControl)
METHOD(Sprite, AddAnimationIK)
METHOD(Sprite, SetAnimationIKTarget)
METHOD(Sprite, GetAnimationIKResult)
METHOD(Sprite, AddAnimationModifier)
METHOD(Sprite, RemoveAnimationModifier)
METHOD(Sprite, ClearAnimationModifiers)
METHOD(Sprite, GetAnimationModifierError)
METHOD(Sprite, SetAnimationSource)
METHOD(Sprite, GetAnimationSource)
METHOD(Sprite, IsAnimationDrawingSupported)
	METHOD(Sprite, SetAnimationDebugDraw)
	METHOD(Sprite, GetAnimationDebugDraw)
	METHOD(Sprite, SupportsAnimationPhysics)
	METHOD(Sprite, SetupAnimationPhysics)
	METHOD(Sprite, SetupPhysicsFromAnimationRig)
	METHOD(Sprite, AttachAnimationPhysicsPart)
	METHOD(Sprite, DetachAnimationPhysicsPart)
	METHOD(Sprite, IsAnimationPhysicsPartAttached)
	METHOD(Sprite, SetAnimationPhysicsRoot)
	METHOD(Sprite, GetAnimationPhysicsRoot)
	METHOD(Sprite, ClearAnimationPhysicsRoot)
	METHOD(Sprite, GetAnimationPhysicsSetupWarnings)
	METHOD(Sprite, SetAnimationPhysicsMode)
	METHOD(Sprite, GetAnimationPhysicsMode)
	METHOD(Sprite, SetAnimationPhysicsDriveSettings)
	METHOD(Sprite, GetAnimationPhysicsDriveSettings)
	METHOD(Sprite, DisableAnimationPhysics)
	METHOD(Sprite, IsAnimationPhysicsEnabled)
	METHOD(Sprite, AddAnimationDrawable)
	METHOD(Sprite, RemoveAnimationDrawable)
	METHOD(Sprite, ClearAnimationDrawables)
	METHOD(Sprite, SetAnimationDrawableEnabled)
	METHOD(Sprite, GetAnimationDrawableError)
	METHOD(Sprite, GetAnimationDrawBounds)
	METHOD(Sprite, EnableAnimationPose)
	METHOD(Sprite, DisableAnimationPose)
	METHOD(Sprite, IsAnimationPoseEnabled)
	METHOD(Sprite, GetAnimationRigError)
	METHOD(Sprite, GetBone)
	METHOD(Sprite, GetAnimationBoneNames)
	METHOD(Sprite, GetAnimationBindingNames)
	METHOD(Sprite, GetAnimationBoneTransform)
	METHOD(Sprite, GetAnimationBindingTransform)
	METHOD(Sprite, SetAnimationBoneTransform)
	METHOD(Sprite, ClearAnimationBoneTransforms)
	METHOD(Sprite, GetAnimationPose)
	METHOD(Sprite, SampleAnimationPose)
	METHOD(Sprite, HasAnimation)
	METHOD(Sprite, StartAnimation)
	METHOD(Sprite, ApplyCharacterMap)
	METHOD(Sprite, RemoveCharacterMap)
	METHOD(Sprite, RemoveAllCharacterMaps)
	METHOD(Sprite, GetAppliedCharacterMaps)
	METHOD(Sprite, EnableSpriterEvents)
	METHOD(Sprite, AreSpriterEventsEnabled)
	METHOD(Sprite, BlendToAnimation)
	METHOD(Sprite, IsBlending)
	METHOD(Sprite, GetBlendProgress)
	METHOD(Sprite, PauseAnimation)
	METHOD(Sprite, ResumeAnimation)
	METHOD(Sprite, StopAnimation)
	METHOD(Sprite, IsAnimationPlaying)
	METHOD(Sprite, IsAnimationPaused)
	METHOD(Sprite, GetAnimationProgress)
  	METHOD(Sprite, GetAnimationName)
  	METHOD(Sprite, HasAttachPoint)
	METHOD(Sprite, GetAttachPoint)
	METHOD(Sprite, AttachSprite)
	METHOD(Sprite, ActivateSubEntity)
	METHOD(Sprite, DetachSprite)
	METHOD(Sprite, GetAttachedSprite)
	METHOD(Sprite, GetSpriterCollisionBox)
	METHOD(Sprite, IsSpriterCollisionActive)
	METHOD(Sprite, GetSpriterCollisionBoxCount)
	METHOD(Sprite, GetSpriterCollisionBoxName)
%#endif // PDG_SPRITER_SUPPORT
%#ifndef PDG_NO_GUI
	PROPERTY(Sprite, WantsMouseOverEvents)
	PROPERTY(Sprite, WantsClickEvents)
	PROPERTY(Sprite, MouseDetectMode)
	PROPERTY(Sprite, WantsOffscreenEvents)
	METHOD(Sprite, SetDrawHelper)
	METHOD(Sprite, SetPostDrawHelper)
%#endif //!PDG_NO_GUI
	METHOD(Sprite, ChangeFramesImage)
	METHOD(Sprite, OffsetFrameCenters)
	METHOD(Sprite, GetFrameCenterOffset)
	METHOD(Sprite, FadeTo)
	METHOD(Sprite, FadeIn)
	METHOD(Sprite, FadeOut)
	METHOD(Sprite, IsBehind)
	METHOD(Sprite, GetZOrder)
	METHOD(Sprite, MoveBehind)
	METHOD(Sprite, MoveInFrontOf)
	METHOD(Sprite, MoveToFront)
	METHOD(Sprite, MoveToBack)
	METHOD(Sprite, SetUserData)
	METHOD(Sprite, FreeUserData)
	METHOD(Sprite, GetLayer)

  METHOD(Sprite, On)
  METHOD(Sprite, OnCollideSprite)
  METHOD(Sprite, OnCollideWall)
  METHOD(Sprite, OnOffscreen)
  METHOD(Sprite, OnOnscreen)
  METHOD(Sprite, OnExitLayer)
  METHOD(Sprite, OnAnimationLoop)
  METHOD(Sprite, OnAnimationEnd)
  METHOD(Sprite, OnAnimationPhysicsRecoveryComplete)
  METHOD(Sprite, OnAnimationBlendComplete)
  METHOD(Sprite, OnFadeComplete)
  METHOD(Sprite, OnFadeInComplete)
  METHOD(Sprite, OnFadeOutComplete)
  METHOD(Sprite, OnMouseEnter)
  METHOD(Sprite, OnMouseLeave)
  METHOD(Sprite, OnMouseDown)
  METHOD(Sprite, OnMouseUp)
  METHOD(Sprite, OnMouseClick)
DECL_END


BINDING_CLASS(SpriteLayer)
%#ifndef PDG_USING_JAVASCRIPT_CORE
public:
    void forgetCppObject() { cppPtr_=nullptr; }
%#endif
  EMITTER_METHODS(SpriteLayer)
  SERIALIZABLE_METHODS(SpriteLayer)
  SPRITE_LAYER_METHODS(SpriteLayer)
%#ifndef PDG_NO_GUI
  SPRITE_LAYER_GUI_METHODS(SpriteLayer)
%#endif
%#ifdef PDG_USE_CHIPMUNK_PHYSICS
  SPRITE_LAYER_CHIPMUNK_METHODS(SpriteLayer)
%#endif
%#ifdef PDG_SPRITER_SUPPORT
	METHOD(SpriteLayer, CreateSpriteFromSpriter)
	METHOD(SpriteLayer, CreateSpriteFromSpriterFile)
	METHOD(SpriteLayer, CreateSpriteFromSpriterEntity)
	METHOD(SpriteLayer, ApplyCharacterMapToAll)
	METHOD(SpriteLayer, RemoveCharacterMapFromAll)
	METHOD(SpriteLayer, EnableSpriterEvents)
%#endif // PDG_SPRITER_SUPPORT
  SPRITE_LAYER_EVENT_METHODS(SpriteLayer)
DECL_END

BINDING_CLASS(TileLayer)
%#ifndef PDG_USING_JAVASCRIPT_CORE
public:
    void forgetCppObject() { cppPtr_=nullptr; }
%#endif
  EMITTER_METHODS(TileLayer)
  SERIALIZABLE_METHODS(TileLayer)
  SPRITE_LAYER_METHODS(TileLayer)
%#ifndef PDG_NO_GUI
  SPRITE_LAYER_GUI_METHODS(TileLayer)
%#endif
%#ifdef PDG_USE_CHIPMUNK_PHYSICS
  SPRITE_LAYER_CHIPMUNK_METHODS(TileLayer)
%#endif
	PROPERTY(TileLayer, WorldSize)
	METHOD(TileLayer, DefineTileSet)
	METHOD(TileLayer, LoadMapData)
	METHOD(TileLayer, GetMapData)
	METHOD(TileLayer, GetTileSetImage)
	METHOD(TileLayer, GetTileSize)
	METHOD(TileLayer, GetTileTypeAt)
	METHOD(TileLayer, GetTileTypeAndFacingAt)
	METHOD(TileLayer, SetTileTypeAt)
  METHOD(TileLayer, CheckCollision)
  SPRITE_LAYER_EVENT_METHODS(TileLayer)
DECL_END


%#endif // PDG_ANIMATION_BINDINGS_H_INCLUDED 

} // namespace pdg
