# An isolated optional library. Never linked to PDG's JavaScript executable.
include(ExternalProject)
set(pdg_net_build "${PDG_SOURCE_DIR}/build/native-network/${BUILD_SUBDIR}")
set(pdg_net_args -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE})
foreach(name CMAKE_C_COMPILER CMAKE_CXX_COMPILER CMAKE_OSX_SYSROOT CMAKE_OSX_ARCHITECTURES CMAKE_OSX_DEPLOYMENT_TARGET CMAKE_TOOLCHAIN_FILE CMAKE_MSVC_RUNTIME_LIBRARY)
    if(DEFINED ${name} AND NOT "${${name}}" STREQUAL "")
        list(APPEND pdg_net_args "-D${name}=${${name}}")
    endif()
endforeach()
foreach(name PICOQUIC PICOTLS MBEDTLS CJSON)
    if(DEFINED FETCHCONTENT_SOURCE_DIR_${name})
        list(APPEND pdg_net_args "-DFETCHCONTENT_SOURCE_DIR_${name}=${FETCHCONTENT_SOURCE_DIR_${name}}")
    endif()
endforeach()
set(pdg_net_archive "${pdg_net_build}/${CMAKE_STATIC_LIBRARY_PREFIX}pdg_net${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(pdg_net_backend "${pdg_net_build}/webtransport/${CMAKE_STATIC_LIBRARY_PREFIX}pdg_webtransport_all${CMAKE_STATIC_LIBRARY_SUFFIX}")
ExternalProject_Add(pdg-native-network-build
    SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/sys/net" BINARY_DIR "${pdg_net_build}"
    CMAKE_ARGS ${pdg_net_args}
    # The default recursive build inherits Make's jobserver.
    BUILD_ALWAYS TRUE INSTALL_COMMAND "" BUILD_BYPRODUCTS "${pdg_net_archive}" "${pdg_net_backend}")
add_library(pdg-net STATIC IMPORTED GLOBAL)
set_target_properties(pdg-net PROPERTIES IMPORTED_LOCATION "${pdg_net_archive}")
add_dependencies(pdg-net pdg-native-network-build)
target_link_libraries(pdg-net INTERFACE pdg-lib "${pdg_net_backend}")
if(APPLE)
    target_link_libraries(pdg-net INTERFACE "-framework Security" "-framework CoreFoundation")
elseif(WIN32)
    target_link_libraries(pdg-net INTERFACE ws2_32 crypt32)
else()
    find_package(Threads REQUIRED)
    target_link_libraries(pdg-net INTERFACE Threads::Threads)
endif()
add_executable(pdg-native-network-tests "${PDG_SOURCE_DIR}/test/cxx/native_network_host.cpp")
target_link_libraries(pdg-native-network-tests PRIVATE pdg-net)
target_link_directories(pdg-native-network-tests PRIVATE ${GLFW_LINK_DIRS} ${LIBJPEG_LINK_DIRS})
if(APPLE)
    target_link_libraries(pdg-native-network-tests PRIVATE "-framework AppKit" "-framework CoreGraphics" "-framework AudioToolbox" "-framework OpenGL" "-framework GLUT" "-framework IOKit")
elseif(WIN32)
    if(MSVC)
        set_property(TARGET pdg-native-network-tests PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
        target_compile_options(pdg-native-network-tests PRIVATE /utf-8)
    endif()
    target_link_libraries(pdg-native-network-tests PRIVATE imm32 psapi winmm user32 strmiids bcrypt advapi32 userenv ${OPENGL_LIBRARIES})
endif()
add_test(NAME native-network COMMAND pdg-native-network-tests --selftest)
