#!/usr/bin/env python3
"""Generate semantic dispatch and recorder methods from public fluent C++ declarations."""
from pathlib import Path
import re,json,os,subprocess
ROOT=Path(__file__).resolve().parent.parent
CLASSES={'Bone':'bone.h','Camera':'camera.h','Sprite':'sprite.h','Part':'part.h','Particle':'particle.h','ParticleEmitter':'particleemitter.h','AnimatedAttributesBase':'animatedattributes.h','Attributes':'attributes.h'}
def uncomment(s):return re.sub(r'//[^\n]*|/\*.*?\*/',lambda m:'\n'*m[0].count('\n'),s,flags=re.S)
def split(s):
 out=[];start=depth=0
 for i,c in enumerate(s):
  if c in '(<{[':depth+=1
  if c in ')>}]':depth-=1
  if c==',' and depth==0:out.append(s[start:i].strip());start=i+1
 if s[start:].strip():out.append(s[start:].strip())
 return out
records=[]
for cls,h in CLASSES.items():
 raw=(ROOT/'src/inc/pdg/sys'/h).read_text();s=uncomment(raw)
 cm=re.search(r'class\s+'+cls+r'\b[^;{]*\{',s);assert cm,cls
 start=cm.end();d=1;end=start
 while d:
  if s[end]=='{':d+=1
  if s[end]=='}':d-=1
  end+=1
 body=s[start:end-1]
 for public in re.finditer(r'public\s*:(.*?)(?=\b(?:private|protected)\s*:|\Z)',body,re.S):
  for m in re.finditer(r'\b'+cls+r'\s*&\s*(\w+)\s*\(([^()]*)\)',public[1]):
   name=m[1]
   if name.startswith('get') or name.endswith('Impl') or name in ['stopIt','restartIt','pauseIt','resumeIt','cancelSchedule','pauseSchedule','resumeSchedule']:continue
   params=[]
   for p in split(m[2]):
    decl,_,default=p.partition('=');pm=re.match(r'(.+?)(\w+)\s*$',decl.strip());assert pm,(cls,name,p)
    typ,pname=pm.groups();params.append({'type':typ.strip(),'name':pname,'default':default.strip()})
   pos=start+public.start(1)+m.start()
   # Preserve feature guards surrounding each declaration, excluding header guards.
   guards=[]
   for line in s[:pos].splitlines():
    z=line.strip()
    if re.match(r'#\s*(if|ifdef|ifndef)\b',z):guards.append(z)
    elif re.match(r'#\s*endif\b',z):
     if guards:guards.pop()
    elif re.match(r'#\s*else\b',z) and guards:guards[-1]='#if !('+guards[-1].removeprefix('#if ')+')'
   guards=[g for g in guards if '_H_INCLUDED' not in g]
   records.append({'class':cls,'name':name,'params':params,'guards':guards})
names=sorted({r['name'] for r in records if r['name']!='diminish'})
header=['// Generated by tools/generate-animation-operations.py. Do not edit.']
for name in names:
 header+=['template<class... Args> AnimationScript& '+name+'(const Args&... args) {',
 '    recordOperation("'+name+'", captureAnimationArguments(args...)); return *this;', '}']
(ROOT/'src/inc/pdg/sys/animation-script-methods.inc').write_text('\n'.join(header)+'\n')
(ROOT/'src/inc/pdg/sys/animation-troupe-methods.inc').write_text('\n'.join(header).replace('AnimationScript&','Troupe&')+'\n')
duration_lines=['// Generated by tools/generate-animation-operations.py. Do not edit.']
seen_duration=set()
for r in records:
 if not r['name'].startswith(('fade','change','zoom','flash','transition','luma','whip','match','scale','diminish')):continue
 for i,p in enumerate(r['params']):
  if p['name'] in ['seconds','durationSeconds','blendTime','recoveryTime']:
   key=(r['name'],i)
   if key not in seen_duration:
    duration_lines.append('if(name=="'+r['name']+'" && arguments.size()>'+str(i)+') return animationArgument<double>(arguments.at('+str(i)+'));')
    seen_duration.add(key)
   break
(ROOT/'src/sys/animation-operation-durations.inc').write_text('\n'.join(duration_lines)+'\n')
for cls in CLASSES:
 cpp=['// Generated by tools/generate-animation-operations.py. Do not edit.',
      'namespace { const bool animationOperations_'+cls+'=[] {']
 for r in [r for r in records if r['class']==cls]:
  ps=r['params'];minimum=sum(not p['default'] for p in ps)
  def arg(i,p):
   exp='animationArgument<'+p['type']+'>(args.at('+str(i)+'))'
   if p['default']:
    default=p['default']
    if cls=='Sprite' and default in ['all_Frames','start_FromFirstFrame','collide_BoundingBox']:default='Sprite::'+default
    exp='(args.size()>'+str(i)+' ? '+exp+' : '+default+')'
   return exp
  guards=r['guards']
  cpp+=guards
  cpp+=['    registerAnimationOperation("'+r['name']+'", [](AnimatedBase& target,const AnimationArguments& args) {',
        '        auto* receiver=dynamic_cast<'+cls+'*>(&target); if(!receiver) return false;',
        '        if('+ (f'args.size()<{minimum} || ' if minimum else '') + f'args.size()>{len(ps)}) return false;',
        '        try { receiver->'+r['name']+'('+', '.join(arg(i,p) for i,p in enumerate(ps))+'); return true; }',
        '        catch(const std::bad_any_cast&) { return false; }', '    }, [](const AnimationArguments& args) -> double {']
  duration='0'
  if r['name'].startswith(('fade','change','zoom','flash','transition','luma','whip','match','scale','diminish')):
   for i,p in enumerate(ps):
    if p['name'] in ['seconds','durationSeconds','blendTime','recoveryTime']:
     duration='args.size()>'+str(i)+' ? animationArgument<double>(args.at('+str(i)+')) : 0';break
  if cls=='Camera' and r['name'] in ['matchCutTo','matchFadeTo']:
   duration='args.size()>1 ? animationArgument<const CameraMatchOptions&>(args.at(1)).approachSeconds + animationArgument<const CameraMatchOptions&>(args.at(1)).settleSeconds'
   if r['name']=='matchFadeTo':duration+=' + animationArgument<const CameraMatchOptions&>(args.at(1)).fadeSeconds'
   duration+=' : 0'
  cpp+=['        return '+duration+';', '    });']
  cpp+=['#endif' for _ in guards]
 cpp+=['    return true;','}(); }']
 (ROOT/'src/sys'/('animation-operations-'+cls.lower()+'.inc')).write_text('\n'.join(cpp)+'\n')
(ROOT/'tools/animation-operations-inventory.json').write_text(json.dumps(records,indent=2)+'\n')
print(f'Generated {len(records)} fluent native overloads, {len(names)} recorder methods.')

node = "node" if os.name == "nt" else str(ROOT/"tools/node")
subprocess.run([node,str(ROOT/"tools/animation-recorder.js")],check=True)
